### ISSUE TITLE
Crash at startup on very old Windows 10 version (1511)

### ISSUE THREAD

**Issue by pmttavara** [OurMachinery/themachinery-public#1000]
- **Version:** Latest Binary Release
- **OS:** Windows

Version: 2022.1.a
OS: Windows 10 v1511 (OS Build 10586.494)

On Win10 version 1511, `the-machinery.exe` crashes at startup. It seems Windows can't support the DPI scaling or XInput functions that The Machinery demands. I've attached the 2 error dialogs + crash dump + console output that `the-machinery.exe` produces, but sadly I need to upgrade this machine to Win10 v21H2 now, so I can't give feedback on future updates to this problem. I fully understand if this is a "wontfix", since 1511 is ancient and users should absolutely be expected to update, but I want to at least report it, so the team can choose whether to identify older versions and tell the user to update, or even just put a note on the download page (e.g. "Required OS: Windows 10, latest version/version XXXX and newer").

![image](https://user-images.githubusercontent.com/34119228/152544374-a8b2964c-5da3-450c-954d-1fe7312175e7.png)
![image](https://user-images.githubusercontent.com/34119228/152544393-49af4e43-28a5-4045-8e41-fb4a004d1ccf.png)
[the_machinery_exe 2022-02-04 09.18.11.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/8003697/the_machinery_exe.2022-02-04.09.18.11.dmp.zip)
[the_machinery_exe command line 2022-02-04 09.30.txt.zip](https://github.com/OurMachinery/themachinery-public/files/8004673/the_machinery_exe.command.line.2022-02-04.09.30.txt.zip)

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery  I think the best solution is latter: "Required OS: Windows 10, latest version/version XXXX and newer" what do you think?

**Comment by niklas-ourmachinery** [comment]
I agree, we should do that for now... if there is need we can go back later and add support for older versions.
