### ISSUE TITLE
Selecting the selected state in the State Graph does not update the Properties tab

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1003]
- **Version:** Git Master Branch
- **OS:** Windows

As a user I expect the last node(e.g. state, transition, variable) I clicked to show it's properties in the Properties tab. Currently when clicking a variable node in the Tree View and then clicking the currently selected state in the State Graph the Properties tab still shows the variable's properties. To go back to inspecting the selected state's properties I have to first select another state.

**Comment by niklas-ourmachinery** [comment]
That makes sense... currently a "focus event" is only sent when the focus "changes", but it makes sense to also send it when clicking on an object that is already focused.
