### ISSUE TITLE
Selecting an entity in the viewport and deleting it breaks the entity

### ISSUE THREAD

**Issue by Arazu161** [OurMachinery/themachinery-public#101]
1. create a new entity and double click it to open it
2. add a tessellated plane component
3. select the plane in the viewport, the entity is highlighted in the tree view
4. hit Del. 

The entity itself seems to be deleted, it still exists in the asset browser, but cannot be re-opened (double clicking on it has no effect). The tree view is empty and displays the "Open an entity in the asset browser" message.

If the entity is a child of another entity, it has all of its components deleted within that tree. Selecting "open prototype"  on that child entity opens a blank scene with no "root" entity and the tree displays the "open an entity in the asset browser" message

**Comment by niklas-ourmachinery** [comment]
Reproduced.

What happens here is you delete the root entity in the asset, so the asset becomes completely empty and then no longer can be opened. I think we should simply disallow deleting the root entity from the Scene view (just as we already do in the Tree view).

**Comment by niklas-ourmachinery** [comment]
Fixed.
