### ISSUE TITLE
Selection and gizmo issues

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1016]
- **Version:** Git Master Branch 
- **OS:** Windows

Pulled master to test the entity selection fixes and it appears selections and gizmos have broken. I tried copying and pasting the entities and the selection was not updated to the new ones. Gizmos do not follow entity anymore (have to reselect the entity)

https://user-images.githubusercontent.com/21057342/153695429-6af84727-8882-478b-a148-aaeddabc97b4.mp4

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in master.
