### ISSUE TITLE
 `tm_plugin_init_i` is not called on reload if the previous implementation did not have an init

### ISSUE THREAD

**Issue by Selmar** [OurMachinery/themachinery-public#1018]
- **Version:** Git Master Branch
- **OS:** Windows

Related to #814.

`tm_plugin_init_i` is not called on reload if the previous implementation did not have an init.

Repro:
- create project with .dll, save & close editor
- add tm_plugin_init_i to plugin, build
- re-open project
- notice missing init call

**Comment by Selmar** [comment]
shutdown is not called when it is removed from the plugin removed either; I think this makes sense. Though it does mean we may leak some resources in that case, at least it won't crash (unlike a missing init, which may cause a crash on shutdown).

**Comment by niklas-ourmachinery** [comment]
I consider this behavior "by design".

`tm_plugin_init_i` is also not called if its implementation changed, so you can't add new initialization steps to it and expect those to be called by a hot reload. So changing `tm_plugin_init_i` or adding it works in a similar sense.

**Comment by Selmar** [comment]
Ok! I'll use the reload.
