### ISSUE TITLE
Properties ui layout issue

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#1019]
- **Version:** Git Master Branch 
- **OS:** Windows 

See the gif for the layout issue.

UI code looks like this:

```
static float properties__sub_points(struct tm_properties_ui_args_t* args, tm_rect_t item_rect, const char* name, const char* tooltip, tm_tt_id_t object, uint32_t property)
{
	if (tm_ui_api->button(args->ui, args->uistyle, &(tm_ui_button_t){.text = "Do", .rect = item_rect })) {		
	}
	return item_rect.h;
}
```

![props_layout_bug](https://user-images.githubusercontent.com/108040/153767575-7aed5842-e1c2-49d5-ae42-13e72aa1b49c.gif)

**Comment by niklas-ourmachinery** [comment]
This is an issue with your code... you should return the y-coordinate where the next control should be drawn after your custom UI. In your case that would be something like:

~~~
return item_rect.y + item_rect.h + 5.0f;
~~~

Where 5.0f is the margin to the next item.
