### ISSUE TITLE
Properties tab doesn't show inherited component properties (individually)

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1020]
- **Version:** Git Master Branch
- **OS:** Windows

As a user I would like to see the properties of the selected component. Currently the only way to see the properties of an inherited component is to select the entity node itself.

**Comment by niklas-ourmachinery** [comment]
We're working on better workflows for inherited objects in general. Unfortunately it's not a quick fix, since it requires some replumbing, but stay tuned.

**Comment by karl-zylinski-ourmachinery** [comment]
Duplicate of https://github.com/OurMachinery/themachinery-public/issues/447
