### ISSUE TITLE
Crash when opening an ASM asset

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1021]
- **Version:** Git Master Branch
- **OS:** Windows

TM crashes when double clicking an ASM file in the asset browser. The context_menu function ptr was null in the Tree View's ui(..)  function. Reproduced 2/2.

![image](https://user-images.githubusercontent.com/91697782/153821953-8c2e557d-1377-4051-9762-9242563f4930.png)

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
