### ISSUE TITLE
Collaboration server crashes on bad data from client with a TM_FATAL_ASSERT

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1023]
- **Version:** Git Master Branch
- **OS:** Windows

The assert is here:
https://github.com/OurMachinery/themachinery/blob/e5ae8f171a3fe191b2f060f7660210826d1117ff/foundation/the_truth.c#L5724

It happened a few seconds after a new client connected.

It has happened twice during last week, but I have no repro for it.

**Comment by niklas-ourmachinery** [comment]
Pushed a partial fix to master that will prevent the server from going down if this happens which should make this less bad.

To fix the actual issue I think I need a repro case to understand what is happening.

**Comment by Tisten** [comment]
I have not seen this one in over a month now. Closing it.
