### ISSUE TITLE
Draw debug nodes

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1040]
Ability to draw shapes / lines / transform history / frustum, etc from graph nodes that render in simulate is invaluable debugging tool I often find myself using.

Example: I make a physX raycast and I want to see if it is casting from the right place, to the right place, and how far it actually goes.

**Comment by frank-ourmachinery** [comment]
There is currently a [PR](https://github.com/OurMachinery/themachinery/pull/893) for this issue that adds: lines, rays, boxes, spheres, cones, capsules, and arrows. Do you have any good references for the transform history (input and expected output) and frustum (input)? Hopefully we can add the majority of these debug shapes for the 2022.2 release.

**Comment by simon-ourmachinery** [comment]
PR has been merged.
