### ISSUE TITLE
Creating labels in asset browser

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1041]
It is possibly to filter on a few pre-defined labels. I would like to create my own labels and assign to things for quicker filtering.

**Comment by simon-ourmachinery** [comment]
You can create your own labels:
https://books.ourmachinery.com/the_machinery_book/the_editor/asset_browser.html#asset-management

**Comment by simon-ourmachinery** [comment]
@TobiasElemental that was what you ment right?
