### ISSUE TITLE
Sequence node with '+' option to go more than 4

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1043]
Add a '+' like with inputs on the sequence node to allow me to increase it / decrease it to however many routes I need it to be.

**Comment by Tisten** [comment]
I had a look at this, and the code which handles the '+' attribute is specific for the "input node", "output node" and "subgraph node" (https://github.com/OurMachinery/themachinery/blob/04d586c2b6a9052701c9d6c9cad816c34f24781a/plugins/editor_views/graph.c#L2876-L2932), and I haven't found any generic way of doing this.

Could that code be generalized so any node can act on "wire connected"?

**Comment by simon-ourmachinery** [comment]
I have a look into it. Ill do that monday/the weekend.
