### ISSUE TITLE
`tm_the_truth_api->uuid()` is not thread-safe

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#1046]
- **Version:** Git Master Branch | Latest Binary Release
- **OS:** Windows | Linux 

It used to be this was only accessed by serialization code, but now it's touching other threads too.

**Comment by simon-ourmachinery** [comment]
Possibly fixed in https://github.com/OurMachinery/themachinery/commit/de3731639582d85ce90197451ce9595c11df9b47 by @tobias-ourmachinery  close this issue for now
