### ISSUE TITLE
Broken undo of "Add Child Entity" and "Add Component" in Entity Tree

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#105]
Repro:
* Add child entity or add component to any entity using Entity Tree
* Try to undo

The undo of "Rename" in the same context menu works. The reason seems to be that "Rename" saves the undo step to a specific document (uses add_to_document), while add child/component does not.

**Comment by niklas-ourmachinery** [comment]
Fixed.
