### ISSUE TITLE
At low frame rates, mouse click state often gets stuck

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#1050]
- **Version:** Git Master Branch
- **OS:** Windows

If you somehow get the engine to stall or run at low frame rate while you have the mouse button pressed, then the mouse up event is often missed, making the mouse stuck in a held state even though the physical button is up. This can often happen when clicking on a tab header which needs to do a lot of things (stalling the engine), in this case the tab gets stuck to the cursor because it thinks you're pulling the tab.

I think this happens because we start ignoring events when we get to many in a single frame.

**Comment by niklas-ourmachinery** [comment]
Yes, we're probably hitting this:

~~~c
enum { MOUSE_EVENTS_BUFFER_SIZE = 128 };
~~~

That's a little low... I think we probably want to increase that (and maybe decrease `MAX_MICE` -- support for 32 mice seems a bit excessive 😄 ).

We could also probably be a bit smarter with how we manage the buffer. For example we don't really need to store multiple MOVE events that happen in the same frame, unless there is a BUTTON event between them.

**Comment by niklas-ourmachinery** [comment]
Pushed a fix for it, have a look and see if it addresses your issue.
