### ISSUE TITLE
Crash in tm_physx

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1052]
- **Version:** Git Master Branch
- **OS:** Windows

Crash where the actor pointer is null on line 1234:
https://github.com/OurMachinery/themachinery/blob/bd8e96b49848c5a2fc8bb6e0879b2340784be5dd/plugins/physx/physx_scene.cpp#L1229-L1237

The problem originates from a bad transform passed in here, so the actor wasn't created but still stored in the component:
https://github.com/OurMachinery/themachinery/blob/bd8e96b49848c5a2fc8bb6e0879b2340784be5dd/plugins/physx/physx_scene.cpp#L2226
https://github.com/OurMachinery/themachinery/blob/bd8e96b49848c5a2fc8bb6e0879b2340784be5dd/plugins/physx/physx_scene.cpp#L2280

**Comment by Tisten** [comment]
Please check so this can't be an issue for create/destroy rigid_body or shapes (or any other type) while you fix this for rigid statics.

**Comment by niklas-ourmachinery** [comment]
Fixed in master.
