### ISSUE TITLE
Crash in "private__save_buffer" on collaboration server

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1055]
- **Version:** Git Master Branch
- **OS:** Windows

On my collaboration server I'm getting a "Access violation reading location 0x000002AEC5881040." with the callstack:
```
>	the-machinery.exe!file_io_write(tm_file_o file, const void *buffer, __uint64 size) Line 273	C
	the-machinery.exe!private__save_buffer(void * ud, unsigned __int64 id) Line 1340	C
 	the-machinery.exe!process_one_task() Line 77	C
 	the-machinery.exe!is_task_done_else_assist(unsigned __int64 id) Line 181	C
 	the-machinery.exe!save_to_directory(tm_the_truth_o * tt, tm_tt_id_t asset_root, const char * dir, tm_tt_id_t * ignore, unsigned int num_ignore, tm_saved_truth_data_o * old_std, tm_allocator_i * allocator, tm_cas_cache_o * cache) Line 1905	C
 	[Inline Frame] the-machinery-dll.tm_hot_reload.dll!save_to_directory(tm_application_o * dir, const char *) Line 5179	C
 	the-machinery-dll.tm_hot_reload.dll!private__save_all_async(void * data, unsigned __int64 task_id) Line 5214	C
```

when trying to read from the first byte of the `buffer_data` pointer in `save_buffer_task_t *data`, the buffer should be 1996008 bytes big.

I suspect that a collaboration change removed the buffer while the server had started a save and were processing the files to save. I have no repro yet.

**Comment by Tisten** [comment]
This bug crashed the server today again.

I spoke to the user who made changes when it happened and he were removing a render material and the textures used by it.

So I guess we should just queue up all incoming changes until the save is done.

**Comment by Tisten** [comment]
I.e I think the idea you had in https://github.com/OurMachinery/themachinery-public/issues/1059 might solve this as well. The sad part is that saving takes a while so the server will be unresponsive for a while, and this is likely to cause invalid behavior on the client, like the timing issues described in this ticket: https://github.com/OurMachinery/themachinery-public/issues/984.

One idea of mine for this issue in particular is to start the save with a pass which increase the ref count of all the buffers so they don't get removed while compressing/writing, and after each written file the ref count can be lowered again. We still need to pause collaboration changes while this ref counting increas is going on, but it should be quick (milliseconds instead of several seconds)

**Comment by niklas-ourmachinery** [comment]
This would work for the buffers, but there could potentially be other issues from modifying the data while it is being saved... so it's a bit scary...

**Comment by Tisten** [comment]
It is indeed scary. By I wouldn't like to lock the entire truth for the duration of transfers of buffers. So if we could gather the truth data and send that first (small json buffers) and then defer the buffers to last, then the reference counting should save us from locking the truth during the commonly longest transfer time.

**Comment by niklas-ourmachinery** [comment]
Pushed a fix that retains and locks the buffers while the background save is in progress. This should prevent this particular crash from happening.

Let's see how this works out and then consider if we need additional protection (preventing incoming collaboration change packets during the "object" (i.e. non-buffer) part of the save).
