### ISSUE TITLE
Renaming with capital `O` confuses Asset Browser

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#1056]
- **Version:** Git Master Branch | Latest Binary Release
- **OS:** Windows | Linux 

* Select an asset in the asset browser.
* Right click and select rename.
* Try to rename it to something with a capital `O` by holding down shift and typing for example `WOOF`.

The Asset Browser reacts to the Shift+O keypress and rearranges the view, aborting the rename operation.

The Asset Browser should not react to Shift keypresses while renaming.

**Comment by simon-ourmachinery** [comment]
Note: Test
