### ISSUE TITLE
Crash while importing changes from disk on a collaboration server

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1059]
- **Version:** Git Master Branch
- **OS:** Windows

In my version of the collaboration server I naively added so changes on disk are immediately imported if there are no unsaved changes, and the changes on disk are discarded if there are unchanged changes.

This behavior led to this crash:
```
 	the-machinery.exe!changelog_size(tm_the_truth_o * tt) Line 1641	C
 	the-machinery.exe!generate_changelog_pkg(tm_collaboration_o * coll, tm_allocator_i * ta_alloc) Line 971	C
 	[Inline Frame] the-machinery.exe!host_send_changelog(tm_collaboration_o *) Line 990	C
 	the-machinery.exe!update(tm_collaboration_o * coll) Line 1445	C
 	the-machinery-dll.tm_hot_reload.dll!tick_application(tm_application_o * app) Line 6352	C
 	tm_ui.tm_hot_reload.dll!progress_box(const char * title, const char * text, const char * * buttons, unsigned int num_buttons, float(*)(void *) callback, void * callback_data) Line 326	C
 	the-machinery-dll.tm_hot_reload.dll!load_any_project(tm_application_o * app, const char * project_path) Line 4871	C
 	the-machinery-dll.tm_hot_reload.dll!private__restore_or_open_project(tm_application_o * app, const char * project_path) Line 4943	C
>	[Inline Frame] the-machinery-dll.tm_hot_reload.dll!handle_project_folder_changes(tm_application_o *) Line 8209	C
 	the-machinery-dll.tm_hot_reload.dll!tick_application(tm_application_o * app) Line 6291	C
```

I.e the project was reloaded since it wasn't modified since last save, but a change was gotten over the network during the reload.

The code is unmodified except for the `handle_project_folder_changes()` not requiring the user to press a button. I guess the load_any_project should tell the clients to wait until the project is reloaded somehow.

Any advice on how to improve the situation is welcome.

**Comment by niklas-ourmachinery** [comment]
Thinking about this some more... the problem here is that we pop a modal dialog (in this case a progress bar) while the collaboration system is in a half-baked state -- we're switching over to a new truth but hasn't notified the collaboration system about the switch yet.

I think a quick fix would be to just not tick the collaboration system while modals are showing.
