### ISSUE TITLE
(1) is always added to any new asset

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#1062]
- **Version:** Git Master Branch
- **OS:** Windows

When creating any new asset, a (1) is always added after the name. This includes when you import assets from other projects.

![image](https://user-images.githubusercontent.com/57644882/154478938-a760744d-ad79-4a9b-b0b6-64faa88e3d9e.png)

**Comment by simonrenger** [comment]
note: Add test @simon-ourmachinery

**Comment by niklas-ourmachinery** [comment]
Fixed in master.
