### ISSUE TITLE
Display Entity Graph wire tooltips even though the connected node is not in view

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1067]
As a user I would always like to be able to see the tooltip of a wire. Currently it seems to be based on if the connected node is in view or not. This would relief the user of a lot of zooming and panning in large graphs.

![graph_wire_tooltip](https://user-images.githubusercontent.com/91697782/154640090-3473d645-ff2b-4b4d-88b6-ac865a64151c.gif)

**Comment by simon-ourmachinery** [comment]
Commit: https://github.com/OurMachinery/themachinery/commit/9ab7e82b0152b9af0c53ecab4d23e684726cc5fd closes it
