### ISSUE TITLE
Menu items that can be checked sometimes check all items in category

### ISSUE THREAD

**Issue by sY9sE33** [OurMachinery/themachinery-public#107]
This is a visual bug only. When reopening the menu, only the expected item is checked.

![machinery_doublecheck](https://user-images.githubusercontent.com/9271353/74488557-8f9e6100-4e90-11ea-95f3-6f08413b83d5.gif)

**Comment by niklas-ourmachinery** [comment]
Reproduced. Investigating.

**Comment by niklas-ourmachinery** [comment]
Fixed.
