### ISSUE TITLE
Propagate changes to prototype is broken in some cases

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#1084]
- **Version:** Git Master Branch
- **OS:** Windows
--------------
- New project
- Right click in asset browser -> New -> New Entity Graph
- Name the new asset g1
- Make the graph look like this:
![image](https://user-images.githubusercontent.com/57644882/155294632-d834b7d3-7173-40e1-9883-68b2ed22d36c.png)
- Right click in asset browser -> New -> New Entity Graph
- Name the new as set g2
- Set the prototype of g2 to g1
- Open g2, make it look like this:
![image](https://user-images.githubusercontent.com/57644882/155294810-ef624ee5-8bde-4888-a2a3-3ebacaaacd23.png)
- In the prototype picker of g2, choose propagate to prototype:
![image](https://user-images.githubusercontent.com/57644882/155294974-fe00476a-3e69-4a49-a3d4-5ad45bf7bdc2.png)
- Both g1 and g2 now look like this:
![image](https://user-images.githubusercontent.com/57644882/155295052-e8c6103d-dde6-4400-b1ad-4cde71128f5a.png)

Here's what goes wrong: `propagate_object` and `propagate_property` in `the_truth.c` need a `lookup` just like `clone_object` does and they also need to pre-build the propagation hierarchy just like in the clone case. This is because the propagation may clone new objects, and if there are internal references among the cloned objects, then those will break. This is why the connections disappear, because their references are to the old nodes that were cloned without having a lookup with which to resolve references etc.

Although I see what's wrong, the difference between the propagate and clone case stumped me a bit and I don't have time to set myself into how it works right now. If you don't have time to fix it anytime soon @niklas-ourmachinery then I can have a look some time after the release.

**Comment by niklas-ourmachinery** [comment]
Yes, I have lots of other stuff on my plate, so would be great if you could look into this.

**Comment by Tisten** [comment]
Does this by an chance have anything in common with https://github.com/OurMachinery/themachinery-public/issues/1124? It too is about entity graph prototype/instance? Just thinking if you got two birds with one stone here?

**Comment by karl-zylinski-ourmachinery** [comment]
Unfortunately, no, but I'll look at that one soon.
