### ISSUE TITLE
Importing Dcc Asset over collaboration is broken

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1085]
- **Version:** Git Master Branch
- **OS:** Windows

Start two the-machinery, one as host and one as client, let the host use the default project. Now import a dcc_asset from another project, and push the "Extract Assets" button on the imported dcc asset. This will create an entity where the mesh is visible on the client, but not on the host. Save the project from both editors results in a difference in a material.tm_creation
Client says:
```
		cached_node_result__instantiated: [
			{
				__uuid: "79dd3d07-88dc-6e73-4281-9c0a53ad0e0e"
				__prototype_type: "tm_graph_cached_node_result"
				__prototype_uuid: "56a82071-a5d5-3bc9-c255-1d5e818ddd41"
				node: "bab5341e-b49f-1e32-a616-4dd3ea5de3bb"
				validity_hash: "a2cd6856a13eabec"
				object: {
					__type: "tm_shader_system_compiled_result"
					__uuid: "535d35af-009f-da03-d216-29d9efc6e1a6"
					name: "a2cd6856a13eabec"
					buffer: "ea2bf1f6e5b524e5"
				}
			}
		]
```
Host says:
```
		cached_node_result__instantiated: [
			{
				__uuid: "79dd3d07-88dc-6e73-4281-9c0a53ad0e0e"
				__prototype_type: "tm_graph_cached_node_result"
				__prototype_uuid: "56a82071-a5d5-3bc9-c255-1d5e818ddd41"
				node: "bab5341e-b49f-1e32-a616-4dd3ea5de3bb"
				validity_hash: "a2cd6856a13eabec"
				object: {
					__type: "tm_shader_system_compiled_result"
					__uuid: "535d35af-009f-da03-d216-29d9efc6e1a6"
					__prototype_type: "tm_shader_system_compiled_result"
					__prototype_uuid: "bc7b07cf-e094-37f6-8413-28c015a9f621"
				}
			}
		]
```

**Comment by simon-ourmachinery** [comment]
I have a few questions:

1. Now import a dcc_asset from another project
Means I import this asset from a different TM project, not an actual asset?

2.  Now import a dcc_asset from another project, and push the "Extract Assets" button on the imported DCC asset.
Does it matter who does it? Host or client?

**Comment by karl-zylinski-ourmachinery** [comment]
Tried some different variations and can't repro. Similar to Simon's questions I would like a more detailed step-by-step repro with info about who does what.

**Comment by Tisten** [comment]
To make this extra clear:
I also to the "Extract Assets" on the client.
And I have done the import both with and without the "Match References On Import" feature flag.

Another interesting case you might want to look at is to do "Undo Undo Redo Redo" on the client a few times after extracting the assets. I have gotten both the client and server to crash by doing this. I showed Karl one such crash so he is aware of that case.

**Comment by karl-zylinski-ourmachinery** [comment]
This should now be fixed in master. It was due to me using `set_uuid` in the cached node results code, which broke collaboration. I do this to make the data more stable and merge friendly. Can we sync UUID changes over collaboration somehow @niklas-ourmachinery? Otherwise set_uuid seems like something bad to expose in the API.

**Comment by Tisten** [comment]
I can confirm that it is fixed.

But as Karl explained, the data is different when saving on both host and client after the fix, but not the difference is a UUID of a tm_shader_system_compiled_result. Harmless but bad if anyone is using version control to store the data.
