### ISSUE TITLE
Property tab sometimes get automatically cleared 

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1088]
- **Version:** Git Master Branch
- **OS:** Windows

With the Simulation tab docked next to the Entity Graph tab the Properties tab ends up in a state where it's properties get automatically cleared. If I select an entity or component in the Entity Tree the properties just flicker.

![properties_get_cleared](https://user-images.githubusercontent.com/91697782/155550780-6be970a3-b462-497f-87c0-f4e91d1aaac3.gif)

**Comment by ElementalAndy** [comment]
This behavior stops if I close the Entity Graph tab.

**Comment by leonardo-ourmachinery** [comment]
I'd like to fix this for the release, but I'm not able to repro it. 

Are you able to repro it consistently? If that's the case, Can I ask you for some detailed repro steps?

**Comment by ElementalAndy** [comment]
I can try and repro it tomorrow. I did get it earlier today but I don't have any reliable steps to reproduce yet.

**Comment by ElementalAndy** [comment]
I attached a small project that should make this easy to reproduce.

1. Open the world entity.
2. Open the graph entity's graph in the Entity Graph tab.
3. Start the Simulation from the Scene tab.
4. Dock the Entity Graph and the Simulation tab next to each other.
5. Open the Entity Graph Debugger and click the running graph instance.
6. Click in the Simulation tab to give it focus and press space on your keyboard to trigger the delay node in the graph.
7. While the delay is running go back to the Graph tab and edit it e.g. move a node.
8. Now click a node or component in the Entity Tree tab and observe the Properties tab flickering.

[properties_tab_issue.zip](https://github.com/OurMachinery/themachinery-public/files/8162754/properties_tab_issue.zip)

**Comment by ElementalAndy** [comment]
I get the same behavior with other nodes that have a "lifetime" e.g. tweening nodes.

**Comment by leonardo-ourmachinery** [comment]
I've pushed a fix to master, so the bug should be gone now.
Though I'll leave the issue open as I'd like @simon-ourmachinery to verify that the fix is correct.
