### ISSUE TITLE
the-machinery considers double mouse down events with no up event in between as a double click

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1089]
- **Version:** Git Master Branch
- **OS:** Windows

When debugging the-machinery, and wanting to understand what the tm_tt_id_t I have at my breakpoint is, I have started to run a second the-machinery session to use the truth inspector. And sometimes when I debug collaboration I might start even more instances.

While having one the-machinery stuck on a VS breakpoint, the other editors have sometimes started to get multiple events per mouse click. So a single click results in 2 mouse down events, and then 2 mouse up events. This is interpreted by the-machinery as a double click, so every click everywhere now suddenly becomes double clicks. I can't blame the-machinery for the double events, these are coming from the windows messaging (and they are identical except for the timestamp), but I would like the-machinery's code to only consider a mouse down followed by a mouse up as a click, and a double click should be mouse "down - up - down - up", not just "down - down".

**Comment by niklas-ourmachinery** [comment]
Fixed in master. If you discover the source of the double events would be interesting to know... I don't think that should happen.

**Comment by Tisten** [comment]
I haven't gotten this since the fix.
