### ISSUE TITLE
Deadlock on collaboration server in `changelog_size()` (the_truth.c)

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1091]
- **Version:** Git Master Branch
- **OS:** Windows

We have had two deadlocks in this code on our headless collaboration server running on a 2 core machine this week:
https://github.com/OurMachinery/themachinery/blob/8bc8ab5d77754493e082d1526429a48bebe04834/foundation/the_truth.c#L1638-L1645

I have not gotten this previously, so my suspicion is that the fix with `wait_for_task()` might be involved? (commit f5aa67e196835bcec135507b485246b193cd5945 and https://github.com/OurMachinery/themachinery-public/issues/1051)

I don't really grasp why the deadlock happens. Only a single thread is active, and it waits on the `changelog_cs` critical section. So no other thread owns that CS, but the thread still wont wake up and take the lock. There are no scope issues where the section isn't unlocked in the right way. Is there any way that `serialize_changes()` could make a fiber switch or such?

I don't have a repro, so just submitting this issue in the hope to hear your thoughts.

**Comment by Tisten** [comment]
I just got this on my 12 core machine now, so it has nothing to do with low cores.

I think @karl-zylinski-ourmachinery just suggested the right reason. This seems to happen when importing changes from disk, or loading a new project while being a collaborator host.

**Comment by karl-zylinski-ourmachinery** [comment]
After talking to @Tisten, one guess is that `changelog_cs` is dead and belongs to an old truth, since this happens during project load. Perhaps it is trying to send a changelog for a dead Truth.

**Comment by Tisten** [comment]
I can verify that the truth which owned `changelog_cs` truely is dead:
![image](https://user-images.githubusercontent.com/6726075/155610887-9bdbe2cd-a783-4fd5-9491-f446d6c7df0f.png)

**Comment by Tisten** [comment]
I got this again today. :/

**Comment by karl-zylinski-ourmachinery** [comment]
@Tisten Can you post the callstack next time this happens?

**Comment by niklas-ourmachinery** [comment]
Probably fixed in master.
