### ISSUE TITLE
`tm_primitive_drawer_api->stroke_capsule_profile` renders capsule sideways.

### ISSUE THREAD

**Issue by frank-ourmachinery** [OurMachinery/themachinery-public#1096]
- **Version:** Git Master Branch
- **OS:** Windows | Linux 

The capsule rendered by `stroke_capsule_profile` renders the capsule on its side instead of straight up.
This capsule way drawn using `half_height = 5` and `radius = 1`
![image](https://user-images.githubusercontent.com/70658773/155839380-db55bcab-9235-4e68-a244-1aa50bc05f94.png)

**Comment by niklas-ourmachinery** [comment]
I think this could be regarded as a documentation bug... this is fine as long as the documentation specifies what the "up" axis of the capsule is.
