### ISSUE TITLE
The OS Open and Save file dialogs should be modal

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#11]
OS file dialogs need to be modal, I can click on the ui and the file dialog goes to back of window

**Comment by niklas-ourmachinery** [comment]
Note: By settting the `hwndOwner` flag of the `OPENFILENAME` struct, we can make the `GetOpenFileName` window modal with respect to its "owner" window.

However, this still allows the user to activate other windows in the application.

**Comment by niklas-ourmachinery** [comment]
**Implementation note:** It might be possible to prevent the activation of other windows by intercepting `WM_ACTIVATE` and/or `WM_MOUSE_ACTIVATE`, but I'm not sure if that is the "right" way to do it.

Asked twitter: https://twitter.com/niklasfrykholm/status/1214321108469465093?s=20

**Comment by niklas-ourmachinery** [comment]
**Implementation note:** Or maybe the right thing to do, is to use `EnableWindow()` to disable all other windows in the application while the dialog box is showing.

**Comment by nekitu** [comment]
it should work when the tab windows are popups of the main window (like in traditional MFC MDI apps), the open file dialog should be then owned by main window, hence all other windows will stop being clickable while open file is active. But I don't know how your windows are created.

**Comment by nekitu** [comment]
> **Implementation note:** Or maybe the right thing to do, is to use `EnableWindow()` to disable all other windows in the application while the dialog box is showing.
> 
> https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enablewindow

sure, it could probably work if you control the open file dialog startup, hidden from user of the api.

**Comment by niklas-ourmachinery** [comment]
We don't really have a "main window" -- all the windows are on equal footing. Same as in Chrome for instance -- no window is more "main" than any other.

**Comment by nekitu** [comment]
ok then, if you have the list of windows, try use the enable/disable trick.

**Comment by niklas-ourmachinery** [comment]
Calling `EnableWindow(wnd, false)` on the other windows prevents the user from activating them by clicking on them, but she can still Alt-Tab to them, putting them on top of the "modal" dialog. I think this will have to do for now though, until I either find an "official" recommended way of doing this, or we implement our own file dialogs (which we probably want to do long term anyway, so that we can have file dialogs that work in VR).
