### ISSUE TITLE
Machinery stuck in infinite loop allocating memory in `bezier_path()`

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1100]
- **Version:** Git Master Branch
- **OS:** Windows

Somehow one of our entity graphs got a few bad wire splines, with NaN values in the curve points.
This made this loop allocate some >70GB before the editor blew up:
https://github.com/OurMachinery/themachinery/blob/d3acb204d4f65e3b078074225ae2da0018680f3c/plugins/ui/draw2d.c#L1436-L1457

If we can find a repro for how those NaNs came to be then a separate issue will be created, but there needs to be a fix for the loop because when the NaNs have been added the graph can't be opened, so the wires can't be deleted.

In our local version we just set all NaN values to 0 before evaluating the splines.

**Comment by niklas-ourmachinery** [comment]
Thanks, I think we can just put a hard limit on the number of iterations.

**Comment by niklas-ourmachinery** [comment]
Fixed in master.
