### ISSUE TITLE
Issues when box-selecting nodes and create subgraph

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1102]
- **Version:** Latest Binary Release
- **OS:** Windows

When selecting nodes in graph and go to create subgraph. The created subgraph dissappears into space, far off the graph canvas.

This is also causing this issue: https://github.com/OurMachinery/themachinery-public/issues/1100

Furthermore, after closing graph and trying to re-open, the entire graph canvas is just completely black and I cannot work more inside it.

**Comment by karl-zylinski-ourmachinery** [comment]
Can't reproduce. Here's what I did:

![image](https://user-images.githubusercontent.com/57644882/156794622-bb629f58-104e-48a8-83c2-ed013eee23fe.png)

![image](https://user-images.githubusercontent.com/57644882/156794651-a62f83db-43d3-413b-87ef-6112dee58d75.png)

Did you do it differently somehow?

**Comment by TobiasElemental** [comment]
I did exactly that, but inside a prototyped entity_graph. I mean not created one but inside one.

**Comment by Tisten** [comment]
@TobiasElemental I can't repro neither. Does this always happen, or was it for a specific graph? Could you create a repro project where this happens?

**Comment by TobiasElemental** [comment]
I can't repro this anymore... Closing until it happens again.
