### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1118]
A huge thing for scripting in graphs would be to have arrays on variables, and the ability to refer to stored values in those arrays as a list/enum type of thing.

Current workflow if one wants to "make lists" that can be added to, removed, or retrieved from is very cumbersome and hacky work-arounds prone to a lot of error.

This would also need to come with accompanied nodes for ease of use with adding, removing, or referring to a specific number in a "list-variable".

**Comment by simon-ourmachinery** [comment]
Duplicate #1024
