### ISSUE TITLE
Add a different icon for error messages in the Graph Editor

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#1122]
@niklas-ourmachinery  suggested:
> I like the way the errors in the graph are shown now... but I think they need a different icon:
The icon doesn't read very well at small font sizes.
It can be interpreted as a "close" icon rather than an "error" icon.
I wonder if we should use :no_entry_sign: or :exclamation:or maybe just the regular ! in red color

![image](https://user-images.githubusercontent.com/70658708/156799612-9cb64f09-d42d-43ff-8cf1-04a222c73f41.png)

@karll-ourmachinery  suggested:
![image](https://user-images.githubusercontent.com/70658708/156799666-58261ca6-7756-48e3-a1f3-c65b2432dc37.png)

I suggested maybe a red corner would be a good idea:
![image](https://user-images.githubusercontent.com/70658708/156799795-4b033e42-4053-4e80-a3e9-8348b543e59a.png)

@karl-zylinski-ourmachinery disagreed with the position on the right he suggested on the left:
> maybe the error marker could be on the left instead
since:
> Sometimes they are both instanced and have an error

I think about the last part its a try an error the first part is more important.

**Comment by karl-zylinski-ourmachinery** [comment]
![bild](https://user-images.githubusercontent.com/57644882/171201471-efc693e3-4280-4853-8da9-579817670ca6.png)

I found a suitable ION icon, it looks like this now.
