### ISSUE TITLE
Teleporting boxes on duplication

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1125]
- **Version:** Git Master Branch
- **OS:** Windows

Duplicating boxes causes one of the boxes to teleport away from its intended position.
![image](https://user-images.githubusercontent.com/21057342/156906391-6ca6acb3-4ff5-4f2a-bd77-22b96cdfc59b.png)

**Comment by niklas-ourmachinery** [comment]
Could you provide more detailed reproduction steps?

**Comment by DaveTheGameDev** [comment]
@niklas-ourmachinery  Add a cube to the scene, select it and press ctrl+d, without deselecting, move the new cube to a new position, press ctrl+d again and the new cube should duplicate adding the position difference you just moved the last cube

https://user-images.githubusercontent.com/21057342/156914972-137d6143-a1ae-4372-8355-96ad9b2df98f.mp4

.

**Comment by Tisten** [comment]
Sounds like a feature! :D

**Comment by simon-ourmachinery** [comment]
Could be related to #705

**Comment by Tisten** [comment]
Brilliant, it is a feature! Feels a bit inspired by the fill behavior of some spreadsheet editors.

**Comment by DaveTheGameDev** [comment]
In this case it's a bug because it only affects a single cube lol. If you duplicate a row of them only 1 teleports.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master. We're close to reaching feature parity with Excel.

Though I personally think that if the user moves the duplicated entities via the gizmo we should "reset" this duplication behavior.
I'll leave that decision to @karl-zylinski-ourmachinery

**Comment by DaveTheGameDev** [comment]
> Fixed in master. We're close to reaching feature parity with Excel.
> 
> Though I personally think that if the user moves the duplicated entities via the gizmo we should "reset" this duplication behavior. I'll leave that decision to @karl-zylinski-ourmachinery

@leonardo-ourmachinery @karl-zylinski-ourmachinery  I feel like exposing a setting would be nice. Sometimes its nice to just move from the origin of the original transform tbh.

**Comment by DaveTheGameDev** [comment]
@leonardo-ourmachinery Looks like this was only partly fixed
The entire line now moves forward, but I have the entire `n*n`  top layer selected
![image](https://user-images.githubusercontent.com/21057342/158573306-f6485eee-f3a7-4c4e-a13e-4c3955fde920.png)

**Comment by simon-ourmachinery** [comment]
@leonardo-ourmachinery I re open this issue

**Comment by leonardo-ourmachinery** [comment]
Fixed in master: the duplication offset should only be applied (to all entities you are duplicating) if the entities that you are duplicating are _exactly the same_ ones that you cloned the last time.
