### ISSUE TITLE
"Local variables" inside graphs / sub-graphs

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1127]
The fact that all variables that belong to a graph either in sub-graph, instantiated prototyped subgraphs, or the graph itself all live in the same "universe" and will write over each-other if referred to comes with two problems:

1. Readability of knowing (not knowing) if a variable with the same name exist in the graph somewhere else. This problem becomes apparent if there are a bunch of sub-graphs on various depths and layers in a more complex graph that maybe multiple people are working on different sub-graphs that go into the same graph.

2. The potential power of sub-graphs is kind of reduced to folders to clean up visual scripting, as opposed to allowing the user to create functions and workflow improvers using subgraphs to create their own specific nodes to be used many times in the same graph.

I have two examples of this from nodes I created with prototyped subgraphs that are replicas of common flow nodes used in Unreal.
![image](https://user-images.githubusercontent.com/99493598/156996875-e3edf6b7-e7e4-4bdd-8066-208afbaac5e8.png)

Inside these nodes there is a simple bool that needs to be set to various values or nullified.
This works like a charm, until I want several of these in different places inside a graph, as they will write over all instances of this bool variable because it is considered to be the same variable.
![image](https://user-images.githubusercontent.com/99493598/156997323-6c909000-1458-42a3-9637-deec2eeafffa.png)

My suggestion to implement would be one form of optional setting on variables to "local", or something along those lines.
What local would mean is that a variable can only be written directly to with "set <> variable" inside the same graph-space, not above and not below.

**Comment by karl-zylinski-ourmachinery** [comment]
My take on this is that the variables should always be "local" and that this is just a oversight from when we introduced subgraphs. I'll look into making the names used behind the scenes, within the graph interpreter, unique.

**Comment by niklas-ourmachinery** [comment]
Should we have a way of referring to variables in subgraphs? Or is it perhaps cleaner to always go through the Input node if we want to change any variables in the subgraph.

**Comment by TobiasElemental** [comment]
I think it is important that there is an option to have some way to write directly to variables that are in subgraphs, but also FROM a subgraph out to its "parent", without having to use input/output. It can become quite messy otherwise.
The options I then have is either to have a bunch of relaying with sending data from variables to each other with the same purpose or name, that could have just been the same variable, Or a cumbersome workflow to always have to pull out both the value, and the event to then set the variable on the outside where it exist. Or a ton of circling wires in and out all over the place in between different subgraph nodes.

I guess this is why I landed in a setting to make local if you just want to make genericly named variables like "is_dirty" or whatever and be able to have multiple of those subgraphs all over the place in a graph without them writing to each other. Could also be the other way around, they are inately local but if you make them public they can be written to directly from anywhere and referred to from remote places.

A common workflow in other engines (unreal, snowdrop, frostbite) that I guess I am used to is that you create your "global" variables in the parent graph (component) that can always be referred to and written to from any layer within it and outside. But variables in sub-graphs or specified as local cannot.

**Comment by karl-zylinski-ourmachinery** [comment]
Looked a bit more at this. While I could add a 'global' flag to all variable nodes, currently we would have to have the 'global' flag on both the Get and Set nodes. This becomes a bit awkward. We have been toying around with the idea of adding explicitly defined variables, i.e. a graph has a list of variables it exposes and those can be selected from a picker in the get / set nodes. When you add new variables to this list, then you could add those as global if you wish.

**Comment by TobiasElemental** [comment]
@karl-zylinski-ourmachinery this solution sounds very similar to how ue4 doea it and would be a great improvement IMO.
It would also hit two bird's in one stone and eliminate my frequent losing / forgetting about old unused variables that lie around in my scripts as well as stop my quick fingers from mistyping the names / having to find variable and copy-paste when getting variables. 

One would still have to type when setting/getting remote variables so I guess that still needs to be supported.

**Comment by simon-ourmachinery** [comment]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/70658708/174820834-5291423c-d680-4bb5-b19d-62ed85ac253f.png">

You have 2 flags per variable to manage their visibility:
- The first flag manages if you can access the variable in a parent graph or subgraph
- the second flag manages if you can access the variable from outside of this graph (remotely)
