### ISSUE TITLE
100% CPU usage when editor has focus

### ISSUE THREAD

**Issue by sY9sE33** [OurMachinery/themachinery-public#113]
This happens even in an empty scene.

![machinery_cpu](https://user-images.githubusercontent.com/9271353/74489646-dd689880-4e93-11ea-8674-f138f37cc170.PNG)

**Comment by niklas-ourmachinery** [comment]
That's surprising, my CPU usage on a mostly empty scene is around 30 % -- of this about 20 % is the engine and the rest is other processes on my machine.

![image](https://user-images.githubusercontent.com/26548514/74490637-0847f200-4e7e-11ea-9b70-8cae8d527346.png)

The engine targets 60 Hz, but it looks like you're not even achieving that, even with all your CPUs at 100 %. Looks fishy, Can you open the profiler view and try to figure out where all this time is being spent?

On a separate note, we should probably implement something like an "interaction mode" where we only re-render if the user is actually interacting with the engine (clicking on things, hovering, etc). This should cut down on the CPU usage.

But it looks like something else is going on in your case, so I'd like to figure out why.

**Comment by sY9sE33** [comment]
Here's a trace file of running in an empty scene: https://drive.google.com/open?id=1frXzFHalALmvCKOq8rWCviWgA1Wn6Kyj

Tick application seems to take about 250ms each run and it doesn't actually seem to run anywhere other than on a single thread. Very strange.

**Comment by sY9sE33** [comment]
Though opening it in chrome show's a pretty different picture...

**Comment by niklas-ourmachinery** [comment]
Ok, I took a look at your trace file and I'm a little bit confused:

![image](https://user-images.githubusercontent.com/26548514/75176104-62e81600-56e8-11ea-93b8-a44849d0a81d.png)

Here I've marked an approximate frame in the output. As you can see, the frame is only about 5 ms second long. That would indicate that you are running at 200 FPS, which is not what I saw from your screenshot. Also, our engine should look at 60 FPS, so it shouldn't happen. It would however explain using 100 % of the CPU. Do you see the engine running at 200 FPS when this happens?

**Comment by sY9sE33** [comment]
Yeah 200FPS sounds correct. I think in the screenshot, it's just because I used the windows snipping tool which removes focus from the engine which is why it's displaying lower than that. I'm going to try running on other PCs I have laying around to see if I can either reproduce it, or at least get some insight as what's taking up all the CPU.

It is a 10+ year old CPU, though, so it may be something out of the ordinary on such an odd system.

**Comment by niklas-ourmachinery** [comment]
Ah that makes sense... if you disable vsyncing we will run as fast as possible which will result in 100 % CPU usage. I will close this issue.

@tobias-ourmachinery Do you think we should do something more to cap the framerate in case vsync is disabled... or should we consider that to be "what the user wanted" in that case?
