### ISSUE TITLE
Corrupt rotations and scale in entities on collaboration server

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1131]
- **Version:** Git Master Branch
- **OS:** Windows

F.Y.I: Recently we have started getting more and more objects which dissapear in entities, and where the gizmo looks strange when we click on the entity. When debugging the cause we found that these have transform components of these entities looks like:
```
								components: [
									{
										__type: "tm_transform_component"
										__uuid: "990e6212-0060-bec0-4c97-0a967fe1d8a8"
										local_position: {
											__uuid: "aeb33765-43cb-cd73-732b-d843f7a7400b"
										}
										local_rotation: {
											__uuid: "bc8df353-f8c9-fba5-e8ab-d86588e997cf"
											w: 0
										}
										local_scale: {
											__uuid: "70f9c2c5-fafa-5d70-1c24-883fc052f66f"
											x: 0
											y: 0
											z: 0
										}
									}
								]
```
We have no idea how the data became this way, but having all zeroes in the quaternion rotation is a bad thing, and the scale doesn't help neither.
The visual result of the gizmo is:
![image](https://user-images.githubusercontent.com/6726075/157062218-5889f183-b348-4548-8fea-8ff4ed763094.png)

Perhaps adding an assert against all zero rotation or scale, or other transform validation could to warn about when this type of data gets introduced?

**Comment by Tisten** [comment]
Found how this happens now. Fixing this issue is high prio for us

Repro:
* Open two editors and set them up with collaboration.
* Drag a dcc_asset into the client and "Extract Assets" with rigging (all other checkboxes unchecked in my case).
* Open the created entity in the client.
* Now drag and drop the dcc_asset into the root of the entity on the client.
* Now open the entity on the host and note that nothing is visible.
* Save the project in both editors and diff the output

The host will have this which the client wont:
```
		components: [
			{
				__type: "tm_transform_component"
				__uuid: "de61662b-78a8-103f-bd3f-6e2fbea30ce7"
				local_position: {
					__uuid: "d8839b3b-dd31-d998-df42-33f6c4ce9790"
				}
				local_rotation: {
					__uuid: "a22ce028-2331-92ac-4c33-9308c06e2e4b"
					w: 0
				}
				local_scale: {
					__uuid: "51461407-8cde-feac-4445-68be8dd8673c"
					x: 0
					y: 0
					z: 0
				}
			}
			{
				__type: "tm_scene_tree_component"
				__uuid: "3361f6fd-ee64-3aad-822d-c956443a7b6e"
				node: "49a82c59bf98829b"
				node_names: "c43d60f3ee92b981"
				asset: "7018af59-6bf7-0b7e-2635-23f805b9054f"
				asset__type: "tm_dcc_asset"
			}
		]
```

**Comment by karl-zylinski-ourmachinery** [comment]
Simpler repro case: Drag any DCC asset into the scene tab on the client, it will be broken on host. Looking into it.

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/2620798853ceb0cf0a5a198c116a4a1fc398d4b2
