### ISSUE TITLE
`TM_RENDERER_BUFFER_USAGE_VERTEX` is unable to be used.

### ISSUE THREAD

**Issue by frank-ourmachinery** [OurMachinery/themachinery-public#1140]
With our current vertex buffer system, there is no way to bind a vertex buffer as they are handled as storage buffers instead.
When issuing a draw call there is currently also no way through the command buffer to indicate that a buffer should be bound as a vertex buffer. We should consider either removing the usage flag or add a code path that allows the user to specify a vertex buffer, just like we do with index buffers.

**Comment by tobias-ourmachinery** [comment]
I think we should begin with removing the flag, its some old left-over from the early days. I don't see much point in adding support for doing vertex fetching through the input assembler, IMO it's easier to just load the data directly from storage buffers.
