### ISSUE TITLE
Spawn entity into a parent entity / set parent

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1141]
It would be great if the spawn entity node had an input for runtime entity that would be "parent entity" that would instantiate the spawned entities as children to this entity.
If nothing is input, it could work as it does now.

If not in the spawn entity node, another solution could be to have a node for entities that would be "set parent" or "set child" that would "shove" an entity into another entity.

**Comment by leonardo-ourmachinery** [comment]
I added a `Set Parent` Node.
Eventually we'll also probably implement something like `spawn_entity_with_parent`, but that will be a bit different since it will also modify the "ownership" of the children, not only the transform parent like we're doing here.
