### ISSUE TITLE
The `tm_ui_popup_item_picker_api->pick_asset()` doesn't show the address to the asset

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1146]
- **Version:** Git Master Branch
- **OS:** Windows

When having multiple assets with the same name then the asset picker doesn't work.
https://github.com/OurMachinery/themachinery/pull/888 fixes this issue

A better fix would be to use the properties asset picker, but it is not available through the api.

**Comment by simon-ourmachinery** [comment]
related: https://github.com/OurMachinery/themachinery/pull/896

I think we should replace all pickers (as possible) from the property view with the picker `tm_ui_popup_item_picker_api`in their core so we reduce the same code over the code base and a reusable way.
