### ISSUE TITLE
`set_parent` modifies the world position of the entity

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#1148]
I personally think that `tm_transform_component_api->set_parent()` shouldn't modify the _world_ position of the entity, but just adjust it's local position to match the new parent instead, thus leaving the entity as it is.

Feels a bit counter-intuitive to me.

**Comment by tobias-ourmachinery** [comment]
Nah, I don't agree. From the code side of things I think the _local_ position should be consistent after changing parent. 

E.g. when linking an object to a characters hand, you'd expect the object to move in the world to end up in the characters hand without having to first calculate that world position before calling `set_parent()`.

In the editor reparenting should preserve the world position, but that's already behaving correctly.
