### ISSUE TITLE
Emission bugs

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1149]
- **Version:** Git Master Branch
- **OS:** Windows

Emission shows graphical issues when DOF  is enabled and camera is close up to object

![image](https://user-images.githubusercontent.com/21057342/158014930-d1eb16fc-5844-457f-a31a-c3a73a405dab.png)
![image](https://user-images.githubusercontent.com/21057342/158014943-26c67240-b89d-44d9-819c-0c180e0ad67d.png)
![image](https://user-images.githubusercontent.com/21057342/158014997-eb522536-70f2-47ae-8017-f93b9b78fc6f.png)

Smaller issue that occurs is adding a light to an emissive object to simulate GI causes flickering. Not sure if its easy to reproduce so I thought I would mention it here.

**Comment by frank-ourmachinery** [comment]
The border around the object seems like an off-by-one error in the DoF shader when it's combining the foreground/background with the in-focus area. I don't think it has anything to do with emissive.

**Comment by DaveTheGameDev** [comment]
Yeah probably not, but it is was very noticeable with the emission being the focused area 🙂

**Comment by frank-ourmachinery** [comment]
Should be fixed in master now.
