### ISSUE TITLE
Some set entity nodes shows error when wanting to set variable to null

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1153]
Latest Binary Release
Windows

The new set 'parent node' and the 'set remote entity variable' does not allow user to set value to "nothing" - to clear variable of reference.

![image](https://user-images.githubusercontent.com/99493598/158169541-f141c35e-4024-433d-b2bc-49537ab3327f.png)
![image](https://user-images.githubusercontent.com/99493598/158169861-ec037688-a456-402d-bcdb-9cb89ce0d3a4.png)

This however works with the 'set entity"node.
![image](https://user-images.githubusercontent.com/99493598/158169954-432b3aaf-a82b-4c68-9a38-57174e160683.png)

**Comment by TobiasElemental** [comment]
In the case of the set parent I guess there always is a parent, as the world in which everything lives in is also an entity.
Maybe then a "remove parent" node is the solution, where the entity is broken out of the entity that was set as parent into... whatever the highelst layer entity in the game is?

**Comment by TobiasElemental** [comment]
Sorry, I guess a work-around is to just store "the world" entity in a variable and then set that as new parent, as opposed to removing parent. Not so intuitive but I guess would work just as well.

**Comment by leonardo-ourmachinery** [comment]
I made it so that the Set Parent node will "unset" the parent if you pass "NULL" to it.
This means that the "Local" transform of the entity will become it's world transform.

Regarding the `Set_entity_*_variable` nodes I think you'll have to wait a bit more as there's an ongoing restructuring of how the variables work... not sure what's the ETA of that. Let's leave the issue open for now.

**Comment by niklas-ourmachinery** [comment]
For **Set Entity Variable** I still think we want to show it as an "error" if no input is connected... to reduce the risk of user errors.

Two other options for setting null:

1. We could have a node that outputs a "nil entity" that you can connect to *Set Entity Variable*.
2. We could have a *Clear Entity Variable* node.

I think (2) might be the best option.

**Comment by TobiasElemental** [comment]
If you want the error there, you should also then have it for the regular "set entity" variable that currently allows to be set to null so it is consistent.

Option 2 sounds clean. In this case a node for "Clear remote entity variable" also needs to exist then.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
