### ISSUE TITLE
Can't do "Replace With Asset..." on an overridden entity

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1158]
- **Version:** Git Master Branch
- **OS:** Windows

Repro steps:
* Create an Asset Entity and "Open" it
* Add an empty "Child Entity" to the root of the Entity Tree
* Right click on the Root, select "Prototype (Advanced)->Created Prototype From Entity"
* In the new entity, right click on on the "child entity" and choose "Override"
* Right click on on the "child entity" and choose "Replace with Asset..." and pick any entity, e.g "core/geometry/plane.entity"
* Note that the entity didn't become a plane, but lost its overridden state.

**Comment by leonardo-ourmachinery** [comment]
The "Replace with Asset..." menu is not supposed to be shown for "overridden" children, for the same reason I described in #1155.

I made it so that it's now hidden for Overridden children.
