### ISSUE TITLE
Can't directly remove an entity which is overridden

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1159]
- **Version:** Git Master Branch
- **OS:** Windows

In an entity instance, where one of the prototype's entities has been overridden, there is no option to immediately "remove" the whole overridden entity via the context menu. You first need to remove the override, and then do "Remove from This Instance". This two step operation is confusing.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
I have refrained from implementing the opposite (removed -> overridden in a single step), I think we want that to be an explicit two step process.

**Comment by Tisten** [comment]
I agree. Thanks for the fix
