### ISSUE TITLE
Crash when opening the "Truth Inspector"

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1160]
- **Version:** Git Master Branch
- **OS:** Windows

When trying to open the "Truth Inspector" tab in my project, the editor crashed on a nullptr access in `plugins\editor_views\graph.c` with this callstack:
```
>	tm_editor_views.dll!input_properties_display_name(const tm_the_truth_o * tt, tm_tt_id_t object, char * buffer, unsigned int size) Line 9143	C
 	tm_editor_views.dll!get_display_name(const tm_the_truth_o * tt, tm_tt_id_t object, char * buffer, unsigned int size) Line 2802	C
 	tm_the_truth_inspector.dll!get_name_if_exists(const tm_the_truth_o * tt, tm_tt_id_t object) Line 518	C
 	tm_the_truth_inspector.dll!private__load_temporary_objects_task(void * data, unsigned __int64 task_id) Line 1288	C
 	the-machinery.exe!process_one_task() Line 77	C
```
The `tm_tt_id_t object` seems valid, but `tm_the_truth_api->owner(tt, object);` returns a null object, and then the whole chain of "owner -> owner -> type -> aspect" makes the aspect pointer null so `aspect->io_type_interface_name` becomes a nullptr access

**Comment by simon-ourmachinery** [comment]
Note to me: sounds like a bug in the "new" way of gathering entity names which seems not be be task save when running in a task.

**Comment by simon-ourmachinery** [comment]
https://github.com/OurMachinery/themachinery/commit/1b9daaa335946b1da5483abff2253d84dceec397

**Comment by simon-ourmachinery** [comment]
I think @tobias-ourmachinery  fixed this. Thanks!
