### ISSUE TITLE
Add "Make unique" for inherited entities/components

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1162]
- **Version:** Git Master Branch
- **OS:** Windows

When having an entity instance, inheriting child entities and components from the prototype, it would be very valuable to be able to convert the inherited data to instead live in the entity instance. This will make it possible to clean up prototypes without destroying the instances, by first making prototype data unique in the instances, and then removing the prototype data.

**Comment by niklas-ourmachinery** [comment]
So at the end of this you would have an entity with:

* The inherited component removed.
* A new component of the same type, which is essentially a "Make Unique" version of the inherited component.

?

**Comment by Tisten** [comment]
Yes, exactly.

I tried with an experiment to see how to do it today. I atttempted to remove the "Light" and "Cubemap Capture" from the "sky" entity in "core", and move them into the "default_world" entity's sky, and it is not that terrible. This is what it ended up with:

* New Project
* Make "default_world" the prototype of "world"
* Override "sky" and set the "Intensity" of the "Light" component to 1.
* Create new components in "default_world" in a temporary entity.
* Copy paste the values from the inherited sky components
* Removed the components in sky
* Move the components from the temporary entity into the inherited sky.
* Done!

BUT, and this is the deal breaker: The override in world with intensity:1 is now gone.

**Comment by Tisten** [comment]
The workflows described are what I wanted. And the name is fine by me.

What still doesn't work is the deal breaker described in my answer to Niklas.

In a inheritance chain of 3 entities (base entity, middle instantiated entity, top instantiated entity), if the top one derives from the middle which derives from the base, then making something unique in the middle should not remove the overrides made in top. This is broken for both components and entities right now.
