### ISSUE TITLE
Publishing builds causes memory leak and crash

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1166]
- **Version:** Git Master Branch
- **OS:** Windows

Publishing through the CLI and the Publish window does not work currently on my computer.
There are no logs after it says it has started publishing.
![image](https://user-images.githubusercontent.com/21057342/158263983-f964bf9a-fed3-4998-b04b-4376bdd3e60d.png)

Repro steps are:
1) Open default project
2) Publish build through tab or CLI

**Comment by DaveTheGameDev** [comment]
This is what my memory window looks like when attempting a build
![image](https://user-images.githubusercontent.com/21057342/158313511-fc914020-798a-46b8-8869-1a40a711d4cb.png)

**Comment by DaveTheGameDev** [comment]
Quick side note. I only have 32GB of RAM haha.

**Comment by minirop** [comment]
Happens also on linux. Takes all 32GB of ram then after a few seconds then closes/is killed. Nothing is generated.
The UI was showing "Task 138/140 (98%)".

**Comment by simon-ourmachinery** [comment]
@karl-zylinski-ourmachinery or @tobias-ourmachinery  I think something funny is going on the task system:

I just looked at this in `publish_task` and well I have a endless loop for wait for a task.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/70658708/158452468-85e13a83-fe97-443d-ae0c-ab9f394d0501.png">
<img width="655" alt="image" src="https://user-images.githubusercontent.com/70658708/158452513-a4970a84-5a10-40bc-8dd2-01cbc5dd5d17.png">

The number of tasks is: 2 but the "task" on index 1 is trash...

<img width="469" alt="image" src="https://user-images.githubusercontent.com/70658708/158452894-36dfba0f-c2a1-4d5f-8cae-f9b62efe8c0f.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/70658708/158452825-0f9200f9-bbb9-4e89-b09b-4dc7c2ecd9f7.png">

**Comment by xenobrain** [comment]
I can confirm this error on the following configurations:

Windows 11, Git Master
Windows 11, 2022.2

Arch Linux, Git Master
Arch Linux, 2022.2

Tested the following projects--personal project, Physics Sample, Pong Sample, 3rd Person Sample

**Comment by simon-ourmachinery** [comment]
@xenobrain  Do you mean you can confirm my finding in my prv comment or the general issue?

**Comment by DaveTheGameDev** [comment]
@simon-ourmachinery  @karl-zylinski-ourmachinery 

I managed to get the build to publish if I launch the machinery through visual studio and by manually loading my project, instead of launching the engine with the project 
![image](https://user-images.githubusercontent.com/21057342/159657916-5dee5711-6463-4203-80af-96659ed1946d.png)

**Comment by xenobrain** [comment]
Replicated on Linux with gdb

Release Editor->Publish = crash
Debug Editor->Publish = crash
GDB->Release Editor->Publish = crash
GDB->Debug Editor->Publish = success

gdb output at time of crash:
[Thread 0x7f9e653fe640 (LWP 5576) exited]
[Thread 0x7f9e65bff640 (LWP 5575) exited]
[Thread 0x7fbeea579640 (LWP 5571) exited]
[Thread 0x7fbef0d76640 (LWP 5570) exited]
[Thread 0x7fbef1577640 (LWP 5569) exited]
[Thread 0x7fbef1d78640 (LWP 5568) exited]
[Thread 0x7fbef2579640 (LWP 5567) exited]
[Thread 0x7fbef2d7a640 (LWP 5566) exited]
[Thread 0x7fbeead7a640 (LWP 5565) exited]
[Thread 0x7fbef357b640 (LWP 5564) exited]
[Thread 0x7fbf1e6fc640 (LWP 5563) exited]
[Thread 0x7fbf1effd640 (LWP 5562) exited]
[Thread 0x7fbf1f7fe640 (LWP 5561) exited]
[Thread 0x7fff9ccfe640 (LWP 5557) exited]
[Thread 0x7fff9edfe640 (LWP 5556) exited]
[Thread 0x7fff9f5ff640 (LWP 5555) exited]
[Thread 0x7fffbaffd640 (LWP 5554) exited]
[Thread 0x7fffbb7fe640 (LWP 5553) exited]
[Thread 0x7fffbbfff640 (LWP 5552) exited]
[Thread 0x7fffdcff9640 (LWP 5551) exited]
[Thread 0x7fffdd7fa640 (LWP 5550) exited]
[Thread 0x7fffddffb640 (LWP 5549) exited]
[Thread 0x7fffde7fc640 (LWP 5548) exited]
[Thread 0x7fffdeffd640 (LWP 5547) exited]
[Thread 0x7fffdf7fe640 (LWP 5546) exited]
[Thread 0x7fffdffff640 (LWP 5545) exited]
[Thread 0x7ffff4d5d640 (LWP 5544) exited]
[Thread 0x7ffff555e640 (LWP 5543) exited]
[Thread 0x7ffff5d5f640 (LWP 5542) exited]
[Thread 0x7ffff6560640 (LWP 5541) exited]
[Thread 0x7ffff6d61640 (LWP 5540) exited]
[Thread 0x7ffff7a62640 (LWP 5539) exited]
[Thread 0x7ffff7a63740 (LWP 5535) exited]

Program terminated with signal SIGKILL, Killed.

**Comment by niklas-ourmachinery** [comment]
@karl-zylinski-ourmachinery Can you have a look at the fix I pushed: https://github.com/OurMachinery/themachinery/commit/8685f923070c75d62ec78bdc169c9dc5642defa2

It seems to fix the issue, but I don't know the code well enough to understand why. I don't know if it should ever be possible for `tm_carray_size(glt->task_ids) >  tm_carray_size(glt->tasks)` or if there is an error somewhere else that causes this to happen.

**Comment by DaveTheGameDev** [comment]
@niklas-ourmachinery  Yeah this seems to fix it. I can now publish builds using the CLI.

**Comment by niklas-ourmachinery** [comment]
Closing this, @tobias-ourmachinery -- reopen if you think there's still an issue.
