### ISSUE TITLE
Visibility toggle in entity tree

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#117]
Need to support some kind of visibility toggling in the entity tree tab. Classic eye-icon next to each entity would probably work.

**Comment by leonardo-ourmachinery** [comment]
Implemented, it will be released in the next release.

**Comment by tobias-ourmachinery** [comment]
@leonardo-ourmachinery I think we might be talking about different visibility toggling. I’m talking about toggling visibility in the scene tab controlled from the tree view.

**Comment by leonardo-ourmachinery** [comment]
Yes, sorry. I tought it was the one talking about hide/show components and closed it.

**Comment by leonardo-ourmachinery** [comment]
@tobias-ourmachinery I'd say we can close this...?
