### ISSUE TITLE
Unexpected data when overriding x component of transform position

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1170]
- **Version:** Git Master Branch
- **OS:** Windows

I did an override of the position's x value in an inherited transform component. When saving that to disc it says:
```
				__type: "tm_transform_component"
				__uuid: "69974ff3-484b-913d-a2cc-b2275ba00c0c"
				__prototype_type: "tm_transform_component"
				__prototype_uuid: "74f86fab-4a59-bcf5-a684-440e812b1b2c"
				local_position: {
					__uuid: "2db0162e-23c3-6c20-f519-994df2366a7c"
					__prototype_type: "tm_position"
					__prototype_uuid: "22af992e-dbab-100f-348b-72fefe905134"
					x: 1
					z: 0
				}
				local_position_double: {
					__uuid: "e13dccb0-4356-b621-d469-564bdb2d6b44"
					__prototype_type: "tm_position_double"
					__prototype_uuid: "045bb92d-dd2c-c600-d87c-63a2b62a09c9"
					x: 1
				}
```
Why is both x and z overriden of the `local_position` but only x for `local_position_double`?

**Comment by leonardo-ourmachinery** [comment]
Fixed in master with https://github.com/OurMachinery/themachinery/commit/a1d0c0f7078a757473ef5f5678a002e690cbd438
Fortunately we'll get rid of the float position property relatively soon so those useless zeros will get removed "automatically".
