### ISSUE TITLE
Bugs when switching entity prototype

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1183]
- **Version:** Git Master Branch
- **OS:** Windows

Repro project: [Bugs.zip](https://github.com/OurMachinery/themachinery-public/files/8283953/Bugs.zip)

Some things to note about the project:
- core/sky.entity has two extra child-entities with lights
- core/elemental_default_world.entity has core/default_world.entity as prototype which contains sky, but removes the inherited two extra child-entities mentioned above and adds two new child entities of its own
- The world.entity uses core/default_world.entity as prototype and have art_assets/cube_5x1x1_composite.entity as a child asset entity

Repro step:
- Switch the prototype for world.entity to use core/elemental_default_world.entity as prototype

Bugs:
- The "world/cube_5x1x1_composite" entity in world.entity dissapeared
- The "world/sky" entity has two "Sun" and two "SkyDir1" child entities, even though the prototype only had one of each.

**Comment by leonardo-ourmachinery** [comment]
Fixed both bugs in master.
