### ISSUE TITLE
Growing list of default anim curves

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#1195]
- Git Master
- Windows 

The `default.entities` list keeps growing with duplicate copies of the default curve.

Repro steps are:

- Load TM
- Save
- Trigger hot reload (recompile a plugin)
- Save
- Trigger hot reload (recompile a plugin)
- Save

On each run through, the default `animation_curve` object will have one more item added to it's sub object set. 

Where the problem arises is inside `create_object_of_type` 

`return ot->default_object.u64 ? clone_object(tt, ot->default_object, undo_scope) : private__create_object(tt, type, undo_scope, (tm_tt_id_t){ 0 });`

So when creating the default object itself, if one already exists - it will be used as a template for the new default object. This normally isn't a problem, except in the case of creating default items for a subobject_set. In this case, the behaviour is to append the new entity instead of replacing it.

I wondered if there should be a `create_default_object_of_type` or something which will always create a completely fresh object.. but then could this has have adverse side effects?

I also considered checking if there was already a default object for the animation curve, but this felt more like a work-around/hack than a real solution.

**Comment by niklas-ourmachinery** [comment]
Closed by merging PR.
