### ISSUE TITLE
Collaboration server crash 

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1196]
- **Version:** Git Master Branch
- **OS:** Windows

Crash with the message `themachinery\foundation\allocator.c(114): error: Fixed allocator out of reserved memory themachinery\foundation\the_truth.c:585`

Parallel stacks:
![image](https://user-images.githubusercontent.com/6726075/159430476-257b3c9d-ac6e-42ba-b99b-9bf4cea24325.png)

Application has allocated 1.2GB and the machine has 4.2GB (out of 8GB in total) free.

No information about how much memory it tried to allocate. The callstack up to the allocation also seems lost, the call to `dialogs_message_box()` is said to come directly from job_system.cpp, but there is no such call in the code.

Other relevant info, the log says that a save was initiated 2 seconds before the crash. And there were 950 tiny messages hitting `recv_changelog` after the save was started and before the crash.

There is not enough info to fix the reason behind the crash, but we should at least include more info in `Fixed allocator out of reserved memory`. And if you have any ideas to why the callstack is so funky that would be most welcome.

**Comment by niklas-ourmachinery** [comment]
Ah, that makes more sense... that allocator is sized to 100 MB and is *only* used for object types, properties and aspects... so it would be expected to use much less than that... there must be some bug that makes it keep growing.

If you set a breakpoint in `private__allocate_immuatable()` you might be able to figure it out... I wouldn't expect that function to be called at all after the first "initialization" phase when truth object types get registered.

**Comment by Tisten** [comment]
I have monitored that allocator over the week, and it is stable around 2 MBs, sometimes reaching up towards 3, but I've not seen anything spiking like in the crash (though I don't know if the request in the crash wanted 101MB or UINT64_MAX bytes).

I've also tried to push it by connecting with clients which are ahead and behind in version, so the host will see new types. It grows a bit initially, but nothing extreme.

I've added more info to the logging of our version as well in case this happens again in the future.

**Comment by Tisten** [comment]
Got a crash on this yesterday, and one more today. So I need to start checking what is up with this again.

**Comment by Tisten** [comment]
I think I know why the crashes happened yesterday and today, _something_ has been integrated from master which caused the server and client to have data missmatches. Probably a shader (my theory is that it causes https://github.com/OurMachinery/themachinery-public/issues/1403 as well) and possibly more things.

My theory is that these data differences caused the immutable data to allocate more memory per old connection, and after ~24 hours it crashed with out of memory.

I have forced everyone to update to latest now by changing the `collaboration_state_id`, so if I'm right we should be stable again until next "shader change" (or whatever it was) sneaks in.
