### ISSUE TITLE
Using the rotation gizmo gives faulty values

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#1203]
- **Version:** Git Master Branch | Latest Binary Release
- **OS:** Windows

When using the rotation gizmo or a mix of gizmo and numbers the rotation values get increasingly wrong. ctrl+z only makes things worse. 

This is when the object has been translated with the gizmo and rotated 180d. Everyting still looks ok.
![image](https://user-images.githubusercontent.com/94915027/160020954-331dc6ee-4887-4102-beb8-631e9997bce4.png)

Now I want to turn it 90d in the Y axis. I do this by writing the number. This is the result:
![image](https://user-images.githubusercontent.com/94915027/160021239-7487c829-f3c4-41a1-a1c2-9ccc53d2c90b.png)

When I do a ctrl+z I get this result:
![image](https://user-images.githubusercontent.com/94915027/160021373-1b8550bc-023b-4863-b9ff-b5299aa16fe0.png)

The only way to go back is to manually write 0 in xyz rotation. 

If I try to do the same thing with only the gizmo I can get it to the right postion but the -180d i z axis is turned into zero rotation!:
![image](https://user-images.githubusercontent.com/94915027/160021750-4d72f9ff-d706-471c-8a08-8cf43257a043.png)

And if I try to add the -180d back in with numbers I get this result
![image](https://user-images.githubusercontent.com/94915027/160022346-d79dd98f-bd2d-4c01-92b6-541bf266eebe.png)

Right now I can't build the entity I need for our delivery as neither gizmo or numerical rotation gives correct values! Can you guys please look at this as soon as possible!

**Comment by niklas-ourmachinery** [comment]
I cannot reproduce this behavior. If I type first `180` for the z rotation and then `90` for the y rotation, my rotation shows up as `0 90 180`.

This is with the latest master.

Does this happen for you with every entity, or just this one?

**Comment by niklas-ourmachinery** [comment]
Tried it as a collaboration client too, to make sure that wasn't the issue and I can't reproduce it there either... the rotations behave normally...

**Comment by LoffanElemental** [comment]
I mostly use the gizmo. This is an entity in an entity that is placed in the world. So maybe that needs to be part of the equation? I think the bugs usually happen if I go to 180d or over. So try rotation and move and rotate again in many directions.

**Comment by Tisten** [comment]
This error is specific to our code, and we've found the issue. We have a change in the naming of the euler rotations components, and while doing that a bug was introduced

**Comment by LoffanElemental** [comment]
Considering this closed!
