### ISSUE TITLE
The Entity Tree view jitters when many entities are expanded

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1204]
- **Version:** Git Master Branch 
- **OS:** Windows

When the number of expanded entities is very large the entity tree view jitters. Hold the left mouse button and scroll up and down a bit, then stop. This results in the view jumping up and down.

![scrollbar_jitter](https://user-images.githubusercontent.com/91697782/160070895-4932b845-511d-469e-8fa9-4b5bc48f5ad0.gif)

**Comment by leonardo-ourmachinery** [comment]
Unfortunately I'm not able to repro the issue, I guess there must be something fishy going on with the selection or something... hard to say sadly.

Do you repro the issue consistently?

**Comment by ElementalAndy** [comment]
I tried reproducing this in a new project and couldn't. Maybe close it for now?

**Comment by leonardo-ourmachinery** [comment]
Yes, let's close it for now. If you happen to repro it consistently on a project that you can share please reopen the issue.
