### ISSUE TITLE
Rotation properties are displayed wrong when the Euler calculation hits the Gimbal lock

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1206]
- **Version:** Git Master Branch
- **OS:** Windows

When the Y rotation becomes 270, 90, -90 or -270 the other rotation axis are displayed wrong in the properties windows.

For example, an object with the rotation (0, 90, 180) was duplicated, and the new object were rotated identically but showed (0, 90, 0).

The function for calculating the values for the properties should handle this case, and always write sane values.

**Comment by Tisten** [comment]
I wrote a small test in `math.c` and `unit_test__quaternion()` when we had a bug in our version of `tm_quaternion_to_euler()` which showed an indication of what is happens:
```
    for (float x = -360.0f; x <= 361.0f; x += 15.0f) {
        for (float y = -360.0f; y <= 361.0f; y += 15.0f) { // This will suffer from gimbal lock at -270, -90, 90 and 270
            for (float z = -360.0f; z <= 361.0f; z += 15.0f) {
                const tm_vec3_t euler_test_rot_loop = { x * TM_PI / 180.f, y * TM_PI / 180.f, z * TM_PI / 180.f };
                tm_mat44_t conversion, round_trip;
                tm_mat44_from_quaternion(&conversion, tm_quaternion_from_euler(euler_test_rot_loop));
                tm_mat44_from_quaternion(&round_trip, tm_quaternion_from_euler(tm_quaternion_to_euler(tm_quaternion_from_euler(euler_test_rot_loop))));
                TM_UNIT_TESTF(tr, tm_mat44_equal_abs_eps(&conversion, &round_trip, 0.01f), "tm_quaternion_from_euler(tm_quaternion_to_euler(quat)) == quat, when quat is created from euler_deg(%.1f, %.1f, %.1f)", x, y, z);
            }
        }
    }
```

**Comment by niklas-ourmachinery** [comment]
Fixed in master.

Great catch! Can't believe there were still bugs in the fundamental math functions 🙄
