### ISSUE TITLE
Renaming entity in entity tree window broken

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1207]
- **Version:** Git Master Branch
- **OS:** Windows

![image](https://user-images.githubusercontent.com/21057342/160218265-3482ccf7-1c4a-419a-b204-d62662eff8cf.png)

❌ D:\themachinery\project_one\themachinery\plugins\ui\ui.c(2021): error: ui: Active data for ID 17000099 has wrong format 48f8d0d5e8348e67, expected 4c9b61dcc710e971. (8)

**Comment by DaveTheGameDev** [comment]
I found you can sometimes break the rename functionality in the asset browser when selecting an asset and pressing f2.
I am yet to find a 100% repro, just thought I would mention it.

**Comment by DaveTheGameDev** [comment]
This seems to only happen when you create an entity.

**Comment by leonardo-ourmachinery** [comment]
mmmh. I'm not able to repro the Entity Tree rename bug. Do you have some specific repro steps I can follow?

**Comment by DaveTheGameDev** [comment]
@leonardo-ourmachinery  

For me the issue occurs when you right click on the Entity Window-> Add Child Entity -> Empty
That triggers the issue 100% of the time on my end.

**Comment by leonardo-ourmachinery** [comment]
thanks for the repro steps, on it.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
