### ISSUE TITLE
Animation blend view rendering issues

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#1208]
- Git master
- Windows

I have seen 2 issues

1) In a particular docking config (anim blend on top of tree view in my case) with no animations added, the animation view resizes between 2 sizes every other frame. Causing flickering. Looks like it could be that a scroll bar is appearing/dissappearing as well.

2) See the image below

![image](https://user-images.githubusercontent.com/108040/160236871-524b74ad-40bc-4d0c-9779-8f662815f274.png)

**Comment by jamesmintram** [comment]
Turns out this is because the area of the box is defined by the ranges for the X/Y variables. In this case, the ranges were 0-1. (Tooke me a while ot figure this out, had to step through code before I realised what was going on)

So I guess the rendering should fail more gracefully but also some feedback to the user that the variable values they have entered are out of range

**Comment by niklas-ourmachinery** [comment]
Fixed in master.
