### ISSUE TITLE
Asset Propagation Doesn't work properly if chidren has physics body component

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#1211]
-Git Master Branch

Steps:
-New project
-Add `box` children to the world entity
-Try updating the world transform position (the box will move automatically)
-Add the physics body component to the box
-Try updating the world transform position (the box won't move anymore)

What's happening is that inside `private__init_body()` we call `tm_transform_component_api->set_parent(physx->transform_manager, e, tm_entity_t{ 0 });` on the body entity, which means that the listener to the parent transform component is removed.

one possible solution to the problem would to _not_ call `set_parent()` if we're in a "editing" context, and in addition add a new listener to the body component that listens to the transform component: if the parent transform component is changed the body is recreacted from scratch.

**Comment by Tisten** [comment]
I see these kind of unexpected things in more places. And it makes me wonder why there physics at all in the scene tab and preview tab? And why is there graph debugging in those tabs?

**Comment by niklas-ourmachinery** [comment]
One reason for having physics in the scene tab is that it allows us to use PhysX visualization, so you can check the physics setup of the scene. We could still have our own physics component visualization without this, but I think there is some value in seeing what the physics engine thinks of the scene.

Some graph events can run in the scene editor -- this can be used for some procedural workflows -- @tobias-ourmachinery added support for this recently.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
