### ISSUE TITLE
When overriding an entity, the entity change place in the entity tree

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1214]
- **Version:** Git Master Branch
- **OS:** Windows

I have an entity with a few child entities. If I create an instance of this entity, and override one of those child entities it suddenly change the order in the entity tree.

**Comment by leonardo-ourmachinery** [comment]
mmmh. I'm not able to repro it locally. It seems to be working fine even in the presence of a prototype "chain"... Do you have a repro project/steps I can look at?

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.

**Comment by Tisten** [comment]
Gold star!
