### ISSUE TITLE
Wire dissapear when doing "Propagate to Prototype" of Entity Graph

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1215]
- **Version:** Git Master Branch
- **OS:** Windows

Created a recording of the issue
![Bug](https://user-images.githubusercontent.com/6726075/160378471-c1cba28e-9c6f-4c7d-b1f6-acb0c8f6a70b.gif)

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/2664b8ba1ab9dbd9de88d99ed04f652d1269e58b

Please verify that it works for you.
