### ISSUE TITLE
 Publish window settings do not get saved to the project

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1219]
- **Version:** Git Master Branch
- **OS:** Windows

@simon-ourmachinery 

Publish window settings do not get saved to the project.
When I reinstalled windows these settings no longer show what I had saved.

![image](https://user-images.githubusercontent.com/21057342/160718203-65ef4c92-bfcb-47d1-a9a1-e20caae9a282.png)

**Comment by karl-zylinski-ourmachinery** [comment]
This is on purpose not saved in project since different people on the team will probably vary these settings.
