### ISSUE TITLE
Add runtime error messages to Entity Graph execution

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#1225]
With this graph:
![image](https://user-images.githubusercontent.com/70660839/160808866-d741b960-3921-4fc9-bafd-a36df65d6cf0.png)

The `Log` node won't ever be executed, which is definitively correct, _but_ I think we should provide a runtime error message considering that there would be basically no cost to it:

![image](https://user-images.githubusercontent.com/70660839/160809133-a4326726-1875-48a3-a147-73c5d90cde26.png)

At runtime we're already checking that the input is valid here, so there would be no additional overhead in printing an error message before returning.

Of course this applies to all nodes and should probably be implemented by the graph node generator automatically.

**Comment by simon-ourmachinery** [comment]
related to #338 partly

**Comment by leonardo-ourmachinery** [comment]
Added in master.
