### ISSUE TITLE
Minor rect translate bug for UI

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#1228]
- **Version:** Git Master Branch 
- **OS:** Windows

UI element does not stay in line with cursor.

https://user-images.githubusercontent.com/21057342/160827220-595e2d2b-64c8-49e7-828f-465983c45648.mp4

**Comment by DaveTheGameDev** [comment]
@raphael-ourmachinery  @simon-ourmachinery  This looks to be fixed on my side after that commit :)

**Comment by simon-ourmachinery** [comment]
So we can close the issue @DaveTheGameDev

**Comment by DaveTheGameDev** [comment]
@simon-ourmachinery   Yup, I will close it now.
