### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#123]
Currently, we don't run on Windows 7 due to only supporting Windows 8.1+ High DPI features. On Windows 7, fall back to the system-wide High DPI support (i.e. no per-monitor, use SetProcessDPIAware instead of SetProcessDpiAwareness).

**Comment by karl-ourmachinery** [comment]
There is more to this than first anticipated. We also have Win 8.1+ specific code for mouse and pen movement. I.e. we use the WM_POINTER messages for the mouse. We cannot just set WINVER define to the Win 7 value, because then we loose access to those APIs. Probably requires us to break Windows support into two separate DLLs and load dynamically.

Also, we haven't really tested Win 8.1, I suspect we might use some Win 10-only features as well.

**Comment by dominikdalek** [comment]
It's obviously your call but are you sure it's worth the time investment at all? Extended support for Windows 7 ended in January 2020 and only Professional and Enterprise volume licenses will get security updates for the next 30 months. VS2017 and VS2019 do run on Windows 7 but I wouldn't expect VS2021 (when it ships) to retain compatibility with a 12 year old system at that point.

**Comment by niklas-ourmachinery** [comment]
It will be mostly up to our customers and their priorities. In the latest steam survey, Windows 7 had 6 %, which is not a ton, but if it’s a not a crazy amount of work and it can boost a game’s revenue by 6 %, might be worth doing.

**Comment by dominikdalek** [comment]
I assumed that "we don't run" refers to the the editor, not the resulting game binary (although I see how the majority of code is shared). WM_POINTER for in-game input is an interesting choice. I'd assume that input is abstracted out to support multiple platforms and Windows/Xbox devices use DirectInput+XInput.

**Comment by niklas-ourmachinery** [comment]
Yes, the code is mostly shared... and we don't make a hard distinction between the editor and the game binary (i.e. someone might want "editing" features in their game). Yes, input is abstracted.

**Comment by karl-zylinski-ourmachinery** [comment]
Let's close this. If someone needs it, then they can open a new issue or talk to us on Discord etc.

**Comment by niklas-ourmachinery** [comment]
I know some people have been asking for it... but Win7 is becoming less and less relevant every day... so I agree with not doing this unless there is a strong impetus for it.
