### ISSUE TITLE
Crash in ui_text_component.c draw(..)

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1236]
- **Version:** Git Master Branch
- **OS:** Windows

Got a crash in the draw function in ui_text_component. The tm_ui_text_component_private_t pointer has a lot of broken (uninitialized) data. 18 threads are in canvas_component.c 's private__draw_ui_elements(..). I have gotten this once so far.

![image](https://user-images.githubusercontent.com/91697782/161070995-d7e23694-85d4-402d-a4c3-63f01aeb0be7.png)

**Comment by ElementalAndy** [comment]
The job system has two threads in set_theme_colors(..) and both has the colors argument as 0xcdcdcdcdcdcdcdcd.

**Comment by Tisten** [comment]
Repro project:
[UICrash.zip](https://github.com/OurMachinery/themachinery-public/files/8398813/UICrash.zip)

Steps to reproduce:

1. Turn on USE_END_OF_PAGE_ALLOCATOR in the_machinery.c
2. Load the project. Watch it crash in plugins\ui\ui_controls.c

**Comment by raphael-ourmachinery** [comment]
These issues should be fixed on the last master. I'm doing a review of UI Components, I saw some regressions while testing. We can close this one after you confirm the fix.

**Comment by Tisten** [comment]
I can confirm that the fix works, please close the issue
