### ISSUE TITLE
Creation graph resources show up as dirty even when no changes have been made

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#124]
Repro:

* Open the Gameplay First Person Sample
* Note that `block.entity` and `level.entity` are marked as dirty.
* Even if you save and then re-open the project, the entities are still marked as dirty even though no modifications have been made to them.

This seems to be caused by the `private__dependency_refresh()` in `creation_graph.c`.

**Comment by tobias-ourmachinery** [comment]
Fixed

**Comment by niklas-ourmachinery** [comment]
Reopening this, because it still seems to happen. If I just go through and open all of our sample projects in a round robin fashion the `graph_version` of some resources eventually get dirty. It seems a bit random -- it doesn't always happen with the same resources, it can be different resources different times.

**Comment by niklas-ourmachinery** [comment]
Fixed now.
