### ISSUE TITLE
Simulation restarts doesn't work as expected

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1242]
- **Version:** Git Master Branch
- **OS:** Windows

Steps:
1. Pressing restart simulation makes the box fall and hit the "ground" *as expected*
2. Changing a property will restart the simulation *as expected* (in the recording below I changed the Physics Body property "Disable Gravity")
3. Flipping the property back again will restart the simulation once more, but now the ground is no longer physical *first bug*
4. Flipping the property once more will restart the simulation again, but now the box is visible for a few frames, then it dissapears *second bug* (I think it teleports to the location of the previous simulation's position, i.e the body transform from step 3, still falling down.

Repro project: [SimulateBug.zip](https://github.com/OurMachinery/themachinery-public/files/8396645/SimulateBug.zip)

Recording of the bug:
![Simulate](https://user-images.githubusercontent.com/6726075/161241239-2b7f3b8c-1bc7-4dda-8aad-0d37fa3d7a54.gif)

**Comment by leonardo-ourmachinery** [comment]
Fixed both in master with: https://github.com/OurMachinery/themachinery/commit/cde65dea39f469144166d6005d46d6e1f11dea61

@niklas-ourmachinery I'll cherry pick this as soon as @Tisten can confirm everything works properly.

**Comment by Tisten** [comment]
Yes, seems to solve the reported project. I imagined that it also should have solved https://github.com/OurMachinery/themachinery-public/issues/1237 but unfortunately it didn't.
