### ISSUE TITLE
Duplicate entity has inconsistent naming

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#1243]
- **Version:** Git Master Branch | Latest Binary Release
- **OS:** Windows

When duplicating an entity from the right klick menu in the entity tree the two entities have identical names.
![image](https://user-images.githubusercontent.com/94915027/161280837-5814e572-7114-47da-8308-f88fcf91be6b.png)

If duplicating by shift dragging in the scene the entity gets a (1) after the name. 
![image](https://user-images.githubusercontent.com/94915027/161281132-1e28880f-bfc6-4de1-bf0e-71aca8262df3.png)

I expect this to be the same behavior. The second one (shift dragging in scene) should be the correct one.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
