### ISSUE TITLE
Error when setting "Value" for Entity Graph Inputs

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1248]
- **Version:** Git Master Branch
- **OS:** Windows

When creating a new Entity Graph and adding Input to it, an error is omitted after setting the Value property of the input.

Recording: 
![SettingGraphInputValue](https://user-images.githubusercontent.com/6726075/161495244-12f75b89-c70b-486b-82ca-0ae9b2d21d3a.gif)

Is this a result of https://github.com/OurMachinery/themachinery/pull/930 @simon-ourmachinery?

**Comment by simon-ourmachinery** [comment]
Hmm... I am investigating... I am unsure tbh since this is a UI Active data issue but it could be caused by this.

**Comment by simon-ourmachinery** [comment]
No, it has nothing to do with my pr https://github.com/OurMachinery/themachinery/pull/930 it's something else. I just went back in time and found the same issue before I merged it. Keep this updated

**Comment by simon-ourmachinery** [comment]
Update log:
It is caused by:
```c
        if (set_by_user) {
            tm_properties_view_api->begin_context_menu_scope(args, item_r, &item, 1);
        }
```
In `graph.c:9497

**Comment by karl-zylinski-ourmachinery** [comment]
No longer happens in master due to me changing how the set_by_user stuff works.
