### ISSUE TITLE
The Entity Graph node "PhysX Add Force" is missing a connector

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1252]
- **Version:** Git Master Branch
- **OS:** Windows

This is the look of a newly created "PhysX Add Force" node:
![image](https://user-images.githubusercontent.com/6726075/161522388-caf29a3e-71e6-4892-9256-f3bc28b977a7.png)

There is no connector to set the "Continuous" checkbox.
And the default value of the "At Position" is (inf, 0, 0) which doesn't make sense.

**Comment by simon-ourmachinery** [comment]
This is the same as #1420 therefore I close this issue.
