### ISSUE TITLE
Entity Graph inputs of type `tm_tt_id_t` do not respect the parameter name for the connection's display name

### ISSUE THREAD

**Issue by tlein** [OurMachinery/themachinery-public#1256]
- **Version:** Git Master Branch
- **OS:** Windows

When creating new entity graph nodes, if one of your input parameters that becomes an input connector is of type `tm_tt_id_t`, the display name does not reflect the parameter name of the function. To see a built in node that suffers from this, compare the `Spawn Entity` node's "Entity" input connection name with the parameter name: `entity_asset_id_t entity_asset` (`entity_asset_id_t` is typedef'd to `tm_tt_id_t`). So, the image below should have an input name of "Entity Asset" instead of "Entity":

![image](https://user-images.githubusercontent.com/815242/161647476-a5e979f6-4322-4684-a8de-b7f489c6a672.png)

I'm currently designing a graph node that takes in multiple entity prototype assets for spawning, and they all become labeled "Entity" in the graph editor because of this. 

The culprit is `graph_nodes.c::private__asset_reference_properties_ui`, this takes in the `name` but it doesn't do anything with it. Though I'm not confident enough to propose an actual change that would address this safely without causing further regressions.

**Comment by niklas-ourmachinery** [comment]
Fixed in master.
