### ISSUE TITLE
Copying input wires to new connections

### ISSUE THREAD

**Issue by TobiasElemental** [OurMachinery/themachinery-public#1259]
Currently I can hold CTRL and drag an input wire in a graph node to move it.
I would also like a hotkey button that I hold and drag the wire to duplicate it.

When scripting larger graphs there is a lot of zooming out, scrolling over to the input, zooming in to grab it, zoom out again to scroll back to where I want to put it, zooming in to put it there.

**Comment by karl-zylinski-ourmachinery** [comment]
Holding CTRL + SHIFT now does what holding CTRL does, but it duplicates the connection instead of moving it.
