### ISSUE TITLE
Selecting DCC asset under DCC image node crashes

### ISSUE THREAD

**Issue by AODQ** [OurMachinery/themachinery-public#126]
Whenever a DCC asset is selected for the DCC Image node, the entire editor seems to hang and then crashes.

To reproduce, open the "modular-dungeon-kit.the_machinery" sample file, click on the barrel, add a "Render Component" to it. Then under the creation graph, add DCC Image and try to select "props/prop_floor_barrel" as the DCC asset. It crashes immediately on my machine.

**Comment by tobias-ourmachinery** [comment]
Fixed
