### ISSUE TITLE
Nothing is selected after you delete some item on Entity Tree.

### ISSUE THREAD

**Issue by raphael-ourmachinery** [OurMachinery/themachinery-public#1260]
- **Version:** Git Master Branch
- **OS:** Linux 

When you delete some item on Entity Tree, nothing is selected after that, I think it would be more useful to have the next item or the parent selected instead.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master, I still need to find a good algorithm to "select something" when you delete multiple entities, but for now I think we're good to go.
