### ISSUE TITLE
Entity graph default values don't (immediately) cause the "connector required" indicator to disappear

### ISSUE THREAD

**Issue by tlein** [OurMachinery/themachinery-public#1261]
- **Version:** Git Master Branch
- **OS:** Windows

Custom entity graph node with a parameter marked with `GGN_PARAM_DEFAULT_VALUE` has the "This connector is required to have a value or connector" when it is first created. A simple change of the data will cause the indicator to disappear:

![image](https://user-images.githubusercontent.com/815242/162334230-a7a44262-c143-47f8-921e-5bbff76188c5.png)

In this specific case, the param is a Vec3

**Comment by leonardo-ourmachinery** [comment]
Yes, we should probably mark the parameter as optional when `GGN_PARAM_DEFAULT_VALUE` is used, even if `GGN_PARAM_OPTIONAL` is not used.

**Comment by tlein** [comment]
Seems to happen even with `GGN_PARAM_OPTIONAL` applied. And if the value changes from `3, 3, 3` in my example to anything else (like say adding a 1 to X so it becomes `31, 3, 3`), then the indicator goes away. Seems like it's just not checking if it's valid with the default values.

**Comment by tlein** [comment]
Seems I was wrong about this occurring when `GGN_PARAM_OPTIONAL` is present, I think I just didn't re-gen my nodes when I tried that. However, this still applies for non-optional params that come with a default value.

**Comment by leonardo-ourmachinery** [comment]
I'm gonna back track here, as there are actually valid use cases where you want to have a default value but not mark the parameter as optional: one of them is the `color constant` node. There you want to initialize the color picker to a reasonable value but still don't flag the parameter as optional.

Another good use case is a `scale` parameter. There you probably want to initialize the value to {1, 1, 1}, but maybe you still want the user to explicitly input something in that field.

Closing this for now.
