### ISSUE TITLE
When adding a prototype to an entity, and then removing it, the inherited data remains

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1267]
- **Version:** Git Master Branch
- **OS:** Windows

Repro project:
[AddAndRemovePrototype.zip](https://github.com/OurMachinery/themachinery-public/files/8463078/AddAndRemovePrototype.zip)

After adding and removing a prototype to an entity, the prototype's components and entity assets remains. When removing these from the entity, they get removed from the previously assigned protoype.

Steps:
1. Open the assigned repro project
2. Set the `default_world.entity` as a prototype for world.
3. Note that grey `sky` and `post_processing` entities appear in the Entity Tree
4. Remove the prototype again
5. Note that `sky` and `post_processing` becomes yellow, instead of disappearing. If you do the same in the default project, they disappear, including the transform component(!?)
6. Remove the `sky` and `post_processing` entities from "world" (i.e not from default_world)
7. Now they are gone in default_world as well(!?)

Recording:
![AddAndRemovePrototype](https://user-images.githubusercontent.com/6726075/162716152-1f8ba4b6-c851-42bb-9a8c-9dd90cd4e97c.gif)

**Comment by Tisten** [comment]
Our project was born half a year ago, and has thus accumulated bad data from all bugs which has existed since then.

In general I still would like to see more data sanitization, i.e a migration tool which removes bad data, so that all known cases of broken data is fixed up. I got one "find broken data" tool from Simon which at least identified a lot of issues. I've also manually fixed several cases of invalid transforms, scale set to (0, 0, 0) and dead prototype uuids over the last months.

For this case, it sounds like it should be enough to use the "Force Reimport Core" option from the File menu, right? But it doesn't seem to make any difference, neither in terms of dirty state, nor affect the bug.

**Comment by Tisten** [comment]
I copied a new core from the latest master and overwrote all the files in the core folder of the repro project above. So now the default_world is guaranteed to be "unbroken". And it still behaved identical.

**Comment by leonardo-ourmachinery** [comment]
Reopening the issue, just to remind my future self that I need to fix the "transform component is removed" problem.

**Comment by leonardo-ourmachinery** [comment]
Fixed the "transform component is removed" problem in master.
