### ISSUE TITLE
Overriding nodes in creation graph creates endpoint errors & rendering issues

### ISSUE THREAD

**Issue by AODQ** [OurMachinery/themachinery-public#127]
When I override nodes in creation graph for the sample projects, I get several errors in the console

c:\repos\themachinery\foundation\the_truth.c(608): error: Property type mismatch in tm_asm_blend_set [3 errors]
c:\repos\themachinery\plugins\editor_views\graph.c(33): error: Graph connection invalid endpoints [several thousand - errors increase every frame]

This also seems to consistently cause several parts of model to not render, with no way to fix it except to shut the editor down & relaunch it. For example, I modify the chest of the model in the mannequin example, by overriding the "Lit Default" property and setting its base color by adding a Constant node with "Color RGB" type, and every time I change the color, several parts from the mannequin (head, legs, etc) will disappear.

**Comment by tobias-ourmachinery** [comment]
I *think* all of these are fixed, as I can't reproduce them and we've fixed a bunch of issues related to what you describe. Let me know if you can reproduce it in the beta (soon to be released).
