### ISSUE TITLE
Can't override "comment" in an entity graph

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1273]
- **Version:** Git Master Branch
- **OS:** Windows

After creating an instance of an entity with an entity graph component, and having overriden that component, I can override nodes and wires, but I can't override the comment boxes.

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/336c9410e12aceb0d5979dce145e6d62ed02f6cd and https://github.com/OurMachinery/themachinery/commit/e3faa6302d16659406233eda700f3ac688a1244e
