### ISSUE TITLE
"Create Prototyped Subgraph" doesn't work in overridden graphs

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1275]
- **Version:** Git Master Branch
- **OS:** Windows

Side note: The context menu entry is misspelled

Repro steps:
1. Start the-machinery with a new project
2. Add a Entity Graph component to the world
3. Add two nodes to it
4. Instantiate the world entity in the asset browser
5. Open the new instance, override the Entity Graph component and open it
6. Override the two nodes, select them and right click to open the context menu
7. Choose "Create Protoyped Subgraph"
8. Note the error log, and that no prototype entity graph is created in the asset browser

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/14fefadd11c2ebe4bcf73d4a4f2c3dea9645b566

It was actually a general issue that surfaced in this specific case.
