### ISSUE TITLE
Error when doing "Connect to Debugger" in Entity Graph Debugger

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1291]
- **Version:** Git Master Branch
- **OS:** Windows

After doing "Add Breakpoint" in Entity Graph Debugger, I'm clicking "Connect to Debugger", this generates an error in the log:
`❌ C:\Dev\Projects\3rdParty\themachinery\plugins\ui\ui.c(2047): error: ui: Active data for ID -500011758 has wrong format 1676e9710a22ba56, expected 16d2a8c40725a2c1.`

![image](https://user-images.githubusercontent.com/6726075/166507410-a7b18aa7-cafe-49df-9951-12eaa4be7591.png)

**Comment by simon-ourmachinery** [comment]
Notes:
```
1676e9710a22ba56 -> push button
16d2a8c40725a2c1 -> button
-------

D:\git\themachinery\plugins\ui\ui.c(2021): error: ui: Active data for ID -100010734 has wrong format 1676e9710a22ba56, expected 16d2a8c40725a2c1.


: Failed to resolve line for 0xF2F054E0: 487
: Failed to resolve line for 0xF4B2485B: 487
[the-machinery.exe] log__error() D:\git\themachinery\foundation\error.c:24
[tm_ui.tm_hot_reload.dll] is_active() D:\git\themachinery\plugins\ui\ui.c:2022
[tm_ui.tm_hot_reload.dll] tm_ui_button() D:\git\themachinery\plugins\ui\ui_controls.c:656
[tm_editor_views.tm_hot_reload.dll] private__list_breakpoints() D:\git\themachinery\plugins\editor_views\graph.c:6825
```

**Comment by simon-ourmachinery** [comment]
I have reused button id's between push buttons and buttons this caused a cache issue with active.
