### ISSUE TITLE
Crash when opening an animation state machine

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1294]
- **Version:** Git Master Branch
- **OS:** Windows

Double clicking a .asm in the asset browser results in a crash accessing the tree pointer which is null in open_animation_state_machine_asset(..).
![image](https://user-images.githubusercontent.com/91697782/167213478-11a7e7f4-28c5-4844-a417-dee771ab4a05.png)

**Comment by ElementalAndy** [comment]
https://github.com/OurMachinery/themachinery/pull/968

**Comment by simon-ourmachinery** [comment]
Should be fixed by @ElementalAndy
