### ISSUE TITLE
When importing a mesh, the-machinery autosmooth normals

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1296]
- **Version:** Git Master Branch
- **OS:** Windows

It happens because of this line:
https://github.com/OurMachinery/themachinery/blob/18a781fbdb398597d9dfb8f5d931f0f500cf7489/plugins/assimp/assimp.c#L1222

If I set it to 0.0f instead of 85.0f then the mesh looks as it should.

**Comment by frank-ourmachinery** [comment]
Autosmoothed normals are now disabled in master. Personally I think it should be up to the mesh creator to make sure normals are smoothed if that is desired. But perhaps it's best to revisit this at a later time and add normal smoothing as an import option.
