### ISSUE TITLE
The new Sponza gltf causes The Machinery to hard crash

### ISSUE THREAD

**Issue by prime31** [OurMachinery/themachinery-public#1297]
- **Version:** Latest Binary Release
- **OS:** Windows

After importing the Sponza gltf file I get a hang then a hard crash of The Machinery editor. Accessing any mesh from the file triggers the crash.

**Steps to reproduce:**
- import new Sponza gltf file (https://www.intel.com/content/www/us/en/developer/topic-technology/graphics-processing-research/samples.html)
- attempt to access any of the meshes from the imported gltf file

**Comment by frank-ourmachinery** [comment]
I'm getting some significant stalls when importing the DCC images associated with the GLTF file, but it doesn't crash for me. Neither on the binary release nor the latest master version.

**Comment by prime31** [comment]
I just tried importing the GLTF on a different computer with a similar result. This time I did get an error message (attached). GPU drivers are all up to date and the computer has 16GB RAM and a 6800M GPU with 12GB of RAM.

![image](https://user-images.githubusercontent.com/60377/167891945-c6ac379a-8bf5-4ef1-b098-6814610b9c9c.png)

**Comment by frank-ourmachinery** [comment]
That error indicates that you're running out of GPU memory. You could add an image compression node to DCC image import creation graph in order to lower the needed GPU memory.

**Comment by prime31** [comment]
I'll close this out for now. I can't seem to get the image creation graphs to save without crashing the editor to test that theory.
