### ISSUE TITLE
Add a search filter for Settings window

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#13]

**Comment by niklas-ourmachinery** [comment]
Which *Settings* window are you talking about?

**Comment by nekitu** [comment]
File->Settings

**Comment by niklas-ourmachinery** [comment]
Ah... I don't think we need a search filter there right now, because there aren't that many settings yet... but maybe for the future.

Also we should probably hide the Recent Files from there... because it is confusing and not something the user likely wants to edit anyway.

**Comment by nekitu** [comment]
Yep, for the future, the settings will increase in number.
