### ISSUE TITLE
The newly added collaboration "palette" isn't saved between sessions

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1301]
- **Version:** Git Master Branch
- **OS:** Windows

@karll-ourmachinery

All users get the same default palette, it would be much more useful to randomize the initial default colors. And the value ought to be persisted between sessions, just as the "Chat Handle", "Server addresss" etc.

**Comment by karll-ourmachinery** [comment]
The palette is now persistent, and I will see about randomizing initial default colors later, it might require changes to the `tm_settings_api` as it seems we can't check if the settings existed previously or not.

**Comment by karll-ourmachinery** [comment]
Solved!
