### ISSUE TITLE
Crash after adding an Physics Body component

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1303]
- **Version:** Git Master Branch (a3d86ca88c9ab92d731aebda7196460a4284694c)
- **OS:** Windows

To reproduce:

1. Load the attached project and ``world.entity`` 
2. Add an Physics / Physics Body component to the "kodim01" entity
3. It should crash on [line 1881](https://github.com/OurMachinery/themachinery/blob/7708aa2a0a7721b63ee0dcb29fbe1aa9cbc3d6ba/plugins/physx/physx_scene.cpp#L1881) with an ``Access violation reading location``.

[machinery_physix_body_crash.zip](https://github.com/OurMachinery/themachinery-public/files/8665261/machinery_physix_body_crash.zip)

**Comment by leonardo-ourmachinery** [comment]
Fixed with: https://github.com/OurMachinery/themachinery/pull/972


Thank you @ElementalAndy, and what a timing :)

**Comment by ElementalAndy** [comment]
@leonardo-ourmachinery yeah I fixed it a while ago. This issue reminded me to post a PR :)

**Comment by julhe** [comment]
Awesome, thank you two! :)
