### ISSUE TITLE
Transform components get corrupted when all values are set to zero while running collaboration

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1304]
- **Version:** Git Master Branch
- **OS:** Windows

This bug has the same symptom as https://github.com/OurMachinery/themachinery-public/issues/1131 (solved by @karl-zylinski-ourmachinery) but the way to make it happen is different.

Not sure if this problem was introduced when @leonardo-ourmachinery implemented https://github.com/OurMachinery/themachinery-public/issues/1162?

Reproduction steps:
1. Start 2 the-machinery with the default project, set them up as host and client
2. Right click the "sky" entity in the "world" which is open in the entity tree to open the context menu
3. Choose "Prototype (Advanced)->Make Unique (Detach from Prototype)"
4. Go to the OTHER editor and check the transform component of "sky" in world. It has scale set to 0,0,0 and the rotation has the quaternion 0,0,0,0 (harder to see)

Another way to reproduce:
1. Start 2 the-machinery with the default project, set them up as host and client
2. Open the "core" folder in the asset browser in one of the editors (it doesn't matter which editor for this bug, but I normally leave the server alone and only edit in the client)
3. Duplicate "post_processing_stack.entity", the new "post_processing_stack (1).entity" is created
4. Drag "post_processing_stack (1).entity" into the root of the "world" in the entity tree
5. Now remove "post_processing_stack (1).entity" in the asset browser. Note that "post_processing_stack (1)" in the entity tree changes color from yellow to white.
6. Go to the OTHER editor and check the transform component of "post_processing_stack (1)" in world. It has scale set to 0,0,0 and the rotation has the quaternion 0,0,0,0 (harder to see)

**Comment by leonardo-ourmachinery** [comment]
Basically we don't send properties if their value didn't changed, which is correct generally speaking... but when we detach an entity from its prototype that doesn't work anymore and we should either:
1) send all the properties 
2) let the receiver initialize objects with their default values
![image](https://user-images.githubusercontent.com/70660839/168056228-b260c933-2b94-4bb5-8592-03a0d47b7dc4.png)

(You can see all the relevant info in the watch window) In this case _haschanged is false, but we _should_actually send the value, unless we assume that the receiver will create objects with their default values here:
![image](https://user-images.githubusercontent.com/70660839/168056280-34f218d3-373d-4617-bc84-0e61049e14a8.png)

Putting  a "True" there fixes the bug... but I'm personally more inclined to explicitly send all the properties on the sender side when we detect that the prototype has been set to zero.
@Niklas (Our Machinery) what do you think about this?

**Comment by leonardo-ourmachinery** [comment]
There could potentially be another, more elegant solution:

```
tm_tt_prop_value_t value_before;
tm_tt_prop_value_t value_after;

if (after->prototype.u64 != before->prototype.u64 && !after->prototype.u64)
{
value_before = get_property_value_no_default_value(tt, before, property_i, 0);
value_after = get_property_value_no_default_value(tt, after, property_i, 0);
}
else
{
 value_before = get_property_value(tt, before, property_i, 0);
value_after = get_property_value(tt, after, property_i, 0);
}

// everything else remains the same
```

**Comment by leonardo-ourmachinery** [comment]
Fixed in master with the "more elegant solution" here: https://github.com/OurMachinery/themachinery/commit/59e29709d6396947201ac986d56d0f3eb127d6a8
