### ISSUE TITLE
Translation gizmo with snapping doesn't result in exact coordinates 

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1305]
- **Version:** Git Master Branch
- **OS:** Windows

Repro steps:
1. Start the-machinery with new default project
2. Add a box to the world (Add Child Entity->Geometry->Box)
3. Set the Box's Transform to Pos (1, 1, 1) and Rot ZYX (90, 0, 0)
4. Enable Snapping in Scene tab toolbar
5. User the translation gizmo to move the box back to the origin (0, 0, 0)
6. Note that the position becomes (1.19209e-07, 1.19209e-07, 1.19209e-07) instead of (0, 0, 0)

**Comment by frank-ourmachinery** [comment]
Fixed.
