### ISSUE TITLE
Collaboration: Can't connect to Host, Decompression error

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#1308]
-Current Master, ea20c67a22819be4ec6292e090fdaac623c9a81e
-Windows

1. Make sure to delete everything from the `AppData/Local/TheMachinery` folder in your personal account, to make sure to have a fresh start.
2. Launch an instance, then File -> New Project
3. Host a LAN session
4. Launch another instance, Connect as a Client to LAN session
5. Close client instance
6. Close Host instance (Click on "Don't Save when asked)
7. Execute steps 2 to 4 again, I'm getting:
![image](https://user-images.githubusercontent.com/70660839/168077034-3b69b811-ab00-4371-be99-a39ba95d008f.png)

where the error in the console is:
![image](https://user-images.githubusercontent.com/70660839/168076230-98adb2a2-1460-4b68-b0bd-10bc973baff5.png)

**Comment by Tisten** [comment]
I can have a look at this

**Comment by niklas-ourmachinery** [comment]
The issue is that when there are no buffers to send a zero-sized compressed buffer is sent, but a decompressed_size of zero is interpreted as an error.

**Comment by niklas-ourmachinery** [comment]
I should be able to merge my PR later today if you want to wait for that for this fix.

**Comment by Tisten** [comment]
Yes, the 0 buffer request was the issue.

I have a fix, but it will only conflict with Niklas' change so if that is close then waiting will save you time.

**Comment by Tisten** [comment]
To @niklas-ourmachinery, why is the `mapped_buffers` carray needed? I.e why would it be bad to map the buffers in `client_recv_state_regular()` instead of waiting to `client_recv_buffers_regular()`

In my fix of this issue I did map the buffers right away and changed the end of `client_recv_state_regular()` to this:
```
    if (tm_carray_size(missing)) {
        // Ask for missing buffers.
        buffer_t buf = { .a = a };
        const message_header_t h = { .type = MESSAGE_TYPE__REQUEST_BUFFERS };
        buf_write(&buf, h);
        buf_write_bytes(&buf, missing, (uint32_t)tm_carray_bytes(missing));
        send(coll, coll->host.id, (message_header_t *)buf.carray, (uint32_t)tm_carray_size(buf.carray));

        coll->client_state = CLIENT_STATE__WAITING_FOR_BUFFERS;
    } else {
        coll->client_state = CLIENT_STATE__SYNCED;
    }
```

**Comment by niklas-ourmachinery** [comment]
I don't think it's needed... I'm just trying to not refactor things too much in my PR, once it has landed, it should be easy to fix this.

**Comment by Tisten** [comment]
@leonardo-ourmachinery Niklas' PR is pushed to master. I have other issues with it, but please verify if this can be closed.

**Comment by leonardo-ourmachinery** [comment]
Yes, it's fixed in master.
