### ISSUE TITLE
Startup crash due to missing AVX intrinsics

### ISSUE THREAD

**Issue by sY9sE33** [OurMachinery/themachinery-public#131]
When I try to launch the new beta build, a window opens and remains black and then crashes out.
![tmbetacrash](https://user-images.githubusercontent.com/9271353/77018227-2ad49b80-6953-11ea-89c6-f2e7196c0325.gif)

I've included the dump that was produced.

[the_machinery_exe 2020-03-18 19.48.11.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/4351958/the_machinery_exe.2020-03-18.19.48.11.dmp.zip)

**Comment by sY9sE33** [comment]
And the more detailed dump here: https://drive.google.com/open?id=1uQrnv7Kqshdse5wr7645j6F4AAqYaYIB

**Comment by karl-ourmachinery** [comment]
Hi, thanks for the bug report.

The crash happens on an intrinsic, what CPU does your machine have?

**Comment by sY9sE33** [comment]
It has dual xeon x5650s.

**Comment by karl-ourmachinery** [comment]
Thank you.

We recently introduced some code that relies on AVX intrinsics not available on your CPU. We have discussed this and decided to lower our minimum spec to the SSE4 instruction set, which your CPU indeed supports.

We will do this change in the near future. I'll change the title of the ticket and leave it open for now.

**Comment by sY9sE33** [comment]
That's great! I would also understand not supporting it as it is such an old CPU and an upgrade to my machine is past due at this point anyway.

**Comment by karl-ourmachinery** [comment]
It is true that it is old. However, AMD didn't introduce AVX until 2015, which we feel is a bit too recently.

**Comment by niklas-ourmachinery** [comment]
Can you try the new beta build we just uploaded to the forum. It should give you an Error Message saying that you don't have AVX. Let us know if it works.

**Comment by sY9sE33** [comment]
I can confirm that it works. I tried it right away :)

**Comment by niklas-ourmachinery** [comment]
Perfect... thank you! We'll work on supporting your CPU, but it may be a little while, because we need to patch up all the places in the code where AVX is used.

**Comment by niklas-ourmachinery** [comment]
I have a new version for you to test -- can I email it to you?

If you put your Forum handle here, I can look up your email address on the Forum if you don't want to post your email publicly.

**Comment by sY9sE33** [comment]
Sure thing! https://forums.ourmachinery.com/u/max/summary on the forums.

**Comment by niklas-ourmachinery** [comment]
Fixed in the next version.
