### ISSUE TITLE
Images not visible in Readme

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#1311]
### Discussed in https://github.com/OurMachinery/themachinery-public/discussions/1310

<div type='discussions-op-text'>

<sup>Originally posted by **jrpat** May 13, 2022</sup>
Hi there — I’m excited to be exploring the engine, but as I’m reading [the Readme](https://ourmachinery.com/apidoc/doc/README.md.html), none of the images show up. If I click them, I can download them from Dropbox, but they don’t show up on the page itself. 

I’m on iOS Safari, and it seems to happen regardless of whether I have content blockers enabled.

Happening to anyone else?</div>

**Comment by niklas-ourmachinery** [comment]
I can't see them in Safari on OS X either... though they are visible in Firefox and Chrome on the same machine.

Should investigate why they are not showing in Safari.

**Comment by niklas-ourmachinery** [comment]
Someone else reported something similar:

* https://www.dropboxforum.com/t5/Dropbox-files-folders/Images-stored-in-dropbox-are-not-displayed-in-Safari/td-p/574921

However, unlike what they report, clearing the cache does not work for me

**Comment by niklas-ourmachinery** [comment]
Will update the README on the web site too.

**Comment by jrpat** [comment]
Thanks for the quick fix!

**Comment by niklas-ourmachinery** [comment]
Web site has been updated now too.

**Comment by niklas-ourmachinery** [comment]
@simon-ourmachinery FYI Simon, this seems to apply to the images at **books.ourmachinery.com** too. Can you update those? I'll reopen this until that is fixed.
