### ISSUE TITLE
One-frame glitch in entity position with Physics body component when propagating asset changes

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#1316]
-Current Master

Steps:
-New project
-Add a Sphere to the world
-Add the Physics body component to it
-Start the simulation and put the simulate tab side to side to the Scene tab
-Move the sphere in the scene tab
-Note the one-frame glitch when the mouse button is released

https://user-images.githubusercontent.com/70660839/168537805-60c7546a-5109-43ce-b487-e51292954080.mp4

**Comment by leonardo-ourmachinery** [comment]
There seems to be two related problems to this.

1) When an asset change to an entity is detected, we loop over its components, find those that changed, and call `notify` on those. (at the end of `propagate_asset_changes_to()`). There's even a todo that states exactly the problem:
```
// TODO: Does this need to be delayed until the end of the propagation.
            if (changed)
                tm_entity_api->notify(ctx, ci, &e, 1);
```
So in the case of  the transform component, we will first notify the Physx plugin that the component has changed, even if the world transform will be the old one. Then inside the transform component's `asset_loaded` callback we'll notify the correct world transform.

2) Even completely removing the call to `notify()` inside `propagate_asset_changes_to()`, there's still a one frame glitch when moving the entity via the _gizmo_. I think what's happening is that there's a conflict between the Physx -> ECS `private__mirror_dynamic_transforms()` and `transform_listener__change_body_position()`. 

My guess is that once we properly solve #1312 (use change detection to update body positions instead of immediately calling `set'GlobalPose()`) both 1) and 2) will go away, so it makes sense for us to solve that issue first.

I still think that we should somewhat address the TODO about delaying the notify calls to the end of the propagation.

**Comment by niklas-ourmachinery** [comment]
It looks to me like the one-frame glitch comes from the way we handle Undo events for the gizmo, what happens is.

* As the gizmo is moved we set the position with `TM_TT_NO_UNDO_SCOPE`.

**Comment by leonardo-ourmachinery** [comment]
Glitch 1) went away, but Glitch 2) is still there. (In other words now the glitch only happens when you edit the position via the gizmo, not via the property tab).

I'm investigating.
