### ISSUE TITLE
Collaboration doesn't send changes to users, and memory tracking reports negative byte count

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1321]
- **Version:** Git Master Branch
- **OS:** Windows

Changes gotten from one client isn't reflected out to the other clients, it is just received by the server and stored there. New connections will get the updated data. And the server will complain about `memory_tracker.c(192): error: Negative byte count in collaboration`

I've debugged the code, and here is a short walk through on the path the code takes:
- A changelog is sent from the client to the host, and the host looks for missing buffers and stores the changelog in `coll->queued_changelogs`
https://github.com/OurMachinery/themachinery/blob/ca3c1dc4f037de7e0b96de3d19997b58a0ae4cbf/foundation/collaboration.c#L1316-L1317
- In the end of `update()` the host will loop through `queued_changelogs` and call `deliver_changelog(coll, &cl_pkg, cl->from_id);`
https://github.com/OurMachinery/themachinery/blob/ca3c1dc4f037de7e0b96de3d19997b58a0ae4cbf/foundation/collaboration.c#L1747
- In `deliver_changelog()` the pointer to the changelog will be changed to 16 bytes before it (i.e the carray header) and casted to a `const char *`. Then it will again be casted to a `message_header_t *` and passed to `send_changelog()`. This type happens to have the same size as the carray header, so the payload is still at the correct offset.
https://github.com/OurMachinery/themachinery/blob/ca3c1dc4f037de7e0b96de3d19997b58a0ae4cbf/foundation/collaboration.c#L1238
https://github.com/OurMachinery/themachinery/blob/ca3c1dc4f037de7e0b96de3d19997b58a0ae4cbf/foundation/collaboration.c#L1259
- `send_changelog()` just pass the `message_header_t *` on to `send()`
https://github.com/OurMachinery/themachinery/blob/ca3c1dc4f037de7e0b96de3d19997b58a0ae4cbf/foundation/collaboration.c#L1176
- `send()` will now change the header, destroying the carray header
https://github.com/OurMachinery/themachinery/blob/ca3c1dc4f037de7e0b96de3d19997b58a0ae4cbf/foundation/collaboration.c#L580-L581
- But the `message_header_t::type` is still whatever the carray left it as. It needs to be `5` (or MESSAGE_TYPE__CHANGELOG) for the receiver to parse the message correctly.

I've fixed this in an ugly way, without understanding how this was intended to work. I will create a PR, but would expect you to fix it in another way @niklas-ourmachinery

**Comment by niklas-ourmachinery** [comment]
Investigating it

**Comment by niklas-ourmachinery** [comment]
Fixed

**Comment by Tisten** [comment]
Thanks, now the code makes full sense again. The "change pointer to 16 bytes before" made me wonder what the original thought was, and thus I was unsure what the best way forward was.
