### ISSUE TITLE
New created creation graph doesn't get rendered in scene view until restart

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1329]
- **Version:** Latest Binary Release (f99771b54fd5f60a1b193b3f34af1ef4f0d766e0)
- **OS:** Windows

To reproduce: 

1. New project, new entity with renderer component
2. New creation graph with a setup like this
![grafik](https://user-images.githubusercontent.com/18037091/169527129-8dfadc6b-ff6a-44ce-8b83-a1506dc7aa5d.png)
3. Asign the creation graph to the renderer component
4. Run simulation
5. Observe that the quad is present in the simulation view but not in the scene view.

**Comment by tobias-ourmachinery** [comment]
Fixed in master.
