### ISSUE TITLE
(Minor) ``tmbuild  --gen-nodes`` doesn't ignore commented out code.

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1331]
- **Version:** Git Master Branch (f99771b54fd5f60a1b193b3f34af1ef4f0d766e0) 
- **OS:** Windows 

I was prototyping nodes, but eventually just wanted to make a clean build of my plugin. I ran ``tmbuild --gen-nodes``, but was supprised to see errors related to my commented out code.

**Comment by leonardo-ourmachinery** [comment]
Fixed in master, both single line comments and block comments are now handled.
