### ISSUE TITLE
Expose host entity for simulation entries

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1332]
(As seen on Discord) It would be usefull to access the host entity id. This would allow me to f.e. tie an behaviour directly to an entity or thier children and thus remove the need for specialized tags.

**Comment by niklas-ourmachinery** [comment]
You mean for the case where a Simulation Entry component is attached to an entity, you would from within the component, want to be able to get the `tm_entity_t` of that entity and the `tm_tt_id_t` of the corresponding entity asset?

**Comment by simon-ourmachinery** [comment]
> component

My understanding is that he means the entity_t and not the tt id since during runtime that id is more interesting. I will add them to the start , shutdown and update args.

**Comment by julhe** [comment]
@simon-ourmachinery Yes, I mean the ``entity_t``.
