### ISSUE TITLE
search in list

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#134]
when adding a component or any other list the topmost GUI element should be a search field so we can quickly find element, like in ... Unity

**Comment by tobias-ourmachinery** [comment]
Agreed. We do have that but it's a bit hidden, if you select the entity and press TAB a you'll get a searchable dropdown with all components. We'll work on making it more consistent.

**Comment by laurentopia** [comment]
Oh TAB is cool!
Perhaps you can add a helper at the bottom, like in maya.

**Comment by niklas-ourmachinery** [comment]
The next version has this for spawning entities as child assets too.
