### ISSUE TITLE
Crash when trying to open an Entity Subgraph

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1347]
- **Version:** Git Master Branch
- **OS:** Windows

I got this crash just after docking the Entity Graph View over the Asset Browser and then attempted to open a Subgraph through the node context menu. It seem like somewhere inside the while loop of the properties_tab's get_asset_name(..) the object type gets an out of bounds index.

![image](https://user-images.githubusercontent.com/91697782/170640348-1ebbcbc5-27a2-4161-806b-697d8ff89c1f.png)

**Comment by simon-ourmachinery** [comment]
I cannot reproduce this.

Steps:
- opend the graph (entity graph with one subgraph)
- moved the graph tab over the asset browser (see image)
- right click on node "Open Subgraph"
<img width="734" alt="image" src="https://user-images.githubusercontent.com/70658708/170685462-fd3de7b3-6545-40e9-81a8-268a70dc6319.png">

**Comment by ElementalAndy** [comment]
Uploaded a project with a simple graph that crashes if I. Double click the entity graph asset to open it and then dock over the asset browser and finally right click on the subgraph node and select open.

[entity_graph_crash.zip](https://github.com/OurMachinery/themachinery-public/files/8805187/entity_graph_crash.zip)
