### ISSUE TITLE
Asset browser regression. The different views no longer work.

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#1349]
- **Version:** Git Master Branch
- **OS:** Windows

![asset_browser_view](https://user-images.githubusercontent.com/91697782/170648914-16d09392-35da-4409-a668-8e972151e9b3.gif)

**Comment by simon-ourmachinery** [comment]
@ElementalAndy can you provide the commit has? I cannot reproduce this issue?

**Comment by ElementalAndy** [comment]
I can't reproduce it either anymore.
