### ISSUE TITLE
contextual menu

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#135]
As a newcomer to Machinery that's used to Unity and Maya, a contextual menu on the right click would help me get up to speed to what is doable

**Comment by niklas-ourmachinery** [comment]
Do you mean in the Scene Tab?

**Comment by laurentopia** [comment]
yes, to create new entities like a cube or a default light, but to reflect what can be done in unity, in the entity tab.
At first glance it seems that entity tab allows to reparent entities, but since it also shows the component within the entity, move component or duplicate component to another entity and also right clicking on the empty part of this tab seems like it should allow to create default objects like sphere, camera, light or empty entity.

**Comment by niklas-ourmachinery** [comment]
Ah you mean in the Entity Tree Tab.

I've added a Create Entity From Asset option to the context menu (also accessible with Shift+Tab) it allows you to quickly add entity assets such as lights etc.
