### ISSUE TITLE
Constant inputs to a subgraph doesn't work

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1350]
- **Version:** Git Master Branch
- **OS:** Windows

Repro project:
[ConstantInputsToSubgraph.zip](https://github.com/OurMachinery/themachinery-public/files/8784981/ConstantInputsToSubgraph.zip)

Reproduction steps:
* Load the project above
* Note that the "Entity Graph" in "world" pass the vec (0, 2) into the subgraph "subbie"
* Start a simulation of "world"
* Note the logging saying `❌ C:\Dev\themachinery\plugins\graph_interpreter\math_graph_nodes.inl(1886): error: connector "vec2" not set, cannot execute node "vec2_components" on "world" Entity Graph (2)`
* Also note that the logging only wrote "0.000000", not all the "0", "1", "2" which it should have.

More detailed description of how it is set up:
* Subbie is an asset entity_graph which is dragged and dropped into world's entity graph.
* To be able to set the constant values (0,2) the subgraph needed to be "overridden" first

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/51f0348bbd1eadfea3fc6be6cb519d6d948cb63a

It was simply that the vec2 wasn't passed along properly from the graph input to the internals of the graph interpreter.

**Comment by karl-zylinski-ourmachinery** [comment]
Indeed, I'm gonna look it over and see why it cant use the same path we use for other graph data -> graph interpreter conversions.
