### ISSUE TITLE
Graph tab doesn't re-center when window resizes

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1355]
- **Version:** Git Master Branch
- **OS:** Windows

The "current center" position of graph view isn't used when drawing it after changing the tab's size. When starting to move the first time after the resize the view will pop to the right place and cause confusion.

The view should either set a new center based on the new size, or keep the old center and actively change what is drawn during the resize.

![Recenter](https://user-images.githubusercontent.com/6726075/170678019-4aa53612-49a0-47bb-9071-bb73fc9490fd.gif)

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/b9c54c0859705205c80947004992a48eb358a888
