### ISSUE TITLE
Custom events that use a dyanmic string hash do not work.

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1359]
- **Version:** Git Master Branch
- **OS:** Windows

(As seen on Discord) Tried out the following setup:
![grafik](https://user-images.githubusercontent.com/18037091/170839647-407bd9ae-34b7-4b49-9f88-23d434b2bab8.png)
 The Log function never triggers however.

**Comment by simon-ourmachinery** [comment]
Note: They do not work because the event is registered on compile not runtime.

**Comment by karl-zylinski-ourmachinery** [comment]
I fixed this specific issue in master branch just now. The string hash node only outputted the hash during run time, and the custom event node expects data during compile time. There is however a bigger issue with the compile/run time of graphs that can cause similar issues in other cases. I will discuss that stuff with the rest of the team.
