### ISSUE TITLE
Dragging an entity to the entity tree view produces a duplicate asset

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#1362]
- **Version:** Git Master Branch | Latest Binary Release
- **OS:** Windows | Linux 

Dragging an entity from the asset browser to the entity tree view produces a duplicate asset. see pic

![image](https://user-images.githubusercontent.com/94915027/171026819-02a7fcd2-bc90-4442-83fc-490259378e48.png)

**Comment by lachsinc** [comment]
I believe https://github.com/OurMachinery/themachinery/commit/498a7b59959fb659a23c613e8d7cbece8604c95d
may have introduced this - I put a msg on discord may have slipped through the cracks :)

**Comment by frank-ourmachinery** [comment]
Fixed it was indeed caused by the commit linked by @lachsinc.
