### ISSUE TITLE
Renaming in the asset browser is not working correctly!

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#1363]
- **Version:** Git Master Branch | Latest Binary Release
- **OS:** Windows | Linux 

When pressing F2 or right clicking and choosing rename from the asset browser the renaming is not working. If you hold down left mouse button you can write one letter. Then you have to release it and press again to write the next. This behavior is hopefully not intended but a bug.

**Comment by simon-ourmachinery** [comment]
I cannot reproduce it on master: `3aedbbb607ab1da8571921d0c3d802df0ccf1723` what is you commit master version?
![ab-rrename](https://user-images.githubusercontent.com/70658708/171033210-957233a6-e04f-46ae-9432-39298006b615.gif)

**Comment by simon-ourmachinery** [comment]
@LoffanElemental  seems to be related issue to #1348 or #1347 which I cannot reproduce either.

**Comment by lachsinc** [comment]
I was having a renaming issue recently too though maybe slightly different - I can repro my one every time via:
![rename-bug](https://user-images.githubusercontent.com/1400236/171039146-0e39af6e-5516-4114-aed0-e891ddaa9146.gif)

(note the second click on the text input)

**Comment by simon-ourmachinery** [comment]
That's slightly different but I take it.

**Comment by simon-ourmachinery** [comment]
Reproduction:
- select asset
- rename
-  try to click in it

Other case:
- select asset
- rename
- click outside (different tab)
