### ISSUE TITLE
Property editor for multiple objects

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#137]
when selecting multiple objects, only the last selection is operated on in the properties window
so if i select 4 cubes and add the physics body component only one will get it

**Comment by tobias-ourmachinery** [comment]
Multi-select editing is work-in-progress at the moment. Right now it only works for moving, rotating and scaling of entities and only when performing those actions in the scene tab. 

The properties tab will show the properties of the last selected entity and any change you do will only be affecting that. Proper support for multi-editing using the properties tab will come.

**Comment by laurentopia** [comment]
Cool, showing "-" when values mismatch is how Unity does it and it works great.
I don't usually praise Unity but this multi selection edit they got right.
Maya got the channel box multi property selection right, do you know it?

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.5.
