### ISSUE TITLE
Unable to connect entity tag graph connector

### ISSUE THREAD

**Issue by lachsinc** [OurMachinery/themachinery-public#1371]
- **Version:** Git Master Branch
- **OS:** Windows

Unable to connect entity tag graph input to 'First Entity with Tag' graph node:

![graph-entity-tag-issue](https://user-images.githubusercontent.com/1400236/171406227-7fb0b582-5997-4cf5-897f-9ebbc1de2006.gif)

**Comment by simon-ourmachinery** [comment]
They are 2 different types one is a string hash while the other one is an entity tag.

**Comment by simon-ourmachinery** [comment]
Note: We need to improve the editor types <--> node types are confusing
