### ISSUE TITLE
In the "Import Project" tab, the "Grid, List, Detail" views doesn't work in the toolbar

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1373]
- **Version:** Git Master Branch
- **OS:** Windows

![ImportProject](https://user-images.githubusercontent.com/6726075/171409176-3ce6826d-3558-4ae1-a8c6-1bdeffc9abe9.gif)

**Comment by simon-ourmachinery** [comment]
I cannot reproduce this I close this and if this happens again we open this issue again.
