### ISSUE TITLE
Crash when setting simulate tab's network node type via 'Simulate' menu

### ISSUE THREAD

**Issue by lachsinc** [OurMachinery/themachinery-public#1378]
- **Version:** Git Master Branch
- **OS:** Windows

Is the strcmp on a null ptr @ https://github.com/OurMachinery/themachinery/blob/75b549db597c196703f4a339e3354fda305a0b04/plugins/simulation/simulation.c#L1489 (`info.node_type_name` is null)

I'll update w more details if I figure it out how I got it into that state (both my 'server' and 'client' network assets have their name set correctly).

**Comment by lachsinc** [comment]
Hmm may be nastier than originally thought.. [network-crash-repro.zip](https://github.com/OurMachinery/themachinery-public/files/8826724/network-crash-repro.zip)

https://user-images.githubusercontent.com/1400236/171706995-2d06bd06-04eb-4553-9d5d-96b6c4fbef6e.mp4

![image](https://user-images.githubusercontent.com/1400236/171710519-58380c4f-1846-42ba-b730-96c514880b6c.png)

**Comment by lachsinc** [comment]
Fairly sure this is because I had a 'connect to local server' bootstrapper set for my server.

Still, here is a repro if you want to protect against crash:

[network-crash-repro.zip](https://github.com/OurMachinery/themachinery-public/files/8827618/network-crash-repro.zip)

1. Open project
2. Press play (so you get server and client sim window)
3. Close server and client
4. Open new simulate via Tab > Simulate
5. Change its node type to 'server' via Simulate > Network Node Type

**Comment by leonardo-ourmachinery** [comment]
Fixed in master, Thank you for the detailed report and repro steps.
