### ISSUE TITLE
Keyboard stealing

### ISSUE THREAD

**Issue by Hoogin** [OurMachinery/themachinery-public#1384]
- **Version:** 2022.5
- **OS:** Slackware 15, Linux, KDE plasma

The machinery keeps stealing the keyboard when I've changed to other applications. Makes it difficult to work with plugin hotswap. Version 2022.4 didn't have this problem.
I starts doing it when I just start machinery and switch to any other application.
It will not change to the machinery window it just grabs the keyboard.

**Comment by raphael-ourmachinery** [comment]
It should be fixed, you can reopen it if needed.
