### ISSUE TITLE
Machinery locks pdb of plugin DLL, preventing recompile 

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#1386]
- **Version:** Git Master Branch
- **OS:** Windows 

I sometimes have to restart Machinery to complete a recompile, as the ``.pdb`` is locked by Machinery for some reason. Don't remeber having this issue when just working with simulation entries. I think this started when I started implementing custom creation graph nodes. (Can investigate that if needed)

**Comment by Tisten** [comment]
Just want to note that this is a documented problem, with suggested workaround:
https://books.ourmachinery.com/extending_the_machinery/hot-reloading.html
> If you are using hot-reloading together with a debugger on Windows, be aware that the debugger will lock .pdb files which will prevent you from rebuilding your code. The suggested workflow is something like this:
>
> * Detach the debugger if it's currently attached.
> * Rebuild your DLL and fix any compiler bugs.
> * When the DLL is built successfully, The Machinery will automatically reload it.
> * If you need to continue debugging, re-attach the debugger.

Also part of:
https://ourmachinery.com/post/dll-hot-reloading-in-theory-and-practice/
https://ourmachinery.com/post/little-machines-working-together-part-2/

And discussed:
https://forums.ourmachinery.com/t/question-on-hot-reloading-plugins/330/7

**Comment by julhe** [comment]
@Tisten Thanks, I'm aware of the debugger situation. However, In this case I haven't any debugger attached and the lock originated from Machinery it self, as seen here:
![grafik](https://user-images.githubusercontent.com/18037091/172816140-440f290c-ab03-491d-af6f-10ce73d408c5.png)

This only appeared after some minutes, as I was able to re-build my plugin as usual for a few times.

**Comment by niklas-ourmachinery** [comment]
FYI, I've also seen `.pdb` files occasionally locked in other situations (no debugger attached, no stack trace printing enabled). Haven't been able to figure out exactly how it happens, but fortunately it's somewhat rare.
