### ISSUE TITLE
Can't switch back to default font after testing to customize fonts since the default font of the-machinery is not a core asset

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1387]
- **Version:** Git Master Branch
- **OS:** Windows

The default font is located in the "data/fonts" subfolder with the-machinery's executable. I tried adding a custom font as an asset, and using it with the UI Text component. But since the default font is not an asset in core, I can't switch back.

Another issues with testing fonts is that after adding a tm_ttf asset and adding a ttf file to it, it still didn't change the rendering. When debugging it I found that I had missed out to add "ranges". I don't really understand what the numbers in ranges should be, so I thought that perhaps I could copy paste from the default font to get something showing at all, but since it isn't an asset it becomes hard to see what the values of its ranges are.

**Comment by niklas-ourmachinery** [comment]
This is when using the UI components, right?

**Comment by Tisten** [comment]
Yes, I used the "UI Text" component

**Comment by raphael-ourmachinery** [comment]
It should be possible to switch back to the default font selecting no font in the picker, but there is a issue in our picker that doesn't allow you do it. I'm working on a fix!

**Comment by raphael-ourmachinery** [comment]
The issue should be fixed on master, not sure if change ranges on fonts should affect the rendering at real time, as we have to rebake it, maybe to use a reload button. Yeah, "ranges" usage should be more intuitive, I'll work on that. I'm closing the issue as the main problem is solved.
