### ISSUE TITLE
Focusing on light.entity incorrectly focuses on world origin

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#139]
In `gameplay-third-person.the_machinery` focussing on the `light.entity` will focus on the world origin instead of the entity's position.

Repro: 

- Navigate to `light.entity` in the asset browser 
- Drag entity into the viewport (somewhere off center)
- Press `F` on the keyboard
- Observe the camera snap to focus on world origin instead of centering the light entity in the viewport

**Comment by niklas-ourmachinery** [comment]
Thank you... I think this happens because the entity doesn't have any physical extent. Should be a simple fix.

**Comment by niklas-ourmachinery** [comment]
Fixed in next version.
