### ISSUE TITLE
The options in a drop down doesn't expand to the required string length

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1394]
- **Version:** Git Master Branch
- **OS:** Windows

Create an entity graph, add a "Get Asset Reference" node and click in the "Asset" input box.
![image](https://user-images.githubusercontent.com/6726075/173558703-662795cf-26b9-4834-bf2f-a81acccb4be7.png)

1. It would be great if the drop down expanded so the whole strings were readable.
2. If it can't expand enough because the strings are very long, it would be great with a scroll bar
3. And if it can't expand enough because the strings are very long, the end of the string is more interesting than the beginning of the string, so draw that by default (at least in this case)

**Comment by frank-ourmachinery** [comment]
The popup item picker API (in master) now supports different expansion modes. 

- Strict is the default which uses the expansion mode as shown in the issue. This is useful for pickers in the properties tab as expanding the width is often impossible without unwanted overlap.
- Automatic mode is what you requested for item 1, this is now in use for any entity graph node. There is no limit on the width of the popup with this mode, I currently don't see a need for it.

If we run into problems with the automatic mode, we can reopen this issue.

![image](https://user-images.githubusercontent.com/70658773/174555450-67c1a23c-8e2e-4d21-83df-21af765bce95.png)
