### ISSUE TITLE
Assert when trying to filter entity tree

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1397]
- **Version:** Git Master Branch
- **OS:** Windows

Got an assert with the callstack
```
 	the-machinery.exe!lookup_property(const tm_the_truth_o * tt, const tm_the_truth_object_o * obj, unsigned int property_i, tm_the_truth_property_type assert_type) Line 573	C
 	the-machinery.exe!get_string(const tm_the_truth_o * tt, const tm_the_truth_object_o * obj, unsigned int property)
>	the-machinery-dll.dll!private__filter_menu(tm_tab_o * tab, tm_ui_o * ui, const tm_ui_style_t * uistyle_in)
 	the-machinery-dll.dll!tab__keyboard_iteraction(void * state, tm_tree_view_o * tree, tm_ui_o * ui, tm_ui_style_t * uistyle, bool is_first_responder)
 	tm_editor_views.dll!ui(tm_tree_view_o * tree, tm_ui_o * ui, const tm_ui_style_t * uistyle_in, tm_rect_t rect)
 	the-machinery-dll.dll!tab__ui(tm_tab_o * tab, tm_ui_o * ui, const tm_ui_style_t * uistyle, tm_rect_t content_r)
 	tm_ui.dll!private__draw_ui_task(void * data)
```
because the owner of the "tag" (https://github.com/OurMachinery/themachinery/blob/e7941722ddbf5a8a44ba59956750688a81abe769/the_machinery/entity_tree_tab.c#L3750) is none.

**Comment by Tisten** [comment]
This is what the truth inspector says about one of the tag objects:
![image](https://user-images.githubusercontent.com/6726075/173791762-9461bc38-e91d-4069-b51f-10d2a16fd389.png)

**Comment by leonardo-ourmachinery** [comment]
I added a check to make sure we only filter for "non-temporary" tags.
I still haven't managed to reproduce it, but it should be fixed with https://github.com/OurMachinery/themachinery/commit/e08fa24158c7ee9d23cfa3e7579f29bd899c1002
