### ISSUE TITLE
Double clicking a folder in the Asset Browser should toggle expand/collapse

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#14]
EDITOR: Asset Browser: dbl click on folder should toggle expand/collapse (no, Unity’s way is bad, you have to be spot on the arrow to click it).

**Comment by niklas-ourmachinery** [comment]
You mean in the folder tree in the left part of the asset browser, right?

**Comment by nekitu** [comment]
Yes, right now expanding folder is done only when clicking on arrow (as in Unity), but it is really tedious (at least for me).

**Comment by niklas-ourmachinery** [comment]
Fixed.
