### ISSUE TITLE
Crash in `tm_graph_interpreter_api->write_wire()` when disabling a ui component

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1400]
- **Version:** Git Master Branch
- **OS:** Windows

Use the PR https://github.com/OurMachinery/themachinery/pull/1003
And this project [crash.zip](https://github.com/OurMachinery/themachinery-public/files/8917958/crash.zip)

Repro steps:
1. Click on the UI Text component in the Entity Tree (in world entity).
2. In the Properties tab, click the "Start Disabled" property 4 times.
3. The-machinery should have crashed now with a deleted graph_intepreter object.

Am I using the code from https://github.com/OurMachinery/themachinery/pull/969 wrong?`Why would it crash in the graph interpreter because of this?

**Comment by simon-ourmachinery** [comment]
Should be fixed. This was because a component could be disabled 2 times which would cause an issue of the "entity" data being 2 times moved destroying the memory layout and bounds.

**Comment by simon-ourmachinery** [comment]
4ee739350612910c2171cb9ceaa5539a0f846ccb
