### ISSUE TITLE
No nodes appear when trying to create a node from the output of the "To String Node"

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1401]
- **Version:** Git Master Branch
- **OS:** Windows

The output of the "To String Node" is a String, so all node types which take a string as input should appear. But not a single node does:
![image](https://user-images.githubusercontent.com/6726075/174245490-f75f0f2f-30be-4b17-b066-cffbabe5cf9e.png)

Compare with a string constant:
![image](https://user-images.githubusercontent.com/6726075/174245556-aec2c03b-fdeb-4b93-8159-22e594c1a49a.png)

**Comment by frank-ourmachinery** [comment]
Fixed in master
