### ISSUE TITLE
Error when updating simulation while changing a graph

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1406]
- **Version:** Git Master Branch
- **OS:** Windows

Repro project:
[UpdateGraph.zip](https://github.com/OurMachinery/themachinery-public/files/8947969/UpdateGraph.zip)

Repro steps:
1. Open the Entity Graph in world
2. Start a simulation and dock Simulation tab next to the Entity Graph tab so both are visible
3. Change anything in the graph (move a node, change Volume argument for `Mixer Set Volume")
4. Note the errors spamming the console

Additional things to try:
- Connect the "Reload Event" to "Mixer Play Wav" and note that multiple sounds will spawn on every update.

Also note:
- Fixing this issue should not regress the fix of https://github.com/OurMachinery/themachinery-public/issues/1237

**Comment by Tisten** [comment]
It would be great if there was a clear picture of when init, reload, terminate and tick is run.

Perhaps something like:

Init is called when an asset has been loaded, tick is called after physics each simulation step and controlling physics will always produce one frame of lag, reload is called from `tm_entity_api->propagate_asset_changes()` and terminate will be called when the graph is removed, e.g from `tm_entity_api->destroy_context()` or `tm_entity_api->clear_world()`

To correctly manage the lifetime of a resource in a graph, this is how it should look:
![image](https://user-images.githubusercontent.com/6726075/174786407-644c7f55-391f-441e-af79-87f0a1028e02.png)

This assumes there is a "Set Variable" which accepts all wire types, like a "playing sound". I guess this will be enabled with https://github.com/OurMachinery/themachinery/pull/954

**Comment by simon-ourmachinery** [comment]
@leonardo-ourmachinery  props we should schedule the graph even in a proper entity system that runs in the init, update but the shutdown runs on component removal.

**Comment by Tisten** [comment]
Not part of this problem, but one way to cut a frame of input latency in the physics is to add separate "tick before phys" and "tick after phys" events.

**Comment by simon-ourmachinery** [comment]
My comment was pointing to a different message. 

Explains when what is called.
https://books.ourmachinery.com/gameplay_coding/visual_scripting/index.html

**Comment by Tisten** [comment]
What is part of this issue is the way a "reload" is implemented. Looking at the code I see that it destroys the intepreter before creating a new. That means that the reload event can't read wires and variables from before the reload, so there is no way to stop the mixer at that point.

I guess there are a few ways to tackle it:
* Transfer values and variables and wires from the old intepreter to the new during the reload, so spawned things survive the reload. It requires knowledge of which old wire became which new wire. Quite complex, but if the graph is engineered as above I think it should solve cases where new assets are added, since they now spawn on reload as well.
* Remove the Reload event since it can't patch data anyway, run Shutdown before the reload and Init after the reload. This feels very limiting since it forces destruction of all things controlled by the graph.
* Make the reload event into a two node event, the first run before destruction which expliclity serialize the state which needs to survive the reload, the second run after the reload and it deserialize the state and create new variables/write to new wires. This means no mapping is needed between before and after reload, only the state stored by the reload node needs to survive.

I guess you can come up with more...

**Comment by leonardo-ourmachinery** [comment]
Me and @simon-ourmachinery talked about this a bit yesterday.
We analyzed a bit all the possible solutions, and it seemed to us that the cleanest solution of all is to "split" the reload event into two separated events. (your option n. 3).

We'll discuss it with the rest of the team internally before proceeding.
