### ISSUE TITLE
The "Type" dropdown for Graph Variables would be much easier to navigate if they were alphabetically sorted

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#1408]
- **Version:** Git Master Branch
- **OS:** Windows

Find "Entity Asset" in this list in 1 second!
![image](https://user-images.githubusercontent.com/6726075/174832046-e10a6c2c-c99a-4b7b-807f-fc7f9f7027e1.png)

**Comment by simon-ourmachinery** [comment]
Note:
In case anyone wonders because they do not have these variables: They are behind a feature flag.

**Comment by Tisten** [comment]
<3
