### ISSUE TITLE
Crash when playing any sound clip

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#141]
Tested when playing the audio samples provided in the `sound` example project. Audio output to external sound card (24-bit, 96kHz, stereo). Same issue occur when using on-board output source as well.

No further reproductions steps unfortunately.

**Comment by niklas-ourmachinery** [comment]
Looks like this is an issue with your CPU not supporting the `vfmadd231ps` instruction. What CPU do you have?

**Comment by niklas-ourmachinery** [comment]
That instruction is apart of the FMA3 instruction set -- currently we only check for AVX support, not for FMA3 support... will look into it.

**Comment by cyberfrank** [comment]
> Looks like this is an issue with your CPU not supporting the `vfmadd231ps` instruction. What CPU do you have?

Crash occurred on i7 3770K.

**Comment by niklas-ourmachinery** [comment]
Yes, confirmed, it's because you are missing the FMA3 instruction set. I sent an updated engine to you without the `vfmadd231ps` instruction for testing.

**Comment by cyberfrank** [comment]
We now have sound! Thanks.
