### ISSUE TITLE
tmbuild does not find Visual Studio Preview editions

### ISSUE THREAD

**Issue by jtlehtinen** [OurMachinery/themachinery-public#1429]
Would it be possible to add Preview edition as the _least_ preferred edition that tmbuild searches for?

An example msbuild location:

> `C:\Program Files\Microsoft Visual Studio\2022\Preview\Msbuild\Current\Bin\MSBuild.exe`

`vswhere.exe` lists Preview editions if `-prerelease` flag is specified.

Currently it is possible to make Preview edition work by setting an environment variable:

> `set TM_VS2019_DIR=C:\Program Files\Microsoft Visual Studio\2022\Preview`

so feel free to close without further action. That being said, in my case would be a slightly less-friction-experience if a Preview edition is found without setting an environment variable.

**Comment by simon-ourmachinery** [comment]
@jtlehtinen  can you ping me on discord in case you have discord. Do you have SC access?
