### ISSUE TITLE
drag and drop un parent

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#144]
Currently the only way to unparent an object is to drop it in the level entity.
It makes sense with the idea that everything is an entity even the level but this becomes tricky when you deal with a very large level with tons of objects so I'm wondering if perhaps a drag and drop in between two objects as a unparent function (ie: reparent to the parent of those two objects) would be a solution.

**Comment by niklas-ourmachinery** [comment]
Dropping on another object reparents to that object, so we can’t reuse that. There is really no Unparent operation — it’s really reparent to the root entity.

I think we probably want keyboard operations for moving items in the tree. That might solve this issue.

**Comment by laurentopia** [comment]
What if you shrink the detection region of each node and the in betwen space, make it parent to level up? they do that on maya and unity, maybe also photoshop

**Comment by niklas-ourmachinery** [comment]
Hmm... I could try that out to see how it feels.

**Comment by leonardo-ourmachinery** [comment]
The Next Release will contain a "Level Up" button in the Entity context menu that will allow you to do exactly this: parent an entity to it's current grand-parent (if any).
It also has a shortcut, Ctrl + U, so you can quickly move "up" in the hierarchy by just keep pressing Ctrl + U.

Unfortunately we couldn't do that with drag and drop "in between", as our plan is to use that for reordering entities.
I'm leaving the issue open both for feedback on the new button and for future suggestions.

**Comment by karl-ourmachinery** [comment]
@leonardo-ourmachinery Can't you use the "in between" thing for both reordering and re-parenting? If you drop-in-between within the current parent, its a re-order. If you drop-in-between into a new parent, it's a re-parent and re-order combined.

**Comment by leonardo-ourmachinery** [comment]
Yes, I should absolutely do that. :) I'll implement that in the next release.

**Comment by leonardo-ourmachinery** [comment]
We now allow re-parenting of entities to any other Entity in the Entity Tree though drag and drop.

The fix will be available in the next release.
