### ISSUE TITLE
forum access?

### ISSUE THREAD

**Issue by laurentopia** [OurMachinery/themachinery-public#145]
it seems a bit silly but ... how do I access the forum?
I deleted the email and the webpage doesn't have a login button
![image](https://user-images.githubusercontent.com/26075468/77211703-ffbc8a00-6ac1-11ea-9a6c-5abf4e74bdb3.png)

**Comment by cyberfrank** [comment]
Once you have received your signup confirmation, you can login at https://forums.ourmachinery.com/.

**Comment by niklas-ourmachinery** [comment]
Yes, use that link. We should probably add it to the web page.

**Comment by laurentopia** [comment]
thanks guys
