### ISSUE TITLE
Frame system time not affected by simulation speed multiplier

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#146]
When doing time-based shader effects, it would be useful to simulate them at the same speed as entity engines in the project, even when using the simulation speed modifier. In detail, the `tm_shader_frame_system_t` time information does not expose a parameter that accounts for the Simulate tab speed modifier. I would only consider this a very minor issue.

**Comment by tobias-ourmachinery** [comment]
Fixed in next release.
