### ISSUE TITLE
Add duplicate option to asset browser context menu

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#147]
I would like to duplicate a creation graph.  The current work around is to create a new create graph, open the graph whose logic I would like to duplicate, copy the selection, and paste it into the new graph.  A duplicate option in the context menu would be ideal.

**Comment by niklas-ourmachinery** [comment]
You can do this today with Copy/Paste in the Asset Browser (copy/paste the asset itself), but I agree that the Asset Browser context menu should have a duplicate option.

**Comment by chrisperrella** [comment]
Okay cool, maybe adding copy paste to the context menu in the asset browser would also be helpful.  Its a lot of mouse movement to get back to the top of the screen and keyboard shortcuts lack discoverability.

**Comment by niklas-ourmachinery** [comment]
Fixed in next release.
