### ISSUE TITLE
Allow users to pin creation graphs to the UI

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#148]
I would like to have 2 creation graphs open at once.  Adding a 'pin' option to tabs would allow the user to keep a particular graph open, while browsing other creation graphs.

**Comment by niklas-ourmachinery** [comment]
Yes, we have a plan for updating the tab/focus system with:

* Ability to pin tabs to viewing a certain object.
* Ability to pin tabs to follow the focus of another tab (instead of every other tab).
* Drop down menu with a "history" for the tab so you can go back to previously edited objects.

**Comment by niklas-ourmachinery** [comment]
This will be in the next version.
