### ISSUE TITLE
Allow the user to rotate the keylight in the preview window

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#156]
While pressing and holding a hotkey `L`(?), allow the user to rotate the keylight in the Preview window. 

![rotate_light](https://user-images.githubusercontent.com/8780192/77237242-a0bf4980-6b83-11ea-833f-a0bde7d9da88.gif)

**Comment by tobias-ourmachinery** [comment]
Related to #157 -- will close this.
