### ISSUE TITLE
Allow the user to set a lighting environment in the preview window

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#157]
Ideally, the user would have a way to set a skybox to be used for reflections and diffuse lighting in the preview window.

**Comment by tobias-ourmachinery** [comment]
Yes, I completely agree.. There is a need for something like this, but not only for the preview tab. As you might have noticed there's a magical directional light in the Scene Tab and Preview Tab, but only until the entity you are currently viewing contains any other kind of light in which case we stop spawning the magical directional light.

This is a bit messy at the moment.. but I *think* what we want is something like this:

Introduce a "Lighting Environment" concept per viewport tab, the lighting environment itself is just a reference to an entity. Make it simple to toggle the lighting environment on/off using, when on allow rotating the lighting environment by holding some special key. Kind of similar to how the default editor camera works.

**Comment by karl-ourmachinery** [comment]
This is partially done now, it is possible to set a skydome as a Lighting Environment, remains to make it rotatable though.

**Comment by karl-ourmachinery** [comment]
In the next version it will be possible to rotate the lighting environment by holding CTRL and drag-clicking.
