### ISSUE TITLE
There are visual artifacts when zooming away from point lights

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#159]
Repro:
- Open `scene.entity` in the root of `light_artifact.the_machinery` 
- Zoom away from assets and lights in scene
- Observe black flickering pixels generated around the point lights

![light_artifacts](https://user-images.githubusercontent.com/8780192/77238720-1204f980-6b90-11ea-88d3-0dbf8db93fe7.gif)

https://www.dropbox.com/s/5fcod3o141gfxix/light_artifact.zip?dl=0

PC Specs: 
- Ryzen 7
- GTX 1080 (Drivers: 442.74)

**Comment by tobias-ourmachinery** [comment]
This is related to default editor camera depth buffer precision issues. Note that the barrels are kind of big (approx 40 meter high and 50 meter in diameter) and our default camera settings are configured to be able to view details up close (with an initial near clip plane of 10cm). 

But I should see if we can't increase the depth buffer precision somehow, maybe by moving to a reverse floating point depth buffer.
