### ISSUE TITLE
Crash when setting a Light Component type to IBL

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#160]
I can't recall the specific steps to repro.  I believe I had switched one of my `light.entity`s from a `Point` to an `IBL` type.  Crash dump is on Dropbox.

https://www.dropbox.com/s/fckohcgrpj0r266/the-machinery.exe.532.zip?dl=0

**Comment by niklas-ourmachinery** [comment]
This crashes with:

~~~
Unhandled exception at 0x00007FFC6B90158A (tm_render_graph_toolbox.dll) in the-machinery.exe.532.dmp: 0xC0000094: Integer division by zero.
~~~

In `shadow_mapping.c:300`:

~~~
const uint32_t sm_size = tm_min(atlas_width / sm, max_shadow_resolution);
~~~

| Name | Value | Type |
| ---- | ----- | ---- |
| n_shadow_maps | 0x00000000 | unsigned int |
| sm | 0x00000000 | unsigned int |

**Comment by niklas-ourmachinery** [comment]
Looks like this was fixed by @tobias-ourmachinery already. Will be in next release.
