### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ivan-cx** [OurMachinery/themachinery-public#164]
Would be great to be able to use The Machinery  on Linux machines. I've heard that you plan to implement it in future, so here is an official issue where you can put labels and comments on :smiley:

**Comment by niklas-ourmachinery** [comment]
Good, good!

Note that the core libraries and command line tools already compile for Linux (tested with Windows Subsystem for Linux) and OS X, but things like rendering and window systems aren't supported yet.

**Comment by frank-ourmachinery** [comment]
Support has been added
