### ISSUE TITLE
GUI: Resource path in property editor should show the end of the path instead of beginning

### ISSUE THREAD

**Issue by oLoPuSo** [OurMachinery/themachinery-public#167]
When showing resource name of a resource in a property editor resource picker you should show the end of the path instead of the beginning of the path. 
In projects with lots of sub paths it is really hard to tell the difference between different creation graphs in a folder as the end of the path is trimmed. The same thing applies to the resource browser drop down.

**Comment by niklas-ourmachinery** [comment]
Fixed.
