### ISSUE TITLE
UX: Copying or instantiating a new item in the Asset browser doesnt show new item in properties

### ISSUE THREAD

**Issue by oLoPuSo** [OurMachinery/themachinery-public#169]
When copying or instantiating an item in the asset browser the newly created item is selected in the asset browser but the property editor does not update with the new item. 

I constantly instantiate an item and then accidentally rename the original item instead of the instance or copy because i miss to click the instance in the asset browser before editing the name in the property editor

**Comment by niklas-ourmachinery** [comment]
Fixed in next version
