### ISSUE TITLE
Don't list components in the Entity Tree

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#17]
Having components listed in scene tree does indeed clutter it, plus you also have them listed in the Properties when entity is selected, redundant in scene tree.

**Comment by niklas-ourmachinery** [comment]
I don't think I agree with this, I think it's nice to see the components in the entity tree. But maybe we could add an option to show/hide them.

**Comment by nekitu** [comment]
That would be perfect, it is actually a natural feature for that tree (to toggle show of components).

**Comment by nekitu** [comment]
It is probably a matter of taste, for me it is too verbose/noisy (and I've seen someone else also asking for entities only in the forums), so a checkbox in the settings would be great indeed

**Comment by leonardo-ourmachinery** [comment]
In the next release we will include a button that will allow you to hide/show Entity components in the Entity Tree.
It will be part of an "Entity Tree toolbar" that it's currently in development, so it will be pretty easy to discover and use.

Closing the issue for now.
