### ISSUE TITLE
Prototypes: Instantiating a graph that is an instance of another graph with an override breaks the graph

### ISSUE THREAD

**Issue by oLoPuSo** [OurMachinery/themachinery-public#171]
So i have an original creation graph that implements a simple image archive - image filtering - image output flow. 
![image](https://user-images.githubusercontent.com/29459104/77294278-47226080-6ce4-11ea-9832-cddb98f31503.png)

I have 3 other graphs that inherits this graph and overrides the filtering options to have specific prototype graphs for importing different types of textures. bc, nm orm textures
![image](https://user-images.githubusercontent.com/29459104/77294314-586b6d00-6ce4-11ea-9363-473131b016cd.png)

Now when i inherit one of these three graphs the final graph filtering node seems broken. 
![image](https://user-images.githubusercontent.com/29459104/77294342-67eab600-6ce4-11ea-902a-d5c7aa2ec768.png)

**Comment by niklas-ourmachinery** [comment]
Unfortunately I think we need to disable the feature of having multiple levels of prototyping for now.

It's something that we always planned to support, but we've run into some tricky issues with how the data model handles this. We'll investigate and re-enable the feature when we can.

**Comment by karl-ourmachinery** [comment]
This works since a while back.
