### ISSUE TITLE
Graphics corruption after loading sample project

### ISSUE THREAD

**Issue by coastwise** [OurMachinery/themachinery-public#174]
I have only been clicking around for a few minutes. I loaded the default content sample, then the animation sample. Opened the simulation tab, then started and paused & reset the simulation a few times. Then when I opened the gameplay-first-person project, this happened:
![2020-03-23 16_33_26-Window](https://user-images.githubusercontent.com/239493/77360766-50cbb880-6d24-11ea-8b22-d42ad6e6f0d8.png)

The editor is still responsive, but everything looks corrupted.

Not sure what data you might need, but here are some specs of my system.
OS: Windows 10 Education 64-bit. Version 1909; OS build 18363.720
CPU: i7-4790 w 16GB ram.
GPU: GeForce GTX 770, Driver version 432.00.

Before that happened, it loaded **so fast**, everything running like butter! I'm really excited to get into this further. Great job all!! 🥂

**Comment by coastwise** [comment]
FYI: I tried doing all the same actions again and have not been able to reproduce the issue so far.

**Comment by tobias-ourmachinery** [comment]
@coastwise Let me know if you figure out a way to reproduce this. Also try upgrading your GPU drivers as the one you are currently running is pretty old by now.

**Comment by niklas-ourmachinery** [comment]
Ok I'll close this for now -- reopen it if you can get it again.

@tobias-ourmachinery FYI.

**Comment by coastwise** [comment]
Good call on the drivers. I'm on a new Windows installation, so I guess that's the one that shipped with it. I've updated them to 445.75 and will keep you posted if it happens again.
