### ISSUE TITLE
README.md - Linebreak in 'forum' link causes breakage when opened in Chrome

### ISSUE THREAD

**Issue by coastwise** [OurMachinery/themachinery-public#175]
I didn't know Chrome could open and render .md files directly! When it does this with the one in ourmachinery, the forum link gets rendered in full, and the closing paren is included in the url.

![2020-03-23 17_00_13-README Beta](https://user-images.githubusercontent.com/239493/77362770-e3218b80-6d27-11ea-8ab9-a0293d2b1b4f.png)

If you change the markup so there are no newlines inside the parens for the link, the problem in Chrome goes away.

**Comment by niklas-ourmachinery** [comment]
Fixed.

Side note: Chrome can't actually open `.md` files -- this is a HTML file (extension is `.md.html`). It has a little piece of code at the end that renders the Markdown into HTML:

~~~
<!-- Markdeep: -->
<style class="fallback">body{visibility:hidden;white-space:pre;font-family:monospace}</style>
<script>window.markdeepOptions = {tocStyle: 'long'};</script>
<script src="markdeep.min.js"></script>
<script src="https://casual-effects.com/markdeep/latest/markdeep.min.js?"></script>
<script>window.alreadyProcessedMarkdeep||(document.body.style.visibility="visible")</script>
~~~

See https://casual-effects.com/markdeep/ for more info.

**Comment by coastwise** [comment]
I'm running on a new Windows install and Explorer defaults to hiding (some) extensions. I swear I opened the properties to double check... alas. I've got them turned on now tho! 👍
