### ISSUE TITLE
animation sample - camera control code still running when simulation is paused

### ISSUE THREAD

**Issue by coastwise** [OurMachinery/themachinery-public#176]
I wasn't sure if this was intended or not, but after opening the gameplay-third-person sample which _didn't_ exhibit this behavior, I think it is a bug.
In the animation.the_machinery sample, if you open the simulation window and pause the simulation, the mouse still moves the camera and rotates the character in the scene.

**Comment by niklas-ourmachinery** [comment]
This happens because the visual script does not look at the simulation time step, which the gameplay plugin does. It’s not a bug in the engine but you could maybe consider it a bug in the sample project.

**Comment by niklas-ourmachinery** [comment]
Fixed as of 2020.9.
