### ISSUE TITLE
Zooming with alt+mousewheel causes camera angle reset

### ISSUE THREAD

**Issue by coastwise** [OurMachinery/themachinery-public#177]
If you rotate the camera to get a certain view of the scene, then use alt+mousewheel to zoom in on the thing you're looking at, the angle (but not the position) of the camera gets reset to the original direction when the scene was first loaded.

**Comment by niklas-ourmachinery** [comment]
Fixed in 2020.5.

The focus point for Zoom and Spin operations is now moved with the camera when you Freeflight Rotate and Translate.
