### ISSUE TITLE
Bind Ctrl+D to duplicate

### ISSUE THREAD

**Issue by chrisperrella** [OurMachinery/themachinery-public#178]
In Maya, the duplicate command uses the hotkey `Ctrl+D`, I believe it should be the default hotkey in the machinery as well. 

Note: `Shift+LMB` is a great hotkey and mimics Maya conventions - duplicate and drag to duplicate are not the same command and should have different hotkeys.

**Comment by niklas-ourmachinery** [comment]
Fixed in 2020.4.a.
