### ISSUE TITLE
Missing context menu on property text fields

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#18]
I cannot get the context menu which appeared on property text fields on right click (with Reset etc.), don’t know why, maybe is off screen.

**Comment by niklas-ourmachinery** [comment]
Could you clarify? I don't understand.

**Comment by nekitu** [comment]
When I right clicked a text input from the Properties window, I think it was Translation or something like that, I got a context menu with Reset value item and such. Right now I cannot get it anymore, doesnt appear on right click.

**Comment by niklas-ourmachinery** [comment]
Ah I see. This is intended behavior. This menu only shows up for entities that have been "instanced" from a "prototype". (See the Prototype section in the README.) It allows you to remove the override on a value in the UI and Reset it back to the default from the prototype.

**Comment by nekitu** [comment]
Ah ok, I thought properties have default values regardless.
