### ISSUE TITLE
Support Visual Studio Build Tools

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#186]
Forum thread: https://forums.ourmachinery.com/t/visual-studio-requirements-for-tmbuild-exe/535

Currently we build with Visual Studio Community Edition 2017 or 2019, but Visual Studio build tools doesn't work.

We look for one of:

* `ProgramFiles(x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe`
* `ProgramFiles(x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe`

We should find out where Visual Studio Build Tools installs it's executables and support that too.

Maybe also investigate doing an automated install of Visual Studio Build Tools -- seems like that should be possible. That way we can fully automate the compile on a blank machine -- no manual installs.

**Comment by GideonUng** [comment]
for my build tools 2019 its located under 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin`

for build tools 2017 it will probably also be analogous to vs 2017

**Comment by xgalaxy** [comment]
I'd suggest utilizing Microsoft's vswhere to locate these things.
See: https://github.com/microsoft/vswhere

**Comment by d44m1n** [comment]
It's ridiculous idea. Almost 8k lines of code to just find msbuild.

**Comment by niklas-ourmachinery** [comment]
That sounds reasonable.

**Comment by niklas-ourmachinery** [comment]
Fixed for first 2020.4 hotfix release: 2020.4.a.

I hardcoded the paths instead of relying on vswhere -- might change to vswhere in a future version.

**Comment by ikrima** [comment]
Could you add the hardcoded paths for other Visual Studio  SKUs in the mean time as well? Ex: Professional - C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin

**Comment by niklas-ourmachinery** [comment]
Already did!

**Comment by shul** [comment]
hi, my vs 2019 is installed in x:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
I don't think hard coding it to C:\... is working so well

**Comment by niklas-ourmachinery** [comment]
It's not hard-coded to C:, it's using `%ProgramFiles(x86)%\Microsoft Visual Studio\2019\MSBuild\Current\Bin`. But if you've installed it to a different directory than your regular *ProgramFiles(x86)* directory, it won't work.

Maybe we should just expose a `TM_VISUAL_STUDIO_DIR` environment variable or command line parameter that you can use if our regular detection doesn't work.

**Comment by shul** [comment]
> It's not hard-coded to C:, it's using `%ProgramFiles(x86)%\Microsoft Visual Studio\2019\MSBuild\Current\Bin`. But if you've installed it to a different directory than your regular _ProgramFiles(x86)_ directory, it won't work.
> 
> Maybe we should just expose a `TM_VISUAL_STUDIO_DIR` environment variable or command line parameter that you can use if our regular detection doesn't work.

great idea, do that

**Comment by niklas-ourmachinery** [comment]
Fixed, for next release, you will be able to control this with `TM_VS2017_DIR` and `TM_VS2019_DIR` environment variables, i.e.:

```
SET TM_VS2019_DIR= x:\Program Files (x86)\Microsoft Visual Studio\2019
```

**Comment by shul** [comment]
> Fixed, for next release, you will be able to control this with `TM_VS2017_DIR` and `TM_VS2019_DIR` environment variables, i.e.:
> 
> ```
> SET TM_VS2019_DIR=x:\Program Files (x86)\Microsoft Visual Studio\2019
> ```

Sorry.. but my msbuild.exe is at X:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin

running the above I get:
X:\Downloads\beta-2020.11.a\bin>set TM_VS2019_DIR="x:\Program Files (x86)\Microsoft Visual Studio\2019"

X:\Downloads\beta-2020.11.a\bin>tmbuild
tmbuild: could not find VS2019 at `"x:\Program Files (x86)\Microsoft Visual Studio\2019"\BuildTools\MSBuild\Current\Bin\msbuild.exe`

so I don't got this "BuildTools" dir

**Comment by simon-ourmachinery** [comment]
Will investigate

**Comment by simon-ourmachinery** [comment]
@shul is this the  exact error message you got: `"x:\Program Files (x86)\Microsoft Visual Studio\2019"\BuildTools\MSBuild\Current\Bin\msbuild.exe`? Including the `"`?

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery  maybe exposing `vs2017_msbuild` and `vs2017_msbuild` via a argument would also solve this issue:

´´´
tmbuild --set-msbuild-path "C:\Program Files (x86)\Microsoft Visual Studio\2019" --build-tool "vs2019"
```

**Comment by niklas-ourmachinery** [comment]
Closing this one as fixed as I believe `TM_VS2019_DIR` variable works. Will reopen if there are additional issues.
