### ISSUE TITLE
Creation Graph line not cancelled on text box focus

### ISSUE THREAD

**Issue by AODQ** [OurMachinery/themachinery-public#188]
The nodegraph line that connects nodes together is not cancelled in a consistent way. Clicking on text boxes does not cancel them, and if clicking on a drop-down menu, the line is not cancelled until an option is chosen. Maybe the latter is intentional but the former definitely seems like a bug.

**Comment by karl-ourmachinery** [comment]
Fixed in the upcoming version 2020.4.
