### ISSUE TITLE
Crash when resuming simulation after restart has been pressed

### ISSUE THREAD

**Issue by jonathansty** [OurMachinery/themachinery-public#189]
A crash eventually occurs when restarting and running the simulation in the gameplay first person sample. 

To reproduce:

1. launch the machinery: I'm using: `the-machinery.exe --hot-reload`
2. Open the first person gameplay sample
3. Open the simulation window 
4. Run around a bit
5. Press the restart button 
6. Start the simulation

Result:
Console gets spammed with the following
![image](https://user-images.githubusercontent.com/7695731/77692778-289bbe00-6f9f-11ea-9a54-b142c6f37a92.png)

[Crash dump](https://we.tl/t-dOGQtkHb0p)

Note: This doesn't always seem to happen.

**Comment by karl-ourmachinery** [comment]
Thank you. I have been looking into this.

@tobias-ourmachinery I looked at this and made it so we destroy & re-create the entity context when restarting. This makes all the gameplay code re-init properly. However, with this in place I get a crash at `render_graph.c:742`. I have put my changes in a branch called `simulate-destroy-context-on-restart`. Please take a look when you have time. All you have to do is open simulate in an empty project and click restart.

**Comment by tobias-ourmachinery** [comment]
Fixed in 2020.4.a
