### ISSUE TITLE
Core assets show up as dirty at launch

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#191]
1. Start The Machinery
2. Open the **Modified Assets** tab.
3. `core/creation_graphs/dcc-material.creation` and `core/light.entity` show up as modified.
4. If you use **File > New Project** you will be asked to save your changes.

Expected behavior: There should be no dirty resources when starting the application.

Note: After selecting **New Project** the assets no longer appear as dirty.

**Comment by tobias-ourmachinery** [comment]
Fixed
