### ISSUE TITLE
Changes to the render pipeline does not hot-reload without explicit step

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#193]
When doing any change to the render pipeline (e.g. injecting new modules), the changes are not immediately reflected in the editor when hot-reloading the plugin. To reflect the changes, one must open and close either the scene or simulation tab.

This can cause some confusion if:
1) you forget to refresh the scene view and therefore assume your changes had no effect
2) the changes made causes a render backend crash that is not seen until the simulate tab is opened or the scene tab is refreshed

For me, both of these scenarios have occurred and I consider the issue to be a mild to moderate annoyance. I assume this happens due to the render graph setup not being performed until a new view is created.

**Comment by tobias-ourmachinery** [comment]
Fixed in 2020.5
