### ISSUE TITLE
tmbuild: could not find VS2019

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#196]
tmbuild.exe fails to find the VS2019 installation.

I'm using beta-2020.4.zip and the Visual Studio version is:

> Microsoft Visual Studio Professional 2019
> Version 16.5.2

```
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by niklas-ourmachinery** [comment]
This is the same basic issue as #186. It will be fixed in the next point release 2020.4.a.
