### ISSUE TITLE
Change “Open an entity” into “Open an entity from Asset Browser”, took me some time

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#20]
Change “Open an entity” into “Open an entity from Asset Browser”, took me some time.

**Comment by niklas-ourmachinery** [comment]
Could you clarify what you mean by this? Where should this be changed?

**Comment by nekitu** [comment]
The Entity Tree tab, when there is no entity opened. There is a centered text in the window.

**Comment by niklas-ourmachinery** [comment]
Ah, thanks, should be an easy fix.

**Comment by niklas-ourmachinery** [comment]
Fixed.
