### ISSUE TITLE
Fatal Error in vulkan_render_backend.c:3603

### ISSUE THREAD

**Issue by GdLinkLock** [OurMachinery/themachinery-public#202]
hi，first thank you creating machinery.
I just run the the-machinery.exe；after some randomization，it pops up an  error box.
Maybe the files can give a clue.
![image](https://user-images.githubusercontent.com/4956809/80295217-8fc9af80-87a3-11ea-994f-4cc5756f2a82.png)
[The Machinery-crash-20200426.zip](https://github.com/OurMachinery/themachinery-public/files/4534485/The.Machinery-crash-20200426.zip)
[the_machinery_exe 2020-04-26 09.50.29.zip](https://github.com/OurMachinery/themachinery-public/files/4534498/the_machinery_exe.2020-04-26.09.50.29.zip)

**Comment by niklas-ourmachinery** [comment]
Did you try updating to the latest drivers as the error message suggested?

What GPU do you have in your machine?

**Comment by GdLinkLock** [comment]
> Did you try updating to the latest drivers as the error message suggested?
> 
> What GPU do you have in your machine?
sorry to reply later.
![vc](https://user-images.githubusercontent.com/4956809/81040326-b98a8100-8edd-11ea-94bd-c9ca0cf2cdc5.png)

**Comment by frank-ourmachinery** [comment]
The code which caused the crash has been updated.
