### ISSUE TITLE
Most gizmos do not behave correctly when multiple objects are selected

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#204]
Iniital issue:

Holding shift and using the move gizmo to clone multiple objects is not working as intended:

![shift_draw_clone](https://user-images.githubusercontent.com/2807036/80307226-feb8ff80-87c7-11ea-8663-28194220cc3c.gif)

Update #1:

After a bit more testing I noticed that it's actually the move gizmo that doesn't behave correctly with multiple objects selected:

![multi_move](https://user-images.githubusercontent.com/2807036/80307361-e2699280-87c8-11ea-9371-d89541e56ee1.gif)

Update #2:

Turns out this same issue occurs for most of the gizmos when operating on multiple objects, for example rotate gizmo:

![multi_actions](https://user-images.githubusercontent.com/2807036/80307463-7dfb0300-87c9-11ea-949a-7ccd9ad700b8.gif)

Updating the title accordingly.

The Machinery - Version 2020.4.a

**Comment by peterlindgren** [comment]
The gizmos work as expected if I move the selected objects from underneath the box entity in the Entity Tree.

**Comment by niklas-ourmachinery** [comment]
Reproduced. I will investigate.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.5.
