### ISSUE TITLE
Malformed postbuildcommands in samples/premake5.lua

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#206]
I noticed that the `{COPY}` token in premake5 expects directory paths.

Generating a vs2019 solution for the samples which includes the following post-build commands:

> postbuildcommands {
>     '{COPY} %TM_SDK_DIR%/bin/plugins/*.dll ../..//bin/%{cfg.buildcfg}/plugins/',
>     '{COPY} %TM_SDK_DIR%/bin/data-simple-3d/shaders/*.* ../../bin/%{cfg.buildcfg}/data-simple-3d/shaders/'
> }

Creates projects with post-build events that look like this:

![image](https://user-images.githubusercontent.com/2807036/80366117-012f5e00-8889-11ea-9778-8732082181b3.png)

Here's my output:

> C:\Users\Peter Lindgren\work\test>the_machinery\bin\tmbuild.exe
> Building configurations...
> Running action 'vs2019'...
> Generated build/test_exe/test-exe.vcxproj...
> Done (65ms).
> Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   test-dll.vcxproj -> C:\Users\Peter Lindgren\work\test\build\test_dll\..\..\the_machinery\bin\plugins
>   \test.dll
>   test-exe.vcxproj -> C:\Users\Peter Lindgren\work\test\build\test_exe\..\..\bin\Debug\test.exe
>   File not found - *.dll
>   File not found - *.*
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: The command "IF EXIST the_machinery\bin\plugins\*.dll\ (xcopy /Q /E /Y /I the_machinery\bin\plugins\*.dll ..\..\bin\Debug\plugins > nul) ELSE (xcopy /Q /Y /I the_machinery\bin\plugins\*.dll ..\..\bin\Debug\plugins > nul) [C:\Users\Peter Lindgren\work\test\build\test_exe\test-exe.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: IF EXIST the_machinery\bin\data-test\shaders\*.*\ (xcopy /Q /E /Y /I the_machinery\bin\data-test\shaders\*.* ..\..\bin\Debug\data-test\shaders > nul) ELSE (xcopy /Q /Y /I the_machinery\bin\data-test\shaders\*.* ..\..\bin\Debug\data-test\shaders > nul) [C:\Users\Peter Lindgren\work\test\build\test_exe\test-exe.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd" exited with code 4. [C:\Users\Peter Lindgren\work\test\build\test_exe\test-exe.vcxproj]

NOTE: The screenshot and output are not from the same project and solution. It shouldn't matter though.

**Comment by niklas-ourmachinery** [comment]
Fixed, will be in next release (2020.5).

I you want to fix it locally, just deleting the last portions of the path should work.

**Comment by peterlindgren** [comment]
An additional note on this:

If **TM_SDK_DIR** contains a space then the premake5 generated IF statement will fail. Adding quotes around the path appears to work.

I regret my chosen username at least twice a week...

**Comment by niklas-ourmachinery** [comment]
Thank you! Fixed this too.

**Comment by niklas-ourmachinery** [comment]
BTW, I accidentally mistyped my username as "nikla" on my work machine... doesn't seem to be any easy & reliable way to change it.
