### ISSUE TITLE
Typo in README.md.html

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#207]
There's a typo under the **What is in this beta?** section: bin/tm**b**build.exe

I've seen plenty more but it's pretty wasteful to create new issues all of the time, or re-opening a closed issue, so I'll collect a couple at a time instead.

**Comment by niklas-ourmachinery** [comment]
Fixed, thank you.

If you have multiple typos, maybe the easiest thing is just to upload a new `README.md.html` file or a patch file and I can merge it.
