### ISSUE TITLE
Old component properties remain "stuck"

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#209]
While trying to figure out how to create a DCC Asset property on a custom component I noticed that the Frequency and Amplitude properties remain after rebuilding the component plugin and even restarting The Machinery. 

![image](https://user-images.githubusercontent.com/2807036/80809265-9b611000-8bc1-11ea-8be0-beb82ca0e408.png)

The component code only registers one property, "DCC Asset", as can be seen below. I obviously haven't figured out how to get the DCC Asset property work yet, but I wouldn't expect that to be an issue with the two old properties remaining.

![image](https://user-images.githubusercontent.com/2807036/80809357-c8152780-8bc1-11ea-8846-c89c0b003189.png)

![image](https://user-images.githubusercontent.com/2807036/80809392-e418c900-8bc1-11ea-8a41-a2a4c14ef5bd.png)

**Comment by peterlindgren** [comment]
Hmm, I'm not sure what I did but the old properties are now gone. I suspect I might've had another instance of The Machinery running in the background.

**Comment by niklas-ourmachinery** [comment]
This is expected, but perhaps somewhat surprising behavior.

When we load a project we preserve all the properties found in that project -- even if those properties no longer exist in the runtime. There are multiple reasons for this:

- We want load to be a non-destructive operation.
- Sometimes those old properties are needed -- for example if you need to migrate content from an old version you might need the values of the old properties to transfer them to new properties.

When you save the project we only save the properties that are present in the current runtime, so at this point, any "old" properties disappear.
