### ISSUE TITLE
Make"history" dropdown menu in the Scene tab easier to find and click

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#21]
The “<” from Scene tab was not obvious at all that it was an arrow to scroll the opened entities, maybe just add new tab when opening new entity in asset browser, it is hard to click on those “arrows”

**Comment by niklas-ourmachinery** [comment]
Agreed.

The main reason it hasn't been fixed yet is that I wanted to do a more major rewrite and give all the tabs in the UI a "history" drop down, similar to the one that the scene tab has.

**Comment by niklas-ourmachinery** [comment]
This has been fixed in 2020.4 -- all tabs now have a Recent Objects sub menu in their context menus.
