### ISSUE TITLE
White text on yellow background color schemes is difficult to read

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#210]
I just wanted to make a note that I find the white text on yellow background quite difficult to read.

The Application Settings support changing the grid color, perhaps the (highlighted) tab, property reference dropdowns (ex DCC Asset) and status bar colors could be user specified as well?

**Comment by niklas-ourmachinery** [comment]
We should probably just change the color. We could add an option for it too, but in general I don’t think options should be used to mitigate bad design choices.

**Comment by frank-ourmachinery** [comment]
We recently had some time to improve the contrast of both the default dark theme and the light theme. There should no longer be any pure white text on bright yellow text anywhere. In some cases the text became black and in same cases we darkened the yellow color. 

The light theme in general has gotten a massive upgrade in contrast and should be much more usable now. Keep an eye out for the next beta release!
