### ISSUE TITLE
Load most recent project and its context on startup

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#211]
It would be great if the editor automatically loaded the most recent project and the context, ie the layout of the various views, which entity I was editing, what folder I was browsing in the Asset Browser, etc.

**Comment by niklas-ourmachinery** [comment]
Yes, agreed!

**Comment by niklas-ourmachinery** [comment]
Fix for 2020.12.

FYI: @leonardo-ourmachinery
