### ISSUE TITLE
Discarding asset changes

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#212]
I've edited an entity but I don't know how to discard the changes. There's a greyed out Revert option in the Asset Browser context menu which might be it?

![image](https://user-images.githubusercontent.com/2807036/80821147-804dca80-8bd8-11ea-9d50-80b4bc336e3a.png)

**Comment by niklas-ourmachinery** [comment]
The Revert option does not work for projects saved in "Single File" format, because in that case there are no individual assets saved to disk. It only works when you save in directory/source control friendly format.
