### ISSUE TITLE
Crash in gameplay_third_person sample when attempting to visualize Physics Shape Component

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#213]
I open the gameplay_third_person sample and with the Scene View highlighted:
Scene->Visualize->Physics Shape Component->All Tags

It appears to be 100% reproducible for me,

[the_machinery_exe 2020-05-02 10.34.21.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/4567328/the_machinery_exe.2020-05-02.10.34.21.dmp.zip)

I have a full dump available as well if there is a need.

**Comment by niklas-ourmachinery** [comment]
Fixed in 2020.5.
