### ISSUE TITLE
Dragging entity into Scene error: Style has not passed a valid feather width in tm_draw2d_style_t.

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#214]
When I drag an entity into the Scene view, in the gameplay_third_person sample, the follow error starts to spam the Console view:

> ✖ C:\work\themachinery\plugins\ui\draw2d.c(1387): error: Style has not passed a valid feather width in tm_draw2d_style_t. (1028)

Dropping the entity works as expected.

**Comment by niklas-ourmachinery** [comment]
Fixed in 2020.5.
