### ISSUE TITLE
Property editor enum either crash or displays corrupt dropdown strings

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#216]
I'm trying to use the editor enum property (`TM_THE_TRUTH__EDITOR__UINT32_T__ENUM`) but The Machinery crashes when I create a new object with the property or displays a dropdown with corrupt strings if I select an object that was created with the same property name and type (`TM_THE_TRUTH_PROPERTY_TYPE_UINT32_T`) but without the enum part.

First case:
[the_machinery_exe 2020-05-03 20.11.42.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/4571282/the_machinery_exe.2020-05-03.20.11.42.dmp.zip)

Second case:
![image](https://user-images.githubusercontent.com/2807036/80921935-e9b90f00-8d79-11ea-84d0-f70381bf9dfc.png)

This is what my property definition looks like:

```
[PROP_PARTITIONING_TYPE] = {
    .name = "partitioning_type",
    .type = TM_THE_TRUTH_PROPERTY_TYPE_UINT32_T,
    .editor = TM_THE_TRUTH__EDITOR__UINT32_T__ENUM,
    .enum_editor = {
        .count = 3,
        .names = (const char *[3]){
            TM_LOCALIZE_LATER("type-a"),
            TM_LOCALIZE_LATER("type-b"),
            TM_LOCALIZE_LATER("type-c")
        },
    },
}
```

I can work around it by creating the dropdown via a properties ui aspect.

**Comment by niklas-ourmachinery** [comment]
`create_object_type()` doesn't copy the `.enum_editor.names` array, so you can't use a local for it as you do in your example, you have to give it permanent storage, i.e.:

```c
static const char *partitioning_type_names[3] = {
    TM_LOCALIZE_LATER("type-a"),
    TM_LOCALIZE_LATER("type-b"),
    TM_LOCALIZE_LATER("type-c")
};

[PROP_PARTITIONING_TYPE] = {
    // ...
    .enum_editor = {
        .count = TM_ARRAY_COUNT(partitioning_type_names),
        .names = partitioning_type_names,
    },
}
```

I'll clarify this in the header file.
