### ISSUE TITLE
Crash on editor startup if creating object type TM_THE_TRUTH_PROPERTY_TYPE_NONE

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#217]
The editor crashes on startup if I create a truth object with type **TM_THE_TRUTH_PROPERTY_TYPE_NONE**.

```
[TM_TT_PROP__CUSTOM_COMPONENT__BUILD_BUTTON] = {
    .name = "build",
    .type = TM_THE_TRUTH_PROPERTY_TYPE_NONE,
},
```

> ---------------------------
> Fatal Error
> ---------------------------
> The application encountered a fatal error and needs to shut down.
> If this error occurred during bootup, try updating your GPU drivers.
> Otherwise, report this error together with crash dumps and logs from
> AppData\Local\{Application Name}.
> 
> C:\work\themachinery\foundation\the_truth.c:678
> 
> align > 0
> ---------------------------
> OK   
> ---------------------------

[Uploading the_machinery_exe 2020-05-06 08.51.13.dmp.zip…]()

It's understandable that TM_THE_TRUTH_PROPERTY_TYPE_NONE is not a valid type, and the assertion **align > 0** gives a clue at least. But I wouldn't expect the editor to crash on startup due to a bad input like that, instead I would expect it to log an error message, "bad object type" and ignore the input.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.5
