### ISSUE TITLE
Dangling buffers are not removed when saving directory projects. 

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#219]
See e.g https://github.com/OurMachinery/themachinery/tree/master/the_machinery/core/light.tm_buffers/ 

Only two of those buffers are referenced from https://github.com/OurMachinery/themachinery/blob/master/the_machinery/core/light.tm_entity

**Comment by niklas-ourmachinery** [comment]
Fixed in 2020.5.
