### ISSUE TITLE
error on opening

### ISSUE THREAD

**Issue by jaredgreen2** [OurMachinery/themachinery-public#220]
on windows, gpu is nvidia 1060:

Entry Point Not Found
The procedure entry point vkCmdSetDeviceMask could not be located in the dynamic link library
<target directory>\beta-2020.3.b\bin\plugins\tm_vulkan_render_backend.dll

and

failed to load the vulkan backend
will continue using nil backend

and the window is black

**Comment by jaredgreen2** [comment]
updated driver, error no longer occurs

**Comment by niklas-ourmachinery** [comment]
Great!
