### ISSUE TITLE
Allow categorized components 

### ISSUE THREAD

**Issue by philipstenmark** [OurMachinery/themachinery-public#226]
You have probably considered this before but I think it would be nice to allow categorization of entity components in similar fashion to how graph nodes are presented. It can get difficult to add and find components in larger projects. As far as I know, the components are named directly from their respective _file names_, so things probably just clutter (in code) when introducing categories, which is unfortunate.

Also, it feels like the search view for adding new components is somewhat hidden. It only appears when pressing `Tab` (in the `Entity Tree` view). When hovered however, another list appears on the right instead. This behavior is not the same as `Add Node` or `Add Child Entity From Asset...`. In the `Properties` view, the component search functionality is not available at all. 

Some nice default categories could be; `The Machinery`, `Physics` and `Sample`.

**Comment by niklas-ourmachinery** [comment]
Yes, I think that would be a good idea.

Another thing I've been thinking of is to automatically add a search field to any menu with >10 items. It would help with navigating through long menus wherever they are, and it is pretty easy to do since we're rolling our own UI system.

**Comment by karl-ourmachinery** [comment]
This is added since some time ago.
