### ISSUE TITLE
Color themes

### ISSUE THREAD

**Issue by philipstenmark** [OurMachinery/themachinery-public#227]
This is probably a recurring topic but I truly envision that there should be an option to change color theme in the editor (e.g. `Window > Theme`). I understand that the dark theme is iconic for The Machinery brand and aligns with other Our Machinery resources. However, I most often find it easier to use a lighter theme - especially when working in the daytime.

The dark theme can also feel misaligned when the user is using a light theme for their code editor or other external applications. 

By this, I suggest that there should at least be _some_ included themes with the engine, such as: `The Machinery` (default), `Light` (white) and `Gray` (a mix of both). Beyond these, it is up to the user to hack and build their own theme and colors for more specific needs.

**Comment by niklas-ourmachinery** [comment]
Agreed. I've been working a bit outside in the summer and the lighter themes definitely work better in those light conditions.

This should not be too complicated... the majority of the work will be finding all the places that have "cheated" and not used one of our predefined theme colors. But it would be a good thing to find those spots anyway.

**Comment by niklas-ourmachinery** [comment]
Fixed: 2020.6 has a color theme editor.
