### ISSUE TITLE
Markdeep seems to be unable to parse apidoc.md.html

### ISSUE THREAD

**Issue by sY9sE33** [OurMachinery/themachinery-public#229]
In the latest beta version (beta-2020.5, though I haven't checked since beta-2020.3), the API docs is unable to load itself (tested in Chrome and Firefox on Windows 10) because of  `<` and `>` tags. Escaping these in the documentation with `&lt;` and `&gt;` respectively seems to fix the issue.

**Comment by niklas-ourmachinery** [comment]
Hmm... that's weird. I just tried it and it works for me (though rendering the page takes a little time). If I enable the Debug Console (in Chrome), there are no error messages printed either.

What exactly are you seeing? Is the rendered page just not appearing? It might be that it takes so long to render that Chrome aborts the JavaScript.

We should probably split it up into smaller documents... or pre-generate the HTML instead of relying on calling markdeep when it's loaded.

But TBH I'm not sure if we should even keep this documentation, or if we should just point users to the header files (which this is generated from). Do you find it useful to be able to read the documentation in the browser like this?

**Comment by sY9sE33** [comment]
It essentially tries loading infinitely and never gets there. When I open the .html file in an IDE, it's quite confused (which is why my guess is that the angle brackets are the problem for me) and is reporting various header includes as HTML tags. In the browser debug consoles, I don't get any errors either, but Chrome hangs outright, and Firefox asks me if I want to kill the script or wait.

![image](https://user-images.githubusercontent.com/9271353/82262609-3894a600-992f-11ea-9082-6c6e05660008.png)

I've tested the previous versions of the docs that I have locally (all releases pre-alpha-200122-1536 - beta-2020.3.b) and I can't reproduce the problem with any of them as shown here (I navigate to beta-2020.3.a after the beta-2020.5.a docs hang):

![docs](https://user-images.githubusercontent.com/9271353/82263488-02582600-9931-11ea-979c-b00b993dc0db.gif)

**Comment by niklas-ourmachinery** [comment]
It might just be that the later versions have more documentation and thus takes longer to render, because I don't think we have changed anything in the documentation system. I think the right fix for this is either to split up the document into multiple smaller ones or pre-render the HTML from Markdown (or maybe both).

BTW, you didn't answer my question... do you find having the documentation in this format useful? Do you prefer reading the .html page rather than the source .h files and if so, what do you like about it?

**Comment by sY9sE33** [comment]
Sorry about that! I actually love having the documentation in the current format as I can always have it open and search through it on my vertical monitor while I'm planning things out in my head. My 2 cents is that I personally really like that it's all on a single page since searching through it is faster, and would prefer that to having it split up into many different pages. Having the docs as a web page also prevents me from having too many files open at once  in Visual Studio and losing myself trying to navigate through them all (in part this is due to not having used Visual studio for ~15 years and preferring other editors while not having taken the time to set those up for this yet).

In regards to rendering time, I've let it run for 30+ minutes while never succeeding. Replacing the angled brackets with `&lt;` and `&gt;` in the content of the page makes the page render pretty much instantly, though I assume that the content is being generated automatically and that's not necessarily something that you have control over. If this is a problem that only I am experiencing, I don't mind dealing with it on my end if it means keeping the docs on a single page.

**Comment by cyberfrank** [comment]
I am getting the same issue too. Document loads briefly and shows text without any active stylesheet, then it just turns white.

**Comment by niklas-ourmachinery** [comment]
I did a pass over the documentation generator:

* Encoded `<`, etc as `&lt;`, etc.
* Removed a bunch of internal stuff that shouldn't be in there.
* Fixed some other minor things.

Doesn't seem to affect the behavior that much for me... the file worked for me before and it works after, and the load time seems similar.

Here is the new `apidoc.md.html` file:

https://www.dropbox.com/t/pEChoUMTcj5h6BxC

Can you check if this works better for you?

**Comment by cyberfrank** [comment]
The new one works fine! I can load it in ~3 seconds now.
I think in a future version of the API documentation it would be beneficial to divide each separate library into their own file and have some landing page with a search function. Optionally, it can be nice to view the docs online. I noticed earlier that the OM guidebook is already online.

**Comment by niklas-ourmachinery** [comment]
Oh, great! I'll close this issue then.

**Comment by cyberfrank** [comment]
> Do you find it useful to be able to read the documentation in the browser like this?

I can respond to this as well. All in all, I think the doc is mostly useful for higher lever overviews of the different systems as well as seeing what components are available to use. This allows to find things without explicitly browsing the `headers` directory and painstakingly opening/closing files. It is also friendlier to look at compared to comments in code!

**Comment by InjaEm** [comment]
Odd, this did not come up in search or I would have posted here instead....

Anyhow, Just to add to this conversation, I prefer NOT to have to view the docs online, as I am not always able to connect to the internet.

**Comment by peterlindgren** [comment]
I have the same issue with `apidoc.md.html` in `beta-2020.8`. That's to say the page is all white and never finishes loading. I've tested it with the following browser versions on Windows:
Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
Microsoft Edge Version 85.0.564.41 (Official build) (64-bit)

If I replace the `<` `>` tags with `&lt;` and `&gt;` as suggested by @sY9sE33 it loads as expected

**Comment by niklas-ourmachinery** [comment]
Hmm... I'm a bit confused. `apidoc.md.html` in 2020.8 doesn't have any `<` and `>` tags in it, they have all been encoded as `&lt;` and `&gt;` already.

I just double checked this by downloading the beta and opening `apidoc.md.html` in a text editor. Are you sure you are looking at the right file?

**Comment by peterlindgren** [comment]
You're right, not sure how I managed to mix up the doc folders... Sorry about that!

**Comment by niklas-ourmachinery** [comment]
No problem, glad it worked out!

I'm considering splitting the API doc file into multiple files, and maybe offline generate the HTML from the Markdown to reduce loading times.
