### ISSUE TITLE
Crash in Vulkan: vkCreateSwapchainKHR() fails

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#231]
When closing and opening multiple windows, the `vkCreateSwapchainKHR()` call in Vulkan sometimes fails:

```
C:\work\themachinery\plugins\vulkan_render_backend\vulkan_render_backend.c(3501): error: res == VK_SUCCESS
```

I can reproduce this pretty consistently by:

1. Open the `animation` sample project.
2. Double click `bot/xbot.asm` to open the ASM editor.
3. Close the ASM editor window.
4. Repeat steps 2-3 until it crashes (usually in <10 tries).

**Comment by tobias-ourmachinery** [comment]
I think I've managed to fix the issue by adding CS_OWNDC to our window class. I can no longer reproduce it after 100+ window open/close operations. Closing this, reopen if you still manage to reproduce it @niklas-ourmachinery
