### ISSUE TITLE
Iconifying and restoring the editor makes the window larger than the native resolution

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#234]
When the `the-machinery.exe` editor is iconified and restored, the editor resolution exceeds the initial resolution before the close occurred. 

I use 1920x1080 with the taskbar at the left side of the screen. Once the window is restored, the new editor window resolution is 1872x1096, which is both wider and taller than the usable desktop space. This requires manually recorrecting the window size, which is annoying. Attempting to maximize the window at this state is an additional entry point to [issue #233](https://github.com/OurMachinery/themachinery-public/issues/233), which is unfortunate.

This issue also appears to be true with the `simple-draw.exe` sample app.

**Comment by tobias-ourmachinery** [comment]
Fixed in next release.
