### ISSUE TITLE
Iconifying the editor window multiple times causes black screen

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#236]
When iconifying and restoring `the-machinery.exe` editor window multiple times, the window turns black. When tested, the window was at most able to be iconified twice in a shorter succession before going dark. 

By resizing the editor window (i.e. by double clicking the title bar or successfully hitting the maximize button), the black screen disappears.  When the black screen shows, I get coil whine due to high framerate.

Additionally, when attempting to close `the-machinery.exe` while the black screen is showing, only the window closes but not the process itself. The process remains to run in the background until manually shutdown.

I get no Vulkan API error in the log and the program does not technically _crash,_ so there is no recorded crash dump either. 

Note that this issue is not true for the `simple-draw.exe` sample application.

**Comment by tobias-ourmachinery** [comment]
Sigh, stupid regression, how sloppy of us. Fixed in next version.
