### ISSUE TITLE
Incomplete documentation for component interfaces

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#238]
I have noticed that `tm_ci_render_i` has no documentation yet. It would be useful to briefly describe the context and usage of it, especially compared to `tm_ci_shader_i`. Also, `tm_ci_shader_i` is missing usage description for `update`. I understand that a better overview can be found on the OM blog, but I suggest that some context should be given near the code too. I definitely imagine that `tm_ci_shader_i` and `tm_ci_render_i` could easily be confused unless properly contextualized.

None of these appear in the generated OM documentation either, which I may assume is by design.

**Comment by frank-ourmachinery** [comment]
Some documentation has been added. The default render pipeline also has a few examples now of how the tm_ci_shader_i is used in practice.
