### ISSUE TITLE
Missing extern "C" scope in headers 

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#240]
Including some foundation headers (chash.inl amongst others) in C++ causes linker errors due to the include not wrapping its declarations in an **extern "C"** scope.

It's easy enough to work around by wrapping the includes myself, however the wild goose chase of debugging cryptic MSVC linker errors is not a good way to start your day, so it would be much appreciated if the scopes were a part of the headers.

**Comment by niklas-ourmachinery** [comment]
If you are writing C++ code you should wrap all the header inclusion from The Machinery in `extern "C"`, like this:

~~~c
extern "C" {
extern "C" {
#include <foundation/allocator.h>
#include <foundation/api_registry.h>
...
}
~~~

We should be clearer about this in the documentation to avoid this error. But I'd prefer to avoid adding the standard C/C++ include boiler plate to every file:

~~~c
#ifdef __cplusplus
extern "C" {
#endif

...

#ifdef __cplusplus
}
#endif
~~~

I like to keep the header files as clean as possible and find this "noisy".

But perhaps there is an alternative solution... maybe we could add something to `api_registry.h` to gives a clear error if it is included in a C++ file without `extern "C"`, then the problem would be easy to pinpoint.

**Comment by niklas-ourmachinery** [comment]
I found a way of getting an error if you forget `extern "C"`:

~~~c
// Generate an error if this file was included in a C++ file, without wrapping the include in extern
// "C". If you forget extern "C", the first declaration will get C++ linkage and you will then get a
// conflict on the second declaration.
#ifdef __cplusplus
void use_extern_c_wrapper_to_include_the_machinery_headers_in_cpp_files();
extern "C" void use_extern_c_wrapper_to_include_the_machinery_headers_in_cpp_files();
#endif
~~~

This will be in 2020.6.
