### ISSUE TITLE
Opening editor after minimizing causes black window.

### ISSUE THREAD

**Issue by Arzana** [OurMachinery/themachinery-public#242]
Version: 2020.5.a

Steps to reproduce ([video](https://youtu.be/x2P1j1iiLpY)):
- Open The Machinery
- Minimize the window
- Open the window again by clicking the icon on the taskbar
- The window is now black.

The window will resume proper rendering upon resize either by maximizing or resizing manually, other window messages don't affect this like input or moving the window.

**Comment by cyberfrank** [comment]
This is probably the same as #236.

**Comment by tobias-ourmachinery** [comment]
@cyberfrank is correct. This was reported in #236 and has been fixed. Will be part of next release.
