### ISSUE TITLE
Mouse Wheel Zooming

### ISSUE THREAD

**Issue by InjaEm** [OurMachinery/themachinery-public#243]
Hello,
I use programs such as bforartists ( Blender 3D fork ) and C4D ( Cinema 4D ) where the Mouse Wheel can allow you to zoom in and out of the 3D environment.

Can you add this ability ?

Thank you

**Comment by niklas-ourmachinery** [comment]
I think that could work... the mouse wheel right now controls the "freeflight" speed. But we could maybe change it so that when you are not in freeflight mode, the mouse wheel zooms instead. Let me have a little think about it.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.6.
