### ISSUE TITLE
Crash on New Project

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#245]
Happens in 2020.6-wip

1. Open `modular-dungeon-kit.the_machinery`.
2. **File > New Project**

Crash in `private__record_save()`

~~~c
if (app->saved.type != SAVE_TYPE__NONE && app->project_settings_id && strcmp(path, app->saved.path) != 0) {
~~~

| Name            | Value                      | Type         |
| --------------- | -------------------------- | ------------ |
| app->saved.type | SAVE_TYPE__SINGLE_FILE (1) | save_type    |
| type            | SAVE_TYPE__NONE (0)        | save_type    |
| path            | 0x0000000000000000 <NULL>  | const char * |

**Comment by karl-ourmachinery** [comment]
Fixed.
