### ISSUE TITLE
Update Button

### ISSUE THREAD

**Issue by ExoVerse** [OurMachinery/themachinery-public#247]
I noticed in the newest thread that they are using a newer version of TM then I am. Is there an update button or menu choice somewhere that I don't know about ?

EDIT : Reason I ask is because of what happened in our previous communications. You had a newer version then I did which had solved the issues on your end, but I reported it as if it was brand new without knowledge that there was a newer version. So it caused confusion not having the latest version.

**Comment by niklas-ourmachinery** [comment]
There is no update button.

Once we move to Open Beta, we will switch to a better distribution method than just uploading the latest exe to the forum and at that point we'll add an Update mechanism too.

**Comment by InjaEm** [comment]
Sounds good. Looking forward to it.

**Comment by niklas-ourmachinery** [comment]
In 2020.9, there is a Downloads tab that shows available updates.
