### ISSUE TITLE
apidoc.md.html does not open in firefox web browser

### ISSUE THREAD

**Issue by InjaEm** [OurMachinery/themachinery-public#248]
As the title states, the apidoc.md.html file does not open in firefox web browser. It just hangs.

However the other doc file guidebook.md.html works fine.

I do not use any other browser, since I either do not trust them or I don't agree with their terms of service. Firefox is the only browser I use for security reasons. So using another web-browser is not an option.

**Comment by niklas-ourmachinery** [comment]
Duplicate of #229.
