### ISSUE TITLE
Graph nodes snap at 1.5x grid size

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#251]
The snapping option in the Graph views (in 2020.6) is unrelated to the grid.

Changing the snapping value should change the grid size so that the snapping and the drawn grid matches.

**Comment by niklas-ourmachinery** [comment]
Sorry, I spoke to soon. It is actually related to the grid, but it seems to snap at 1.5x the grid size instead of at the grid size itself. See attached gif:

![Uploading graph-snapping.gif…]()

I expect them to snap at the actual grid size.

This is probably related to the UI scale set in Windows... mine is set at 150 %... if you have your UI scale set at 100 % you might not be able to see the issue.

**Comment by karl-ourmachinery** [comment]
I do this in the graph code 

```
const tm_draw2d_aux_data_grid_t aux_data = {
    .offset = graph->offset,
    .scale = graph->scale * ((1.0f / 30.0f) * snap_distance)
};
tm_draw2d_api->aux_rect(uib.vbuffer, uib.ibuffers[TM_UI_BUFFER_MAIN], style, rect, TM_DRAW2D_AUX_DATA_TYPE_GRID, &aux_data, sizeof(aux_data));
```
It may be that we need to do something smarter than the 1/30 hack, for example make it possible to specify the virtual cell size instead of scale.

**Comment by tobias-ourmachinery** [comment]
We're now specifying cell_size instead of the scale value and I've made sure it correctly respects the dpi_scale_factor.
