### ISSUE TITLE
Event inputs are merged in subgraph

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#252]
If we create this graph:

![image](https://user-images.githubusercontent.com/26548514/84961681-c643ec80-b0b9-11ea-91de-9cecba4ffd22.png)

And then create a subgraph of the two Spawn Entity nodes, the two Input Events are merged to a single Input connector. The two Entity inputs remain separate though (as `Entity` and `Entity (1)`:

![image](https://user-images.githubusercontent.com/26548514/84961760-f25f6d80-b0b9-11ea-9870-f9aded1bafbb.png)

If we double click the subgraph to look inside it, the two event inputs look separate, but when we zoom back out to the bigger graph, they are merged again:

![image](https://user-images.githubusercontent.com/26548514/84961811-1622b380-b0ba-11ea-9835-da04bdc4318e.png)

**Comment by karl-ourmachinery** [comment]
Fixed.
