### ISSUE TITLE
Importing glTF asset crashes the editor

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#254]
Importing glTF asset crashes the editor (Tested on The Machinery June 2020 Release).

1. Download following glTF file [crash.glb](https://github.com/infosia/themachinery-issues/blob/master/0001/crash.glb)
2. Check if glTF file is valid (ie. Open it with Windows 3D Viewer)
2. Launch The Machinery Editor
3. Import `crash.glb` asset from editor menu `File` -> `Import`
4. The editor crashes

Expected: The Editor should not crash and should be able to load glTF asset.

**Comment by niklas-ourmachinery** [comment]
Reproduced the crash.

The crash happens inside the Open Asset Import Library (https://github.com/assimp/assimp) which is a third party library that we use for importing assets.

We'll investigate it a bit further to see if it's an easy fix or something we need to report as an issue with that library.

**Comment by infosia** [comment]
Thanks for the information. I was able to fix the crash locally by checking vertex id for bone weight in assimp. https://github.com/infosia/assimp/commit/6acaaee80f51fa43e62f55a8728bdfb26d364be2 I'm not sure why glb file produces invalid vertex id but assimp should not crash in any way. I am willing to report & push a PR to them. Feel free to apply this change onto your assimp library too :)

So I am now able to import the file onto the Machinery Editor without crash (it produces some more error messages though but it works anyway) so I'm happy to close this issue now.

**Comment by infosia** [comment]
Just in case the issue in assimp is already fixed on its `master` https://github.com/assimp/assimp/pull/3288 in June. I tried to fix it by overwriting Machinery's assimp DLL (`assimp-vc142-mtd.dll`) but overwriting assimp DLL caused  plugin load error in `tm_assimp`. I'm wondering if there's any chance to opensource `tm_assimp` plugin so that we can customize assimp's behavior in case it'll take long time to fix?

**Comment by tobias-ourmachinery** [comment]
In 2020.11 this file imports correctly and there is no longer any problem with the skinning. Closing this.
