### ISSUE TITLE
Ability to use point primitives

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#255]
`tm_renderer_primitive_type` does not have point list primitive type. My understanding is `tm_renderer_primitive_type` is somehow related to `VkPrimitiveTopology` in that case supporting point list (`VK_PRIMITIVE_TOPOLOGY_POINT_LIST`) is needed because it is often used to implement GPU particles (for instance [GPU particle system](https://github.com/SaschaWillems/Vulkan/blob/master/examples/computeparticles/computeparticles.cpp))

**Comment by tobias-ourmachinery** [comment]
Fixed in next release.
