### ISSUE TITLE
Make color editor a popup

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#26]
Too many clicks to edit a color, I don’t want to expand/collapse it every time I change a color, make it a popup, otherwise I need to close it myself by going to the actual color button, it pollutes the inspector when the color editor stays expanded.

**Comment by niklas-ourmachinery** [comment]
Not sure about this one -- will leave the design as-is for now and do some more thinking about this.

**Comment by simon-ourmachinery** [comment]
@karll-ourmachinery is working on this one and this issue can be seen as closed. Since we have changed the implementation of the color picker in general from when this has been issued.
