### ISSUE TITLE
It should be possible to reorder the inputs and outputs of a subgraph

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#260]
We need to be able to reorder the inputs and outputs to make the node look the way we want.

Not being able to reorder the connectors can lead to strange setups like this:

![image](https://user-images.githubusercontent.com/26548514/86185302-dbbe0b00-baea-11ea-957d-9caaaa9e96c4.png)

**Comment by karl-ourmachinery** [comment]
This has been added for 2020.12
