### ISSUE TITLE
Input events do not work when placed in subgraphs

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#261]
In the `physics` sample project, if you simulate `Scenes/Stack`, you should be able to throw balls by pressing Space and shoot bricks by pressing the mouse button -- this doesn't work in the latest version of the sample-projects that has the event nodes in a subgraph.

In `Special Objects/Ball Thrower` -- this doesn't work:

![image](https://user-images.githubusercontent.com/26548514/86187209-1c6c5300-baf0-11ea-91ad-325f7ff8bd50.png)

But this does:

![image](https://user-images.githubusercontent.com/26548514/86187229-29894200-baf0-11ea-8674-0bd32bff9d39.png)

Even though the subgraph contains the exact same nodes.

**Comment by karl-ourmachinery** [comment]
I can't reproduce this.

Here's the graph I had:

![image](https://user-images.githubusercontent.com/57644882/86243621-fe155e80-bba6-11ea-9942-4051436c1be5.png)

Then I created a subgraph:

![image](https://user-images.githubusercontent.com/57644882/86243662-0e2d3e00-bba7-11ea-9c7e-81af2747b5ac.png)

And it still works. Can you check again, does the subgraph have the output node connected?

**Comment by karl-ourmachinery** [comment]
(closed by accident)

**Comment by niklas-ourmachinery** [comment]
Fixed with the latest changes.
