### ISSUE TITLE
See the subgraph path when editing

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#262]
Instead of just displaying [< Back] the subgraph editing view should display the whole path to the subgraph.

In this case [Root / Check Collision with Walls / Check East Wall (z > 4.5)]

![image](https://user-images.githubusercontent.com/26548514/86277721-0c09b600-bb8c-11ea-956c-1720bb1948e3.png)

**Comment by karl-ourmachinery** [comment]
Fixed in the next version. There are now breadcrumbs that both indicate the path and give you the ability to go back to any parent graph.
