### ISSUE TITLE
Program not running properly on Asus TUF 505DU when integrated graphics are active.

### ISSUE THREAD

**Issue by Kos86** [OurMachinery/themachinery-public#265]
Using the June Build, when running the program and after updating graphics drivers to the most up to date version:
![Capture1](https://user-images.githubusercontent.com/14097373/86541659-df002f00-bf0e-11ea-9fd0-2d63ea70785c.PNG)
![Capture2](https://user-images.githubusercontent.com/14097373/86541660-e1fb1f80-bf0e-11ea-82ef-0a0385b37ca1.PNG)

The issue is not present when manually disabling the integrated graphics (Radeon RX Vega 10 ) connected to the Ryzen7 3750H CPU. After disabling it the program is forced to run on the dedicated GF 1660Ti GPU and runs correctly. 
Setting the program (in Windows "Graphics settings" or the "Nvidia Control Panel") the program to use the Nvidia GPU does not affect the situation.

Log and Memory Dumps under link (file was quite big so needed to use dropbox):
[https://www.dropbox.com/s/63a0d3q6wpgz3ou/LogAndMemDump.zip?dl=0](https://www.dropbox.com/s/63a0d3q6wpgz3ou/LogAndMemDump.zip?dl=0)

**Comment by Arzana** [comment]
It's likely that AMD's switchable graphics feature is blocking Vulkan from detecting your graphics card and integrated card. I think that disabling the integrated graphics causes the AMD features to be disabled as well, giving you access to your dedicated GPU. I don't think there is anything we can do to solve this issue.
