### ISSUE TITLE
There is no `ui_vec2` method in `tm_properties_view_api`

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#266]
Currently (2020.6.a) there is no properties view ui method for `tm_vec2_t`, while there are for `tm_vec3_t` and `tm_vec4_t`.

Something like `tm_properties_view_api->ui_vec3` would be a convenient addition:
```
item_rect.y = tm_properties_view_api->ui_vec2(args, item_rect, ...);
```

**Comment by niklas-ourmachinery** [comment]
Good suggestion, I'll add it.

**Comment by niklas-ourmachinery** [comment]
Fixed for next release.
