### ISSUE TITLE
the_machinery.exe does not run correctly from the command line when in %PATH% -- you must specify the full path to the file

### ISSUE THREAD

**Issue by photex** [OurMachinery/themachinery-public#268]
Howdy!

When you run `the-machinery.exe --hot-reload` from any directory other than `%TM_SDK_DIR%\bin`, the editor fails to launch with the following message box:

![hot-reload-problem](https://user-images.githubusercontent.com/301903/87754290-da882000-c804-11ea-9ec2-f5deb2abb965.png)

**Comment by niklas-ourmachinery** [comment]
I'm having trouble reproducing this.

Could you clarify what you mean by "run from another directory"? I.e., what are the exact steps taken?

Do you copy the whole `bin` directory to `c:\projects\slowgames`? Do you run it from the command line?

Could it be that you don't have write privileges to `c:\projects\slowgames`? `--hot-reload` copies the DLLs to temporary file names before loading them (to get around Windows file locking issues). You should be able to see if this is the case by checking if the `tm_hot_reload` copy of the file was created at all. It should appear next to the original DLL.

**Comment by photex** [comment]
Howdy!

So I have a big perforce depot and that workspace is `c:\projects\slowgames\`. Inside of this directory I unzip the beta archive to the `OurMachinery` folder. 

My environment is then setup via an env.bat script in the depot root:
```
set TM_SDK_DIR=%cd%\OurMachinery
set TM_LIB_DIR=%cd%\OurMachinery\lib

set PATH=%TM_SDK_DIR%\bin;%PATH%
```

I open a shell, cd to `c:\projects\slowgames`, then `call .env.bat`.

From this point I was just running from the command line (I'm using cmd.exe with clink under the new Windows Terminal). Since updating to the latest beta though, running from the command line does nothing. Hrm... I can double click the-machinery.exe and it'll startup just fine.

Before the behavior is that I could run it without arguments from any directory, but `--hot-reload` gave me this error.

Ok, if I run it from the command line without a full path given, then it doesn't start. No output to the console, nothing. If I run it with the full path it runs fine, including when using the `--hot-reload`. I wonder if this isn't related somehow?

**Comment by photex** [comment]
I should mention, that in my perforce client spec I'm using the "allwrite" setting and relying on `p4 reconcile`, rather than the default behavior of everything in the depot being read-only unless you `p4 edit` it.

**Comment by niklas-ourmachinery** [comment]
Hmm... I wonder if it's not perforce somehow interfering with this.

* If you unzip the binaries somewhere that is not a perforce directory, does everything work fine?
* When you run it in your perforce directory with `--hot-reload`, does the temporary DLL copy (`the-machinery-dll.tm_hot_reload.nnnnnnnn.dll`) get created or not?

**Comment by photex** [comment]
Yes that all worked fine. Before it only worked if I ran the-machinery.exe from the TM_SDK_DIR\bin directory. Now the only way anything will run is when using the full path to the executable (i.e. I can't run it at all if it's just on my path).

I'll download the previous beta and unzip to c:\OurMachinery and try from there...

**Comment by photex** [comment]
```
Microsoft Windows [Version 10.0.18363.959]
(c) 2019 Microsoft Corporation. All rights reserved.
Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink


c:\projects>set TM_SDK_DIR=c:\OurMachinery

c:\projects>where the-machinery.exe
INFO: Could not find files for the given pattern(s).

c:\projects>set PATH=%TM_SDK_DIR%\bin;%PATH%

c:\projects>where the-machinery.exe
c:\OurMachinery\bin\the-machinery.exe

c:\projects>the-machinery.exe

... Nothing happens, same as the current release ...

c:\projects>the-machinery.exe --hot-reload

... Jackpot, I get the message box as posted to this issue ...

c:\projects>
```

**Comment by photex** [comment]
So not being able to run it without the full path appears to have been a feature of the 2020.6a release. I'll try the previous 2020.6 release as well next.

**Comment by photex** [comment]
Nevermind.. I must have just been using the full path when running it alone before (I didn't use my .env.bat immediately).

But in all cases, I get the sense that if the-machinery.exe is on my path and I try to run it without specifying the full path to the exe then it isn't correctly determining the executable directory.

**Comment by niklas-ourmachinery** [comment]
Ah, I see... so if I interpret everything right, the only issue is that it doesn't run from `PATH` and `--hot-reload` just affects how the error manifests itself.

**Comment by photex** [comment]
That's correct. I could have tested a bit more thoroughly, sorry.

**Comment by niklas-ourmachinery** [comment]
No problem! Glad we found the root cause, should be pretty easy to fix now.

**Comment by niklas-ourmachinery** [comment]
Fixed for the next release.
