### ISSUE TITLE
Windows Win+D function offsets the left of the whole editor

### ISSUE THREAD

**Issue by Gonzako** [OurMachinery/themachinery-public#269]
Here's a simple gif of the whole thing. I'm just pressing Win + D and back in to the editor. Res is 1080

![asdf](https://user-images.githubusercontent.com/18658724/87982398-093d1980-cad7-11ea-84cd-57b937e124ed.gif)

**Comment by niklas-ourmachinery** [comment]
Reproduced.

This seems to only happen in full-screen mode.

@tobias-ourmachinery This seems like your domain.
