### ISSUE TITLE
Pong sample project has two copies of skydome buffer

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#270]
In 2020.7, the `pong` sample project has two copies of the skydome buffer.

One is found here:

```
{
    __uuid: "747c7d4d-f0de-ed5f-79af-ce40848d2218"
    type: "gpu_image_to_image"
    position_x: 161.9479522705078
    position_y: 15.59732913970947
    settings: {
        __type: "tm_cpu_image"
        __uuid: "8834eb4d-005c-a05b-fc34-72ec1d8eb568"
        buffer: "59aefc691b9fa78c"
        description: {
            __uuid: "1e02b415-3128-4f2b-d65e-fbf883698fbb"
            type: 3
            pixel_format: 21038096
            widht: 1024
            height: 1024
            mip_levels: 10
            layer_count: 6
        }
    }
}
```

And the other one here:

```
{
    __uuid: "b9a333d0-3a7b-08b5-91db-82eb7181029a"
    node_settings: "8834eb4d-005c-a05b-fc34-72ec1d8eb568"
    node_settings__type: "tm_cpu_image"
    instanced_settings: {
        __type: "tm_cpu_image"
        __uuid: "61263783-ebbb-2247-a040-0646a3270f2a"
        validity_hash: "7c7582e5bd3c1364"
        buffer: "99ebb40e6f17083a"
        description: {
            __uuid: "293cd205-5fd6-7229-3d14-aaccf8316b2b"
            type: 3
            pixel_format: 21038096
            widht: 1024
            height: 1024
            mip_levels: 10
            layer_count: 6
        }
    }
}
```

Since the skydome buffer is 65 MB this makes a big difference in the size of the project.

* This didn't use to be the case before 2020.7.
* The other project that uses the same skydome (modular dungeon) only has one copy (the `59aefc691b9fa78c` buffer).
* The second copy was introduced by commit [b5657b](https://github.com/OurMachinery/sample-projects/commit/b5657b76c464ce8488de2d7a3a4f0fb951122b3c).
* Before that commit the second `tm_cpu_image` node used the same buffer `59aefc691b9fa78c` as the first one.

So it looks like the root issue is that because of non-determinism or something else, the second `tm_cpu_image` is generating a slighting different 65 MB buffer than the first one, causing both buffers to be saved and the project size to bloat. (When the buffers are identical, they can be shared.)

**Comment by niklas-ourmachinery** [comment]
@tobias-ourmachinery Still there in 2020.9 -- can you investigate if this is expected or not?

**Comment by tobias-ourmachinery** [comment]
Closing this as Pong's skydome has been replaced with a procedural sky.
