### ISSUE TITLE
Support setting Resolution Scale to <1.0

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#271]
Currently, the Resolution Scale setting only allows zooming in, not zooming out (Resolution Scale is clamped to `[1.0, 4.0]`).

It might be useful to also allow zooming out to Resolution Scales < 1.0. I'm not sure if there are any technical limitations that would prevent this. I tried just removing the clamp, but this creates a black border around the UI:

![image](https://user-images.githubusercontent.com/26548514/88087159-5522a980-cb3d-11ea-9667-6b4b7bd0e820.png)

It seems some adjustment to the renderer is needed to support Resolution Scales < 1.0.

**Comment by tobias-ourmachinery** [comment]
Fixed.
