### ISSUE TITLE
Make project path as optional first argument to the-machinery.exe

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#272]
Apart from using `the-machinery --load-project C:/my_project.the_machinery` to open the editor with a project running, it would be great to be able to do `the-machinery.exe C:/my_project.the_machinery`. This allows to associate project files and open by double clicking in Windows (without any custom file association registry or such).

![image](https://user-images.githubusercontent.com/3429723/88262431-78c62b00-ccc8-11ea-8252-0993d2db8266.png)
![image](https://user-images.githubusercontent.com/3429723/88262115-e2920500-ccc7-11ea-802f-73d8aeab4ec6.png)

**Comment by niklas-ourmachinery** [comment]
Good suggestion. Fixed for the next release!
