### ISSUE TITLE
`tm_camera_transform` enum missing from header apidoc output

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#273]
For some reason the APIDOC misses completely the line with the name of the `tm_camera_transform`, that's a really small issue, but may cause new symptoms and confusion in the future, especially with newcomers. While not critical, it's still important to document it here.

## APIDOC
![image](https://user-images.githubusercontent.com/13659144/88279871-27fc0580-ccbb-11ea-9626-56520aff3cc7.png)

## The header and its missing line
```
typedef enum {
    TM_CAMERA_TRANSFORM_DEFAULT = 0,
    TM_CAMERA_TRANSFORM_EYE_LEFT = 1,
    TM_CAMERA_TRANSFORM_EYE_RIGHT = 2,
    TM_CAMERA_TRANSFORM_MAX_TRANSFORMS
} tm_camera_transform; // <--------------------------- Missing line

typedef struct tm_camera_t
{
    tm_mat44_t projection[TM_CAMERA_TRANSFORM_MAX_TRANSFORMS];
    tm_mat44_t view[TM_CAMERA_TRANSFORM_MAX_TRANSFORMS];
    float near_plane;
    float far_plane;
    float vertical_fov;
} tm_camera_t;
```

**Comment by niklas-ourmachinery** [comment]
Fixed for next release.
