### ISSUE TITLE
Crash when move window to another monitor

### ISSUE THREAD

**Issue by vasconssa** [OurMachinery/themachinery-public#274]
Sometimes, when trying to drag the window to another monitor, the editor crashs

![498f8y](https://user-images.githubusercontent.com/7650118/88351930-6aaaf580-cd2e-11ea-96d2-f3fefdc48498.gif)

**Comment by vasconssa** [comment]
I did a test with simple-3d sample, which was crashing too, I moved check_swapchain_resize(app); to the begin of render() function and seems to work.

**Comment by niklas-ourmachinery** [comment]
Thank you for looking into this.

I'll have @tobias-ourmachinery examine if this is the right fix for this... I'm not sure if moving it may have other consequences.

Do you have a crash dump file for the crash?

**Comment by vasconssa** [comment]
> 
> 
> Thank you for looking into this.
> 
> I'll have @tobias-ourmachinery examine if this is the right fix for this... I'm not sure if moving it may have other consequences.
> 
> Do you have a crash dump file for the crash?
I reproduce the bug again, here is the dump file:
[the_machinery_exe 2020-07-29 19.41.49.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/4997078/the_machinery_exe.2020-07-29.19.41.49.dmp.zip)

**Comment by frank-ourmachinery** [comment]
I've been trying my hardest to reproduce it in the current build and I cannot get it to crash anymore. The code at the crash location has also been updated since. So I think it's fair to say that this bug has been fixing.
