### ISSUE TITLE
Different dirty flag behavior for single- and multi-file projects 

### ISSUE THREAD

**Issue by dominikdalek** [OurMachinery/themachinery-public#279]
There is also no way to revert dirty flag on a single asset and all `View > Modified Assets` enables is saving all of them when project is saved as a single file. This behavior differs from multi-file projects and is confusing. Per Niklas:

> If you are saving a project in Single File mode – you can’t revert individual assets, because the assets aren’t individually saved. However, if you save it in “directory” / git friendly mode (the default if you choose Save), assets are saved individually and can be reverted individually. In the near future we will switch to a “database” model for the single file format which will allow saving and reverting individual files there too.

So this issue is either a duplicate of another one or could be used to track implementation of the database model (or neither; reporting for completeness).

**Comment by niklas-ourmachinery** [comment]
Thanks! As said above this will be fixed when we switch over to the "database" model. I'll close this for now, because I think big long-term projects like this are better tracked in other ways than with the issue tracker, but thanks for reporting it!
