### ISSUE TITLE
Dialog window doesn't deselect the menu

### ISSUE THREAD

**Issue by dominikdalek** [OurMachinery/themachinery-public#280]
Clicking `File > Import` opens file selector dialog but doesn’t clear the “menu is active” state, so once dialog is closed, hovering over menu bar opens submenus without any clicks.

**Comment by niklas-ourmachinery** [comment]
The same seems to be true for any menu option that opens a system dialog box (i.e. Open, Save As, etc).

**Comment by niklas-ourmachinery** [comment]
Fixed for next release.
