### ISSUE TITLE
Difficulty in navigating subgraphs

### ISSUE THREAD

**Issue by dominikdalek** [OurMachinery/themachinery-public#281]
Subgraphs aren’t clearly indicated as such. I feel like they would benefit from a distinct color, or border style, etc. to improve affordability.

Once in the subgraph view, the back button is available but it’s not visually distinct in any way so it took me some time to find it. This view does have the history stack but what’s missing is support for backspace and perhaps some indicator of what is on the stack (e.g. breadcrumbs). The UX here should probably be shared with other views (Entity Tree primarily, perhaps others).

According to Niklas:
> Yes, subgraphs should be better indicated and I think there should be a “breadcrumbs” view that shows the subgraph context. I think this is distinct from a “history” view and more like a file system “path”.

**Comment by karl-ourmachinery** [comment]
For the next version we have added breadcrumbs that both show the "path" and also gives you the ability to go back to any parent. Also, backspace can be used to go back to the immediate parent. Other than the breadcrumbs, there is currently no 'border style', we'll see if the breadcrumbs are strong enough visual indicators.

**Comment by dominikdalek** [comment]
@karl-ourmachinery Border style would be a visual indicator that node can be stepped into the node and is separate from breadcrumbs which tell you that you can step out of a node. In theory I could memorize every existing built-in node and use that as a reference to tell built-ins from subgraphs, but that doesn't really scale.

**Comment by karl-ourmachinery** [comment]
Ah, now I understand. I thought you meant something else. I agree, some indicator that you can "open" the subgraph node is a good idea. I'll reopen this.

**Comment by karl-ourmachinery** [comment]
There is now an explicit "Subgraph" label on the subgraph node. There is also a mouse help text at the bottom of the editor screen that tells the user that they can double click it. Also, a context menu item for opening the subgraph had been added, it has a hint that you can double click it instead. I think these things combined give strong enough hints to the user.
