### ISSUE TITLE
Crash when deleting multiple entities at the same time

### ISSUE THREAD

**Issue by erpeo93** [OurMachinery/themachinery-public#283]
[Beta 2020.07]

The editor crashes when trying to delete multiple entities at the same time.
It doesn't crash with _any_ entity combination, but it's easily reproducible:

-Open Pong sample project
-Try to delete multiple static "floor" entities at the same time

**Comment by niklas-ourmachinery** [comment]
Reproduced in 2020.8 -- investigating.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.8.a.
