### ISSUE TITLE
Materials with overwritten inputs in 2020.7 don't convert correctly to 2020.8

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#284]
I've tried migrating a project from 2020.7 to 2020.8 and materials that had their original input values overwritten (Base Color Texture, Normal Map, etc) stopped working.

They end up looking like the left creation graph, even though they should be like in the right example. 

![Annotation 2020-08-31 124300](https://user-images.githubusercontent.com/13659144/91739827-d7fd4200-eb88-11ea-95e2-28c29dac74b9.png)

**Comment by khskarl** [comment]
Opening the prototype seems to work fine and shows the whole input list.

![image](https://user-images.githubusercontent.com/13659144/91740621-f0219100-eb89-11ea-864a-633bc8c2b1dd.png)

**Comment by karl-ourmachinery** [comment]
Hi. Thanks for the bug report. I though I addressed this issue in the 2020.7 -> 2020.8 migration. Would it be possible for you to send me the data for a project where this happens? You can email it to karl@ourmachinery.com

**Comment by khskarl** [comment]
I've sent the files(2020.7) to your address.

Let me know if something doesn't work or seems wonky.

**Comment by karl-ourmachinery** [comment]
Thank you! I have found and fixed the issue. We will put out a new version later this week.
