### ISSUE TITLE
No clear indication for the location of the loaded project

### ISSUE THREAD

**Issue by dominikdalek** [OurMachinery/themachinery-public#288]
I can't find any place in the UI that would tell me which copy of the `pong.the_machinery` file I'm currently editing. Is it `D:\machinery\projects-2020.6\pong.the_machinery` or `D:\machinery\projects-2020.7\pong.the_machinery` or `D:\machinery\projects-2020.8\pong.the_machinery` - there's no way for me to find out.

The `File -> Save Project As...` can't be used to determine that because it point to the last folder in which something was saved, not the one current project is opened in.

Ideally I'd be able to click "open project location" somewhere. For folder projects this would simply open explorer with its location. For single file ones it'd open containing folder with correct file selected (`explorer.exe /select,"d:\Machinery\projects-2020.8\pong.the_machinery"`)

**Comment by niklas-ourmachinery** [comment]
That seems reasonable.

Maybe it should also show a popup with the full path to the project when you hover over the name in the title bar.

**Comment by dominikdalek** [comment]
That would work. It would also be nice to have tooltip with path for entries in the recent list as well.

**Comment by simon-ourmachinery** [comment]
The issue will be solved with the next update. You will have access to the path and you can open the folder/file in the file explorer.
