### ISSUE TITLE
Pan in a newly created graphs makes the camera jump.

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#292]
Repro steps:

1. Create a new graph
2. Spawn a node
3. Press middle mouse button (or ALT+left mouse button)
4. Notice how the focus point / camera suddenly jumps approximately the size of the graph window and you have to pan back to find your newly spawned node.

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/bec5ed56a11d16d7eaf4694707c2ab387308daa7
