### ISSUE TITLE
Arrow keys can't be used to navigate main menu

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#296]
After opening the file menu with ALT + F, the menu seems to loose focus immediately, so I can't navigate it with the arrows.

**Comment by niklas-ourmachinery** [comment]
This seems to apply to all menus, not just the File menu, investigating further.

**Comment by niklas-ourmachinery** [comment]
Investigating this, keyboard navigation of the main menu has never worked (there is no keyboard processing in the menu code except for Alt+Letter combinations), so I'm changing this to an enhancement instead of a bug.

**Comment by karl-ourmachinery** [comment]
I have started work on this here: https://github.com/OurMachinery/themachinery/compare/main-menu-keyboard-navigation?expand=1

I'll finish it up on Monday.

**Comment by karl-ourmachinery** [comment]
Keyboard navigation has been added to all menus. It should closely match how Windows does it.
