### ISSUE TITLE
Crash when deleting Scene Tree component that was automatically created by Entity Rigger Component.

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#299]
[beta-2020.09]

repro step:
-import simple 3d model. (dcc asset created)
-create new child entity of the world entity
-add Entity Rigger component to the new entity
-"Rig" using the dcc asset you just imported and dcc-mesh as creation graph.
-Delete Entity Rigger component.
-Delete Scene Tree component.

[the_machinery_exe 2020-10-04 23.02.51.zip](https://github.com/OurMachinery/themachinery-public/files/5324410/the_machinery_exe.2020-10-04.23.02.51.zip)

**Comment by niklas-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/eb6b1676087ed4477b1a397dffceb1e45d2f6dbf
