### ISSUE TITLE
"Add Subgraph" option inside graph editor

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#302]
In the graph editor It should be possible to "add subgraph" (that have already been defined elsewhere) as well as adding simple nodes, just so it's easier to reuse previously defined functionalities (Like for example WASD movement).

**Comment by karl-ourmachinery** [comment]
You can already do this, but maybe the discoverability is b ad. Add a subgraph node and set the prototype to a graph asset. Should probably add drag n drop of graph assets into the graph view. Leaving this open.

**Comment by karl-zylinski-ourmachinery** [comment]
Maybe I will take a look at this when I do https://github.com/OurMachinery/themachinery-public/issues/820

**Comment by karl-zylinski-ourmachinery** [comment]
There is a now an explicit Add Subgraph context menu item. It just adds a subgraph node.
