### ISSUE TITLE
Add default support for common rendering/physics objects like billboards and simple textured models.

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#304]
It should be easier to get stuff going on the screen, We definitively need to include the most common rendering objects by default for rendering simple objects.

**Comment by karl-zylinski-ourmachinery** [comment]
Do we have this yet @leonardo-ourmachinery ? We can drag out creation graphs to create billboards like so. And we have a couple of geometry entities in core. Is that what you meant?

**Comment by leonardo-ourmachinery** [comment]
Yes, let's close this.
