### ISSUE TITLE
Cut, etc shouldn't be available in the root folder context menu

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#305]
If you right-click on the root folder in the Asset Browser there are a number of options there that shouldn't be available:

![image](https://user-images.githubusercontent.com/26548514/95364107-41a5f580-0885-11eb-9d38-ef703ae565c0.png)

Cut, Copy, Duplicate & Rename should not be available.

Paste & New should be there (to create or paste assets in the root folder).

**Comment by niklas-ourmachinery** [comment]
Still some issues with this:

* Rename shouldn't be available on the root folder either. (Currently, if you select Rename, you will get a Truth error.)
* You can still use the keyboard commands for Cut/Copy/Paste/Delete. This will result in error messages, or, in the case of the Delete command, a crash.

**Comment by simon-ourmachinery** [comment]
> Paste
Should be possible. You should be capable of pasting to the root. Therefore I will only disable Cut/Copy/Delete and ofc Rename.

**Comment by niklas-ourmachinery** [comment]
Seems to work now.
