### ISSUE TITLE
DCC asset component doesn't respect updated output shaders

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#309]
Updating output shaders (`output_nodes/*.shader`) manually does not update DCC asset components.  Neither trying `Tools/Reload Shaders` in menu bar nor pushing `Refresh the cached result of this node` button for the output node in the `dcc-material` does not seem to work.

How to reproduce:

1. Open `output_nodes/lit_output.shader` in text editor, update something visible. For instance

```
line 417            //float4 base = float4(graph.base_color, 1);
line 418           float4 base = float4(1, 1, 1, 1);
```
2. Launch `the-machinery.exe`.
3. Import asset and put into the world. (Menu ->Import)
4. Imported asset still is rendered with original color.

Expected: It should only have white/black colors.

I noticed that extracting materials from dcc_asset respects the updated shader. Tested following:

1. Select your imported `dcc_asset` and extract materials by pushing `Import Assets` from Properties tab.
2. Select your extracted `entity` and you'll see that the extracted asset respects the updated shader (It is rendered with white/black colors)

**Comment by tobias-ourmachinery** [comment]
So this is not really a bug, it's just a bit confusing at first. 

So basically if you're dragging in a `dcc_asset` directly into the scene tab (or view it in the preview tab) it's falling back to use an hard-coded uber-shader called `mesh_uber_shader.shader` which can be found under `components/`. If you edit that file and reload things will refresh as expected.

Essentially when you import a `dcc_asset` it becomes a single monolithic object that you can be visualized using the `DCC Asset Component`, typically you want to extract materials, textures and meshes from the `dcc_asset` by selecting it and press `Import Assets` in the Properties Tab. If you have `Rig Entity` checked an entity representing the full `dcc_asset` will be created automatically for you. 

The meshes in this newly created entity will point to the extracted materials, which in turn are instanced Creation Graphs with a shader graph representation that reflects the features set found in the `mesh_uber_shader.shader`, these Creation Graphs uses the `lit_output` node, so if you view this entity and tweak the `lit_output.shader` file and hit reload, the change will get reflected.
