### ISSUE TITLE
Add ability to mix shader output

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#310]
This is feature request. 

Can the Machinery have ability to mix shader output? Currently only one output_node (like `lit_output.shader`) can be used in Creation Graphs (from my understanding) but DCC tools like Blender has ability to mix its results and reuse the result in the node graph.

For instance:

* [Diffuse BSDF](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/diffuse.html)
* [Mix Shaders](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/mix.html)

They are useful to customize output in node graph (such as toon shader) even by non-programmers without touching any shader code. See also: 

* [Blender Toon Shader Tutorial](https://www.youtube.com/watch?v=TpWI2rU8iF0&t=702s)
* [Screenshot of Blender's node graph](https://github.com/infosia/themachinery-issues/blob/master/0003/001.png)

**Comment by tobias-ourmachinery** [comment]
Yes, some kind of BSDF abstraction with mixing capabilities is planned. Right now it's not on our immediate roadmap but we'll get there eventually.

**Comment by tobias-ourmachinery** [comment]
Material property mixing can done using the `material_properties` nodes. Eventually we also would like to support layering of materials with different shading models but that's for the future. 

Closing this as I think I think it mostly referred to a nicer material abstraction then having to blend each individual property manually.
