### ISSUE TITLE
Projects opened from command line should be converted to absolute path

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#312]
If you open a project from The Machinery command-line with:

```
the-machinery.exe --load-project bla\myproject
```

Then the path stored for the project will be the local path "bla\myproject", not the absolute path. If you later run The Machinery from a different folder and try to open that project using **Open Recent**, it won't work, because it will no longer find a project at the local path "bla\myproject".

We should converts local paths passed to `--load-project` to absolute paths.

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery  is it intended that the recovery still works than? 

If I start a project via `--load-project` I say: I want this project. So I wonder if its necessary in that case that the recovery ask you if you want to recover the last project, if closed improperly?

**Comment by niklas-ourmachinery** [comment]
Yes, I think in this case it should still show the recovery window.

* If the user selects **Recover** -- we open the old project and recover it.
* If the user selects **Discard** -- we open the new project passed in `--load-project`.

Users should only encounter the "Recovery" dialog box if the application crashes without having saved their data. In this case, the most important thing is to get their data back.

(It is a bit different for us programmers because we tend to generate a lot of crash bugs as we're hacking as well as force quitting a lot in the debugger, and we don't really care about the projects we're working on -- they're just simple test projects. But for end users, crashes should be rare and if they do happen we absolutely want to retreive their data if possible.)
