### ISSUE TITLE
Crash when detaching default light entity from prototype and then undoing

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#313]
[beta 2020.09]

steps to reproduce:
-Detach light Entity from Prototype. (Make Unique)
-Undo

I Think we should support this, but either way we shouldn't crash.

[the_machinery_exe 2020-10-11 11.14.40.zip](https://github.com/OurMachinery/themachinery-public/files/5360827/the_machinery_exe.2020-10-11.11.14.40.zip)

**Comment by niklas-ourmachinery** [comment]
Crash is in the creation graph system.

**Comment by frank-ourmachinery** [comment]
tm_component_i->load_asset is not getting called after the undo call, but detaching from the prototype does call load_asset. Is this possibly the issue?

**Comment by frank-ourmachinery** [comment]
Fixed, creation graph was trying to update a newly created graph instance before it has a chance to be initialized.
