### ISSUE TITLE
Importing external assets with drag and drop should work when dropping in the Asset Browser view.

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#314]
At the moment it seems we actually import the asset only when it's dropped into the Scene view.
I think we absolutely want to support importing assets when dropping them into the Asset Browser view... My gut feeling is that we should either:
A) drag and drop of external files should import the asset when dropping it in the **entire** The Machinery view.
B) drag and drop of external asset files should work only on the Asset Browser.

**Comment by leonardo-ourmachinery** [comment]
It seems like it is related to multi-monitor/resolution stuff, as on my desktop it's working as expected. (Only import the asset when dropped into the Asset Browser).

Will investigate further.

**Comment by karl-ourmachinery** [comment]
Should be fixed now. It was due to the mouse position reported by the Windows drag and drop interface not being scaled by DPI scaling properly. It thought it dropped stuff onto the asset browser when you put them into the scene tab.
