### ISSUE TITLE
Importing an asset into The Machinery trough drag and drop isn't registered into the undo/redo stack

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#315]
[2020.09]

steps:
-import simple model as a dcc_asset
-try ctrl + z to undo (it won't undo the import)

**Comment by niklas-ourmachinery** [comment]
Agreed -- this should be available as an undo step when the Asset Browser tab has focus.

**Comment by karl-ourmachinery** [comment]
Fixed.
