### ISSUE TITLE
Propagating changes to prototype has undesired behavior

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#316]
[2020.09]

steps to repro:
1) import simple model as a dcc asset
2) drag dcc_asset just imported and drop it in the Entity Tree view as a child of the default light entity
3) propagate changes of the light entity instance to prototype

After step 3, the light Link component is reset, but I wouldn't have expected that. (Even if I had modified the link component position/rotation, I wouldn't have expected to see the light change position at all after propagating changes to prototype)

**Comment by niklas-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/4dd3cf5e068a75ffc18819ace6578132ebd02b70
