### ISSUE TITLE
Graph: When socket is "hot" (selected to be connected) it can't be unselected using escape

### ISSUE THREAD

**Issue by dominikdalek** [OurMachinery/themachinery-public#318]
To the left of the entity name there's an entity socket that can either take connector from another node, or indicates that there's a value typed in in the textbox next to it (i.e. socket is set through name).

When connecting nodes it's not uncommon to select node and change one's mind or select node by accident. I'd expect escape button to cancel this action but it doesn't. RMB has to be clicked to open the popup menu and only then two escapes can be used to abandon the action (first escape closes the popup search menu, second abandons the action).

Repro video: https://imgur.com/2cAtE20

I've consistently encountered this with scene entity input socket but haven't verified if this happens for other types of sockets as well.

**Comment by karl-ourmachinery** [comment]
Thanks for the bug report. This will be fixed in the next release. Esc will work then, also you'll be able to 'click again' on the source connector to abort the connection.
