### ISSUE TITLE
Support not having an audio card

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#321]
Currently, we run into an assert when setting up the windows audio backend when there is no audio card. This happens during our GItHub CI, where it  fails during the unit tests.

This should probably be fixed by adding a function such as `check_available()`  on the waveout backend that we call before creating it. If it returns false, then we create the "nil" audio backend instead, which is an audio backend that is mostly empty and does nothing.

**Comment by niklas-ourmachinery** [comment]
Fixed.
