### ISSUE TITLE
Crash: Delete of core folder in default project and than ctrl +z

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#322]
*Version:* beta-2020.9, beta-2020.9a, internal

**Problem**
When opening the engine and deleting the `core` folder of the default project and than pressing `ctrl + z` the engine will crash in `tm_creation_graph_clear_output`.

**Comment by frank-ourmachinery** [comment]
Fixed, was the same issue as #313
