### ISSUE TITLE
some fbx asset renders incorrectly when it is extracted from dcc_asset

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#324]
Extracted asset that is from `dcc_asset` renders incorrectly (not for every assets, but for some assets). I can see that drag-droppping `dcc_asset` directly into scene renders fine, but when you drop `.entity` which is extracted from `dcc_asset` using "Import Assets", it  renders incorrectly.

![See screenshot](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0004/0001.png)

How to reproduce:
1. Download [this fbx model](https://github.com/infosia/themachinery-issues/blob/master/0004/Sendagaya_Shibu-uniform.fbx)
2. Check if downloaded models is fine (Open it with Windows 3D Viewer)
2. Launch the Machinery and then `File -> Import` the model.
3.  Drag and drop imported `dcc_asset` into the scene and check if it renders fine (See screenshot above)
4. Select `dcc_asset` and click `Import Assets`, then select extracted `.entity` and drag-and-drop into the scene.
5. The imported entity renders incorrectly. ([See screenshot](https://github.com/infosia/themachinery-issues/blob/master/0004/0001.png))

I found that similar issue is happening on [this model](https://sketchfab.com/3d-models/cartoon-person-2-for-game-41450e11afa54d34b718f08cb7e01a1b) too.

**Comment by frank-ourmachinery** [comment]
I've been able to find multiple issues, the FBX model seems to get more corrupted then the automatically generated GLTF model (images show the GLTF from Sketchfab).
![image](https://user-images.githubusercontent.com/70658773/96836553-6da8a580-1445-11eb-8237-0b33042d8490.png)
The roughness on the model is also different after importing (DCC asset on the left, Entity on the right).
![image](https://user-images.githubusercontent.com/70658773/96836647-916beb80-1445-11eb-8ab6-9183fea46bf9.png)

**Comment by frank-ourmachinery** [comment]
Seems to be a skinning issue, If I disable the skinning in the lit shader then the model renders just fine. Investigating further...

**Comment by tobias-ourmachinery** [comment]
Verified that these files imports and skins correctly in 2020.11. Also roughness values are correct between rigged entity and dcc_asset. 
Closing this.
