### ISSUE TITLE
`default_render_pipe` sample fails to lookup the fullscreen pass

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#326]
### What's happening
After succesfully compiling the default render pipeline, console prints out `✖ C:\work\themachinery\plugins\render_graph_toolbox\toolbox_common.c(185): error: Failed looking up shader (691942ed0fe7a55f) for fullscreen pass. Pass deactivated (3584)`. 
This doesn't happen with the render pipelines `DLLs` that come with the _2019.9.a_ files.

Everything else seems to work normally. Couldn't find anything visibly broken, just an endless spam in the console log.

![image](https://user-images.githubusercontent.com/13659144/97002920-09ebae80-1511-11eb-8fb6-41740960f98c.png)

### How to reproduce:
1. Compile the sample `default_render_pipe`, located in `The Machinery/samples/plugins/default_render_pipe`
2. Open _The Machinery_ with an empty project (any project, doesn't matter) 
3. Check the console log

---

### Environment
Version: 2020.9.a

**Comment by frank-ourmachinery** [comment]
Interesting, I can't find the hash you specified in The Machinery or in the sample plugin. I'm fairly certain that it's some outdated code trying to load a shader that no longer exists. Sadly I don't have a handy way to decrypt the hash so I'm not entirely sure which shader it's looking for either. 

Maybe try a clean build, it might be some lingering code from an older version.
