### ISSUE TITLE
DBL hover help for Entity Tree shows "Focus", should be "Open"

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#328]
If you hover over a node in the Entity Tree, the `DBL` hover help text in the status bar shows "Open", it should be "Focus".

"Open" is hard-coded in `ui_tree.c`, so it must be refactored to support different values, because some trees may still want to use "Open".

**Comment by leonardo-ourmachinery** [comment]
Fixed.
