### ISSUE TITLE
navigating with up,down through entity tree does not behave as expected. Lots of entities, general

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#331]
**Prerequisite**
Lots and lots of entities

**Where**
All Entity Trees

**Problems**
When using the arrow keys (up,down) to navigate through the entity tree one would expect that the scrollbar moves with them when reaching the end of the visible content area. This does not happen when the end of the visible content area is reached the selections jumps back up. 

Besides keep pressing the arrow keys does not result in keep scrolling. Moreover when navigating with arrow keys (up&down) the moment you hit a disabled entity you lose the selection. Expected: you would move further either with gray or just to the next selectable entity.

**Image**
![entity_tree](https://user-images.githubusercontent.com/70658708/97278252-d58e3000-1839-11eb-9eec-694e993505e9.gif)

**Comment by leonardo-ourmachinery** [comment]
Fixed.
