### ISSUE TITLE
Custom UI themes don't support color alpha

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#332]
The built-in themes use color alpha in some places, but the custom themes don't support this, so when a custom theme is created that is based on one of the built-in themes, the alpha is lost.

Probably needs to migrate the UI themes to use RGBA type instead of RGB, which in turn requires us to enable migrations for the Settings The Truth object so we can migrate any old themes.

**Comment by karl-zylinski** [comment]
Reading this again -- I'm not sure that we need to enable migration on the settings object. We should first look at if it's possible to just switch the type of the color from RGB to RGBA. The issue might be that we get errors or alpha 0 -- which might force us to add a migration. If we do introduce the migration, then it should just set any preexisting RGB values to have alpha 255 in their new RGBA form.

**Comment by karl-ourmachinery** [comment]
Fixed in 2021.4
