### ISSUE TITLE
Cannot build beta package without `clean` step

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#333]
The first step of the `beta-package.json` build is a "clean" step that deletes all previous binaries and build files.

I sometimes want to skip this step, because making a complete rebuild of everything can take several minutes. However, if you remove the clean step and try to build the package more than once, you get an error:

```
LINK : fatal error LNK1104: cannot open file 'tm_https_static.lib' [C:\work\themachinery\utils\build\tmbuild\tmbuild.vcxproj]
```

It should be possible to run the beta package build without requiring the clean step.

**Comment by simon-ourmachinery** [comment]
on it has shown some more issues in our premake file and the packageing. Working on a solution.
