### ISSUE TITLE
Entity tree will not be updated during simulation

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#336]
**Problem**
When running in the simulation the entity tree will not update. The expected behaviour would be that the tress updates and one can inspect the current changes of the scene.

**Tested**
Tried to add a cube to the scene via the graph, it did not show up in the entity tree.

**Comment by niklas-ourmachinery** [comment]
Not a bug.

The Entity Tree in The Machinery represents the serialized/saved state of the entity, not the runtime state. Thus, it doesn't show any changes made to the scene during the simulation (entities added, removed, etc). These changes will also not be saved when the project is saved.

There are no plans to make the Entity Tree reflect the runtime state.

It could perhaps be useful to have a separate view that would let you inspect the runtime state of a scene (for debugging purposes), but to avoid confusion I think it should be kept separate from the Entity Tree.

(Note that this behavior is different from Unity, where the tree view will reflect runtime changes.)
