### ISSUE TITLE
Provide more error messags for the graph

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#338]
**Problem**
The graph has no error messages in case something goes wrong. This makes debugging the graph without having access to the source code very difficult.

**Possible problems**

- entity does not have component which is needed
- the required pin has not been added.
- the entity could not be found

**Comment by simonrenger** [comment]
This could be fixed than when nodes get generated and pins are required that there will be an auto log to the user saying hey pin X has not been connected.
A log could look like this:

> Error: Node name_of_node requires pin x to be connected

Besides I think we need to display via e.g. hover over a pin if this pin is required or optional. This would solve issue  #339 from being actually bothering.

**Comment by simon-ourmachinery** [comment]
Next to the console output an indication in the graph itself would be good. E.g. a warning symbol or a colouring (orange/red) to indicate *Oppsy there is something wrong*.

**Comment by niklas-ourmachinery** [comment]
We have a coloring in the graph already (a red bar when the pins are not set), but it should perhaps be more visible.

Just like in a programming language I also think we want both "compile time" and "runtime" errors. The runtime erros are just dumped in the log right now, but it would be useful if that information could also be visualized in the graph.

**Comment by simon-ourmachinery** [comment]
@karl-zylinski-ourmachinery I think this has been addressed by your late change.
