### ISSUE TITLE
Crash when overriding entity deeply

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#345]
This crash is only in HEAD, not in the 2020.10 release.

Repro case:

* Open the Modular Dungeon Kit sample project.
* Create a New Entity in the Asset Browser and double-click to open it.
* Drag the room entity into the new entity to instantiate it.
* Expand room > props > prop_floor_barrel in the tree.
* Right-click on the Link component in prop_floor_barrel and choose Override.

Crashes in entity_tree_tab_internal.inl:906:

~~~c
tm_the_truth_object_o *parent_w = tm_the_truth_api->write(tt, parent->id);
~~~

`parent->id` is not a valid ID.

**Comment by leonardo-ourmachinery** [comment]
Fixed.
