### ISSUE TITLE
Editor "Not Responding" (GeForce GTX 1080 457.09, Vulkan 1.2.141)

### ISSUE THREAD

**Issue by pbrooks** [OurMachinery/themachinery-public#347]
On attempting to run **the-machinery**, **simple-3d** or **simple-draw** the windows remain black and quickly become unresponsive.

[2020-11-06 21.56.24.log](https://github.com/OurMachinery/themachinery-public/files/5503717/2020-11-06.21.56.24.log)
[VulkanInfo.txt](https://github.com/OurMachinery/themachinery-public/files/5503721/VulkanInfo.txt)

In terms of spec:
- Intel Xeon E3-1245 v5, 32GB ECC DDR4 Ram
- Windows 10 Pro 19041

No dumps are generated, because the app never actually crashes.

Let me know anything else to help diagnose.

**Comment by frank-ourmachinery** [comment]
I'm running the exact same GPU so I don't think it's a driver issue and it's at least creating the Vulkan instance. My guess is that it's either a device layer blocking device creation or something non graphics related that's blocking. I'll try matching the device layers to see if those will also block on my machine.

**Comment by frank-ourmachinery** [comment]
Found it, it seems that the XSplit broadcaster layer is blocking something.

**Comment by frank-ourmachinery** [comment]
There seems to be a bug in the XSplit broadcaster device layer that blocks the presenting command buffer from executing. I've added a timeout to this so we can force a crash if this takes too long. That should give us more information in the future. 

Sadly this seems to be a bug in with XSplit, currently the only solution I have is disabling the XSplit layer all together. This can be done by adding an environment variable called DISABLE_VK_LAYER_XSPLIT and setting its value to 1. Make sure to restart your PC afterwards as (at least on Windows) it doesn't update automatically.

**Comment by pbrooks** [comment]
Excellent, that makes complete sense.
I'll probably just remove it, thanks for investigating.
