### ISSUE TITLE
Attempting to drag window while maximized doesn't work.

### ISSUE THREAD

**Issue by cairnc** [OurMachinery/themachinery-public#348]
I'm not sure how to view the version but here is the issue:
1. Launch the-machinery.exe (It should launch fullscreen)
2. Attempt to drag the window from the top bar.

It seems like the visible window becomes out of sync with the actual window, I have no idea how this could happen. Clicking on any portion of the window then seems to maximize the window again.

not sure how much of this is relevant:

         Operating System: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
         DirectX Version: DirectX 12
         User DPI Setting: 96 DPI (100 percent)
         System DPI Setting: 120 DPI (125 percent)
         Card name: NVIDIA GeForce GTX 1660 Ti
         Current Mode: 1920 x 1080 (32 bit) (60Hz)
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll
         Driver File Version: 26.21.0014.4223 (English)
         Driver Version: 26.21.14.4223
         DDI Version: 12
         Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
         Driver Model: WDDM 2.6

**Comment by leonardo-ourmachinery** [comment]
I'm not seeing the issue, I think it has been fixed a while ago when the resize window stuff was rewrote.
Closing it.
