### ISSUE TITLE
New Plugin / Entity Component - Boilerplate is out of date

### ISSUE THREAD

**Issue by pbrooks** [OurMachinery/themachinery-public#350]
For the generated boilerplate, the following two lines need to be modified:

Location has been changed to within plugins:
`#include <the_machinery/component_interfaces/editor_ui_interface.h>`
`#include <plugins/the_machinery_shared/component_interfaces/editor_ui_interface.h>`

function definition changes **uint64_t -> tm_tt_id_t**
`static void component__load_asset(tm_component_manager_o* man, tm_entity_t e, void* c_vp, const tm_the_truth_o* tt, uint64_t asset)`
`static void component__load_asset(tm_component_manager_o* man, tm_entity_t e, void* c_vp, const tm_the_truth_o* tt, tm_tt_id_t asset`

**Comment by leonardo-ourmachinery** [comment]
Thank you for reporting this. 
The fix has been implemented and it will be available in the next official release.
