### ISSUE TITLE
Preview and Properties freeze with wav

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#351]
**Problem**
Moving through the asset browser with keyboard and having open: preview & properties will cause the engine to freeze:

**No Property & No Preview**
![move_ab_up_dowm_no_pp](https://user-images.githubusercontent.com/70658708/98653672-97b30080-233d-11eb-862b-328c04acd047.gif)

**Preview**
![move_ab_up_dowm_w_p](https://user-images.githubusercontent.com/70658708/98653836-d21c9d80-233d-11eb-9423-94fc8909f17d.gif)

**Properties**
![move_ab_up_dowm_w_pp](https://user-images.githubusercontent.com/70658708/98655759-20cb3700-2340-11eb-860d-2118d36ee034.gif)

**Comment by niklas-ourmachinery** [comment]
The freeze comes from generating the waveform picture for the WAV which is slow for big WAV files. I'll move it to a background thread.
