### ISSUE TITLE
Crash when clearing console

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#352]
- Let the engine run for a while
- Make sure the console is filled with a bunch of different messages
- Clear it by clicking in it and then pressing delete
- Usually crashes (not always)

**Comment by simon-ourmachinery** [comment]
Cannot reproduce ....

**Comment by frank-ourmachinery** [comment]
Cannot reproduce either

**Comment by karl-ourmachinery** [comment]
I'll try to catch it next time. It often happens after I've been running for a long while and the console is spammed with a lot of things.

**Comment by karl-ourmachinery** [comment]
Haven't seen in a while. Closing.
