### ISSUE TITLE
Makefile dependencies are not generated correctly for Linux and OS X builds

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#353]
Seems something has recently broken in the build generation for Linux and OS X. 

The generated dependency files only show local dependencies and not any dependencies on other projects, such as `foundation`. For example, `asset_browser.d` is:

~~~
obj/Linux/Debug/asset_browser.o: \
  ../../../plugins/editor_views/asset_browser.c \
  ../../../plugins/editor_views/asset_browser.h \
  ../../../plugins/editor_views/editor_views_loader.h

../../../plugins/editor_views/asset_browser.h:

../../../plugins/editor_views/editor_views_loader.h:
~~~

Even though `asset_browser.c` depends on a lot of `foundation` files and `ui` files. This forces us to do clean rebuilds whenever we change a `foundation` header.

I have noticed this behavior for a while, but it definitely used to work before. Unsure when the regression happened.

**Comment by simonrenger** [comment]
I am fixing the other tmbuild related issue I will check this one as well
as soon as the other one is fixed.

**Comment by niklas-ourmachinery** [comment]
I reverted the repository back to March 2020 and this still wasn't working in that version (I rebuilt tmbuild using that version to make sure it wasn't caused by the new tmbuild version) so now I'm not sure if this ever worked. I have a memory of it working, but I might be wrong.

**Comment by niklas-ourmachinery** [comment]
Yes, @simon-ourmachinery, if you can take a look at it, that would be great.

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery found a solution/issue. Will discuss this with you in person.

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery is this still a problem? I cannot remember how we ended on this... because on linux we are override the premake build-in preprocessor flags from -MMD to -MD

**Comment by niklas-ourmachinery** [comment]
Not sure... let me investigate.

**Comment by simon-ourmachinery** [comment]
@raphael-ourmachinery  can you check this and comment if it is fixed?

**Comment by raphael-ourmachinery** [comment]
@simon-ourmachinery  changes dependencies generation flags from `-MMD to -MD`, which causes system headers to be considered too. The difference is when using `#include <file>`, the headers are considered a system header, and `#include "file"` a user header (https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html). Did some tests and everything is working fine now.
