### ISSUE TITLE
Pong sample crashes in beta build

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#355]
In any beta build (released or from GitHub master), the pong sample crashes the engine when you start simulating. Does not happen in a debug build from GitHub master.

**Comment by karl-ourmachinery** [comment]
The Stack scene in the Physics sample also crashes. Might have something to have something to do with UI rendering.

**Comment by niklas-ourmachinery** [comment]
The simulate UI setup set blackboard pointers pointing to local variables. Fixing...
