### ISSUE TITLE
Crash on startup if the project has recursive entity spawning

### ISSUE THREAD

**Issue by JoNil** [OurMachinery/themachinery-public#361]
Steps to reproduce:

1: Add a graph to the root entity of your main scene
2: Add an Init Event and connect it to a Spawn Entity
3: Select the root of scene as the entity to spawn
4: Save
5: Go to a simulation tab

Now the-machinery will immediately crash with this dump: https://drive.google.com/file/d/1pzSlec5dhug4CD7tMVj1B8qBl8aBXpDO/view?usp=sharing

Today when i wrote these repro steps i can recover by clicking discard changes on startup. Yesterday when i had it in my real project that didn't work. The only way i found to recover my project (it was not in git yet) was to manually edit the entity with the graph and remove the recursion.

**Comment by niklas-ourmachinery** [comment]
Fixed for next release (2020.11.a). This will now give an error message `Graph Interpreter max recursion depth exceeded -- check graph for loops`.

**Comment by niklas-ourmachinery** [comment]
In addition, I also added so that if you start The Machinery with `--safe-mode` or hold down `F8` during the boot sequence, we won't try to restore the last used project or the Windows settings. You can use this to recover when The Machinery crashes at startup because of a bad project state.
