### ISSUE TITLE
Crash on override component

### ISSUE THREAD

**Issue by JoNil** [OurMachinery/themachinery-public#362]
In this project: https://github.com/JoNil/machinery_test

When i click here:

![repro](https://user-images.githubusercontent.com/840235/99907154-76f28f80-2cdb-11eb-8d77-3e2d0ef8258e.png)

the-machinery crashes with this dump: https://drive.google.com/file/d/1b-tSfeko4dYG9KOYQ_cqjeewnBYm_fh7/view?usp=sharing

**Comment by leonardo-ourmachinery** [comment]
Thank you for reporting this.

You will find the fix to the crash in the next release.
