### ISSUE TITLE
Extracted asset disappears from scene at re-launch

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#363]
1. Download [CesiumMan.glb](https://github.com/infosia/themachinery-issues/blob/master/0006/CesiumMan.glb)
2. Launch `the-machinery.exe`, then import CesiumMan.glb.
3. Drag&Drop `CesiumMan.dcc_asset` on the scene
4. Select `CesiumMan.dcc_asset` from Assert Browser and push `Import Assets` from Properties Tab.
5. Drag&Drop `CesiumMan.entity` on the scene
6. Save the project and exit `the-machinery.exe`.
7. Launch `the-machinery.exe` again, and then one of CesiumMan is gone (the extracted one)

![scene](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0006/tm-scene.png)

Following error message is shown on the console 
![error](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0006/tm-error.png)

It seems this is not 100% reproducible but happens with high frequency for me.

**Comment by niklas-ourmachinery** [comment]
Reproduced it... investigating...

**Comment by niklas-ourmachinery** [comment]
Fixed.

Will push out a 2020.11.a hotfix with this fix shortly.
