### ISSUE TITLE
Use of strcpy without checking valid range

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#364]
I found use of `strcpy` in `tm_assimp` which causes overflow when `file` is longer than 8 character. 
Is there any reason not to use `strcpy_s`? 

In `assimp.c`
```
static uint64_t import(const char *file, const struct tm_asset_io_import *args)
{
...
    strcpy(task->file, file);
...
}
```

`import_assimp_task_t`

```c
typedef struct import_assimp_task_t
{
    uint64_t bytes;
    struct tm_asset_io_import args;
    char file[8];
} import_assimp_task_t;
```

**Comment by niklas-ourmachinery** [comment]
This is not actually an error. When we allocate the struct, we will allocate extra memory for the actual size of the string.

**Comment by infosia** [comment]
aha! Interesting but it sounds like it confuse the maintainer and easily shoot yourself in the foot (no offence). Is there any reason just to use `char*` in the struct?

**Comment by niklas-ourmachinery** [comment]
Yes, that would require us to use a separate allocation to hold the string data... this way, the string data can be allocated together with the rest of the struct.

I think a clearer way to indicate this would be `char file[0]`... unfortunately, not all compilers support "zero-sized" arrays.

**Comment by infosia** [comment]
I see why. Thanks for the information! 👍
