### ISSUE TITLE
apidoc.md.html load time - up to 16 seconds.

### ISSUE THREAD

**Issue by cmartin99** [OurMachinery/themachinery-public#365]
It takes 15-16 seconds to load apidoc.md.html on my system.
OS=Win10
Browser=Brave
I also tested it on Firefox, Chrome, and MSEdge and they're also about the same load time as Brave.

**Comment by niklas-ourmachinery** [comment]
Yes, the file is getting too big. We will split it up into individual files for the next release.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.12, the `apidoc.md.html` file has been split up into individual, smaller files.
