### ISSUE TITLE
Large font sizes are blurry

### ISSUE THREAD

**Issue by d44m1n** [OurMachinery/themachinery-public#37]
For example, if you zoom in on a node in the graph, the text will be blurry.

**Comment by niklas-ourmachinery** [comment]
Yes, the reason for this is that we generate font bitmaps at a particular size, and when we zoom in, these bitmaps are just rendered bigger. But we should fix this by supporting multiple sizes for the bitmaps.

**Comment by niklas-ourmachinery** [comment]
Fixed in 2020.5.
