### ISSUE TITLE
Very long waiting time to preview default geometry mesh asset.

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#370]
The first time an asset under the default "geometry" folder (box/sphere/plane) is clicked in the asset browser, it takes around a second before it is correctly rendered in the preview tab.

**Comment by tobias-ourmachinery** [comment]
Core needs to get its shaders cache flushed.  This is not a bug, it’s just you waiting for the shader compiler to finish. Sigh.
