### ISSUE TITLE
Failed to import files from directory that has fullwidth digit

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#372]
I came across import failure when directory has full width character (for instance `素体２`) and ends up finding it is not failing when directory  name is `素体` but fails when it is  `２`.

- Create directory  that has fullwidth digit for instance `C:\２`
 (If you don't have IME just copy this -> `２` should work with clipboard I think)
- Put model file to import (I used [CesiumMan.glb](https://github.com/infosia/themachinery-issues/blob/master/0006/CesiumMan.glb))
- Launch the Machinery and import the glb (from `File...Import File` menu)
- It fails to import with following errors

![message](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0007/error.png)

**Comment by niklas-ourmachinery** [comment]
Fixed for next release (2020.12).

Was an error in our UTF-16 surrogate pair handling, thanks for finding it!
