### ISSUE TITLE
Crash when closing import project tab

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#373]
- Start The Machinery (empty project)
- Import the first person sample project
- Pull in the player.entity from the first person sample to the empty project
- Close the import project tab
- The Machinery crashes

**Comment by niklas-ourmachinery** [comment]
Could not reproduce using these steps.

**Comment by karl-ourmachinery** [comment]
Okay. It doesn't happen for me either if I launch in Safe Mode. Must be something local on my machine that messes with the tabs, maybe some setting that triggers a bug. I'll look into it later.

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/2adc0b463304c19bbbe9c1596d92afd9b3f0843f

@niklas-ourmachinery It was due to us initing tab->file with "" instead of zero, so when it tried to do

```
