### ISSUE TITLE
Recomputing inertia tensor uses world position for center of mass

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#375]
- Add a box (instance of box in core) with a physics shape and stretch it so it becomes a floor
- Add another box (instance of box in core), add a physics shape and body
![image](https://user-images.githubusercontent.com/57644882/101053414-0d4e6d00-3588-11eb-9d72-06f7b0e01502.png)
- Offset box with body it so it sits above the "floor"
- Recompute inertia tensor of box with body
- Note that it gets a center of mass based on its world position
- Press play button
- It won't sit still on the floor because it falls over on its weird center of mass

I think we would like it compute the center of mass based on the relative position between the entity and the geometry rather than the world position.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.12
