### ISSUE TITLE
Viewing simple-sky creation graph scene while dragging color slider makes graph unusable

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#388]
- Open Creation Graphs sample
- Go to simple/simple-sky.entity
- Open the creation graph of the sky and the scene of the sky side by side: 
![image](https://user-images.githubusercontent.com/57644882/101087089-0ccacc00-35b2-11eb-8465-fdc29522b732.png)
- Try dragging any slider in the color picker of one of the colors fed into the Lerp node.
- The graph view becomes unresponsive. Don't happen if the scene view isn't viewed next to the graph like this.

**Comment by karl-ourmachinery** [comment]
Having the simple-sky entity visible in the preview tab while dragging the slider also makes this happen.

**Comment by karl-ourmachinery** [comment]
Seeing this in more places. Having the simple-particles entity simulating next to the graph view makes it hard to edit the properties in the graph nodes.

**Comment by karl-ourmachinery** [comment]
Disabling Multithreaded UI fixes most of it (the slider still has some issues, it looses focus when you drag it)

**Comment by tobias-ourmachinery** [comment]
I think we are seeing two things here,

1) The shaders weren't really design for doing what you are doing. You're dragging a slider inside a _Constant_ node and not a slider attached to a _Variable_ node, essentially every single value change will initiate a shader compile. Previously though that has still worked decently well and it has been kind of a nice stress test of the shader system.

2) I suspect the new stalls are coming from the new jobs created from the multi-threaded UI are competing with the shader compile tasks. We're clamping the thread pool size for the task systems to be `num_logical_cores() / 2` in an attempt to prevent starvation of regular jobs but there are still no guarantees it will be well-behaving. 

(There might also be a third factor in play here which is my somewhat sloppy fix to make sure DXC is thread-safe by always creating an instance of `IDxcUtils` and an instance of `IDxcCompiler3` for every compile and then destroy them when done. I have no idea what DXC is doing on the inside but chances are creating / destroying these instances aren't cheap so we should probably pool them on our side. )

**Comment by karl-ourmachinery** [comment]
Fixed.
