### ISSUE TITLE
Grid settings only apply for a single frame

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#392]
If you go into settings and change the grid color or alpha, the setting only lasts for a single frame before the default grid comes back.

**Comment by frank-ourmachinery** [comment]
Is this related to the graph grid colors or the grid in the scene view?
The graph color works fine for me and I cannot actually find a way to change the grid color as they are inherited.
![image](https://user-images.githubusercontent.com/70658773/101331056-b7254680-3873-11eb-8a6d-ca4eb0816443.png)

**Comment by frank-ourmachinery** [comment]
I found out that it's in the application settings. Not sure why we have this `Grid Settings` option in the Scene menu if it doesn't allow you to actually edit all the settings. Seems like a bad idea to scatter global preferences like this, should this be part of a theme instead?

**Comment by frank-ourmachinery** [comment]
This bug is caused by the grid color being defined in two places. First there is the truth representation which you're editing in the settings menu. But that gets overridden with the viewport grid color defined in the theme. I have removed the grid settings from the theme to fix this.
