### ISSUE TITLE
Renaming while having multiple assets selected doesn't rename all of them

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#393]
- Select multiple assets
- Press F2 to rename
- Only the most recently selected in the selection gets renamed

Expected:
- All files get renamed to the same thing, which is fine given that they have different type extensions. For assets of the same type the standard _NUMBER suffix is added.

**Comment by leonardo-ourmachinery** [comment]
I misread and thought it was related to renaming multiple entities in the entity tree at the same time... I will do it for the Entity Tree, but maybe @simon-ourmachinery can look at it in the assets browser.

**Comment by simon-ourmachinery** [comment]
on it.

**Comment by simon-ourmachinery** [comment]
The previous solution was not sufficient and was changed. Needs some more work.

**Comment by simon-ourmachinery** [comment]
next release should this work smoother
