### ISSUE TITLE
It should be possible to propagate added component or child entity to prototype

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#397]
I have this instance of an entity in my level. I added a component to it, but realized I want to have that component in the prototype as well. But I do not want to propagate the whole `lever_2` entity, since the other changes in it are not relevant to the prototype. I just want to propagate the component so that it is added to the prototype. Same should be possible for child entities.

![image](https://user-images.githubusercontent.com/57644882/101230863-55fd4780-36a8-11eb-9449-5d7b42d2f153.png)

In essence we need to check if the parent of a component or entity has ASSET or INSTANCED prototype relation and in that case make it possible for the ADDED component or child entity to be propagated into the prototype.

**Comment by leonardo-ourmachinery** [comment]
Implemented for the next release.
