### ISSUE TITLE
Add ability to query arbitrary node name string

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#399]
`tm_scene_tree_component_api` only has API to deal with node names by `uint64` hash. This is useful when you know "exact name" of the bone beforehand but this makes it impossible to search for arbitrary node name such as "_the bone name that ends with `Hips`_". 

This is useful when you want to search for specific bone that has similar pattern such as _"mixamorig:Hips", "Hips", "mixamorig1:Hips", "mixamorig6:Hips"_ and so on for instance. Maybe `tm_scene_tree_component_api` needs an API to return bone name as string from string hash or index something like

```
const char* (*node_name_from_index)(const tm_scene_tree_component_t *component, uint64_t index);
```

**Comment by frank-ourmachinery** [comment]
I added this function for the next release. Note that this cannot always get the string name of a node. Only when `debug_names` was used then `setup_nodes` was called. But this seems to always be the case currently.

```c
const char *(*node_debug_name_from_index)(const tm_scene_tree_component_t *component, uint32_t node_idx);
```
