### ISSUE TITLE
Add ability to query tags without tm_gameplay_entity_api

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#401]
Currently only `tm_gameplay_entity_api` only has API to deal with entity tags (such as `add_tag()` and ` find_entity_with_tag()`) but why tag needs to be tightly coupled with "gameplay system"? This makes it difficult to deal with tags within custom component without gameplay api. Maybe `tm_entity_api` fits more to take tagging role.

**Comment by karl-ourmachinery** [comment]
You can query and manage tags using `tm_tag_component_api`, see `tag_component.h`.

We are aware that the gameplay APIs add confusion by having semi-duplications of stuff found in other APIs. The gameplay APIs wrap some APIs that need an annoying amount of typing to "get things done". But I have realized that they are perhaps more confusing than helpful. I am currently revamping this, it should be done for the December release. It will probably lead to a deprecation of the gameplay APIs and addition of some new functions to APIs such as `tm_tag_component` and `tm_entity_api` as well as some helper functions. I'll let you know how it goes.

**Comment by infosia** [comment]
@karl-ourmachinery Thanks for quick reply! Yes makes sense. I see deprecating gameplay API would resolve some confusions but I also think that gameplay API is still very good example of how to get things done, so probably moving it to "examples" would be more helpful than disposing everything I guess? :)

I am aware of the `tm_tag_component_api` but I was not able to use it because creating newly `tag_component_manager_o` under entity context produces errors. I would guess that it needs to be only one tag_component_manager exists in the context?

```C++
static void component__register_engine(struct tm_entity_context_o *ctx)
{
...
    tag_component_manager_o = tm_tag_component_api->create(ctx);
...
}

TM_DLL_EXPORT void tm_load_plugin(struct tm_api_registry_api *reg, bool load)
{
...
    tm_add_or_remove_implementation(reg, load, TM_ENTITY_SIMULATION_INTERFACE_NAME, component__register_engine);
...
}
```

This produces following error 

![error](https://user-images.githubusercontent.com/1661068/101267629-1153d800-379e-11eb-84cf-af8c4329966e.png)

**Comment by karl-ourmachinery** [comment]
At the place in the code where you want to work with the tags, do this:

```
const uint32_t tag_component_idx = entity_api->lookup_component(entity_ctx, TM_TT_TYPE_HASH__TAG_COMPONENT);
tm_tag_component_manager_o *mgr = (tm_tag_component_manager_o *)entity_api->component_manager(entity_ctx, tag_component_idx);
// Use tag component API with mgr
```

See the comment in the top of `tag_component.h` for what the API expects from you.

I see that the `create` function is poorly named and confusing. It is for internal usage, it's what registers the component type in the entity system, it's not for creatuing or managing the actual tags. I'll make sure to clarify that by renaming or moving that function.

**Comment by infosia** [comment]
Awesome it's working now 👍 Thanks for helping.
