### ISSUE TITLE
The naming of lookup_component in tm_entity_api is misleading

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#402]
The naming of `lookup_component` in `tm_entity_api` is confusing. You're getting the index of a component _type_ in the ECS system, but it sounds like you're looking up a component on an entity. Essentially, if a user sees just the word 'component' they are likely to think it has something to do with the component instances on entities. I think we should:

- Change `lookup_component` to `lookup_component_type`
- Change any `uint32_t component` parameter (see `add_component` function etc) to `uint32_t component_type`
- Perhaps introduce a component type struct, i.e.: `struct tm_entity_component_type_t { uint32_t type };`

**Comment by simon-ourmachinery** [comment]
I am advocating for a type 
> Perhaps introduce a component type struct, i.e.: struct tm_entity_component_type_t { uint32_t type };

**Comment by frank-ourmachinery** [comment]
I think renaming the function to `lookup_component_type` and returning a `tm_component_handle_t` or something similar might be the most clear way to distinguish this function from the other entity component functions.

**Comment by frank-ourmachinery** [comment]
I renamed `lookup_component` to `lookup_component_type` and replaced all the uint32_t used throughout the codebase for this with a `tm_component_type_t`.
