### ISSUE TITLE
Proper application settings tab

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#405]
Currently, if you go to File -> Settings you get a properties tab with the application settings The Truth object focused in it. It shows the users lots of internal settings state and it is also very unfriendly to use.

The application settings dialog should be hand made, only showing things the user may actually be interested in, laid out in a nice manner. It could have a "All Settings" expandable thing at the bottom which shows the current stuff.

**Comment by leonardo-ourmachinery** [comment]
We now expose only what its relevant to the user. Closing this one.
