### ISSUE TITLE
IMGUI textfield doesn't accept input when IME is on

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#406]
IMGUI text field doesn't accept keyboard input when IME is on. Tested on Microsoft IME + Windows 10.

FYI How to Use Microsoft IME on Windows 10 to Type in Japanese
https://cotoacademy.com/type-japanese-windows-10/

**Comment by frank-ourmachinery** [comment]
Currently we're handling all text input through WM_CHAR. It seems like that Windows message doesn't get send if you have a IME keyboard on, doesn't matter on which mode. I'm looking into this.

**Comment by frank-ourmachinery** [comment]
Fixed for next release. Our current UI font doesn't support Japanese glyphs currently, but the Latin keyboard should now work.
