### ISSUE TITLE
Material alpha is ignored for dcc assets

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#407]
Material alpha is ignored when importing dcc assets.

Tested by [this model](https://github.com/infosia/themachinery-issues/blob/master/0008/Vita.fbx).

**Comment by infosia** [comment]
I was able to fix this partially by adding  alpha property in `assimp.c`;

```c++
struct aiString alpha_mode;
res = aiGetMaterialString(ai_material, AI_MATKEY_GLTF_ALPHAMODE, &alpha_mode);
if (res == aiReturn_SUCCESS) {
    if (tm_strcmp_ignore_case(alpha_mode.data, "opaque") == 0) {
        tm_the_truth_api->set_uint32_t(tt, tm_material, TM_TT_PROP__DCC_ASSET_MATERIAL__ALPHA_MODE, TM_TT_VALUE__DCC_ASSET_MATERIAL__ALPHA_MODE__OPAQUE);
    } else if (tm_strcmp_ignore_case(alpha_mode.data, "mask") == 0) {
        tm_the_truth_api->set_uint32_t(tt, tm_material, TM_TT_PROP__DCC_ASSET_MATERIAL__ALPHA_MODE, TM_TT_VALUE__DCC_ASSET_MATERIAL__ALPHA_MODE__MASK);
    } else if (tm_strcmp_ignore_case(alpha_mode.data, "blend") == 0) {
        tm_the_truth_api->set_uint32_t(tt, tm_material, TM_TT_PROP__DCC_ASSET_MATERIAL__ALPHA_MODE, TM_TT_VALUE__DCC_ASSET_MATERIAL__ALPHA_MODE__BLEND);
    }
}

float alpha_cutoff = 0;
res = aiGetMaterialFloatArray(ai_material, AI_MATKEY_GLTF_ALPHACUTOFF, &alpha_cutoff, 0);
if (res == aiReturn_SUCCESS) {
    tm_the_truth_api->set_float(tt, tm_material, TM_TT_PROP__DCC_ASSET_MATERIAL__ALPHA_CUTOFF, alpha_cutoff);
}
```

But when you extract asset from dcc_assets, extracted asset still ignores alpha.

**Comment by tobias-ourmachinery** [comment]
We will be working on streamlining the automatic creation graph material rigging from `tm_dcc_asset_material` that have alpha masking or opacity. 

Thanks for the GTLF additions to the assimp importer. We'll investigate if we can move our open sourced plugins to a public repository so that it becomes easier to contribute with fixes through PRs.

**Comment by tobias-ourmachinery** [comment]
@infosia I've added the suggested code changes from above and if `AI_MATKEY_GLTF_ALPHAMODE` isn't present I try looking at `AI_MATKEY_BLEND_FUNC`. Also made sure to automatically enable double sidedness if the alpha mode is masked or blended, as that appears to be what assimp recommends. 

However, as the provided sample file is an `.fbx` the `AI_MATKEY_GLTF_ALPHAMODE` won't get set, so not sure how this code did anything for you, but maybe you also tested with a `.gltf` file and attached the wrong sample file to this issue?

Also we are still lacking a good way to translate the imported material properties (such as blend mode / double sidedness etc) into settings on an output node.. will try to come up with something nice there.

**Comment by infosia** [comment]
> However, as the provided sample file is an .fbx the AI_MATKEY_GLTF_ALPHAMODE won't get set, so not sure how this code did anything for you, but maybe you also tested with a .gltf file and attached the wrong sample file to this issue?

Thanks for following up 👍 How about this one? https://github.com/infosia/themachinery-issues/blob/master/0008/Vita.glb

**Comment by infosia** [comment]
I don't see alpha issue in the latest release, I think this issue has been already addressed. Closing 👍
