### ISSUE TITLE
Physics settings

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#408]
Currently there is no way to alter the settings passed to PhysX such as the gravity acceleration vector etc. We need to make this configurable on a project basis somehow.

Either we need to add project settings and put them there, or make some kind of asset than contains these settings. The latter has sort-of become the way we did such things for Simulate Entry and Importer Settings. There are currently no project settings other that the per-application project settings. We can't save this in the per-application project settings since this is project data, not users settings.

**Comment by niklas-ourmachinery** [comment]
I agree. I think these settings belong in an asset.

**Comment by karl-ourmachinery** [comment]
@niklas-ourmachinery Perhaps we should set up guidelines that all settings that live in the project must live in some asset. Much like the unix philosophy of having everything as files, as opposed to a registry.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.1.

We might want to add more settings to this in the future, such as timestep settings. Currently, I've left them out, because I'm not sure if all the timestep settings we have right now makes sense.
