### ISSUE TITLE
Gizmo modes are taking up too much space

### ISSUE THREAD

**Issue by d44m1n** [OurMachinery/themachinery-public#41]
Gizmo modes are taking too much space imho. It would be much better to have something like UE4 have, small buttons on top of viewport.

**Comment by niklas-ourmachinery** [comment]
By gizmo modes do you mean the icons in the left part of the scene window (select, move, rotate, scale)?

**Comment by d44m1n** [comment]
Yup

**Comment by karl-ourmachinery** [comment]
Fixed since we introduced the new toolbars. The different tools now live in a much more compact toolbar. Which shares its space with other toolbars.
