### ISSUE TITLE
Entity picker: Add more context when there are items with identical names

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#414]
In this image I am trying to pick an entity using a local entity picker (i.e. picking anything within the scene)

![image](https://user-images.githubusercontent.com/57644882/101992903-bd258800-3cb6-11eb-8d21-3fcbd67fc988.png)

However, I want to set it to a thing called collider. Each of the buttons and levers in my game have such a sub-entity. It is impossible to distinguish them unless I go in and rename these sub-entities

When there are conflicts like this in the picker, it should probably give more context. For example it could put the parent name greyed out to the right (like we do with categories in some other pickers). Maybe it should be able to put in up to three parent names (like a path), in case the conflict persists.

**Comment by frank-ourmachinery** [comment]
The local picker will now show its owning entities (up to a depth of 3) if the name conflicts with another item in the list. This can still create some names that are equal. But I think it's reasonable to expect some name change with a depth of 3.
