### ISSUE TITLE
Hiding entities in editor doesn't work when entity with render component isn't overridden

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#415]
- Have an instance of some entity in your scene
- The prototype of the entity should contain a sub entity which has a render component
- Make sure the sub entity isn't overridden in the instance
- Click the instance in the entity tree and hit H
- The entity gets the hidden symbol, but nothing is hidden. It works if you override the sub entity on which the render component lives.

In images. This does not work (nothing is hidden):
![image](https://user-images.githubusercontent.com/57644882/102024283-6b9dfb80-3d91-11eb-84b8-ec20aceb9c79.png)

This works:
![image](https://user-images.githubusercontent.com/57644882/102024296-7bb5db00-3d91-11eb-897a-9bffdd00aba9.png)

**Comment by leonardo-ourmachinery** [comment]
Fixed for the next release.
