### ISSUE TITLE
Not showing entities with generated names in entity picker is confusing

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#419]
If I want to use a entity that is not stored as asset I cannot use the Entity Scene node because it wont show me the Entity:

![image](https://user-images.githubusercontent.com/70658708/102355199-d296fc80-3fab-11eb-83c2-fbc46174f916.png)

Improvement here would be not to assume that the entity is always a asset.

EDIT BY KARL: See comments.

**Comment by niklas-ourmachinery** [comment]
I think you just need to give the entity a name and it will show up in the list. Unnamed entities aren’t shown.

**Comment by simon-ourmachinery** [comment]
opps my bad... I though that this is basically a name.

**Comment by karl-ourmachinery** [comment]
I find this confusing too. One assumes that the Entity NUMBERNUMBER are entities with generated names. I think don't think we should have such "placeholder names" that aren't real, searchable names. Instead we should give the entities names, even if it is something generated. One could also ponder if we we should call them New Entity 1, New Entity 2 etc to be more consistent with how the asset browser does this.
