### ISSUE TITLE
Typo in TM_SOCKET_IP_LOCALHOST

### ISSUE THREAD

**Issue by peterlindgren** [OurMachinery/themachinery-public#42]
The fourth (first in network-byte-order) octet should be 1 instead of 0.

**Comment by peterlindgren** [comment]
After reading up a bit on IPv4 a bit it appears that the whole range 127.0.0.0/8 is reserved for loopback, but on Windows 10 I've been unable to establish a connection by using 127.0.0.0.

**Comment by niklas-ourmachinery** [comment]
Fixed -- will be in the next release.
