### ISSUE TITLE
tmbuild custom path to msbuild

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#420]
Related but slightly different: #186

Problem: User installs VS on none typical path such as D:\Program Files\vs2019 where vs2019 is the root folder. This means there are no subfolder such as   "BuildTools", "Community", "Professional", "Enterprise".

This is a problem because tmbuild assumes that VS or the build tools live in such a directory. Also the new macro will not help.

Solution: When the user uses the macro they have to give the correct full path to the `MSBuild` folder

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery  should we rely on vswhere? https://github.com/microsoft/vswhere and download that as a dependency on windows? This would reduce the code tmbuild of the tool and make it possible more stable?

**Comment by niklas-ourmachinery** [comment]
I'm a bit conflicted. `vswhere` seems ridiculously complicated so I'm a bit vary of relying on it, but maybe it's the Right Thing To Do™.

**Comment by simon-ourmachinery** [comment]
I could play around with it tomorrow? Make a branch and you can see if you
like it ?

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery 

We could use `vswhere` call it once store the location in a settings.json in our AppData folder and than use this file instead of calling vswhere everytime only if the found path is invalid we could call `vswhere` again to update the path.

**Comment by niklas-ourmachinery** [comment]
I'm not so worried about the cost of calling `vswhere`... it's probably pretty cheap... more about the sort of inherent complexity of depending on another complicated piece of software...

But more than anything it's my annoyance with this being so complicated, when it should be a pretty simple thing...

Adding vswhere to the lib directory is probably the right thing to do... we want things to work out of the box for everybody without  having to set up environment variables... I'm just annoyed by it 😄

**Comment by xgalaxy** [comment]
My understanding is that vswhere is supposed to be installed in the same place on every windows machine for every modern version of visual studio. In that sense you wouldn't have to ship vswhere with the engine at all unless you are weary of Microsoft changing the location of where vswhere gets installed.
