### ISSUE TITLE
Drag & dropping dcc_asset few times into scene crashes the Editor

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#422]
Drag & dropping `.dcc_asset` few times into scene crashes the Editor. 

1. Download [CesiumMan.glb](https://github.com/infosia/themachinery-issues/blob/master/0006/CesiumMan.glb)
2. Import the model
3. Drag & Drop `CesiumMan.dcc_asset` few times into the scene (like 4 times)
4. Editor crashes

This happens on `2020.12` and did not happen on `2020.11.a`
This happens only when you drop `.dcc_asset`. This does not happen on the extracted `.entity`.

**Comment by tobias-ourmachinery** [comment]
I've tried really hard to reproduce this but so far failed. Might be a race condition, will try it on more machines.  

If you run into it again, please upload a crash dump for us to look at. 

Thanks!

**Comment by infosia** [comment]
It's 100% reproducible on my machine. Because actual crash dump is too big (1GB~) I took some logs that may help analyze it;

![](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0009/error.png)
![](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0009/dump.png)

[2020-12-20%2004.44.14.log](https://github.com/infosia/themachinery-issues/blob/master/0009/2020-12-20%2004.44.14.log)
[analyze -v from WinDbg](https://github.com/infosia/themachinery-issues/blob/master/0009/analyze.txt)

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff6adc3ed08 (the_machinery+0x000000000000ed08)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000001
   Parameter[1]: 0000000000000000
Attempt to write to address 0000000000000000

PROCESS_NAME:  the-machinery.exe

WRITE_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000001

EXCEPTION_PARAMETER2:  0000000000000000

STACK_TEXT:  
00000084`5e9fecf0 00007ffe`4c237784     : 000039b8`00000000 0000088c`2cb032a4 00000000`00000000 00007ffe`4c259f10 : the_machinery+0xed08
00000084`5e9ff170 00007ffe`4c240de1     : 00000000`0005ad3a 000004b0`feb6ce68 00000258`e1bfff60 000004b0`feb6cf90 : tm_vulkan_render_backend_tm_hot_reload+0x17784
00000084`5e9ff1b0 00007ffe`611ae43e     : 00000000`00000000 00000084`5e9ff340 000004b1`10e6b10c 000003e8`fb7e1340 : tm_vulkan_render_backend_tm_hot_reload+0x20de1
00000084`5e9ff240 00007ff6`adc316c0     : 00007ff6`add0d938 00007ff6`add0d938 00007ff6`ade6c7b8 00000258`e1c65820 : the_machinery_dll_tm_hot_reload+0x4e43e
00000084`5e9ffbc0 00007ff6`adc33a21     : 00000000`000039b8 00000258`d6870000 00000000`00000000 00000000`000001ac : the_machinery+0x16c0
00000084`5e9ffbf0 00007ff6`adc3b554     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : the_machinery+0x3a21
00000084`5e9ffcb0 00007ffe`94577034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : the_machinery+0xb554
00000084`5e9ffd20 00007ffe`9653d0d1     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000084`5e9ffd50 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

```

**Comment by infosia** [comment]
This is no longer reproducible on the latest `beta-2021.1-windows` 🎉 I'll do some more tests and close this issue if it's plausible 👍
