### ISSUE TITLE
extracting dcc asset shows wrong color figure

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#424]
1. Download & import [theboss.fbx](https://github.com/infosia/themachinery-issues/blob/master/0010/theboss.fbx)
2. Check if `theboss.dcc_asset` previews fine
3. Extract `theboss.dcc_asset` by pushing "Import Asset" button
4. `theboss.entity` previews black figure

![](https://raw.githubusercontent.com/infosia/themachinery-issues/master/0010/preview.png)

This does not happen on the-machinery `2020.11.a`.

**Comment by tobias-ourmachinery** [comment]
Fixed in next release.

**Comment by infosia** [comment]
Now `theboss.dcc_asset` preview shows wrong figure. Tested on `2021.1`.

![Capture](https://user-images.githubusercontent.com/1661068/106340142-2ea7ad00-62dc-11eb-877c-7df7e152ed59.PNG)

**Comment by infosia** [comment]
Confirmed fixed in `2021.1.a Hotfix` 👍
