### ISSUE TITLE
Mouse back button should work as back arrow in Scene toolbar

### ISSUE THREAD

**Issue by creikey** [OurMachinery/themachinery-public#428]
It would be useful to be able to this after quickly peeking into an object's prototype to peek back out.

**Comment by simon-ourmachinery** [comment]
Thanks for the report. I hope I understood you correctly. You are saying that you would like to have a button to change the scene forward/backwards depending on the entity you have selected. This is currently possible via the back and forth button in the scene tab. This indicated that the visibility of this function is not as it should be.
![image](https://user-images.githubusercontent.com/70658708/103292779-c882ee00-49ee-11eb-892a-1020efbbad59.png)
Which allows you to go back to the previous "scene" or entity you saw.

Alternatively you can right click on the tab label and than you see in the context menu "Recent Objects" where you can pick the object you want to switch to.
![image](https://user-images.githubusercontent.com/70658708/103292910-1861b500-49ef-11eb-8c74-ffd6be6ae227.png)


I hope I could help you.

**Comment by creikey** [comment]
@simon-ourmachinery I am not sure why I didn't see those buttons, I swear I looked right there, apologies. In this issue I was referring to the back button on my mouse though, I usually use them to navigate across definitions in vscode (ctrl+click to go into definition, forward/backward button on mouse to go backwards and forwards on the definition chain).

**Comment by simon-ourmachinery** [comment]
@creikey No worries . This indicates a discoverability issue.
In terms of your mouse suggestion we will discuss this.

**Comment by niklas-ourmachinery** [comment]
I think having the forward/backward buttons on the mouse do this makes sense.

**Comment by karl-ourmachinery** [comment]
Fixed in 2021.2
