### ISSUE TITLE
Crash on pasting of entity from another project

### ISSUE THREAD

**Issue by creikey** [OurMachinery/themachinery-public#429]
1. Copied the skydome.entity from the third person sample
2. Went to my own project and pasted it
Crashed. Memory dump file:

[the_machinery_exe 2020-12-28 12.07.47.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/5748639/the_machinery_exe.2020-12-28.12.07.47.dmp.zip)

**Comment by niklas-ourmachinery** [comment]
Copying and pasting across projects is not supported. To move assets between projects use **File > Import Project**.

Still, it shouldn't crash. Looking into it.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2020.12.a hotfix release.
