### ISSUE TITLE
Closing unsaved entity graph caused editor crash

### ISSUE THREAD

**Issue by creikey** [OurMachinery/themachinery-public#432]

**Comment by simon-ourmachinery** [comment]
Thank you for reporting! Unfortunately can I not reproduce this bug.

I would need some more information:
- Is it a new project (your own) or a sample project?
- Which nodes did you have in your graph? (if you remember) 
- Is this a bug which happens always?
- Could you upload the minidump?

If you could provide some of those information that would be great @creikey .

**Comment by karl-zylinski-ourmachinery** [comment]
Closing this as it is very old I don't see this happen.
