### ISSUE TITLE
Scrolling UI lists with the mouse only scrolls one item at a time

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#433]
Windows has a setting that allows you to control how much should be scrolled "per scroll". 

![image](https://user-images.githubusercontent.com/1578924/104224805-c0db3480-5445-11eb-8ac3-755a2cda2476.png)

But mouse-scrolling in this view only scrolls one item at a time.

![image](https://user-images.githubusercontent.com/1578924/104224924-ed8f4c00-5445-11eb-8c9b-b4d0a81282b4.png)

**Comment by leonardo-ourmachinery** [comment]
Implemented, will be in for the next release.

**Comment by leonardo-ourmachinery** [comment]
Reopening this. Thinking about this, We might want to offer an in-engine setting that "overrides" the OS one if changed.
This would also support OS where the OS doesn't have this concept.

Anyway, on windows now we are following the OS setting.

@raphael-ourmachinery @simon-ourmachinery

**Comment by simon-ourmachinery** [comment]
@raphael-ourmachinery and I had a quick chat about it. Will share in slack.
