### ISSUE TITLE
Asset browser doesn't recognize removed folders, crashes.

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#434]
Repro:

I added an asset called something like assets/fbx/myfbx.fbx
It was imported.
I then deleted that whole fbx folder in Windows Explorer.
The asset was still in TM.
I then right clicked the asset in TM, and chose "Show in Explorer"
TM then took a few seconds, then crashed to desktop.

**Comment by niklas-ourmachinery** [comment]
Closing this as related to #435 -- we need a complete solution for live modifications to the project folder.

**Comment by simon-ourmachinery** [comment]
The engine should crash and it gets handled correctly by the Windows API complaining that the folder does not exists. There would be a modal call but the crash happens in the modal call.  This can be validated via removing the modal. @niklas-ourmachinery When I run the debugger and set a breakpoint it does not crash only without breakpoint.
