### ISSUE TITLE
Shortcut to open "New" menu inside Asset Browser context menu

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#438]
Similar to what we have in the graph for creating new nodes, I'd like a shortcut to popup the New menu inside the asset browser and be able to choose one of the available assets types. When adding a lot of different things, for example I was adding a bunch of tags, it get tedious.

**Comment by niklas-ourmachinery** [comment]
This should probably use the `Tab` key, just as we do in the other editors.

An issue is that we are already using the Tab key to tab between the fields in the Asset browser (to get to the search box for instance).

I wonder if we need another default key for the "Spawn" menu...

**Comment by simon-ourmachinery** [comment]
For constancy do you want to use also use the same menu as in the others ? The pop up picker? 


If there is any time better than change the default spam key than now. Because it's still a beta.

**Comment by niklas-ourmachinery** [comment]
I think it should use the same popup picker.

And yes... we should probably change the default spawn key... though I'm not sure to what... Space? Enter?

**Comment by karl-ourmachinery** [comment]
We could also use one the F-keys, like F4 or something.

**Comment by simon-ourmachinery** [comment]
I think F keys are not that nice because they are usually on the top of the keyboard so I am unsure if they are actually speedy enough.

**Comment by niklas-ourmachinery** [comment]
I agree... I think the F keys are too hard to reach...
