### ISSUE TITLE
Selecting multiple entities using shift doesn't work when first entity is not visible in the list

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#444]
Start with something like this:
![image](https://user-images.githubusercontent.com/1578924/104234899-6ac1bd80-5454-11eb-80a0-c552bbc8d301.png)

Shift-clicking the bottom one works as expected:
![image](https://user-images.githubusercontent.com/1578924/104234918-74e3bc00-5454-11eb-96e0-6d596afc2955.png)

Scrolling down a bit so that the top one isn't visible anymore doesn't work:
![image](https://user-images.githubusercontent.com/1578924/104234971-89c04f80-5454-11eb-9444-bb59be0582e3.png)

i.e. shift clicking one of those entities doesn't select all the entities inbetween the first one and the one you clicked.

**Comment by leonardo-ourmachinery** [comment]
Fixed for the next release.
