### ISSUE TITLE
Preview camera when selected in the Entity Tree

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#453]
Imagine a game with a lot of fixed cameras, it would be quite time consuming to "find" a specific camera in the scene dropdown menu every time I want to switch camera.

It would be nice to be able to either:

1) double click on a camera component in the Entity Tree and have the scene "switch" to that camera
2) when I select a camera component in the Entity Tree, the preview tab shows the world as viewed from that camera

Having both would be even nicer in my opinion.

**Comment by simon-ourmachinery** [comment]
Also a great use case would be to add a way to visualize other people in collab view and be able to select their camera to see what they see or change to their view.

**Comment by frank-ourmachinery** [comment]
Both features are now in master, will be released in 2021.8.
To use this with collaboration we would need to add additional hidden camera entities to the scene for every user in a session. Then we could send focus events to those entities if the user wishes to view the collaborators output view.

**Comment by simon-ourmachinery** [comment]
@frank-ourmachinery I might make a new issue for this at some point.
