### ISSUE TITLE
Clicking an asset should update the property window only when the button is released

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#455]
Right now, if you want to drag an asset, like a texture, into a property field, you first need to remember to pin the properties window, then find the other asset and drag it in. Then you need to unpin the property window again.

I feel like the typical behavior here is to only update the property window when the mouse is released.

And related to this, the property window for folders is pretty useless. I would like to click on a folder without the property window changing context. Could add "View properties" in the context menu for the rare case where you want this.

**Comment by Srekel** [comment]
Related question, is there a hotkey for pinning/unpinning? That could help quite a bit.

**Comment by frank-ourmachinery** [comment]
I've updated the asset browser API to only select objects when the button is released. It seems to improve the workflow with the properties view a lot. Currently the folders are still being shown as they count as selectable items as well, I think we want to make a distinction between selected assets and selected folders.

I don't believe there is currently a hotkey for pinning/unpinning a tab, but that seems like a good feature to add as well.

**Comment by niklas-ourmachinery** [comment]
Closing this now since a separate issue was added for the hotkey.
