### ISSUE TITLE
Preview for dcc_asset doesn't use material

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#461]
![image](https://user-images.githubusercontent.com/1578924/104845988-8c99c500-58d8-11eb-8a6b-fc00e73e2c1b.png)

![image](https://user-images.githubusercontent.com/1578924/104845999-9ae7e100-58d8-11eb-9e82-56f0af40800c.png)

**Comment by tobias-ourmachinery** [comment]
Yeah, this is not really a bug. When you imported the `dcc_asset` no textures were assigned to it. Hence when you preview it you will see it without textures as you are essentially previewing the "intermediate file".. Then you setup materials and assigned textures to them and mapped them to the rigged entities.. 

I'm still a bit on the fence if we should allow previewing `dcc_assets` or if that implicitly should trigger some kind of entity rigging.. Not sure.
