### ISSUE TITLE
Crash in `component_remove()` in `render_component.c`

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#465]
When a new projects is loaded and the Truth is reset with `reset_truth()`, `component_remove` does this call:

~~~c
tm_creation_graph_api->destroy_instance(&c->creation_graph_instance, &ctx);
~~~

Code here:

~~~c
static void destroy_instance(tm_creation_graph_instance_t *instance, struct tm_creation_graph_context_t *context)
{
    tm_creation_graph_manager_o *manager = *creation_graph_manager_ptr;
    if (instance->graph.u64 && instance->version == tm_the_truth_api->version(manager->tt, instance->graph)) {
        trigger_event(instance, TM_CREATION_GRAPH_EVENT_DESTROY_INSTANCE, context);
        tm_creation_graph_interpreter_api->destroy_instance(instance);
    }
}
~~~

In this code, the `creation_graph_manager_ptr` seems to have been updated with the **new Truth** (`manager->tt`). However, `instance->graph` refers to an object in the **old Truth**. Accessing an object in a different Truth may lead to crashes or other unexpected behavior.

Possibly, the `instance` itself should carry information about The Truth, rather than fetching it from a different source, to reduce the risk of desynching.

**Comment by karl-ourmachinery** [comment]
Fixed for 2021.1
