### ISSUE TITLE
Long function signatures not shown in full in the API docs

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#466]
See this screenshot:
![image](https://user-images.githubusercontent.com/1578924/105453618-bceab600-5c80-11eb-9c4e-45ebae9aca0a.png)

**Comment by niklas-ourmachinery** [comment]
This has already been fixed for 2021.1 -- I've done a review pass over the `foundation` documentation.

I'm reviewing all the plugin documentation too, but it might not make it in for 2021.1, because we have *a lot* of documentation.
