### ISSUE TITLE
Add a "Copy Asset Path" to asset browser context menu

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#467]
Currently, Copy Path copies the file's path on disk. When working "inside" the machinery, it seems more useful to have the asset path, e.g. "core/light.entity".

So it would be nice to add this, and rename the existing one to something like "Copy File Path".

**Comment by simon-ourmachinery** [comment]
We could also just drop the current function and only provide a project path for working inside the machinery?

**Comment by simon-ourmachinery** [comment]
changed: Copy path will copy the internal path. If the external path is needed one can open the explorer via Show in explorer.
