### ISSUE TITLE
Crash when importing FBX file

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#469]
Importing [this FBX file](https://www.dropbox.com/s/78ktdng3d3c0km7/cooper-hewitt_exterior.fbx?dl=1) into the `modular-dungeon-kit` project gives a Vulkan error:

```
C:\work\themachinery\plugins\vulkan_render_backend\vulkan_render_backend.c(9904): error: res == VK_SUCCESS (code -4)
```

The call that fails is:

```
 VkResult res = vkQueueSubmit(device->queues[QUEUE_GRAPHICS], 1, &submit_info, submit_headers[d]->complete_fence);
 ```

in `internal_submit_resource_command_buffers()`.

Interestingly, if I import the file into a new blank project (instead of the `modular-dungeon-kit` sample), I don't get the error:

![image](https://user-images.githubusercontent.com/26548514/105881194-0c9aeb80-5fb9-11eb-83f9-fc4b12618886.png)

**Comment by frank-ourmachinery** [comment]
Interestingly, If I first open a new project and import the asset there and then open the `modular-dungeon-kit` and import it there it works fine for me. Only when I start the engine in a project with other assets it seems to crash.

**Comment by frank-ourmachinery** [comment]
I have the same issue with the assets in [this](https://drive.google.com/file/d/1rpqPni4Vr-yq42kQHAyFOke-85hJY6wZ/view?usp=sharing) project. They seem to be part of the same overall model
