### ISSUE TITLE
Add shortcuts settings

### ISSUE THREAD

**Issue by d44m1n** [OurMachinery/themachinery-public#47]

**Comment by niklas-ourmachinery** [comment]
Do you mean to configure shortcuts for menu options? I agree that this would be nice-to-have but it's not high on our priority list right now.

**Comment by d44m1n** [comment]
Yup, for menu options, tabs etc.
Basically for everything that uses shortcut.

**Comment by simon-ourmachinery** [comment]
we have support for shortcuts now
