### ISSUE TITLE
forum.ourmachinery.com email validation not sending

### ISSUE THREAD

**Issue by omenjohn** [OurMachinery/themachinery-public#471]
I got off the phone with your publicist who introduced me to the idea of The Machinery, and was able to create an account on ourmachinery.com.  However, I am unable to log in on the forum as validation emails are not currently sending... :(  I was able to receive the email when creating the main website account.

Yes, I have checked that I can receive emails and that it wasn't captured by my spam filter.

Outside of the forum, I wasn't sure where to report this.  I was able to receive a validation email when creating the main website account.

**Comment by niklas-ourmachinery** [comment]
Hi, thanks for reporting this!

Can you give me the email you were attempting to register and I can investigate?

**Comment by niklas-ourmachinery** [comment]
Never mind, I see your mail here... looks like it sent OK from our end... so not sure what happened... I'll try sending it to you from a different mail address and see if you get it:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/26548514/105942193-9bd4ed00-6013-11eb-8394-f591568815b5.png">

**Comment by omenjohn** [comment]
Hey!  So yeah, I just got a verification email, but I think it's for your
website and not the forum.  My impression is that both these tools use
different accounts (as in, one for the forum and one for the main website
proper).  I received the verification email that you just sent, but it
doesn't seem to satisfy first-time use of the forum.  Thanks for looking
into this, by the way.

**Comment by omenjohn** [comment]
For comparison, the forum account that I just made uses the username OmiSC.

**Comment by niklas-ourmachinery** [comment]
Ah sorry, my bad. I read too hastily and didn’t see that it was the forum that you were having problems with. Let me investigate the forum mails.

**Comment by niklas-ourmachinery** [comment]
I've verified that emails are not sending and activated your account manually. Digging into why the emails are not sending.

**Comment by niklas-ourmachinery** [comment]
Fixed, emails are now sending again.

**Comment by omenjohn** [comment]
Thanks!
