### ISSUE TITLE
Potential portability issue with tm_tt_id_t

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#475]
tm_tt_id_t has a bitfield that allows you to extract type, gen, etc.

Zig isn't able to translate this. No biggie, I thought, I could just write this:

```C
inline uint64_t tm_tt_id_t_type(tm_tt_id_t id) {
    return id.u64 & 0x03ff;
    // return id->u64 >> 54;
}
```

(As you can see I had to try both ends of the bits because I wasn't sure where type was held.. :) )

In the end, this works. But, bitfields aren't necessarily portable between compilers. Is this something you're concerned about? Using masking macros would be less convenient but perhaps safer?

**Comment by niklas-ourmachinery** [comment]
I think bitfield layout is defined by the ABI, i.e. on Windows it's defined by the x86_64 ABI, so it should match between all compilers using the same ABI (which we need anyway).
