### ISSUE TITLE
Add the option to disable Systems in Simulate mode, just as we can disable Engines

### ISSUE THREAD

**Issue by d44m1n** [OurMachinery/themachinery-public#48]
It would be great to have possibility to disable/enable systems/engines through UI.

**Comment by niklas-ourmachinery** [comment]
This is already available.

With the *Simulate* tab open you can choose **Simulate > Engines** to disable individual engines. Currently it's just showing engines though and not engine systems, so those should be added to the menu.

**Comment by d44m1n** [comment]
Oh, I didn't know. Thanks!

**Comment by leonardo-ourmachinery** [comment]
Fixed for 2021.08
