### ISSUE TITLE
Preview difference between .dcc_asset and .entity

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#489]
When you preview assets, I see there's a difference between `.dcc_asset` and `.entity`. Seems `.entity` assets previews correctly.

<img src="https://user-images.githubusercontent.com/1661068/109268376-542dc500-784e-11eb-9019-580b6d43d3f0.png" height="50%" width="50%">

Tested by following model with The Machinery 2021.2.

https://github.com/infosia/readyplayerme-Tpose/blob/main/models/t-pose.glb

**Comment by karl-ourmachinery** [comment]
Fixed for the next version.

We now keep a hidden _preview entity_ inside the DCC asset that is rigged in the same way as when rigging an entity from the DCC asset.
