### ISSUE TITLE
Handle plugins using APIs wrongly

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#506]
I apologize for the poor title. :)

I've recently updated to the most recent version. I think my last update was two months ago, so a few things have changed in the API.

When calling this, the editor crashes:

``` zig
 if (tm_ui_api.button.?(ui, &uistyle, &gallerize_button)) {
```

`ui` is simply the object passed in to my tab function, guessing there's not much I can do about that.

`uistyle` is a variable I've zero-initialized and have also set:
``` zig
    uistyle.buffer = c.enum_tm_ui_buffer.TM_UI_BUFFER_MAIN;
``` 

Here's my button, also zero initialized:
``` zig
    var gallerize_button: c.tm_ui_button_t = undefined;
    std.mem.set(u8, std.mem.asBytes(&gallerize_button), 0);
    gallerize_button.text = "Gallerize";
    gallerize_button.rect.x = rect.x + 100;
    gallerize_button.rect.y = rect.y + 200;
    gallerize_button.rect.w = 200;
    gallerize_button.rect.h = 100;
``` 

So I'm guessing there are fields I need to fill in, which is of course fair. But it seems reasonable that TM could detect that I'm passing in 0 and provide an error, even if it's just a popup saying:

> hey, this variable need to be something, now I'm going to crash!

So to be clear, I'm not asking how to solve this specific thing, I'm sure I can figure it out, it's just noting that it would be nice to get a hint, when possible.

**Comment by frank-ourmachinery** [comment]
In your case the `font` field in the `tm_ui_style_t` isn't being set, but you are passing text to be rendered. I'll add some validation for the `tm_ui_style_t` so we can log an error.
