### ISSUE TITLE
Incomplete documentation in tag_component.h

### ISSUE THREAD

**Issue by marot** [OurMachinery/themachinery-public#507]
I tried to use the `tag_component.h` api for a custom project based on the simple draw example (non-machinery application).

I had some difficulties that could be resolved by better documentation:
- `add_tag` crashed when passing in a hashed string. I expected it to work out of the box. The documentation is not clear about the need to first define tags in the truth.
- How to define a tag in the truth is unclear (The hashed asset name is the tag & the tag subobject has no properties).
- I think the comment `// Tags are 64 bit values (typically string hashes)` is misleading, as with the current setup string hashes are the only possible value

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.5
