### ISSUE TITLE
`VkWriteDescriptorSet with no data!` when capturing with RenderDoc on "raytracing-less" AMD card.

### ISSUE THREAD

**Issue by khskarl** [OurMachinery/themachinery-public#508]
### Environment
- The Machinery 2021.2a
- AMD Radeon RX 5700 XT 27.20.14527.2002
- RenderDoc v1.12 Windows 64-bit Release (40b86b63fbb990b26cc083ced32cb55f11ad263c) 

### Description
When trying to open a capture of The Machinery running on a AMD card, RenderDoc fails to replay the capture and reports:
```
Failed to open capture for replay: Replaying the capture failed at the API level.
```
Not sure if it happens in any other cards, but the log seems to indicate the error may be related to raytracing-less AMD cards, as it has other errors related to ray tracing structures.

### Steps to reproduce
1. Open **The Machinery** without any external plugins in **RenderDoc**
2. Create a new empty project 
3. Press `F12` to capture a frame
4. Close `The Machinery`, causing the captured frame to be loaded; Or double click the captured frame;
5. Popup dialog opens up: `Failed to open capture for replay: Replaying the capture failed at the API level` + information about diagnostic log.

### Log 

The resulting RenderDoc diagnostic log can be found below.
It's probably worth highlighting the _ray tracing structure_ related errors.

Log with only errors and `warning`:
```
QTRD 013800: [12:24:57] ToolWindowManager.cpp(1528) - Warning - area parameter ignored for this type
RDOC 007352: [12:25:14]       win32_hook.cpp( 525) - Warning - CreateToolhelp32Snapshot() -> 0x00000018
RDOC 007352: [12:25:14]       win32_hook.cpp( 525) - Warning - CreateToolhelp32Snapshot() -> 0x00000018
RDOC 007352: [12:25:14]       win32_hook.cpp( 525) - Warning - CreateToolhelp32Snapshot() -> 0x00000018
RDOC 007352: [12:25:14]   vk_next_chains.cpp(1092) - Error   - Unhandled struct VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR in pNext chain
RDOC 007352: [12:25:14]   vk_next_chains.cpp(1092) - Error   - Unhandled struct VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR in pNext chain
RDOC 007352: [12:25:14]   vk_next_chains.cpp(1931) - Error   - Unhandled struct VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR in VkDeviceCreateInfo pNext chain
RDOC 007352: [12:25:14]   vk_next_chains.cpp(1931) - Error   - Unhandled struct VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR in VkDeviceCreateInfo pNext chain
RDOC 007352: [12:25:14]     vk_serialise.cpp(1436) - Error   - No support for VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR is available in this build
RDOC 007352: [12:25:14]     vk_serialise.cpp(1436) - Error   - No support for VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR is available in this build
RDOC 007352: [12:25:21]        vk_common.cpp( 997) - Error   - Unexpected descriptor type
RDOC 007352: [12:25:25]        vk_common.cpp( 997) - Error   - Unexpected descriptor type
RDOC 007352: [12:25:29]        vk_common.cpp( 997) - Error   - Unexpected descriptor type
RDOC 013800: [12:25:36]    win32_network.cpp( 261) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.
RDOC 013800: [12:25:36]  vk_device_funcs.cpp(2759) - Warning - robustBufferAccess is available, but cannot be enabled due to robustBufferAccessUpdateAfterBind not being avilable and some UpdateAfterBind features being enabled. out of bounds access due to bugs in application or RenderDoc may cause crashes
RDOC 013800: [12:25:36]     vk_initstate.cpp( 827) - Error   - Unexpected descriptor type 1000150000
RDOC 013800: [12:25:36]        vk_common.cpp(1039) - Error   - Encountered VkWriteDescriptorSet with no data!
```

Full Log:
[renderdoc_the-machinery_empty-descriptor.log](https://github.com/OurMachinery/themachinery-public/files/6136969/renderdoc_the-machinery_empty-descriptor.log)

**Comment by frank-ourmachinery** [comment]
Renderdoc currently doesn't support the ray tracing extension in any way, so when we bind acceleration structures to the bindless descriptor set Renderdoc sees it as a descriptor set with no valid data. We have a macro in place to disable all ray tracing support in the Vulkan backend which I'm currently using every time I want to use Renderdoc. 

I'm not quite sure how to nicely solve this as these extensions are very dependent on the Renderdoc version and Baldur will likely add support for Vulkan ray tracing in the future. We could add a temporary command line option to disable ray tracing.

**Comment by frank-ourmachinery** [comment]
After a bit of thinking I added a command line argument for the next release. If you run with `--frame-debugging` Renderdoc should work again. I intend to add Renderdoc API detection if you run with this command line argument in the future, so you can do things like capture a specific viewport.

**Comment by khskarl** [comment]
Sounds like a great compromise, thanks for the help. 😄

**Comment by frank-ourmachinery** [comment]
I ended up going a bit further and I added the ability to capture a frame from a specific viewer, I'm my testing this makes taking RenderDoc captures quite a bit faster. You can capture from the Scene and Preview tab if you launch The Machinery through RenderDoc by pressing the camera button in the toolbar (I'll change that to the RenderDoc icon once we have better custom icon support).
