### ISSUE TITLE
toolbars in graph: dragging -> box select, click on overlay gets through

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#509]
- When dragging a toolbar in the graph the box select is active
- when moving a toolbar over a node the node can be selected by accident

![image](https://user-images.githubusercontent.com/70658708/111170112-dedb2780-85a3-11eb-864f-795c5884d34f.png)
![overlay_issue_graph](https://user-images.githubusercontent.com/70658708/111170331-1944c480-85a4-11eb-9705-62c5322b0072.gif)
![image](https://user-images.githubusercontent.com/70658708/111170388-2a8dd100-85a4-11eb-9110-e1b8d1548f1c.png)

**Comment by karl-ourmachinery** [comment]
Fixed.
