### ISSUE TITLE
Allow to get entity system/engine by using its name, or id

### ISSUE THREAD

**Issue by d44m1n** [OurMachinery/themachinery-public#51]
I know that I can use `registered_engines`/`registered_systems` , but well, I don't think it's very convenient if you only want to get one specific system/engine.
I think there are 2 options.

1. By name
As engine/system name is localized, we need to define something like that:
```c
#define TM_SPIN_COMPONENT_ENGINE_NAME "tm_spin_component_engine"
```
and later:
```c
tm_engine_i* engine = api->get_engine(ctx, TM_SPIN_COMPONENT_ENGINE_NAME);
```

2. By id/hash
```c
#define TM_SPIN_COMPONENT_ENGINE_ID TM_STATIC_HASH("tm_spin_component_engine", 0x0ULL)
```
and later:
```c
tm_engine_i* engine = api->get_engine(ctx, TM_SPIN_COMPONENT_ENGINE_ID);
```

From users perspective there is no difference, so choice is up to you.
Also this will be useful for #50.

**Comment by niklas-ourmachinery** [comment]
Yes, we could easily add this -- would you mostly use it to enable/disable systems or is there another use for it you see?

**Comment by d44m1n** [comment]
At this moment I just want do enable/disable systems, but in the future, when engine will evolve it could be useful to get pointer to the specific system/engine.

**Comment by frank-ourmachinery** [comment]
Added for next release.
