### ISSUE TITLE
Bounding volume for DCC asset animations is incorrect

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#510]
The bounding volume for DCC asset animations can contain incorrect values, such as `Inf` or `1e+38`. This can be seen by selecting one of the DCC asset animations in the `animation` sample, such as `bot/animation/walking.dcc_asset`. [bound_selected_assets()](https://ourmachinery.com//apidoc/plugins/the_machinery_shared/scene_common.h.html#structtm_scene_common_api.bound_selected_assets()) will return the wrong value.

I've currently hacked around the problem by having [bound_selected_assets()](https://ourmachinery.com//apidoc/plugins/the_machinery_shared/scene_common.h.html#structtm_scene_common_api.bound_selected_assets()) ignore any "too large" points, but this should be investigated to find out why these points appear in the bounding volume to begin with.

Hack is here:

https://github.com/OurMachinery/themachinery/commit/1048dac43564f00f36e8c9f2f6493d29fa7cceb7

**Comment by tobias-ourmachinery** [comment]
Can't be reproduced in master. Assuming this has been resolved, closing.
