### ISSUE TITLE
Updated Linux installation documentation accuracy

### ISSUE THREAD

**Issue by RoryO** [OurMachinery/themachinery-public#513]
At the ![linux installation instructions](https://ourmachinery.com/beta.html) provided it says what packages are required.

```
sudo apt-get install libxcb-ewmh2 libxcb-cursor0 libxcb-xrm0 unzip
```
However, it's missing one more. Using those packages and running from a standard 20.04 system the editor still won't start

```
./the-machinery 
The Machinery - Version 2021.2.a
../../foundation/os.linux.c:548:0: error: Error loading `/home/rory/OM/bin/plugins/libtm_dxc_shader_compiler.tm_hot_reload.so`: libtinfo.so.5: cannot open shared object file: No such file or directory'

[1]    21265 segmentation fault  ./the-machinery
```

The fix is also installing the `libtinfo5` package. After doing so, the editor starts fine.

**Comment by raphael-ourmachinery** [comment]
Thanks for the feedback, `libtinfo5` should had to be shipped with the engine, which will be fixed in the next release.
