### ISSUE TITLE
Show full list when clicking a filterable choice field

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#514]
The Machinery 2021.2.a

When you click any filterable choice list (a text field limited by a type you can select), it gets filtered by the current value. This is almost always pointless because you actually want to change the value. So I often have to press Backspace to view the full list of options or start typing if I know what I need. It'd much more convenient if the behavior after clicking was to show the full list (as if the filter string is empty) and the filtering would start only after you actually change the current value.

**Comment by simon-ourmachinery** [comment]
Hi @endragor thanks for your feedback,
I just want to clarify if I understand you correctly. What you are saying is:
- click on TextEdit with filter
- start typing -> filter start
- Click again on TextEdit to see full list
- start typing again -> filter continuous 

Am I understanding this correctly?

**Comment by endragor** [comment]
Hi @simon-ourmachinery, thanks for the reply. 

No, that sequence is not what I meant. What I meant is:

- click on TextEdit with filter -> full list is shown (no filtering applied) and the current input is selected
- change input -> filtering starts

Basically the same behavior as now, except now it filters by the current value when you click on the text field. That's pointless because I clicked on it to set a different value. So a more meaningful behavior is to NOT apply any filtering until I input something new.

**Comment by niklas-ourmachinery** [comment]
I agree... this would be useful when the list of possible matches is short. (If the list is long you probably would need to type something anyway to get meaningful filtering.)

**Comment by simon-ourmachinery** [comment]
will be in the next release
