### ISSUE TITLE
Cannot switch keyboard layout when focus is in editor

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#515]
The Machinery 2021.2.a
Windows 10 Pro Version 1909

I have two keyboard layouts set up in the system: English US and Russian. Usually, I can switch between the layouts either by pressing Shift+Alt or from the taskbar. However, when the focus is in The Machinery window, neither method works. Even if I actually select another layout with the mouse from the taskbar, nothing happens. I have to either minimize The Machinery or switch focus to a different app to be able to switch the layout. I haven't encountered this problem in other applications I use.

**Comment by frank-ourmachinery** [comment]
Fixed for next release.
