### ISSUE TITLE
Cannot move newly created ASM nodes

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#520]
The Machinery 2021.2.a
Windows 10 Pro Version 1909

I haven't quite figured the conditions for this, but the bug is pretty easy to reproduce.

1. Create a new Layer in the Animation State Machine Editor
2. Create nodes of different types in the State Graph.
3. Try to move them around.

For me, only Empty nodes can be stably moved after this. Other nodes may or may not be movable (if you try to drag them, they return to their previous position next frame). After you configure the nodes they often become movable, but sometimes not.

**Comment by niklas-ourmachinery** [comment]
Failed to reproduce this in 2021.3. Can you maybe make a video of this happening, so I can make sure I have the exact same repro case?

**Comment by endragor** [comment]
Can't reproduce it either in 2021.3. So either it was fixed in the new version or there is some tricky condition required for this to start to be reproducible. Will reopen if I see this again.
