### ISSUE TITLE
Actions for multi-selected items of the same type

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#521]
The Machinery 2021.2.a
Windows 10 Pro Version 1909

When working with dcc_asset animations, you often have to create clips for them or reimport them. For one file this can be done by opening the context menu and selecting the corresponding action. However, when selecting multiple dcc_assets these actions are no longer available, even though all I want is to execute an existing action separately for each asset. So instead I have to do this manually one by one for each file. It'd be nice if these and other similar actions worked with multi-selection.

**Comment by simon-ourmachinery** [comment]
related #460

**Comment by niklas-ourmachinery** [comment]
Related #377

**Comment by niklas-ourmachinery** [comment]
* [ ] Create .clip from .dcc_asset
* [ ] Create .animation from .dcc_asset
* [ ] Create .clip from .animation
* [ ] Reimport
* [ ] Export
* [ ] Instantiate

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.4
