### ISSUE TITLE
Closing the "Main" window should do a full exit

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#526]
I had dragged out a separate window with a creation graph.

Then I closed down the main window. This left the creation graph window open. I closed that too.

Next time I started the application, the only window that was opened was the graph window, on the monitor it had been dragged out to.

Expected: When I close the "main" window, either close the whole TM application, or prompt for it. When I open TM again I expect the "main" window layout to have survived, so to speak.

**Comment by niklas-ourmachinery** [comment]
I don't know if i makes sense to say that the "main" window should always be restored when you open a project. The Machinery doesn't really have the concept of a main window -- i.e. each window is equally "main" as any other.

We actually have code to deal with the case you run into -- where the user wants to close the application, but does it by closing all the windows one-by-one. Here, the assumption is that the user wants to restore *all* the windows when the application is opened again, not just the last closed one.

Currently, I think we use a timer to detect this situation. I.e. if you close all the windows within X seconds, we interpret is as a "shutdown" and try to restore all those windows on boot up. @leonardo-ourmachinery knows the details.

I don't know if you ran into these because you took some time to close the creation graph window... maybe the time limit should be increased... or if there was some other issue.

**Comment by leonardo-ourmachinery** [comment]
At the moment we have a 5 seconds timer that allows the user to close all the windows and have all of them being restored next time. 

Do you feel like that's too restrictive? @niklas-ourmachinery @Srekel 
Maybe we should expose it in the settings?

**Comment by niklas-ourmachinery** [comment]
I don’t think we need a setting — too many settings just get confusing — but maybe increase it to like 60 seconds. I think if the user wants to close a window and not have it restore, they’ll do some fair amount of work before quitting so the timer can be quite high.

**Comment by Srekel** [comment]
I imagined you would say that there isn't a main window, and, I do think it makes sense. :) 

But, I don't think a timer is a great idea as I think most people won't understand it and will simply feel that the layout is remembered "at random". I think by increasing it to a minute would help quite a lot though and work decently, but I do think you'll get reports down the line.

The reasons why I think it isn't great is that 
A) Most other applications do have a main window, like Visual Studio, so they are used to there simply being one action needed to exit.
B) It's quite likely to close the first window, only for the window in the background to become visible, showing something that steals your attention, like, say, your favorite goat video*. Maybe you watch this for a minute, then remember oh yeah, I was shutting down, but by then the timer has run out.

---

I think my preferred solution to this would be an extension of the layout settings you already have. The very first time you start TM, you spawn and place all the windows/tabs, then you save this to TheMachineryDefaultConfig. The user can save additional ones.

Then, upon startup, you open up the last opened windows (just as you do now), loop over the available settings, and if *none* of the saved layouts have *all* of its tabs showing, then you display a dialog: "Would you like to load one of these layouts?"

---

(*) While not being my favorite one, I've watched this one several times today: https://twitter.com/Rubberbandits/status/1377927349644230656

**Comment by niklas-ourmachinery** [comment]
Web browsers are an example of an application that works this way. I agree that it's not always great... I'm always a bit worried that my browser will fail to restore my "main window" with 40 tabs in it, and instead restore the single Google Meet tab that dragged out to a separate window...

Not a super fan of your solution... first I'm not sure I completely understand "none of the saved layout have all of its tabs showing"... also I think modal dialogs are kind of ugly in general...

Maybe an easily found menu option **Restore recently closed windows** would work, though discoverability can be an issue.

**Comment by Srekel** [comment]
Agree about modal dialogs, they are overused and often don't even have to be modal. 

So with regards to saving layout I think you can continue to use the timer 'heuristic'. Another option could be to add another button to next to the Close/Max/Minimize buttons, similar to a Pin button, that would mark it as "If this is closed, the whole application should shut down".

Just to be clear about my suggestion: A layout configuration would look something like this:

```
TM Default Config
Windows
    Window 1
           Pos 100 200
           Size 500 500
           Tabs
                  Asset Browser (Pos+Size)
                  Scene (Pos+Size)
                  Entity Tree (Pos+Size)

```

Let's say that's the only saved config.

Now, when TM opens, it loads the last state. If the state has a bunch of windows, but at least one of Asset Browser, Scene, and Entity Tree is missing, it would realize that it doesn't match any existing layout, indicating that the user is not in a preferred mode.  

Then it would ask the user if they want to reset to a known layout. This doesn't have to be a modal dialog. For example, it could be one of those bright bars situated just below the menu bar, like this one from Discord. It could disappear after 60 seconds or something.

![image](https://user-images.githubusercontent.com/1578924/113469872-5a1c5480-9451-11eb-8974-ff5494ee373d.png)

**Comment by Srekel** [comment]
Btw, with risk of stating the obvious.. While I think *something* like that would be nice, so long as the timer is extended, this isn't a high-prio request. :)

**Comment by leonardo-ourmachinery** [comment]
I've extended the timer to 60 seconds.

@Srekel Closing this issue for now, but I think that the "would you like to open a standard window?" popup message thing has potential, I wrote it down in my notebook :)
