### ISSUE TITLE
Crash when undoing entity add

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#527]
Found it when reproing this: #278

1. Open TM
2. Open core/default_world.entity
3. Drag in sky.entity
4. Press Ctrl Z (Sky is still in the scene here, already reported #454 )
5. Press Ctrl Z again. Sky is now removed, though default_world is marked as dirty, as mentioned in #278 
6. Drag in sky.entity
7. Press Ctrl Z
8. Press Ctrl Z. TM now crashes.

**Comment by niklas-ourmachinery** [comment]
@tobias-ourmachinery I reproduced this... I get an access violation in `vulkan_render_backend.c:destroy_image()` when trying to access `vk_image`.

Is this the cubemap destruction issue you talked about?

**Comment by niklas-ourmachinery** [comment]
Fix for 2021.3.a.
