### ISSUE TITLE
tm_strncpy_safe - maybe not use strncpy?

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#529]
`strncpy` has a zero-padding feature which is often not needed for its use case. Usually you use `tm_strncpy_safe` to copy an existing string into a buffer. The buffer is often large enough (e.g. 1024 bytes), while the string you copy from is a short name or user input (around 64 bytes or less I'd say). In addition to copying the string, `strncpy` fills the remainder of the buffer with zeros. So instead of writing just ~64 bytes it writes the whole 1024-byte buffer, which is a waste.

A better approach is to use `memccpy` and put `\0` at the end depending on its return value.

**Comment by niklas-ourmachinery** [comment]
Good point... I didn't know about `strncpy()` zero-padding... will fix.
