### ISSUE TITLE
Status bar should show mouse actions

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#53]
The status bar should show a hint of what the mouse buttons will do. These hints should update when modifier keys are pressed.

Blender does this well:

![image](https://user-images.githubusercontent.com/26548514/71853201-84853380-308f-11ea-81ce-c45001deb564.png)

**Comment by karl-ourmachinery** [comment]
Fixed in upcoming version 2020.4
