### ISSUE TITLE
Crash when creating new entity (The thread tried to read from or write to a virtual address for which it does not have the appropriate access.)

### ISSUE THREAD

**Issue by PreyK** [OurMachinery/themachinery-public#530]
Hello!
I've encountered a crash in the latest build (2021.3) where if I try to create anything new in the world the engine just crashes.
I've made a video reproducing it:
https://www.youtube.com/watch?v=-iysmiqAc4Q
There's a new memory dump file created in the bin folder after the crash, opening it in VS says The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
![image](https://user-images.githubusercontent.com/1968543/113450769-d2a6f500-9400-11eb-8cca-cb9a56c333ee.png)

I've attached the memory dumps, my "AppData\Local\The Machinery\Logs" folder, and a DxDiag from my PC

[DxDiag.txt](https://github.com/OurMachinery/themachinery-public/files/6251123/DxDiag.txt)
[dumps.zip](https://github.com/OurMachinery/themachinery-public/files/6251110/dumps.zip)
[Logs.zip](https://github.com/OurMachinery/themachinery-public/files/6251112/Logs.zip)

**Comment by niklas-ourmachinery** [comment]
Reproduced.

@tobias-ourmachinery This one crashes in the same place in `destroy_image()` as #527, seems to be the same issue.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.3.a.
