### ISSUE TITLE
Crash after deleting entity

### ISSUE THREAD

**Issue by Srekel** [OurMachinery/themachinery-public#536]
I *think* this is what happened prior to the crash:

I'd run my gallerizer plugin, generating my gallerizer.entity. I believe something went wrong here, because I think it crashed afterwards.

Next I open TM, navigated to my entity, tried to delete it, and it crashed.

I then again opened TM, did the same thing, but this time it did not crash.

Attaching dumps. The last one should be the the crash.
[dumps_04_03.zip](https://github.com/OurMachinery/themachinery-public/files/6252790/dumps_04_03.zip)

**Comment by frank-ourmachinery** [comment]
See #535.
