### ISSUE TITLE
Duplicating a node duplicates the connection

### ISSUE THREAD

**Issue by Hastur007** [OurMachinery/themachinery-public#543]
The Machinery 2021.3.a

![ScreenShot 2021-04-09 154343](https://user-images.githubusercontent.com/28621517/114140570-691c6e80-994b-11eb-8951-c2d3f6cff390.png)

**Comment by simon-ourmachinery** [comment]
I think this is by design when duplicating instead of copy nodes. @tobias-ourmachinery ping, can correct me if I am wrong.

**Comment by tobias-ourmachinery** [comment]
@simon-ourmachinery To be honest I didn't even that we supported node duplication (CTRL-D). @karl-ourmachinery might know ?

It looks fishy though as the resulting graph is not valid.

**Comment by simon-ourmachinery** [comment]
Yes agreed it looks fishy and it can invalidate graphs... so we might wanna either add some more logic to this or remove the connection copy ... I think

**Comment by karl-zylinski** [comment]
We do support it. However, it probably shouldn't duplicate the connections at all.

**Comment by niklas-ourmachinery** [comment]
Duplication should definitely duplicate some connections — such as internal connections between the duplicated nodes. But it should not create invalid configurations as in the situation above.

Also, Duplicate should be equivalent to Copy + Paste, which I think it already is.

**Comment by karl-ourmachinery** [comment]
Agreed on the internal connections. I'm not sure duplicating external connections (even though we make sure to not add invalid connections) is very convenient though. I think I'll make it do what copy + paste does, which doesn't duplicate external connections.

**Comment by niklas-ourmachinery** [comment]
Yeah I'm not sure 100 % either what the best choice is... sometimes you want the external connections duplicated... sometimes not... but maybe following Copy/Paste is best.

(OTOH you could argue that there is an advantage of not following Copy/Paste because then you could use either Duplicate or Copy/Paste depending on if you want connections duplicated or not.)

**Comment by karl-ourmachinery** [comment]
I went with doing whatever copy + paste does. I always see duplicate as a shorthand for copy + paste. Fixed for next release.
