### ISSUE TITLE
Code generated by "File/New Plugin/Entity Component..." cannot be compiled

### ISSUE THREAD

**Issue by Hastur007** [OurMachinery/themachinery-public#545]
The Machinery 2021.3.a
VisualStudio 2019

I used "build.bat".

The following needs to be modified:
- Fix `truth__create_types` function
- Fix `engine_filter__custom_component` function
- Replacing `tm_entity_api-> lookup_component` to `tm_entity_api->lookup_component_type`

**Comment by niklas-ourmachinery** [comment]
Related to #544.

**Comment by simon-ourmachinery** [comment]
Is already fixed
