### ISSUE TITLE
Entity tree does not scroll on the x axis

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#546]
Editor: 2021.3/4-internal
If added enough entities the tree will not offer a scroll axis for the x dimension

![image](https://user-images.githubusercontent.com/70658708/114559872-764b9d00-9c6c-11eb-9e11-7f507d0f7b97.png)

**Comment by leonardo-ourmachinery** [comment]
I pushed this on master, behind a feature flag.

There are two things that makes me a bit doubtful about the current implementation:

1) The fact that there will always be some horizontal scrolling to do no matter what, assuming that what we want to do is that when you've scrolled all the way to the end the element that's the deepest in the hierarchy should be seen completely. This means that if there's a simple tree made of a root entity and one children, the tree will allow you to scroll horizontally, even if that's not really necessary.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/70660839/152746734-5b485452-a749-400a-ac6d-c1133afe69ca.png">

2) You can click and interact with an item of which you cannot see the name. We could solve this by always scrolling horizontally when selecting an item, but I'm not sure about it, we should at least try it I guess.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/70660839/152746803-dd9a29be-9651-44e3-be34-577429617a70.png">

I don't think that 1) is a big deal, but I think we should come up with something for 2). I'll try horizontal auto-scroll when selecting.

**Comment by leonardo-ourmachinery** [comment]
Ok, I pushed horizontal auto-scrolling to fix 2). I'll leave the issue open for now so that we can discuss this.

**Comment by simon-ourmachinery** [comment]
> The fact that there will always be some horizontal scrolling to do no matter what, assuming that what we want to do is that when you've scrolled all the way to the end the element that's the deepest in the hierarchy should be seen completely. This means that if there's a simple tree made of a root entity and one children, the tree will allow you to scroll horizontally, even if that's not really necessary.

@leonardo-ourmachinery  When using the scrollbar you can just check if the canvas with would be bigger than the tab width if so than you turn on the flag for X scrolling otherwise you do not. Besides Wasnt there an automatic scroll On/off flag?

**Comment by leonardo-ourmachinery** [comment]
That's what we're doing. But a Tree with just two items will be larger than the canvas anyway, because we're using the entire horizontal canvas width to draw the root item: is child will _always_ go past that no matter what (Because of indentation), so there will always be some scrolling possible even in that simple case

So either:
1) we artifically say "don't allow scrolling if the tree has less than _x_ levels"
2) we set a fixed limit for the width of an element (200px for example)

But neither of those seem acceptable to me... so I'm currently more inclined to leave things as they are...
---

I don't exactly understand what do you mean with Automatic scroll On/off flag, but surely it wasn't handling autoscroll in the _x_ direction, as there was not horizontal scrolling at all.

**Comment by simon-ourmachinery** [comment]
> I don't exactly understand what do you mean with Automatic scroll On/off flag,
Sorry @leonardo-ourmachinery  I meant:
```
// Controls when a scrollbar will be shown.
enum tm_ui_scrollbar_visibility {
    // The scrollbar will be shown only when the content is too big to fit the view.
    TM_UI_SCROLLBAR_VISIBILITY_WHEN_NEEDED,
    // The scrollbar will never be shown.
    TM_UI_SCROLLBAR_VISIBILITY_NEVER,
    // The scrollbar will always be shown.
    TM_UI_SCROLLBAR_VISIBILITY_ALWAYS,
};
```

I had the same issue in the TT and I just subtracted the base intend of my width and then it works. Also, your clip rects are not correct at the moment which indicates something is not correct with the width calculation.

**Comment by leonardo-ourmachinery** [comment]
What are the clipping issues you're seeing?

**Comment by simon-ourmachinery** [comment]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/70658708/152804137-19743e6d-6c7f-4405-94be-a22ef0b2e7e5.png">
<img width="114" alt="image" src="https://user-images.githubusercontent.com/70658708/152804401-9930e162-f44e-4d4a-af78-a3bdff3e67d3.png">

**Comment by simon-ourmachinery** [comment]
@leonardo-ourmachinery  I needed to shrink the window I had some issues with my tm installation and my screenshot tool

**Comment by leonardo-ourmachinery** [comment]
No problems! That clipping issue is not scroll-related, but has to do with the fact that the tree view code reserves space for the buttons (hide, lock, etc) even if the entity doesn't use it. I'd like to solve it as well soon, but it's not related to horizontal scrolling.

Still leaving the issue open for a bit.

**Comment by leonardo-ourmachinery** [comment]
I'm closing this for now, but the horizontal scrolling has only be "disabled" so we'll be able to revisit it in the future if we want to.
