### ISSUE TITLE
Let user control execution order of entity engines

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#547]
From Discord channel:

> Currently there is no way for user's to manage the order... the engines are executed in the order that they are registered.
>
> We will probably introduce a simple execution_order float and sort the engines by that before execution... I've been holding off on that to see if I could come up with a better solution... because it's not super elegant... but so far I haven't come up with anything... it's a bit tricky since engine and components can come from different plugins that may not know about each other.
>
> My idea right now is to have the execution_order float, but to allow it to be "overriden" (i.e. set from another plugin than the one that defines the component). That way, your "main gameplay plugin" or whatever can take complete control of the execution order of all components.

https://discord.com/channels/690290013585408136/691973666140848148/831556331835228200

**Comment by simon-ourmachinery** [comment]
bevy 
https://bevyengine.org/news/bevy-0-5/

Another example of ECS is flecs.
https://github.com/SanderMertens/flecs

In flecs, the order of "System" is controlled by "Phase".
https://github.com/SanderMertens/flecs/blob/master/docs/DesignWithFlecs.md#phases-and-pipelines

Unity DOTS:
https://docs.unity3d.com/Packages/com.unity.entities@0.1/manual/system_update_order.html

**Comment by niklas-ourmachinery** [comment]
Current plan for this is to be similar to Bevy and allow engines to specify engines that should run before and after them using `before_me` and `after_me` fields in `tm_engine_i`.

~~~c
 .before_me = { TM_ENGINE__SCENE_TREE },
 ~~~
 
 Further goals for this:
 
 * Allow the same functionality for `tm_entity_system_i`.
 * Allow the execution order of engines and systems to be intermixed... i.e. engines can be set to run before or after a certain system.
 * Allow for parallel execution of `tm_entity_system_i`.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.5.

* Scheduling order can be specified using `before_me` and `after_me` arrays.
* Note that this doesn't determine parallelism, that is determined by which components are read and written.
* Engines and systems now run in the same scheduler.
* An `exclusive` flag can be used for engines and systems that should run exclusively.
* A `phase` concept has been introduced for grouping jobs. I.e. if you set `.before_me = {TM_PHASE__ANIMATION}`, your job will be scheduled after all jobs that have been tagged with `TM_PHASE_ANIMATION`.

Here's a sample picture of the scheduling in action:

![image](https://user-images.githubusercontent.com/26548514/118702042-46426d00-b7c9-11eb-9ed2-b61377da2996.png)
