### ISSUE TITLE
The color of the "first person sample" executable becomes whitish

### ISSUE THREAD

**Issue by Hastur007** [OurMachinery/themachinery-public#549]
The Machinery 2021.3b
windows 10
nvidia rtx3080

1. Open Gameplay First Person
2. File->Publish
3. set "Executable Name", "Window Title", "World Entity"
4. Publish...
5. Execute .exe

editor:
![スクリーンショット 2021-04-16 114152](https://user-images.githubusercontent.com/28621517/114968611-afc11a00-9eb1-11eb-80e5-854dd9b86d02.png)

exe:
![スクリーンショット 2021-04-16 115703](https://user-images.githubusercontent.com/28621517/114968619-b2bc0a80-9eb1-11eb-9dad-f051edc85318.png)

**Comment by frank-ourmachinery** [comment]
Fixed for 2021.4 release.
