### ISSUE TITLE
Open File Dialog does not respect DPI scaling

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#55]
On high-resolution screen, the open file dialog is to small.

On a low res screen:

![image](https://user-images.githubusercontent.com/26548514/72002547-77d21e00-31fc-11ea-892a-b176074d0e36.png)

On a high res screen:

![image](https://user-images.githubusercontent.com/26548514/72002586-891b2a80-31fc-11ea-95ce-83831296dc9c.png)

**Comment by frank-ourmachinery** [comment]
I don't think this is possible on Windows. The file dialog is a system dialog so the application has no control over its appearance. I think the default size is somehow stored in the users preferences and we should not edit those.

**Comment by niklas-ourmachinery** [comment]
Windows seems to behave somewhat inconsistently with regard to this too.

Even in the same program, on the same screen, sometimes the dialog is big and sometimes it is small. Not just in our program, but in lots of different programs (Microsoft programs too).

I'll close this issue for now... maybe reopen it later if there is any indictation that we're doing something we shouldn't be doing.
