### ISSUE TITLE
Allow for component specific settings

### ISSUE THREAD

**Issue by frank-ourmachinery** [OurMachinery/themachinery-public#550]
Sometimes it's useful to expose component type specific constants to the user so they can tweak them.
A few examples:
- Free camera speed increase/decrease sensitivity.
- Debug geometry level of detail
- Minimum light influence 

Being able to set this through the `tm_component_i` would be desirable I think:
```c
float (*settings_ui)(tm_component_manager *manager, tm_ui_o *ui, const tm_ui_style_t *ui_style, tm_rect_t item_rect);
```

**Comment by raphael-ourmachinery** [comment]
It's possible to use `tm_settings_api` for this now, I'll close this issue, but feel free to reopen if you feel something is missing.
