### ISSUE TITLE
The Machinery does not start.

### ISSUE THREAD

**Issue by Calorifaire** [OurMachinery/themachinery-public#554]
Nothing happens when trying to execute the-machinery.exe with a freshly unzipped set of files.
[the_machinery_exe 2021-05-06 04.02.21.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/6432889/the_machinery_exe.2021-05-06.04.02.21.dmp.zip)

**Comment by simonrenger** [comment]
original bug report on discord:
>I have this exception in the dump file: "The thread tried to read from or write to a virtual address for which it does not have the appropriate access."
https://discord.com/channels/690290013585408136/779314091990319104/839768631838769213

extra information:
> Yes I saw this. I could not find my Vulkan version but I have an AMD RX 580 so I'm pretty sure it's enough and I have the latest stable drivers from autumn 2020.
https://discord.com/channels/690290013585408136/779314091990319104/839773331251265547

**Comment by frank-ourmachinery** [comment]
It seems to crash when trying to create the default acceleration structures. Could you also share the generated log file, this should be in `AppData/Local/The Machinery/Logs`. According to the Vulkan hardware database your card doesn't support ray tracing so it should not try to create these resources.

**Comment by Calorifaire** [comment]
Here is the log file.
[2021-05-06 04.02.21.log](https://github.com/OurMachinery/themachinery-public/files/6436875/2021-05-06.04.02.21.log)

**Comment by frank-ourmachinery** [comment]
I'm not sure why it's trying to create ray tracing structures as your card doesn't support them. I'm noticing that you're not on the latest driver, make sure to update as this might cause your issue.

**Comment by Calorifaire** [comment]
Yes that was the problem. The new drivers came out 2 weeks ago.
Thank you for the quick support and sorry to disturb you for this. I should have checked before.
