### ISSUE TITLE
Clicking a node in the graph editor doesn't bring it to the front

### ISSUE THREAD

**Issue by tlein** [OurMachinery/themachinery-public#565]
Version: 2021.4.a
Platform: Windows 10

Clicking a node in the graph editor doesn't bring it to the front of the other visual nodes. 

While this functionality was described in an older blog post on the IMGUI implementation for the engine, it doesn't seem to actually work in engine. See "Handling Overlap" section of this blog post: https://ourmachinery.com/post/one-draw-call-ui/

![image](https://user-images.githubusercontent.com/815242/119270032-b5a0ce00-bbc8-11eb-8dfb-d50362059109.png)

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed for version 2020.5.

Thanks for your bug report. The graph drawing code is custom and needed a sorting key.
