### ISSUE TITLE
Rigging Shapes/Box in the Physics sample creates unexpected entity hierarchy

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#574]
* Open the Physics sample.
* Select `Meshes/Box.dcc_asset` in the asset browser.
* Click **Extract Assets** in the properties window.
* Open the created `Box.entity`.

The entity hierarchy created looks like this:

![image](https://user-images.githubusercontent.com/26548514/121219706-d740bd00-c838-11eb-99b3-2e0eb2b83ab3.png)

WIth `Mesh:Red` having the properties:

![image](https://user-images.githubusercontent.com/26548514/121219799-ea538d00-c838-11eb-98ae-17aeedaed84b.png)

The problem here is that `Mesh:Red` is not linked to any Scene Tree node, so it uses the entity tree linking, but its immediate parent `Meshes` does not have a `Transform` node. Therefore, the mesh will not get a proper hierarchical transform.

**Comment by tobias-ourmachinery** [comment]
Fixed.
