### ISSUE TITLE
Bad performance when previewing UI canvas with text

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#575]
When an entity with a UI canvas that has text in it is previewed in the preview window, the framerate drops to 6 fps or so.

![image](https://user-images.githubusercontent.com/26548514/121220607-985f3700-c839-11eb-8a21-1da563e93628.png)

The time is being spent in the `bake()` function of `ttf_baker.c`. Looks like the fonts are being baked every frame.

**Comment by raphael-ourmachinery** [comment]
Changing windows size doesn't change The Truth data anymore, and was implemented `tm_asset_preview_api->reload()` to entities, so we only propagate changes when data changes instead of recreating the entity in the preview tab. These changes solve performance issues for UI Components.
