### ISSUE TITLE
Graphics starts blinking when a lot of objects are added

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#576]
https://user-images.githubusercontent.com/26548514/121225403-571d5600-c83e-11eb-8bfa-e1d85780be9e.mp4

**Comment by tobias-ourmachinery** [comment]
I took a look at this and it appears to be the view frustum culling that breaks down with lots of objects making them blink. If I comment out:
```
//if (!tm_culling_frustum_visible(args->frustum_visibility, args->offset + i, v, args->num_viewers))
     //  continue;
```
in `private__ci__render_task()` the flicker goes away.

Ping @frank-ourmachinery Let me know if you need assistance tracking down the root cause.

**Comment by frank-ourmachinery** [comment]
Fixed.
