### ISSUE TITLE
Console font illegible on startup

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#577]
Sometimes (not 100 % sure when) the font in the Console view is illegible when you start up the application:

![image](https://user-images.githubusercontent.com/26548514/121250463-98236380-c85a-11eb-84c5-5f5daafb96fe.png)

If you enter the window with the mouse the font becomes legible:

![image](https://user-images.githubusercontent.com/26548514/121250518-a96c7000-c85a-11eb-860a-923a80e443d1.png)

Entering the window with the mouse disables the "cached UI" path -- so it seems like this may have something to do with UI caching not being active the first frame.

**Comment by simon-ourmachinery** [comment]
I also see this sometimes 
![image](https://user-images.githubusercontent.com/70658708/121361385-86fb5500-c935-11eb-9684-e762026e8a2c.png)

**Comment by leonardo-ourmachinery** [comment]
Fixed.
