### ISSUE TITLE
When you delete a folder in the asset browser tree view, expanded folders close

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#580]
For example, deleting `pong/struct/walls` in the Modular Dungeon sample closes `pong/struct` which was previously expanded.

Expected behavior is that the expanded/closed status of folders shouldn't change if folders are deleted.

**Comment by simon-ourmachinery** [comment]
other issue can be that a "random" other folder opens. I am on the solution
