### ISSUE TITLE
Cubemap from prototype sky not applied

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#581]
If you open the `physics` sample project at revision `ce3bad3978710aedafbefaa7a5fa3f049177b4f5`, the cubemap from the `sky` entity is not being applied:

![image](https://user-images.githubusercontent.com/26548514/121431413-346a6a80-c92e-11eb-8389-d8c7f343be7d.png)

If you double-click the `Cubemap Capture` component to override it, the cube map will be applied:

![image](https://user-images.githubusercontent.com/26548514/121431463-4946fe00-c92e-11eb-8ffa-a94b1e69838c.png)

However, if you then right click `Cubemap Capture` and remove the override, it goes back to the original state:

![image](https://user-images.githubusercontent.com/26548514/121431413-346a6a80-c92e-11eb-8389-d8c7f343be7d.png)

**Comment by tobias-ourmachinery** [comment]
Fixed in master.
