### ISSUE TITLE
Asset browser sometimes doesn't respond to F2 to rename

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#582]
When this happens `keyboard_target` is false in:

~~~c
const bool keyboard_target = tm_ui_api->is_first_responder(ui, rec->file_tree_id) && ab->current_directory_cache.u64 == directory.u64 && !tm_carray_size(ab->renaming_objects);
~~~

Both the `is_first_responder()` and `current_directory_cache` tests seem to be failing:

![image](https://user-images.githubusercontent.com/26548514/121561991-e0af5e00-c9cd-11eb-8ef4-93cee9e2059e.png)

![image](https://user-images.githubusercontent.com/26548514/121562061-f1f86a80-c9cd-11eb-9738-137d47bfc2bc.png)

Still not sure exactly how I got into that state and unfortunately I lost my debug session so I couldn't dig deeper.

**Comment by simon-ourmachinery** [comment]
Ill investigate!

**Comment by simon-ourmachinery** [comment]
I think I close this till this issue can be reproduced.
