### ISSUE TITLE
Crash in The Machinery when adding Spin Component to sky entity

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#583]
* Open The `modular-dungeon` sample project.
* Add a Spin Component to the `room` and set y component to 1.
* Simulate

![image](https://user-images.githubusercontent.com/26548514/121568017-11929180-c9d4-11eb-95bd-cd166a307863.png)

Triggered by the `tm_carray_resize()` here:

~~~c
static struct tm_shader_constant_buffer_instance_t *viewer_constant_buffers(tm_shadow_map_manager_o *manager, uint32_t num_buffers)
{
    uint32_t size = (uint32_t)tm_carray_size(manager->shadow_viewer_cbuffers);
    if (num_buffers > size) {
        tm_carray_resize(manager->shadow_viewer_cbuffers, num_buffers, manager->allocator);
        tm_shader_io_o *io = tm_shader_api->system_io(manager->viewer_system);
        tm_shader_api->create_constant_buffer_instances(io, num_buffers - size, manager->shadow_viewer_cbuffers + size);
    }
    return manager->shadow_viewer_cbuffers;
}
~~~

Is it caused by moving the light source?

**Comment by niklas-ourmachinery** [comment]
Seems to be triggered if I spin the Sky entity but not by spinning any other entity.

**Comment by raphael-ourmachinery** [comment]
@niklas-ourmachinery I'm not able to reproduce it.

**Comment by niklas-ourmachinery** [comment]
Tried these reproduction steps (Windows, Debug build) and I'm still getting the crash... I'm also getting a weird flashing behavior for the light source before the crash appears.

**Comment by frank-ourmachinery** [comment]
I'm not able to reproduce this either (Windows, debug build). Is this bug still here or was it already fixed?

**Comment by niklas-ourmachinery** [comment]
It's 100 % reproducible for me. This time I'm getting it in this line:

~~~c
*lights[l].shadow_data_offset = (uint32_t)(output - mapped_output);
~~~

Looks like there's two lights, but the second one is corrupt (garbage data):

![image](https://user-images.githubusercontent.com/26548514/123107538-7c899280-d3ee-11eb-9e23-8b112fc9bb86.png)

**Comment by niklas-ourmachinery** [comment]
I see a weird light flickering in the scene view too, so probably the corrupt light is there too (but not causing a crash).

**Comment by tobias-ourmachinery** [comment]
I had the flicker but no crashes. I've fixed what I think was the root cause of the flicker (and probably the crash) in master. Please reopen this if you still can reproduce it after you've tried with latest code.

**Comment by niklas-ourmachinery** [comment]
Tried it with the latest code and it works now. It runs kind of slow though, because the rotation triggers a cubemap capture every frame.
