### ISSUE TITLE
Can not import blender file saved with Blender 2.93.0

### ISSUE THREAD

**Issue by Hoogin** [OurMachinery/themachinery-public#585]
I imported an old prop in a blender file into a project and it worked fine. I then decided to make some changes to the prop in blender 2.93.0. When Importing I got this error.

❌ Import of file /home/hoogin/GameDevelopment/Spelet/Props/SingleSteelDoor3.blend failed with error message: BLEND: Expected at least one object with no parent

Next I tried this.
- New general project in blender
- Save it
- Import into the machinery

❌ Import of file /home/hoogin/GameDevelopment/Spelet/Props/cube.blend failed with error message: BLEND: Expected at least one object with no parent
Same error, my older blender files import just fine.

Does this have something to do with the version of the assimp(^‿^) that come with 2021.5 beta?

**Comment by Hoogin** [comment]
Compiled and installed assimp 5.0.1 and moved the lib coming with the machinery to another folder, same thing.
Did blender change something with their 2.93 release perhaps?
A bit of searching and I found this [https://github.com/assimp/assimp/issues/3316](https://github.com/assimp/assimp/issues/3316) seems to have been scheduled a fix for version 5.1 of assimp.
Guess I'll export to another format for the time being.

**Comment by raphael-ourmachinery** [comment]
I suspect that is related to Blender moving to collections, I'll try to explore assimp source, maybe we can help with something.

**Comment by Hoogin** [comment]
The assimp exception is thrown in BlenderLoader.cpp in the ConvertBlendFile function.
This FIXME is found there.
```
    // FIXME it must be possible to take the hierarchy directly from
    // the file. This is terrible. Here, we're first looking for
    // all objects which don't have parent objects at all -
```
I'll see if I can gather some information how the format changed when moving to collections.
Then take a closer look at the code.

**Comment by Hoogin** [comment]
I gathered some more information about the blend format.

Blender developers have the general consensus that the blend file format is not guaranteed to be stable. 
A quote..
```
"My first advice here is always, don’t write a .blend file reader or writer. It’s Blender’s 
internal file format and we make no guarantee that it remains stable or try to document all the 
quirks."
```
This ["mystery of the blend tries"](https://github.com/fschutt/mystery-of-the-blend-backup) explain more about how the format worked for 2.54.
The same information along with 2 scripts for blender 2.5 exists in the doc folder of the source for blender 2.93.

I don't have time to poke around the code today but I'll probably take a look later.

**Comment by raphael-ourmachinery** [comment]
@Hoogin this weekend I haf a look at this issue, if you look at Scene struct in Blender source, the basact field is deprecated, assimp uses this field to look for objects, I believe that we have to look at children collections of master_collection field, Assimp doesn't take in account collections, and probably there are other fields deprecated too. So for now I think is best to export to gltf or fbx instead of using .blend files directly

**Comment by raphael-ourmachinery** [comment]
We will not officially support importing Blender files anymore, we still will keep an unofficial support through Assimp. Maybe in the future, we can write a custom Blender exporter addon for The Machinery. Thanks for reporting, and please keep helping us to improve the engine, but unfortunately it would be very hard to keep the importer compatible with .blend files, as they are not stable.

**Comment by Hoogin** [comment]
That is understandable, we will see when Assimp 5.1 is released if they have fixed it.
I thought about writing an plugin for The Machinery it would most definitely be a good chance to learn new things. 
But since time is finite, I guess I will spend time on making my game instead.
It's not the end of the world, I'll write a script that export all my .blend files to an intermediate format. :)
