### ISSUE TITLE
Recently used folder resets when importing file from file menu

### ISSUE THREAD

**Issue by Hoogin** [OurMachinery/themachinery-public#588]
Recently used folder seems to reset when a file has been imported from file menu.

Did this on linux.
- Go to file and then Import file..
- Import an asset from a folder
- File -> Import file..
- Now it opens the bin folder instead of the import folder
- File -> Open project now also opens the bin folder

**Comment by simon-ourmachinery** [comment]
@Hoogin 
> Now it opens the bin folder instead of the import folder
In the Engine or in the File Explorer when trying to import assets?
> File -> Open project now also opens the bin folder
I also assume in the file explorer

**Comment by Hoogin** [comment]
Exactly the file manager opens the bin folder when you want to select file or project to import/open.

**Comment by raphael-ourmachinery** [comment]
I believe that will be fixed on the next release, if it's not the case we can reopen the issue again.
