### ISSUE TITLE
Dragging files into the asset browser UI sometimes doesn't work

### ISSUE THREAD

**Issue by Hoogin** [OurMachinery/themachinery-public#589]
On linux sometimes when I try to drag files into the asset browser UI nothing happens.
Tried on 2 different desktop environments with different results.

On linux with KDE5 and dolphin file manager.
- Drag file into the Upper part of the asset browser UI element
- File gets imported
- Drag file into the lower part of the asset browser UI element
- Nothing happens

On linux with xfce4 and thunar file manager.
- Drag file into the Upper part of the asset browser UI element
- Nothing happens
- Drag file into the lower part of the asset browser UI element
- File gets imported

OS: Linux Slackware 15 Beta

**Comment by raphael-ourmachinery** [comment]
Thanks. Are you using multi monitor setup? When that happens, is the file manager window floating above The Machinery window?

**Comment by Hoogin** [comment]
I'm using a single monitor on a laptop.
OS: Linux, Slackware 15 beta

On KDE5
- New project
- Dragging files into the asset browser tab lower part doesn't work
- Create a new asset browser tab, a smaller portion of the lower UI it doesn't work
- New empty window
- New asset browser tab
- Now there is only that small area where it doesn't work

![nplzKDE5](https://user-images.githubusercontent.com/12593971/122834912-7af69680-d32a-11eb-9323-1050f489a2ee.png)

![natKDE5](https://user-images.githubusercontent.com/12593971/122834973-92ce1a80-d32a-11eb-9c97-08387ec17812.png)

![dabKDE5](https://user-images.githubusercontent.com/12593971/122834994-9a8dbf00-d32a-11eb-8275-d27b5aa9f8f7.png)


On xfce4
- New project
- Dragging into the asset browser tab upper part doesn't work
- Create a new asset browser tab, no problems dragging in files
- New empty window
- New asset browser tab , No problem dragging in files

![auzXFCE4](https://user-images.githubusercontent.com/12593971/122835079-b8f3ba80-d32a-11eb-83f3-0574000a337d.png)

Looking at the screenshots I seem to have UI scaling on KDE5, I'll turn that off and see if I get a different result.

**Comment by Hoogin** [comment]
When I turn off the global UI scaling on KDE5 I get the same results as with Xfce4.

**Comment by raphael-ourmachinery** [comment]
I'm still looking at it, I wasn't able to exactly reproduce it, but zoom in the Editor seems to trigger a similar behavior. I tested on my archlinux setup with i3, on xfce4 and gnome too and on Ubuntu. Whats your resolution? Thanks again :)

**Comment by simon-ourmachinery** [comment]
confirmed on windows as well.

**Comment by Hoogin** [comment]
I'm using 1920x1080.

**Comment by simon-ourmachinery** [comment]
should be fixed next release

**Comment by Hoogin** [comment]
Okay, Nice. :)
