### ISSUE TITLE
Window Set Size --> Windows Border & when dragged it expanes

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#590]
OS: Windows
What: Windows Set Size 720p
1. Issues: Adds weird border
![image](https://user-images.githubusercontent.com/70658708/122970352-14a35f80-d38e-11eb-9a4e-2e18d9310700.png)
2. When dragged it automatically maximizes the window instead of move it along
![window_border](https://user-images.githubusercontent.com/70658708/122970550-5af8be80-d38e-11eb-90ce-2702ac2ad048.gif)

**Comment by frank-ourmachinery** [comment]
Fixed.
