### ISSUE TITLE
Fatal Error: Failed Initializing Vulkan

### ISSUE THREAD

**Issue by wobes1** [OurMachinery/themachinery-public#591]
Just starting out with the Engine and having a Vulkan related issue. My specs are: i7-7700k, GTX 1070, Win 10 Enterprise LTSB?, latest GPU drivers (477.11), vulkaninfo returns Version: 1.2.170.  A lot of Vulkan games work perfectly (Doom, No Mans Sky, RDR2) on my machine yet the Machinery not able to find it out. I was lucky to capture a fatal error message as well. 

As for the logs not all the time I am able to get a dmp that is not 0 bytes in size. 

Here is the log file and .dmp file (renamed to .txt for upload)
[2021-06-23 14.23.54.log](https://github.com/OurMachinery/themachinery-public/files/6704223/2021-06-23.14.23.54.log)
[the_machinery_exe 2021-06-23 14.29.51.txt](https://github.com/OurMachinery/themachinery-public/files/6704227/the_machinery_exe.2021-06-23.14.29.51.txt)

Error message that I am able to get from time to time on my screen  (most of the time the machinery just ends up being in task manager with no cpu usage)
![image](https://user-images.githubusercontent.com/24993673/123152357-7e754500-d432-11eb-89a8-412349529cf4.png)

**Comment by tobias-ourmachinery** [comment]
@wobes1 477.11 is a typo right? you meant 471.11 ? Upgrading my drivers to 471.11 to see if I can reproduce this.

**Comment by wobes1** [comment]
> @wobes1 477.11 is a typo right? you meant 471.11 ? Upgrading my drivers to 471.11 to see if I can reproduce this.

my bad. it was 471.11 yes.

**Comment by simonrenger** [comment]
Discord ref https://discord.com/channels/690290013585408136/690290014202233044/857328123212464178

**Comment by wobes1** [comment]
I was able to get past the warning of Vulkan initialization with 2021.3 yet still crashed. Please see the log and crash dump
[the_machinery_exe 2021-06-23 23.02.38.zip](https://github.com/OurMachinery/themachinery-public/files/6705273/the_machinery_exe.2021-06-23.23.02.38.zip)
 attached
[2021-06-23 23.02.36.log](https://github.com/OurMachinery/themachinery-public/files/6705272/2021-06-23.23.02.36.log)

**Comment by wobes1** [comment]
@tobias-ourmachinery I believe my issue is indeed Windows related. After updating to 2021.6 I was able to get more detailed error message. 
![image](https://user-images.githubusercontent.com/24993673/123355596-fd05db80-d533-11eb-8c8f-4ff10afb6076.png)


Please see the link below https://stackoverflow.com/questions/62243162/how-to-access-setthreaddescription-in-windows-2016-server-version-1607

**Comment by frank-ourmachinery** [comment]
That's an interesting bug. The procedure it's looking for has been upgraded to Vulkan 1.2 so I expected it to be available on any Vulkan 1.2 capable GPU. However, to use this procedure a device feature is required (`bufferDeviceAddress`) which is generally only enabled on ray tracing capable GPUs.

The weird thing is that some drivers that don't support ray tracing will support this procedure as it's part of the Vulkan 1.2 standard and will only throw an error if it's called, but it seems that your driver just doesn't define it at all. I'll manually load this procedure to prevent this crash, this will be in the hotfix.
