### ISSUE TITLE
Different output in editor vs published build

### ISSUE THREAD

**Issue by cforfang** [OurMachinery/themachinery-public#592]
Comparing output in editor vs published build for the gameplay-first-person-2021.6 sample:
![editor_vs_publish](https://user-images.githubusercontent.com/544178/124832795-7e6e5c80-df7d-11eb-9ba4-df8bbc9d212a.png)
Brightness appears to be off (too bright) in the published build. 

Win 10 / RTX 2060, can repro with both beta-2021.6.a-windows and master@75617c463f2

**Comment by frank-ourmachinery** [comment]
Seems to be an issue with the sky entity, if I remove it from the scene then the lighting is the same. Perhaps the cubemap isn't capturing?

**Comment by karl-zylinski-ourmachinery** [comment]
@tobias-ourmachinery I can get it this bright in the editor by opening the simulate tab, then refreshing the cubemap and jumping back and forth between simulate and scene tab a few times. Also, if I refresh the cubemap again, it can crash during `destroy_image`.

**Comment by frank-ourmachinery** [comment]
The `destroy_image` crash is likely the same bug as produced in #594.

**Comment by raphael-ourmachinery** [comment]
The issue was runner doesn't having cubemap capture interfaces, it will be fixed on the next release!
