### ISSUE TITLE
Crash when pressing Refresh twice on Cubemap component

### ISSUE THREAD

**Issue by TheMarcsOv** [OurMachinery/themachinery-public#594]
* Open New Project
 * In the Entity Tree tab, click on the entity _sky_ then _Cubemap Capture_  
 * Press twice on the compnent's _Refresh_ button (not double clicking, just pressing it twice within the span of one second)
 * The editor crashes

Here are the specs of the laptop I'm running TM on:
 * Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 * Discrete: NVIDIA GeForce GTX 1050
 * Integrated: Intel(R) HD Graphics 630
 * 16 GB RAM

[dumps.zip](https://github.com/OurMachinery/themachinery-public/files/6785113/dumps.zip)

**Comment by tobias-ourmachinery** [comment]
Reproduced. Working on a fix.

**Comment by tobias-ourmachinery** [comment]
Fixed in master. Will be part of July release.
