### ISSUE TITLE
Linux: tmbuild --install error

### ISSUE THREAD

**Issue by Hoogin** [OurMachinery/themachinery-public#608]
I tried to install using only the tmbuild provided on ourmachinery.com i got this error.
> tmbuild: Required file `libs.json` not found

I had set the executable flag on the tmbuild before running it.
The whole console output..
> bash-5.1$ ./tmbuild --install
Cloning into 'themachinery'...
Username for 'https://github.com': hoogin
Password for 'https://hoogin@github.com': 
remote: Enumerating objects: 85150, done.
remote: Counting objects: 100% (2138/2138), done.
remote: Compressing objects: 100% (489/489), done.
remote: Total 85150 (delta 1696), reused 2024 (delta 1633), pack-reused 83012
Receiving objects: 100% (85150/85150), 39.18 MiB | 3.94 MiB/s, done.
Resolving deltas: 100% (69669/69669), done.
tmbuild: Required file `libs.json` not found

Checking the files downloaded there are  libs.json files in these folders.
> /themachinery
/themachinery/foundation
/themachinery/samples
/themachinery/utils

 I compared with the source and it doesn't seem to be any libs.json missing.
Checking the tmbuild source, it seems to be failing at the install libs function, calling read on the libs.json file.

**Comment by Hoogin** [comment]
I got this email from github after using tmbuild --install
> Hi @Hoogin,
> 
> You recently used a password to access the repository at OurMachinery/themachinery with git using git/2.32.0.
> 
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

Does tmbuild work with token authentication?

**Comment by CGKurisu** [comment]
Move tmbuild into the "themachinery" folder it made and run again, fixed it for me

**Comment by simon-ourmachinery** [comment]
> I got this email from github after using tmbuild --install
> 
> > Hi @Hoogin,
> > You recently used a password to access the repository at OurMachinery/themachinery with git using git/2.32.0.
> > Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
> > Thanks,
> > The GitHub Team
> 
> Does tmbuild work with token authentication?

Thanks so much for reporting we will adjust `--install` asp

**Comment by simon-ourmachinery** [comment]
@Hoogin if you get latest:
```
$ tmbuild --project tmbuild
```
and copy tmbuild (the new one) into a new folder and rund:
```
tmbuild --install --github-token MY_GITHUB_PERSONAL_ACCESS_TOKEN
```

does this work for you?

**Comment by raphael-ourmachinery** [comment]
Thanks @Hoogin, It will be fixed on the next release.
