### ISSUE TITLE
Suspected typo in error message when missing DejaVu font on linux

### ISSUE THREAD

**Issue by qrikko** [OurMachinery/themachinery-public#609]
When missing DejaVuSans.ttf at a location where it can be found I get this error message. I believe it is meant to say:
/usr/**share**/fonts/TTF
 instead of:
/usr/**shader**/fonts/TTF
![typo](https://user-images.githubusercontent.com/5863849/125157040-ef259c80-e168-11eb-8928-9e64d3e00d40.png)

**Comment by raphael-ourmachinery** [comment]
Thanks, is a typo error, will be fixed on next release.
