### ISSUE TITLE
Project size doesn't decrease after delete nodes with cached data from creation graphs

### ISSUE THREAD

**Issue by raphael-ourmachinery** [OurMachinery/themachinery-public#617]
Steps to reproduce:
1. Create a new project
2. Add a filter node and a crunch compress node to `import-image.creation` 
![Screenshot from 2021-07-12 09-42-26](https://user-images.githubusercontent.com/75702792/125289308-7d2e8e00-e2f5-11eb-998a-e1ca67121972.png)
3. Save the project, check the saved size
4. Change back `import-image.creation` to the original
![Screenshot from 2021-07-12 09-46-25](https://user-images.githubusercontent.com/75702792/125289975-32f9dc80-e2f6-11eb-84fe-6b27f007162a.png)
5. Resave the project. Project size doesn't decrease

**Comment by niklas-ourmachinery** [comment]
I don’t think this is a bug. The database is not set up to shrink. Rather unused pages are marked as free so they can be reused later. If you resave the database under a new name it should shrink since this defrags the database.

**Comment by raphael-ourmachinery** [comment]
I forgot to mention, the same behavior occurs for directory projects, and resaving with a different name doesn't decrease the size too, it seems that cached data from nodes isn't be deleted.
