### ISSUE TITLE
Opening Dinosaur Collector project with TheMachinery version 2021.6.a on Windows crashes the editor

### ISSUE THREAD

**Issue by JorenJoestar** [OurMachinery/themachinery-public#618]
Hello there, just trying to open project (https://github.com/niklas-ourmachinery/dinosaur-collector) on Windows TM 2021.6.a crashes the editor. I'll add the log and send a crash dump file.
Any more information I can give please let me know!

Thank you :)

The Machinery - Version 2021.6.a
Number of available instance layers: 16
    VK_LAYER_NV_optimus (Description: NVIDIA Optimus layer)
    VK_LAYER_RENDERDOC_Capture (Description: Debugging capture layer for RenderDoc)
    VK_LAYER_NV_nomad_release_public_2020_5_1 (Description: NVIDIA Nsight Graphics interception layer)
    VK_LAYER_NV_GPU_Trace_release_public_2020_5_1 (Description: NVIDIA Nsight Graphics GPU Trace interception layer)
    VK_LAYER_VALVE_steam_overlay (Description: Steam Overlay Layer)
    VK_LAYER_VALVE_steam_fossilize (Description: Steam Pipeline Caching Layer)
    VK_LAYER_EOS_Overlay (Description: Vulkan overlay layer for Epic Online Services)
    VK_LAYER_EOS_Overlay (Description: Vulkan overlay layer for Epic Online Services)
    VK_LAYER_OBS_HOOK (Description: Open Broadcaster Software hook)
    VK_LAYER_OBS_HOOK (Description: Open Broadcaster Software hook)
    VK_LAYER_LUNARG_api_dump (Description: LunarG API dump layer)
    VK_LAYER_LUNARG_device_simulation (Description: LunarG device simulation layer)
    VK_LAYER_LUNARG_gfxreconstruct (Description: GFXReconstruct Capture Layer Version 0.9.2)
    VK_LAYER_KHRONOS_validation (Description: Khronos Validation Layer)
    VK_LAYER_LUNARG_monitor (Description: Execution Monitoring Layer)
    VK_LAYER_LUNARG_screenshot (Description: LunarG image capture layer)

Number of available instance extensions: 13
    VK_KHR_device_group_creation
    VK_KHR_external_fence_capabilities
    VK_KHR_external_memory_capabilities
    VK_KHR_external_semaphore_capabilities
    VK_KHR_get_physical_device_properties2
    VK_KHR_get_surface_capabilities2
    VK_KHR_surface
    VK_KHR_surface_protected_capabilities
    VK_KHR_win32_surface
    VK_EXT_debug_report
    VK_EXT_debug_utils
    VK_EXT_swapchain_colorspace
    VK_NV_external_memory_capabilities

Number of physical devices: 1
Device: 0 Name: GeForce RTX 2070 Super (Discrete GPU)
    Vendor ID: 10de Device ID: 1e91
    Driver Version: 452.6.0.0
    Supported Vulkan Version: 1.2.133

    Number of available device layers: 2
        VK_LAYER_NV_optimus (Description: NVIDIA Optimus layer)
        VK_LAYER_OBS_HOOK (Description: Open Broadcaster Software hook)

    Number of available device extensions: 115
        VK_KHR_16bit_storage
        VK_KHR_8bit_storage
        VK_KHR_bind_memory2
        VK_KHR_buffer_device_address
        VK_KHR_create_renderpass2
        VK_KHR_dedicated_allocation
        VK_KHR_depth_stencil_resolve
        VK_KHR_descriptor_update_template
        VK_KHR_device_group
        VK_KHR_draw_indirect_count
        VK_KHR_driver_properties
        VK_KHR_external_fence
        VK_KHR_external_fence_win32
        VK_KHR_external_memory
        VK_KHR_external_memory_win32
        VK_KHR_external_semaphore
        VK_KHR_external_semaphore_win32
        VK_KHR_get_memory_requirements2
        VK_KHR_image_format_list
        VK_KHR_imageless_framebuffer
        VK_KHR_maintenance1
        VK_KHR_maintenance2
        VK_KHR_maintenance3
        VK_KHR_multiview
        VK_KHR_pipeline_executable_properties
        VK_KHR_push_descriptor
        VK_KHR_relaxed_block_layout
        VK_KHR_sampler_mirror_clamp_to_edge
        VK_KHR_sampler_ycbcr_conversion
        VK_KHR_separate_depth_stencil_layouts
        VK_KHR_shader_atomic_int64
        VK_KHR_shader_clock
        VK_KHR_shader_draw_parameters
        VK_KHR_shader_float16_int8
        VK_KHR_shader_float_controls
        VK_KHR_shader_non_semantic_info
        VK_KHR_shader_subgroup_extended_types
        VK_KHR_spirv_1_4
        VK_KHR_storage_buffer_storage_class
        VK_KHR_swapchain
        VK_KHR_swapchain_mutable_format
        VK_KHR_timeline_semaphore
        VK_KHR_uniform_buffer_standard_layout
        VK_KHR_variable_pointers
        VK_KHR_vulkan_memory_model
        VK_KHR_win32_keyed_mutex
        VK_EXT_blend_operation_advanced
        VK_EXT_buffer_device_address
        VK_EXT_calibrated_timestamps
        VK_EXT_conditional_rendering
        VK_EXT_conservative_rasterization
        VK_EXT_custom_border_color
        VK_EXT_depth_clip_enable
        VK_EXT_depth_range_unrestricted
        VK_EXT_descriptor_indexing
        VK_EXT_discard_rectangles
        VK_EXT_external_memory_host
        VK_EXT_fragment_shader_interlock
        VK_EXT_full_screen_exclusive
        VK_EXT_hdr_metadata
        VK_EXT_host_query_reset
        VK_EXT_index_type_uint8
        VK_EXT_inline_uniform_block
        VK_EXT_line_rasterization
        VK_EXT_memory_budget
        VK_EXT_memory_priority
        VK_EXT_pci_bus_info
        VK_EXT_pipeline_creation_feedback
        VK_EXT_post_depth_coverage
        VK_EXT_sample_locations
        VK_EXT_sampler_filter_minmax
        VK_EXT_scalar_block_layout
        VK_EXT_separate_stencil_usage
        VK_EXT_shader_demote_to_helper_invocation
        VK_EXT_shader_subgroup_ballot
        VK_EXT_shader_subgroup_vote
        VK_EXT_shader_viewport_index_layer
        VK_EXT_subgroup_size_control
        VK_EXT_texel_buffer_alignment
        VK_EXT_tooling_info
        VK_EXT_transform_feedback
        VK_EXT_vertex_attribute_divisor
        VK_EXT_ycbcr_image_arrays
        VK_NV_clip_space_w_scaling
        VK_NV_compute_shader_derivatives
        VK_NV_cooperative_matrix
        VK_NV_corner_sampled_image
        VK_NV_coverage_reduction_mode
        VK_NV_dedicated_allocation
        VK_NV_dedicated_allocation_image_aliasing
        VK_NV_device_diagnostic_checkpoints
        VK_NV_device_diagnostics_config
        VK_NV_external_memory
        VK_NV_external_memory_win32
        VK_NV_fill_rectangle
        VK_NV_fragment_coverage_to_color
        VK_NV_fragment_shader_barycentric
        VK_NV_framebuffer_mixed_samples
        VK_NV_geometry_shader_passthrough
        VK_NV_mesh_shader
        VK_NV_ray_tracing
        VK_NV_representative_fragment_test
        VK_NV_sample_mask_override_coverage
        VK_NV_scissor_exclusive
        VK_NV_shader_image_footprint
        VK_NV_shader_sm_builtins
        VK_NV_shader_subgroup_partitioned
        VK_NV_shading_rate_image
        VK_NV_viewport_array2
        VK_NV_viewport_swizzle
        VK_NV_win32_keyed_mutex
        VK_NVX_binary_import
        VK_NVX_device_generated_commands
        VK_NVX_image_view_handle
        VK_NVX_multiview_per_view_attributes

Number of device groups: 1
    Device Group: 0 Number of physical devices: 1 Supports subset allocation: true
        Physical available_device: 0 Name: GeForce RTX 2070 Super (Discrete GPU)

Hardware accelerated ray tracing is not supported.
Missing features:
    accelerationStructure
    rayTracingPipeline
Loading project DLL tm_dinosaur_simulate-4cbe43686f74ac90.dll.
Core update report
    Created core/creation_graphs/dcc-material-opacity.creation
    Created core/creation_graphs/dcc-mesh-lod-step.creation
    Created core/creation_graphs/dcc-mesh-lod.creation
    Updated core/creation_graphs/dcc-material.creation
    Updated core/creation_graphs/editor-icon.creation
    Updated core/geometry/sphere.entity
    Updated core/sky.entity
c:\work\themachinery\foundation\the_truth.c(545): error: Property type mismatch in `tm_asset`, property `object` is not of type `reference`.

**Comment by raphael-ourmachinery** [comment]
Thanks for reporting! Probably you'll need to rebuild the dll from this project.

**Comment by niklas-ourmachinery** [comment]
Yes the DLLs weren’t built for 2021.6.a, they need to be rebuilt. You can rebuild the DLLs, and replace them in the project by opening the project in safe mode. I’ll do an update of the project at some point in the future to fix it too.

**Comment by JorenJoestar** [comment]
Sounds good - thank you guys :) I think we can close this then - it is just a dll mismatching. Hopefully will be useful for others to read if something similar happens in the future!

**Comment by raphael-ourmachinery** [comment]
Agreed, if you need help to build the project let us know!
