### ISSUE TITLE
Entity From Path node is confusing with unnamned instantiated assets

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#62]
Every *entity* has a *name*, and when we look at the entity tree, that is what we see. If the entity hasn't been given a name we just see `Entity 1116e3dc` or something like that.

However, *entities* that are instantiated from *assets* also have an *asset name* (set in the asset browser). The asset name isn't necessarily the same as the entity name. (The entity name can be overridden, but the asset name can't.)

When an entity doesn't have a name, but it is instantiated from an asset, the Entity Tree helpfully shows the asset name instead of just the ID (`Entity 1116e3dc`):

![image](https://user-images.githubusercontent.com/26548514/72099073-ad4a3a80-32d4-11ea-96f1-33c2ab48e44f.png)

Generally, this is useful, but it can be confusing. For example, the `Entity From Path` allows the user to identify an entity by name. This, however, only works with *entity names*, not with *asset names*. This can be confusing for the user, because the user will see a name in the Entity Tree, and not realize that that is the *asset name* and that the entity doesn't have a name. The user will then be puzzled as to why *Entity From Path* doesn't work.

Potential fixes:

1. `Entity From Path` should work with asset names too. If an entity doesn't have an entity name, it should perform the lookup using the asset name, just as Entity Tree does.

2. Somehow force the entity name and the asset name to be the same.

I think 1 is probably the better solution.

**Comment by Srekel** [comment]
Not sure if this is the same problem or not, but when I override the Light entity in the default_world, it changes name from Light to an "ID" name, like this:

![image](https://user-images.githubusercontent.com/1578924/113410220-2c80ce00-93b3-11eb-8af8-ad50dcd01f7f.png)

I would expect it to keep its name.

**Comment by niklas-ourmachinery** [comment]
Can you report this as a separate issue?

**Comment by karll-ourmachinery** [comment]
Implemented fix `1.` for 2021.4.
