### ISSUE TITLE
Crash when import a gltf file

### ISSUE THREAD

**Issue by quicklyslow** [OurMachinery/themachinery-public#620]
When drag a gltf(https://sketchfab.com/3d-models/vilhelm-13-low-res-textures-cb49a1f71ba54cad8e9dc09da8ef47cd) into tm editor, it crashed, only the first time, could not reproduce. 
Here is the crash dump, sorry I had not use enable-full-dumps so this is not a full dump
Editor version: beta-2021.6.a-windows
[the_machinery_exe 2021-07-12 11.17.14.dmp.zip](https://github.com/OurMachinery/themachinery-public/files/6805242/the_machinery_exe.2021-07-12.11.17.14.dmp.zip)

**Comment by frank-ourmachinery** [comment]
I'm not able to open the dump sadly, but it gives me the option to `Debug with Managed Only` which seems to me that [Assimp](https://github.com/assimp/assimp) itself is crashing. I'm not sure though, but we've had quite a few issues with Assimp before. As you said as well, the model loads fine. I'll leave the issue open so other people can try to open the dump file and figure out where it is crashing.

**Comment by simon-ourmachinery** [comment]
@quicklyslow is this still a issue?

**Comment by quicklyslow** [comment]
I can not reproduce it. so can be closed
