### ISSUE TITLE
Texture thumbnails does not automatically refresh when creation graph is changed.

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#624]
Changed compression setting of a texture, thumbnail did not refresh after compression task completed running.

![image](https://user-images.githubusercontent.com/26548681/125605932-35d57349-0276-41ef-a32a-b63236e411c7.png)

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed for 2021.8 https://github.com/OurMachinery/themachinery/commit/1f3d147f9fbb9d8b8aca8650066651eebdd095e1
