### ISSUE TITLE
Select objects not working after changing tool in Scene tab

### ISSUE THREAD

**Issue by ForxVT** [OurMachinery/themachinery-public#626]
If we try to select (moving while left clicking) objects in the scene viewport to select entities after having changed the current tool (select, move, rotate or scale), nothing happens. To be able to select objects again we have to lose focus of The Machinery window and regain focus of The Machinery window.

https://user-images.githubusercontent.com/12241801/125691648-d76ed0d1-76bc-4be9-96e5-628a7a1f78b3.mp4

Step to reproduce:

- Open The Machinery.
- Select an entity in the viewport (it should work as expected).
- Change the current tool in the toolbar at the top of the tab.
- Select an entity in the viewport (it should **not work** anymore).
- Lose focus of The Machinery window (eg: click on your desktop).
- Regain focus of the Machinery window (eg: click on the window).
- Select an entity in the viewport (it should work as expected).

**Comment by frank-ourmachinery** [comment]
Fixed for next release, the gizmo buttons were setting themselves as active before the actual gizmo was used, making the multi-selection think that a gizmo was in use.
