### ISSUE TITLE
Can't start The Machinery on Windows 11

### ISSUE THREAD

**Issue by Shyclops** [OurMachinery/themachinery-public#628]
I'm running Windows 11 with a GeForce GTX 1660
Attached is my log file
[2021-07-15 20.46.03.log](https://github.com/OurMachinery/themachinery-public/files/6827529/2021-07-15.20.46.03.log)
The following is the discord link to my dmp
https://ptb.discord.com/channels/690290013585408136/779314091990319104/865411545131646986

**Comment by simon-ourmachinery** [comment]
I cannot reproduce the issue. Is the issue still persistent? (I have windows 11) @Shyclops

**Comment by simon-ourmachinery** [comment]
We can reopen the issue if there are more information. We have tested on windows 11 and cannot reproduce this issue.
