### ISSUE TITLE
Graph tab can't be dragged

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#63]
When a graph is open, the Graph Tab can't be dragged.

This was introduced by commit:

* https://github.com/OurMachinery/themachinery/commit/f2902191bba8b424d6316318758cf3445363faa4

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/efd94e95743660ccde7761aba91d641acb6b9dd2
