### ISSUE TITLE
Entering value in Resolution Scale setting repeats keypresses

### ISSUE THREAD

**Issue by ifschleife** [OurMachinery/themachinery-public#631]
When I try to change the value to 2, it will instead enter 222 or something like it.
Which causes the UI to immediately become huge (good that the max is clamped to 4 :)
But I can't even scale it down anymore because entering 1 will enter 111 and get clamped to 4 as well.
Looks like there is a keypress repeat issue or something. Curiously this does not seem to happen in other LineEdits.

**Comment by simon-ourmachinery** [comment]
@ifschleife I seem to be not able to reproduce it. Are you using the source code to build or the prebuild binary version? What operating system are you using?

**Comment by ifschleife** [comment]
I'm using the binary version. Maybe this has been fixed already then but not released?
This is on Windows 10 20H2.

**Comment by simon-ourmachinery** [comment]
@ifschleife yes as it seems it's changed in the source build ... I will keep this open to document it so we can test again before next release.

**Comment by niklas-ourmachinery** [comment]
Fixed for next release.
