### ISSUE TITLE
Changing component data from editor triggers reload?

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#635]
This also confused me when I wrote a simple go-to-destination component. For testing purpose, I was tweaking the destination while the simulation was running. However my character would reset everytime I made a change, which made futher testing difficult. 

On the Discord I was told the component change would trigger a asset reload. How can I keep my transform data alive?

**Comment by simon-ourmachinery** [comment]
related #634

**Comment by simon-ourmachinery** [comment]
This is basically the same as #634
