### ISSUE TITLE
destroy_resource() was called more then once with same handle

### ISSUE THREAD

**Issue by infosia** [OurMachinery/themachinery-public#640]
Relates to #622 and https://github.com/OurMachinery/themachinery/issues/676

I see that the fix above is a workaround to avoid crash. Turns out that it's not just a issue in `runner` but it also happens on the editor. I always get the warning on following project. 100% reproducible for me.

https://github.com/infosia/themachinery-issues/blob/master/0013/project.the_machinery_db

How to reproduce:

1. Download [project.the_machinery_db](https://github.com/infosia/themachinery-issues/blob/master/0013/project.the_machinery_db)
2. Launch the Machinery editor and open downloaded `project.the_machinery_db` (`File->Open Project`)
3. After you see project has been opened in the editor, then close the project (`File->New Project` for instance)

Error message below is shown in the console on `2021.7-dev`. (On the machinery `2021.6.b` it will crash)

```
vulkan_render_backend.c(10495): error: Trying to destroy a resource thas has already been destroyed. tm_renderer_resource_command_buffer_api->destroy_resource() was called more then once with the same handle. Handle: xxx
```

**Comment by tobias-ourmachinery** [comment]
Reproduced. Investigating.
