### ISSUE TITLE
Create an animation from dcc_asset and delete it with out compress will cause the editor crash

### ISSUE THREAD

**Issue by quicklyslow** [OurMachinery/themachinery-public#642]
just like this issus: https://github.com/OurMachinery/themachinery-public/issues/623
but different is that not create a new animation, but create an animation from dcc_asset, and then delete it, will crash the editor, the same place, but the null pointer is "player->playing"

**Comment by simon-ourmachinery** [comment]
@quicklyslow can you make sure that it's now fixed on the latest? If yes  OurMachinery/themachinery#674 fixed it

**Comment by quicklyslow** [comment]
No, just the same place, but not fix because the null pointer is "player->playing"

**Comment by simon-ourmachinery** [comment]
could you provide the DCC asset if possible?

**Comment by quicklyslow** [comment]
I just use gameplay-third-person sample, player/animations/idle.dcc_asset, in fact, any of them is ok.

**Comment by quicklyslow** [comment]
There are two ways I can think to fix this:
 one is changing "if (new_player && player) " to "if(new_player && player && player->playing)". 
 the other is when creating an animation from dcc_asset, auto compress it immediately.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.7
