### ISSUE TITLE
Application settings does not save every changes after exiting.

### ISSUE THREAD

**Issue by ForxVT** [OurMachinery/themachinery-public#644]
The current implementation of a saving system for the applications settings is a task that can only happen after the end of a cooldown session (30 seconds). Which is fine for performances, however, this causes an issue when you modify multiple application settings in a small timespan and just close the-machinery, the save doesn't happen.
I think the ideal way to fix it would be to save the application settings file during the shutdown of the-machinery.

**Comment by leonardo-ourmachinery** [comment]
I agree that we should always save the settings on exit, but we should do that only if some changes actually happened to the settings. I don't want to make the shutdown time longer than necessary.

The code to only do the save if the The Truth version has changed is already there, so the thing that should happen (and is not happening atm) is that when the "last" window is closed we should always do the check to see if the settings have changed.

I'll take a deeper look at this during the day.

**Comment by ForxVT** [comment]
I understand what you mean, I should have done it my PR already, my mistake. I just need to add the if check in my PR if the code is fine for you and it would me done. If you want to make some deeper changes, go ahead.
See: https://github.com/OurMachinery/themachinery/pull/685

**Comment by ForxVT** [comment]
I added the if check in my PR code.

**Comment by leonardo-ourmachinery** [comment]
@ForxVT Your PR has been integrated into master, I'm closing the issue.
Thank you very much for the help.
