### ISSUE TITLE
Engines don't hot-reload?

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#648]
Hot-reloading works for simulation entries well, but I can't make it work for engines.🙁 A simulation-entry however doesn't fit my use-case, since I wan't to operate on any entity with certain components. (I could think of a workaround with tags, but that sounds unnecessarily complicated to me.)

**Comment by niklas-ourmachinery** [comment]
This has been fixed for 2021.7.

When a hot reload happens, we will now automatically query the `TM_ENTITY_SIMULATION_REGISTER_ENGINES_INTERFACE_NAME` interface and update the callback functions of all registered engines and systems.
