### ISSUE TITLE
trying to import from the animation project causes crash

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#649]
Steps:
-trying to import something from the animation project
- try to open the bot folder
Place:
`private__shader_system_cl_evaluate` => `variables == NULL`
![image](https://user-images.githubusercontent.com/70658708/126665802-ff847565-8a92-4be4-8465-42cb4e1392e3.png)

**Comment by tobias-ourmachinery** [comment]
It appears like asset browser used when importing is trying to generate thumbnails.
