### ISSUE TITLE
Functionality necessary for safe wrappers around API pointer tables

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#657]
Currently, function table pointers are updated during a 'safe point' barrier on hot-reload, see relevant discord discussion:
https://discord.com/channels/690290013585408136/690290014202233044/869260626147557487

For providing a completely safe access API in Rust around API function table pointers, they need to be entirely inaccessible during the time they are being overwritten, so that even custom threads in plugins can't accidentally access them at the wrong time.

For this it would be nice to have events a plugin can register to be called at the start and end of hot-reloading, to place locks on resources internally, or pause background threads.

**Comment by LaylBongers** [comment]
Thinking about this more, should be be a callback specifically for hot-reloads, or more specific for API reloads? During plugin loading the APIs won't be available yet regardless of if it's a hot-reload or not, so you want to be notified there as well when the APIs become available.

**Comment by niklas-ourmachinery** [comment]
I think only for hot-reload. For the initial load I think you may want to be notified when all plugins have completed loading which would be a separate mechanism.

**Comment by LaylBongers** [comment]
The main motivation for this request though is being able to lock/unlock API tables within the plugin, which extends beyond just hot-reloading as the APIs should start locked until loading is complete first time as well.
Unless there's another reason to have hot-reloading specifically be captured by events instead, I think that lock/unlock events may be more directly useful, as it stays targeted to this specific use case and communicates the intent of the event well.

**Comment by niklas-ourmachinery** [comment]
Closing this with the "later" tag for now as right now we don't have plans to add this. (May change in the future.)
