### ISSUE TITLE
Node IO with incompatible types can connect

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#659]
Node IO with incompatible types can connect, which makes mistakes harder to spot while working. Perhaps introduce manual conversion nodes instead of coercing automatically between otherwise incompatible IO types?

**Comment by niklas-ourmachinery** [comment]
@tobias-ourmachinery This is specific to creation graphs, right?

**Comment by tobias-ourmachinery** [comment]
@LaylBongers Can you elaborate a bit more on this, what type of graphs and context are you referring to?

**Comment by LaylBongers** [comment]
Checking the editor again, I'm seeing that they actually do *not* connect in most cases, I think I just encountered a bug where some incompatible types connected. Specifically GPU shader values seem to be able to connect even if incompatible. This is already covered in #359 so I'll close this issue.
