### ISSUE TITLE
Opening a new window will occasionally result in a Vulkan crash

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#66]
```
res = vkCreateSwapchainKHR(d->device, sc_info, vb->vk_allocation_callbacks, &sc.swap_chain);
```

fails with `VK_ERROR_INITIALIZATION_FAILED`.

I don't currently have exact repro steps to make this happen, but I've seen it a number of times.

**Comment by niklas-ourmachinery** [comment]
Details: It happens when I open the Animation State Machine window by double-clicking an `.asm` asset... but I can't seem to provoke it by opening and closing the ASM window ten times.

**Comment by frank-ourmachinery** [comment]
@niklas-ourmachinery does this still happen?

**Comment by niklas-ourmachinery** [comment]
I haven't seen this in a long time. Will close it.
