### ISSUE TITLE
display_name is only used on output connectors.

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#67]
If specified, `tm_graph_connector_t::display_name` should be used instead of `tm_graph_connector_t::name` when rendering the labels of node connectors. This works for output connectors but not for input connectors, probably related to the refactoring of the node rendering.

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/f1e8154074f3622d5caa2e75aa1de235142cfd0f
