### ISSUE TITLE
2021.7 and 2021.6.b - opening a second project (or reloading the current) causes "depth" artifacts

### ISSUE THREAD

**Issue by creadmefford** [OurMachinery/themachinery-public#670]
- start TM and open a sample project -- everything looks fine.
- open a second sample (or reload the current) and visual depth artifacts appear.
- I've only seen this on my AMD Radeon based desktop and not on my NVIDIA based laptop or desktop.
- I have the latest AMD drivers.

first launch: (everything is normal)

![image](https://user-images.githubusercontent.com/976243/127680073-7357181f-f8b7-4d8c-8739-b1b0de1d61a6.png)

after reload:
![image](https://user-images.githubusercontent.com/976243/127679998-9937287c-3f2a-4919-aa4a-5822de7f7cf5.png)

AMD driver version:
![image](https://user-images.githubusercontent.com/976243/127680459-930d2ec7-6364-4b26-9a9d-1a3f3e0707bf.png)

From windows 10 sysinfo:
Name	Radeon RX 580 Series
PNP Device ID	PCI\VEN_1002&DEV_67DF&SUBSYS_C5801682&REV_E7\6&128C7FE0&0&0010000A
Adapter Type	AMD Radeon Graphics Processor (0x67DF), Advanced Micro Devices, Inc. compatible
Adapter Description	Radeon RX 580 Series
Adapter RAM	(1,048,576) bytes
Installed Drivers	C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\aticfx64.dll,C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\aticfx64.dll,C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\aticfx64.dll,C:\Windows\System32\DriverStore\FileRepository\u0368925.inf_amd64_05ef22929fd9ebfc\B368707\amdxc64.dll
Driver Version	27.20.22001.14011
INF File	oem28.inf (ati2mtag_Polaris10 section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	3840 x 2160 x 60 hertz
Bits/Pixel	32
Memory Address	0xD0000000-0xE01FFFFF
Memory Address	0xE0000000-0xE01FFFFF
I/O Port	0x0000FF00-0x0000FFFF
Memory Address	0xFCA00000-0xFCAFFFFF
IRQ Channel	IRQ 4294967263
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\U0368925.INF_AMD64_05EF22929FD9EBFC\B368707\AMDKMDAG.SYS (27.20.22001.14011, 77.82 MB (81,597,776 bytes), 7/2/2021 10:35 AM)

**Comment by creadmefford** [comment]
actually graphical issues appear in both the scene view and simulate tabs:
![image](https://user-images.githubusercontent.com/976243/128224729-6625fe7b-def8-4778-96c6-46058950e769.png)

**Comment by tobias-ourmachinery** [comment]
@creadmefford Can't reproduce this internally on our AMD hardware. Can you verify if the problem remains with the latest Radeon drivers (21.9.2)? 

If it does, and if you have the time, it would be great if you could install the Vulkan SDK and launch the machinery with the command line argument `--vulkan-validation` to see if you get any validation warnings in the log when this starts happening. Thanks!

**Comment by creadmefford** [comment]
dang.  i'm out of town until October 7th but will retest this then and report back.  thanks for looking into it!

**Comment by creadmefford** [comment]
- load sample "first person" and it mostly works (there are a few flickers in the yellow selection box but overall things look normal)
- reload the sample and everything turns black or multicolored. 
- load the dungeon kit and it's all black and i see the following errors:
![image](https://user-images.githubusercontent.com/976243/136142081-35dd4866-5498-456b-957c-b2fa7f9b8313.png)

**Comment by creadmefford** [comment]
here is the console output from starting up the engine in case this is useful:


C:\Users\cread\OneDrive\Desktop\the-machinery-2021.9-windows\bin>the-machinery.exe --vulkan-validation

C:\Users\cread\OneDrive\Desktop\the-machinery-2021.9-windows\bin>The Machinery - Version 2021.9
Number of available instance layers: 13
    VK_LAYER_AMD_switchable_graphics (Description: AMD switchable graphics layer)
    VK_LAYER_RENDERDOC_Capture (Description: Debugging capture layer for RenderDoc)
    VK_LAYER_VALVE_steam_overlay (Description: Steam Overlay Layer)
    VK_LAYER_VALVE_steam_fossilize (Description: Steam Pipeline Caching Layer)
    VK_LAYER_EOS_Overlay (Description: Vulkan overlay layer for Epic Online Services)
    VK_LAYER_EOS_Overlay (Description: Vulkan overlay layer for Epic Online Services)
    VK_LAYER_LUNARG_api_dump (Description: LunarG API dump layer)
    VK_LAYER_LUNARG_device_simulation (Description: LunarG device simulation layer)
    VK_LAYER_LUNARG_gfxreconstruct (Description: GFXReconstruct Capture Layer Version 0.9.9)
    VK_LAYER_KHRONOS_synchronization2 (Description: Khronos Synchronization2 layer)
    VK_LAYER_KHRONOS_validation (Description: Khronos Validation Layer)
    VK_LAYER_LUNARG_monitor (Description: Execution Monitoring Layer)
    VK_LAYER_LUNARG_screenshot (Description: LunarG image capture layer)

Number of available instance extensions: 11
    VK_KHR_device_group_creation
    VK_KHR_external_fence_capabilities
    VK_KHR_external_memory_capabilities
    VK_KHR_external_semaphore_capabilities
    VK_KHR_get_physical_device_properties2
    VK_KHR_get_surface_capabilities2
    VK_KHR_surface
    VK_KHR_win32_surface
    VK_EXT_debug_report
    VK_EXT_debug_utils
    VK_EXT_swapchain_colorspace

Number of physical devices: 1
Device: 0 Name: Radeon RX 580 Series (Discrete GPU)
    Vendor ID: 1002 Device ID: 67df
    Driver Version: 2.0.193
    Supported Vulkan Version: 1.2.182

    Number of available device layers: 2
        VK_LAYER_AMD_switchable_graphics (Description: AMD switchable graphics layer)
        VK_LAYER_KHRONOS_validation (Description: Khronos Validation Layer)

    Number of available device extensions: 110
        VK_KHR_16bit_storage
        VK_KHR_8bit_storage
        VK_KHR_bind_memory2
        VK_KHR_buffer_device_address
        VK_KHR_copy_commands2
        VK_KHR_create_renderpass2
        VK_KHR_dedicated_allocation
        VK_KHR_depth_stencil_resolve
        VK_KHR_descriptor_update_template
        VK_KHR_device_group
        VK_KHR_draw_indirect_count
        VK_KHR_driver_properties
        VK_KHR_external_fence
        VK_KHR_external_fence_win32
        VK_KHR_external_memory
        VK_KHR_external_memory_win32
        VK_KHR_external_semaphore
        VK_KHR_external_semaphore_win32
        VK_KHR_get_memory_requirements2
        VK_KHR_imageless_framebuffer
        VK_KHR_image_format_list
        VK_KHR_maintenance1
        VK_KHR_maintenance2
        VK_KHR_maintenance3
        VK_KHR_multiview
        VK_KHR_pipeline_executable_properties
        VK_KHR_relaxed_block_layout
        VK_KHR_sampler_mirror_clamp_to_edge
        VK_KHR_sampler_ycbcr_conversion
        VK_KHR_separate_depth_stencil_layouts
        VK_KHR_shader_atomic_int64
        VK_KHR_shader_clock
        VK_KHR_shader_draw_parameters
        VK_KHR_shader_float16_int8
        VK_KHR_shader_float_controls
        VK_KHR_shader_non_semantic_info
        VK_KHR_shader_subgroup_extended_types
        VK_KHR_shader_subgroup_uniform_control_flow
        VK_KHR_shader_terminate_invocation
        VK_KHR_spirv_1_4
        VK_KHR_storage_buffer_storage_class
        VK_KHR_swapchain
        VK_KHR_swapchain_mutable_format
        VK_KHR_synchronization2
        VK_KHR_timeline_semaphore
        VK_KHR_uniform_buffer_standard_layout
        VK_KHR_variable_pointers
        VK_KHR_vulkan_memory_model
        VK_KHR_win32_keyed_mutex
        VK_EXT_4444_formats
        VK_EXT_calibrated_timestamps
        VK_EXT_color_write_enable
        VK_EXT_custom_border_color
        VK_EXT_depth_clip_enable
        VK_EXT_depth_range_unrestricted
        VK_EXT_descriptor_indexing
        VK_EXT_extended_dynamic_state
        VK_EXT_extended_dynamic_state2
        VK_EXT_external_memory_host
        VK_EXT_full_screen_exclusive
        VK_EXT_global_priority
        VK_EXT_hdr_metadata
        VK_EXT_host_query_reset
        VK_EXT_image_robustness
        VK_EXT_inline_uniform_block
        VK_EXT_line_rasterization
        VK_EXT_memory_budget
        VK_EXT_memory_priority
        VK_EXT_pipeline_creation_cache_control
        VK_EXT_pipeline_creation_feedback
        VK_EXT_private_data
        VK_EXT_queue_family_foreign
        VK_EXT_robustness2
        VK_EXT_sampler_filter_minmax
        VK_EXT_sample_locations
        VK_EXT_scalar_block_layout
        VK_EXT_separate_stencil_usage
        VK_EXT_shader_demote_to_helper_invocation
        VK_EXT_shader_image_atomic_int64
        VK_EXT_shader_stencil_export
        VK_EXT_shader_subgroup_ballot
        VK_EXT_shader_subgroup_vote
        VK_EXT_shader_viewport_index_layer
        VK_EXT_subgroup_size_control
        VK_EXT_texel_buffer_alignment
        VK_EXT_tooling_info
        VK_EXT_transform_feedback
        VK_EXT_vertex_attribute_divisor
        VK_AMD_buffer_marker
        VK_AMD_calibrated_timestamps
        VK_AMD_display_native_hdr
        VK_AMD_draw_indirect_count
        VK_AMD_gcn_shader
        VK_AMD_gpa_interface
        VK_AMD_memory_overallocation_behavior
        VK_AMD_mixed_attachment_samples
        VK_AMD_pipeline_compiler_control
        VK_AMD_rasterization_order
        VK_AMD_shader_ballot
        VK_AMD_shader_core_properties
        VK_AMD_shader_core_properties2
        VK_AMD_shader_explicit_vertex_parameter
        VK_AMD_shader_fragment_mask
        VK_AMD_shader_image_load_store_lod
        VK_AMD_shader_info
        VK_AMD_shader_trinary_minmax
        VK_AMD_wave_limits
        VK_GOOGLE_decorate_string
        VK_GOOGLE_hlsl_functionality1
        VK_GOOGLE_user_type

Number of device groups: 1
    Device Group: 0 Number of physical devices: 1 Supports subset allocation: false
        Physical available_device: 0 Name: Radeon RX 580 Series (Discrete GPU)

Hardware accelerated ray tracing is not supported.
Missing features:
    accelerationStructure
    descriptorBindingAccelerationStructureUpdateAfterBind
    bufferDeviceAddress or accelerationStructureHostCommands
    rayTracingPipeline

**Comment by creadmefford** [comment]
it says i'm on the latest AMD with **21.8.2** (you mention 21.9.2 which does not appear to be available to me yet)
![image](https://user-images.githubusercontent.com/976243/136142252-2a38dbb4-373d-4adf-9aa4-1827ce1da95a.png)

**Comment by creadmefford** [comment]
i can no longer repro this very annoying issue on Radeon 21.10.2 and our machinery 2021.10.a!  thanks!
