### ISSUE TITLE
startup system/engine to run before all other systems once

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#677]
bevy has a nice way of providing a system that can run before all other systems. It's called startup systems. This can be very handy when it comes to solving issues or setting up scenes/data at the beginning of the simulation live time.

```rust
fn main() {
    App::build()
        .add_startup_system(add_people.system())
        .add_system(hello_world.system())
        .run();
}
```

This is what bevy has and it's pretty useful.

This way we could provide a alternative to a simulate entry in form of the ECS which can run always hence plugins can register setup systems for their own stuff.

**Comment by simon-ourmachinery** [comment]
Pseudo code:
```
tm_add_or_remove_implementation(reg, load, TM_ENTITY_SIMULATION_REGISTER_SETUP_SYSTEM_INTERFACE_NAME, entity_simulation_setup__register);
```

**Comment by LaylBongers** [comment]
My use case for this feature is a scripting plugin that needs to load in all the scripts when simulation starts, fetching the script files from the truth and loading the modules.

**Comment by simon-ourmachinery** [comment]
A simulate entry would require the user to create an asset and select the correct entry as well. With this, the plugin could just register itself.

**Comment by simon-ourmachinery** [comment]
Having 2 main phases here would be good:

- 1 before a scene is loaded
- 2 after scene is loaded
