### ISSUE TITLE
Engine stops processing input after opening a file browser

### ISSUE THREAD

**Issue by Arazu161** [OurMachinery/themachinery-public#68]
After opening and then closing a file browser (either through "open project" or "save-as", or similar) the ui _appears_ to freeze and no longer registers input events.

The engine itself continues to run, any viewports and "simulate" tabs update, but any input such as mouse clicks/mouse position and keyboard shortcuts no longer do anything.

The input log stops updating with events, but characters/numbers/symbols do register as "text". Modifier keys such as ctrl and alt do not register.

The editor window can be moved and resized, but must be closed through the taskbar or taskmanager

**Comment by Arazu161** [comment]
This appears to have resolved itself, although nothing has changed so I'm not sure what has fixed it. I don't even think I have restarted my pc in between it not working, and working again. I suppose it is possible an unknown process was causing issues, but I'm not sure I'll ever be able to find out what the cause was.

Hopefully it won't come up again.

**Comment by niklas-ourmachinery** [comment]
Oh that's great... I wonder what it was.

Will close this for now... reopen or create a new bug if it appears again.
