### ISSUE TITLE
Blackboard operations are not thread-safe

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#681]
Setting or retrieving a blackboard ptr using `set_blackboard_ptr` and `get_blackboard_ptr` is not thread safe, and will cause access violation crashes occasionally if done from two threads at the same time.

This happens for example if you access the blackboard from within a node run during an `Init Event`.

**Comment by simon-ourmachinery** [comment]
uncommenting line: 1012-1021 helps since the delta time etc is not anymore written to the blackboards.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.8
