### ISSUE TITLE
Gizmo nullptr crash when changing mode while active

### ISSUE THREAD

**Issue by Nomoresleep** [OurMachinery/themachinery-public#682]
When editing an entities transform component with the gizmo and switching the mode (by pressing keyboard shortcuts for translate/rotate/scale w/e/r respectively) from:

1. translate to rotate
2. translate to scale
3. rotate to scale

The application runs into an nullptr crash as it can't find an active scale_active_t/rotate_active_t and the return value of tm_ui_api::is_active is not checked for such a case.

Issue is present on the latest 2021.8-dev version of The Machinery and can be easily reproduced in an empty project with the sky entity.

**Comment by frank-ourmachinery** [comment]
Fixed.
