### ISSUE TITLE
Regular UI controls mouse input doesn't work within grid view node properties

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#684]
I created a node with a static input wire, set to a truth type that implements `custom_subobject_ui` on the `tm_properties_aspect_i` aspect. When adding a button to this callback, the button renders, but clicking it only briefly flashes the button active color (doesn't hold) and the click isn't registered. It does work in the properties panel, but not in the grid view.

**Comment by LaylBongers** [comment]
Additional information: the `tm_properties_view_api` components do seem to work.

**Comment by karl-zylinski-ourmachinery** [comment]
Should be fixed in https://github.com/OurMachinery/themachinery/commit/cf88556eb6a8dfff0c347a0d7bf64a33b269b8b1 and later in 2021.8
