### ISSUE TITLE
Be more clear about canceled builds in tmbuild

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#686]
(Nit) I was building the release package (``release-package.json``) from the source repo and was wondering why I coudn't find a folder where the build went. Since I never did a full build with tmbuild, It wasn't clear to me that the build proccess actually didn't finished and halted uppon ``tmbuild: Environment variable `TM_OURMACHINERY_COM_DIR` is not set``. I guess, it would be nice for new users to be a bit more verbose about this, just something like `Build canceled`. 🙂

**Comment by simon-ourmachinery** [comment]
Thanks for your feedback! Just a warning `release-package.json` is mainly used for us internally. I understand your issue! I would recommend using tmbuild regularly to build to ensure that unit tests are run! Since they are always executed at the end of every build/build step.

**Comment by julhe** [comment]
Just to add some context why I initially had to use the source build: I was investigating some wierd C errors when generating a custom node, and I susspected that it was due to TM_SDK_DIR pointing at version 2021.6, but I was using tools from 2021.7. (Turned out the isssue was something different.)

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.8 -- added an explicit `*** BUILD FAILED ***` message.
