### ISSUE TITLE
Deleting the last truth object of a type if referenced by a graph node crashes the editor

### ISSUE THREAD

**Issue by LaylBongers** [OurMachinery/themachinery-public#689]
I have a node that references a type defined within an asset. When I delete the last entry in that asset, the editor crashes as it cannot find an element to replace it with.
As a side-note I would personally prefer it if a selected reference were deleted that the property defaults to no-selection.

**Comment by simon-ourmachinery** [comment]
Could you provide a dump file? Could you provide a image of the node?

**Comment by LaylBongers** [comment]
Here is the node:
![the-machinery_Ir6BcNRhhg](https://user-images.githubusercontent.com/3094382/128215744-7b3b7bf6-8ad3-4548-97f4-d97be5b29228.png)

And the properties of the object that contains the objects being referenced:
![the-machinery_ngK99a3iVI](https://user-images.githubusercontent.com/3094382/128215796-40593ce6-74e9-4441-98d8-c7adea4ea8f8.png)

When "startup" here is deleted it produces the following crash:
[the_machinery_exe 2021-08-04 18.08.07.zip](https://github.com/OurMachinery/themachinery-public/files/6932736/the_machinery_exe.2021-08-04.18.08.07.zip)

**Comment by simon-ourmachinery** [comment]
Is it build against the binary version of the engine or against a source build?

**Comment by LaylBongers** [comment]
This is against the binary version, 2021.7

**Comment by niklas-ourmachinery** [comment]
If you delete a referenced object, that reference should turn into a nil-reference:

![delete-reference](https://user-images.githubusercontent.com/26548514/128580451-8a414831-a938-4636-96ee-7ce6ede491c6.gif)

I don't fully understand your repro case though... is this what you are doing, or something else?

I also couldn't get the call stack from the crash dump, I get `[Frames may be missing, no binary loaded for tm_celphase_deno.tm_hot_reload.dll]`.

Can you give me the call stack of the crash.

**Comment by LaylBongers** [comment]
This "(none)" option doesn't seem to exist in my dropdown by default. I'm using `ui_reference_popup_picker`, is that correct? Should I be using something else, or turning something on to get the "(none)" option? I'll get a callstack when I've got some time to look at it.

**Comment by niklas-ourmachinery** [comment]
You should be able to use `ui_reference_popup_picker()`.

The `(none)` option isn't added automatically, you have to add it yourself by having an explicit `(none)` item that maps to `(tm_tt_id_t){0}`.

If `ui_reference_popup_picker()` can't find the reference in the list of references, it defaults to using the first one... so by having `(none)` be the first reference, that becomes the default if the referenced object is deleted.  This is normally what you want. I'll add a note about this to the documentation.

I tried to reproduce your crash by removing the `(none)` element from one of my reference pickers, but I still couldn't get it to crash, so if you can get me the crash details that would be helpful.
