### ISSUE TITLE
Non-empty focused graph view cannot be closed

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#69]
When using a non-empty graph editor view, it cannot be closed by using the mouse to close the tab. Additionally, when the graph view is focused, no other view can be closed without being focused first. However, the Ctrl+W shortcut still works.

Also, a non-empty focused graph view cannot either be grabbed and moved around in the editor.

**Comment by karl-ourmachinery** [comment]
Hi, thanks for the bug report. This has been fixed, but we have not yet released a build containing the fix.
