### ISSUE TITLE
Add more math helpers.

### ISSUE THREAD

**Issue by ProtonGustave** [OurMachinery/themachinery-public#692]
Would be nice to have:

vec2, vec3:
- angle_to(vector): float - angle to given vector(ref: https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3-method-angle-to)
- rotation(vector): tm_vec4_t - rotation of vector(ref: https://docs.unrealengine.com/4.26/en-US/API/Runtime/Core/Math/FVector/Rotation/)
- distance_to(vector) - distance to given vector, right now there is only squared distance

quat:
- look_at(vec3 from, vec3 to, vec3 up): quat - return a quat which after applying it to "from" will rotate it towards "to"

mat44:
- basis_from_mat44(vec3* x, vec3* y, vec3* z, mat44)/xyz_from_mat44 - right now there is only xyz_from_quaternion

**Comment by julhe** [comment]
For look at, I would use `look_at(vec3 forward, vec3 up): mat44` as this is the most basic form (to my knowledge).
Also a `transpose(): mat44` would be usefull. 🙂

**Comment by ProtonGustave** [comment]
@julhe not sure how to use it, can you provide example?

Example for my option:
We have 2 entities(A and B), we need A to look at B, we take A position, B position, up vector({0,1,0} for example), then we get quat, apply this quat to A(with tm_set_rotation) and A will be looking at B.

**Comment by julhe** [comment]
> @julhe not sure how to use it, can you provide example?

This is from my personal math helper header (haven't check for correct orientation yet but it works for my meshes):
```C
tm_mat44_t tm_mat44_look_at(tm_vec3_t forward, tm_vec3_t up) {
    tm_vec3_t right = tm_vec3_normalize(tm_vec3_cross(up, forward));
    return (tm_mat44_t) {
        right.x     , right.y   , right.z   , 0,
        up.x        , up.y      , up.z      , 0,
        forward.x   , forward.y , forward.z , 0,
        0           , 0         , 0         , 1
    };
}
```

So, from my (stackoverflow) resarch, the safest methode for look-at is build a rotation matrix and convert it afterwards into a quaternion (via `tm_mat44_to_quaternion` for example). Also In some cases, you might already have a normalized look direction, therefore just `forward` and `up` as a parameter.

**Comment by simon-ourmachinery** [comment]
> > @julhe not sure how to use it, can you provide example?
> 
> This is from my personal math helper header (haven't check for correct orientation yet but it works for my meshes):
> 
> ```c
> tm_mat44_t tm_mat44_look_at(tm_vec3_t forward_norm, tm_vec3_t up_norm) {
>     tm_vec3_t right = tm_vec3_normalize(tm_vec3_cross(up_norm, forward_norm));
>     return (tm_mat44_t) {
>         right.x          , right.y        , right.z        , 0,
>         up_norm.x        , up_norm.y      , up_norm.z      , 0,
>         forward_norm.x   , forward_norm.y , forward_norm.z , 0,
>         0                , 0              , 0              , 1
>     };
> }
> ```
> 
> So, from my (stackoverflow) resarch, the safest methode for look-at is build a rotation matrix and convert it afterwards into a quaternion (via `tm_mat44_to_quaternion` for example). Also, in some cases, you might already have a normalized look direction, therefore just `forward_norm` and `up_norm` as a parameter.
> 
> Usage would be:
> 
> ```c
> tm_vec3_t forward = tm_vec3_sub(target, eye);
> tm_mat44_t look_at = tm_mat44_look_at(tm_normalize(forward) , up);
> transform[i].world.rot = tm_mat44_to_quaternion(&look_at);
> ```

Maybe worth a PR? your helpers?

**Comment by frank-ourmachinery** [comment]
I added a couple of new functions today:
- `tm_vec2_dist`, `tm_vec3_dist`, and `tm_vec4_dist`.
- `tm_mat44_transpose`.
- `tm_quaternion_from_direction`.

@ProtonGustave you could already get the basis functions from a `tm_mat44_t` using the `tm_mat44_x`, `tm_mat44_y`, and `tm_mat44_z` functions, so I don't think adding a function that combines those is all that useful.

@julhe I left some comments on the pull request for the `look_at` function.
