### ISSUE TITLE
Entity Tree View: Add Component (Space) does only work once

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#699]
After being used once it does not work anymore. CTRL+ Space as well.

**Comment by leonardo-ourmachinery** [comment]
I fixed the problem with Space and SHIFT + Space. (The Context Menus weren't clearing the responder chain).
Though I'm not seeing any problem with CTRL + Space. (It makes sense as it doesn't open any menu, so I'm assuming you meant Shift + Space instead, which is "create child entity from asset").

Fixed for 2021.08, feel free to reopen if there was really a problem with CTRL + Space.

**Comment by simon-ourmachinery** [comment]
yes that was what I meant XD
