### ISSUE TITLE
Crash when DDS texture is loaded using Creation Graph

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#70]
Attempt to load and display a volume DDS texture with 3 slices using a creation graph immediately freeze and crashes the editor. The texture appears valid according to RenderDoc and `texdiag`.

![graph](https://user-images.githubusercontent.com/3429723/72667896-f874f380-3a20-11ea-9897-d1d76647ab4e.PNG)

The used texture can be retrieved here: [texture.zip](https://github.com/OurMachinery/themachinery-public/files/4081200/texture.zip)

**Comment by tobias-ourmachinery** [comment]
Reproduced and fixed in our master branch. Fix in next version.
