### ISSUE TITLE
Picker popup size limit - Adding Scrolling

### ISSUE THREAD

**Issue by ProtonGustave** [OurMachinery/themachinery-public#703]
Right now picker popup size is limited by this variable
`enum { TM_FIND_PATH_MATCHES_COUNT = 20 }`
i.e. just 20 items, which is fairly low. Need to add scroll there i guess

**Comment by simon-ourmachinery** [comment]
generally speaking yes we need to add Scrolling. Besides this from a UI /UX perspective a user can mainly remeber 7-9 items so maybe reducing the amount of visible items to 7-9 and add scrolling.

**Comment by niklas-ourmachinery** [comment]
I think that would be a misapplication of the 7-9 rule. It's fine to show a list with more than 9 items -- the user does not need to remember all these items, they are scanning the list sequentially.

In fact, we could probably allow more than 20 items in the list (even without scrolling). If we look at what other programs do, Visual Studio Code seems to limit the list to about 50 % of the screen height... so depending on how big your screen is, you will get more items in the list. We could do something similar.

Showing more items with scrolling would probably be helpful too... though I think there's probably a limit at some point... i.e. scrolling through >1000 items is going to be annoying, so we don't really need to support that.

**Comment by simon-ourmachinery** [comment]
Fair enough. When you look at the Web most applications show 7-9 items in their lists. For example, GitHub when it comes to issues or linking  #people, but they provide auto filtering based on typing.

> In fact, we could probably allow more than 20 items in the list (even without scrolling). If we look at what other programs do, Visual Studio Code seems to limit the list to about 50 % of the screen height... so depending on how big your screen is, you will get more items in the list. We could do something similar.

I think this in combination with scrolling might be good so that if let's say you have more than 20 items you get a scrollbar.

I think we should support typing always in dropdown menus as well (since this is about popup pickers its build-in there).

**Comment by huseyin-ourmachinery** [comment]
We might have some problems with the search algorithm. I believe letter keys are more prioritized, so they show up on top of the suggestion list in the "Pull Key" entity graph node. E.g. W, A, S, D. But some letter keys don't show up on the list at all. E.g. E, T, N

**Comment by simon-ourmachinery** [comment]
> We might have some problems with the search algorithm. I believe letter keys are more prioritized, so they show up on top of the suggestion list in the "Pull Key" entity graph node. E.g. W, A, S, D. But some letter keys don't show up on the list at all. E.g. E, T, N

This is due to the limit of 20 items and no scrollbar

**Comment by simon-ourmachinery** [comment]
Extra UX issue:
> hello! i've started poking at the machinery, and figured i'd try the Publish part to make an exe of the Animation sample > project, but I can't figure out what to pick in World Entity?
i've tried a couple different ones but it either just shows a grey screen when running the exe or just closes instantly

See Discord

**Comment by simon-ourmachinery** [comment]
Related #46

**Comment by frank-ourmachinery** [comment]
There is now a "windowed" version of the path matching algorithm (`tm_find_path_matches_windowed`) that allows for scrolling type behaviour. This is implemented in the textedit popup item pickers. So they can scroll, see #891 for an example of this.
