### ISSUE TITLE
Importing a texture asset crashes the editor in Ubuntu

### ISSUE THREAD

**Issue by Polyrhythm** [OurMachinery/themachinery-public#704]
Title pretty much says it. If I drag and drop an image into the scene tab or asset browser, the editor crashes on Ubuntu.
Built from source.

Also, on re-opening the editor, my last opened project has the scene hierarchy wiped out (i.e., no `world` entity).

**Comment by Polyrhythm** [comment]
I think this might be related to https://github.com/OurMachinery/themachinery-public/issues/674.
I am getting some strange `sudo` related behavior.

**Comment by Polyrhythm** [comment]
Reopening because I debugged and found more info.

Importing assets of any kind tends to crash the editor here:
`plugins/os_window/os_window.linux.c`

Specifically:
740: `finished.window = msg_ev->data.data32[0];`
or 
746: `xcb_send_event(window->connection, 1, msg_ev->data.data32[0], XCB_EVENT_MASK_NO_EVENT, (char *)&finished);`

It seems that `msg_ev->data.data32[0]` is often a null pointer.

**Comment by simon-ourmachinery** [comment]
Thank you for your report. @raphael-ourmachinery will investigate this for you!

Please keep in mind that those kinds of source code-related issues are sometimes better to be opened in the private one. Currently, it does not matter but at one point it does!

**Comment by raphael-ourmachinery** [comment]
Fixed on master. Thanks for report that, I wonder if that's could be related to wayland xorg client.
