### ISSUE TITLE
Scene Tab Ctrl + D unexpected behavior

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#705]
When using CTRL + D in the Scene Tab the coordinates of the Duplicated items seem to be random or not where to be expected. 

Lil feature request: Maybe looking ad Blender would be cool and add a way to move items only on the Axis if needed with a line implemented.

**Comment by niklas-ourmachinery** [comment]
*Duplicate* tries to find the offset from the last duplicate operation and then apply that to the new one.

I.e., you can make repeated copies of an element by first creating a duplicate, moving it to where you want and then keep pressing Ctrl +D to create more duplicates:

![image](https://user-images.githubusercontent.com/26548514/130128288-8ffe4a22-80f8-4d94-9c74-ee146bc03e5b.png)

If no existing duplicate operation could be found to get the transform from, duplicate will just move the copy 1m in the X direction.

Is it behaving differently than this or do you think this is not a good behavior?

**Comment by simon-ourmachinery** [comment]
At its core, it is a cool concept, just unexpected. Since I expected the spawn in my object like I usually know it from other Engines and Blender. In unity/Blender for example when you duplicate it just spawns at the same location and you have to move it up. In Blender and Unity, you can then drag it to the location you want it. This is what I personally considered as the default.

I personally like this better: What blender is doing
https://youtu.be/AVwiC_gxuAI

**Comment by karll-ourmachinery** [comment]
I like a lot the "predictive" duplicate behavior, but I relate to Simon's point, it is confusing sometimes as the user needs to do more than one duplicate to see the behavior. 

There is probably a less confusing way to have this feature. I love the feature, as duplicating and moving all the time is annoying when you want to have a lot of copies. we could have a new default behavior (Blender style) and come up with a new approach to  solve the problems the current behavior is solving.

**Comment by simon-ourmachinery** [comment]
I agree with you. I think it would be a good extra node or something. With
a predictable UX.

**Comment by niklas-ourmachinery** [comment]
I'm not super sold on having additional keystrokes for the user to remember, so I did it in a different way.

The duplicate transform is only applied if the user is duplicating the same object that was the result of the last duplicate operation.

AND less than 5 minutes has passed since the last duplicate operation.

I think this is a good compromise of having Duplicate working automatically most of the time, but not doing anything weird when you don't want it to.
