### ISSUE TITLE
Multi Select UI can cause crash in Entity Tree View

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#706]
In a multi-select UI of multiple 100 objects, the editor might crash in the look-up function of the truth. I suspect this has something todo with the multi-threaded UI of the Entity Tree View. See #698 for the dump file

**Comment by leonardo-ourmachinery** [comment]
Yesterday I was able to get the crash a couple of times by simply creating and duplicating a cube entity from the core folder a thousand times or so and then trying to select all of them via the scene tab.
Today I wanted to try to investigate the problem more but I'm currently unable to repro the crash.

Anyway, @niklas-ourmachinery, yesterday I tried to debug it a bit and it seemed like it may actually be related to multithreading, as there was memory filled with garbage that was supposed to be valid memory.

**Comment by leonardo-ourmachinery** [comment]
Fixed for 2020.08.

@niklas-ourmachinery @karl-zylinski-ourmachinery (?) when you have time, can you take a quick look at https://github.com/OurMachinery/themachinery/commit/33ba08d816feb3895fd9e0bfd063a6dd2867e50d
and see if that's the right fix? (I'm not able to repro the crash anymore, but it was hard to repro it even before the fix so...)

**Comment by niklas-ourmachinery** [comment]
I think it's the right fix...

But `proxy_to_objects()` seems a bit dangerous, since the returned array can easily be invalidated. Maybe we need to change the function signature.
