### ISSUE TITLE
Animations perf issue: in task blend

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#707]
When copying the Y Bot in the animation sample project more than 100 times. In my test 1000 times, the fps drops between 2-5. A view in the profiles shows its the blend task which takes up to 144ms. I have attached a trace of the profiler as well as my animation project. Loading times are also really bad.
[load_trace.zip](https://github.com/OurMachinery/themachinery-public/files/6954005/load_trace.zip)

![image](https://user-images.githubusercontent.com/70658708/128697182-69dcaec6-dd55-4b5e-8523-4b67714ca49f.png)

[blend_task.zip](https://github.com/OurMachinery/themachinery-public/files/6953972/blend_task.zip)

[animation.zip](https://github.com/OurMachinery/themachinery-public/files/6953995/animation.zip)

**Comment by niklas-ourmachinery** [comment]
I identified a performance bug in `private__tick_blend_task()`.

Fixing it significantly improved the performance (about x50). A scene with 100 bots now runs without problems. A scene with 1000 bots is still pretty slow, but it is render bound. (Also updating the physics of 1000 character controllers is expensive.)

Fixed for 2021.8.
