### ISSUE TITLE
[UX] Improve Camera view setup workflow

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#714]
There should be an easier way to setup a camera's view.  One would expect to select the camera and see a preview or be able to drive the camera after selecting it in a Scene's camera menu. A workaround is to create a new Scene tab, select the camera for that tab, then adjust the camera from another Scene tab.

https://user-images.githubusercontent.com/27040/128961693-7454ade6-3dbe-416a-bffb-8a07c6b07dd3.mp4

The setup requires several clicks.  You have to select the camera in the camera's Scene, then select the camera in the Entity View before manipulating it from your world Scene. Unfortunately, there are no live updates of the camera's view when its properties are being manipulated.  So making adjustments is a tedious process.  Imagine if you have a game comprised of lots of static camera views.

**Comment by frank-ourmachinery** [comment]
A solution for this was very recently added and will be available in the 2021.8 release. #453 was the original issue.

https://user-images.githubusercontent.com/70658773/128973377-1b942cdf-51f7-427a-9e7c-73c5fdb8d822.mp4
