### ISSUE TITLE
Request: Wrap Entities into Parent

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#716]
Add the ability to wrap entities in a parent:
![image](https://user-images.githubusercontent.com/70658708/129049052-b04a85b6-d959-4a12-ac98-f43c91a9d957.png)

- Wall 1 and battlement 1 could be grouped together with a parent entity
This speeds up the workflow of creating prototypes.

**Comment by leonardo-ourmachinery** [comment]
You can now do this via Shift + P. (Ctrl + P now moves to the parent while Shift + P moves to a new parent).
I will add this to the multi-object context menu once we have one.
