### ISSUE TITLE
Dragging multiple entities into the asset browser does not create multiple prototypes.

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#717]
Expected behaviour:
When drag and drop multi-selected entities into the asset browser they would either all be added to the asset browser as a prototype

**Comment by niklas-ourmachinery** [comment]
Seems reasonable. Did you have another option in mind too? "either X or Y"?

**Comment by simon-ourmachinery** [comment]
I would probably make the option default that when the user drags entities X&Y into the asset browser that they are both seperate prototypes. But maybe we could also have a modal asking when multi select is used if the user wants seperate once or group them to one single prototype by adding all selected and dragged entities into one parent.

**Comment by niklas-ourmachinery** [comment]
We don't want to interrupt the user with modal dialogs unless absolutely necessary, and I don't think we need the grouping option. (The user can easily group in the entity tree before creating the prototype if so desired.)

**Comment by simon-ourmachinery** [comment]
Is part of the next release when dragging entities from the Tree View into the Asset Browser they will all create a prototype:
![image](https://user-images.githubusercontent.com/70658708/130257872-e0602d57-307a-4caa-9b22-c097832502da.png)
