### ISSUE TITLE
Entity Tree: Right click into void does not open the context menu

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#718]
Somehow the expected behaviour for me is that when I click into the void I would be able to have the context menu and add a entity/component to the root entity. This is the same for pressing space .... when just selected the ENtity Tree view 
![image](https://user-images.githubusercontent.com/70658708/129050003-af5e1b40-e2bd-468b-ba35-02df98539834.png)

**Comment by leonardo-ourmachinery** [comment]
I think I disagree on this:

The Context menu is opened when you right click on an object, but that implies that that object is _selected_:
If We were to implement what you suggested, it would mean that the root entity of the asset should be selected automatically when I click on the Entity Tree background, and I don't think that's the correct decision, or at least it doesn't feel so intuitive to me.

Also, even if we did it, we would have to decide _where_ to position the context menu, and both:
1) position it at the mouse cursor
2) position it at the root
seems bad to me, as 1) means that the context menu is drawn far away from the entity it's referencing, and 2) means that we're opening the context menu away from the mouse cursor, which is not a good idea either imo.

@karll-ourmachinery @niklas-ourmachinery what do you think?

**Comment by simon-ourmachinery** [comment]
The main reason why I say this is because when coming from Unity (see picture) or unreal its a normal workflow there that when clicking in the Hierarchy of the scene without having anything selected you always have the root selected and can add things to it: 
<img width="243" alt="image" src="https://user-images.githubusercontent.com/70658708/152323822-fed4d5ed-564e-4ae5-9a6f-9752e5de7913.png">

**Comment by leonardo-ourmachinery** [comment]
I just added this in master, but note that the context menu is opened only if you right click. Left clicking on the background still deselects everything like it was doing before.
