### ISSUE TITLE
Entity Tree: When adding a new Entity I cannot change the name directly

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#719]
When adding a new asset to the asset browser you can rename it directly.
![image](https://user-images.githubusercontent.com/70658708/129050692-f8bf1643-6dc4-42aa-bbb4-c7c95057430d.png)

**Comment by niklas-ourmachinery** [comment]
Do you mean that when a new entity is added it should enter the "rename" mode immediately? Like the Windows Explorer does when you create a new folder?

I think that would be a good idea, but I'm not 100 % sure.

**Comment by simon-ourmachinery** [comment]
Yes I would like that since it's the same in the asset browser

**Comment by leonardo-ourmachinery** [comment]
I just added this. Let's see how that feels internally... it's one line of code so it will be super easy to revert shall we decide to go back before the release.
