### ISSUE TITLE
Request: Primitive drawer in Creation Graphs

### ISSUE THREAD

**Issue by Polyrhythm** [OurMachinery/themachinery-public#722]
I want to do line render given a set of points from a creation graph. I suppose this can live in the Draw Call node?

**Comment by frank-ourmachinery** [comment]
I've added the ability to set the primitive type in the `Draw Call` node. Currently you'll need to supply a mesh that used line list as its primitive type as I haven't added a geometry node for a list of point yet.

![image](https://user-images.githubusercontent.com/70658773/129735281-c3ec03f0-b3fd-4c30-a9e4-054790208df5.png)

**Comment by tobias-ourmachinery** [comment]
From what I gather this has been fixed, closing.
