### ISSUE TITLE
Crash manipulating emissive material. Emissive material color not showing up when exported from Blender/GLTF.

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#728]
This bug is two parts.  I have a simple cube exported as gltf from blender that has an emissive material. When import the asset, the entity does not appear to have any emissive color.  If I open the creation graph for the emissive material the color is white, and if I manipulate it TM crashes.

https://user-images.githubusercontent.com/27040/129664405-18da539d-36eb-4456-b508-6d10d08e90d8.mp4

**Comment by geekrelief** [comment]
If I trying to detach the material prototype, or Override/"Remove From Instance" the creation graph nodes, I also get a crash.

**Comment by frank-ourmachinery** [comment]
The crash is fixed and the Assimp plugin now loads the emissive color. For some reason though the emissive color is not being set correctly in the creation graph when the DCC asset material is being extracted.
