### ISSUE TITLE
Shader reload appears to have no effect

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#73]
I am not sure this is the intended behavior or if I am interpreting the shader reload action incorrectly.

1. Open the default-content project
2. Comment out line 63 in **skycube.shader** (output color assignment)
3. Press the reload button in the editor

Additionally, when a shader compile error occurs as the project is loaded, the editor freezes and crashes. This makes it hard to read the shader error message (unless the editor was launched through a console and piped its output).

**Comment by cyberfrank** [comment]
It appears to work on another machine... tricky!

**Comment by tobias-ourmachinery** [comment]
Fixed in latest.
