### ISSUE TITLE
Child entity not simulated?

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#732]
I have `spheroid2` as a child entity of `world`.  Its entity is in a folder which has a simulate entry. When I first simulate nothing happens until I move it to the parent folder with `world.entity`.

https://user-images.githubusercontent.com/27040/129959093-440324ac-9da6-424a-8ff4-3ad535847254.mp4

Is this expected behavior where child entities simulate_entry isn't executed with the parent entity?

**Comment by karl-zylinski-ourmachinery** [comment]
This should be fixed since we moved to having Simulate Entry Components instead of Simulate Entry assets.
