### ISSUE TITLE
[UX] `Graph` component rename to `Entity Graph` for clarity and discoverability

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#734]
When referring to a "graph" in the documentation, it's always referred to as either an `Entity Graph` or `Creation Graph` unless you're referring to the `Graph Tab/View`.

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery  what do you think? I personally agree that it can be miss leading since the Graph Component does not necessarily say it's the entity graph.

**Comment by niklas-ourmachinery** [comment]
Yes, I think "Entity Graph" would be clearer.

**Comment by simon-ourmachinery** [comment]
@niklas-ourmachinery How should we rename this? On the surface level or also everywhere. I think if we do it we should do it soon. If we rename it properly (so also in code etc) we need migration.

**Comment by niklas-ourmachinery** [comment]
Just a surface rename (what's visible in the UI).
