### ISSUE TITLE
`Scene Entity` input to entity subgraph generates an error

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#735]
```❌ C:\tm\gr-tm\foundation\the_truth.c(545): error: Property type mismatch in `tm_entity_graph`, property `graph` is not of type `string`.

❌ C:\tm\gr-tm\foundation\the_truth.c(543): error: Property type mismatch in `tm_entity_graph`, object does not have property `2`.

❌ C:\tm\gr-tm\foundation\the_truth.c(545): error: Property type mismatch in `tm_entity_graph`, property `graph` is not of type `string`. (1346)```

https://user-images.githubusercontent.com/27040/129985826-012ff8a5-bd6d-47a8-a16a-048d9d37d675.mp4

**Comment by geekrelief** [comment]
In the video, when I drag the connector from the `Scene Entity` node should it be able to find the potential input nodes?

**Comment by geekrelief** [comment]
I think the latest push 6a56469d72794b7c2fae60f88bfe9a5f92b8bf55 broke this Entity Graph for setting up the camera. 

I'm getting an error message:
```
❌ C:\tm\gr-tm\plugins\graph_interpreter\graph_component.c(774): error: Unknown data type: f04a971fe569b002
```
![the-machinery_EKVvEbcOf8](https://user-images.githubusercontent.com/27040/130010580-87dc0246-e76c-4437-8dbb-b786455e7e48.png)

**Comment by simon-ourmachinery** [comment]
Problem is partly fixed
