### ISSUE TITLE
Zooming affects render quality of the viewport

### ISSUE THREAD

**Issue by LennardF1989** [OurMachinery/themachinery-public#738]
I was playing around with some of the examples. Due to the UI font being really small at a scale of 1x, I set it to 1.5x (as this also alleviates the #639 issue somewhat). I then noticed that the zoom also effects the render quality of the viewport.

Without scaling:
![image](https://user-images.githubusercontent.com/869973/130128839-941d23ea-6294-4d9a-b50f-2bbbdb2d1c66.png)
![image](https://user-images.githubusercontent.com/869973/130128951-e2efab3c-ee21-4e51-b748-c68481ac6677.png)

With scaling (1.5):
![image](https://user-images.githubusercontent.com/869973/130128918-e0673be2-ac1e-49ab-82ad-301256193911.png)
![image](https://user-images.githubusercontent.com/869973/130128933-30706371-f6cc-4653-a7a2-a968de5bc82d.png)

**Comment by tobias-ourmachinery** [comment]
Fixed in master.
