### ISSUE TITLE
Crash on model import.

### ISSUE THREAD

**Issue by ProtonGustave** [OurMachinery/themachinery-public#739]
In latest git version when i import this model [model.zip](https://github.com/OurMachinery/themachinery-public/files/7025907/model.zip) in new project i see `Dependency cycles found in graph` in console and then SIGSEGV.
In previous versions it was fine.

**Comment by simon-ourmachinery** [comment]
Its somewhere in the creation graph:
Commit: https://github.com/OurMachinery/themachinery/commit/c19dd4922cbade48be06edfc80bd7d73619079d7 breaks
![image](https://user-images.githubusercontent.com/70658708/130330116-f9df405c-d67e-4c66-88e6-58186f9a0a01.png)

**Comment by simon-ourmachinery** [comment]
Fixed
