### ISSUE TITLE
Creation Graph scalar input causes undefined behavior while it should not

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#74]
As known, the number of vertices should be set to 3 for the skycube to render properly.
![capture0](https://user-images.githubusercontent.com/3429723/72814603-9b1db400-3c65-11ea-8156-64f5f7ba6503.PNG)
However, using a separate **Creation Graph Input** to provide the same scalar value (3), the output skycube becomes invalid. Inputs that are lower than 3 also output wierd visual results. According to the shader code, any value lower than 3 should produce an empty image.
![capture1](https://user-images.githubusercontent.com/3429723/72814604-9bb64a80-3c65-11ea-93c4-aba95fc79440.PNG)

**Comment by tobias-ourmachinery** [comment]
Fixed in: https://github.com/OurMachinery/themachinery/commit/effb7dd7865f23f5add1598e4c6d6628de6c5f62
