### ISSUE TITLE
Asset import issue: gltf / glb files with vertex colors end up black when imported.

### ISSUE THREAD

**Issue by photex** [OurMachinery/themachinery-public#741]
Howdy!

I've attached some files and their source scene in blender. A glft file exported without vertex colors imports with the correct material and texture, but then doesn't have it's vertex colors. A gltf *with* vertex colors is imported entirely black. An fbx import appears perfect correct with it's material and vertex colors.

I've verified that the gltf file opens in the native microsoft viewer and looks correct.

![Screenshot 2021-08-24 213816](https://user-images.githubusercontent.com/301903/130680983-23894334-342d-42a4-8277-9c6baeb0a36e.png)

[vertex_color_import_sample.zip](https://github.com/OurMachinery/themachinery-public/files/7041764/vertex_color_import_sample.zip)

**Comment by tobias-ourmachinery** [comment]
This looks like a bug in our version of assimp that can't handle vertex colors in gltfs coming in in any other format then float4. It has later been fixed: https://github.com/assimp/assimp/commit/6d13fd6aa2271fb923a6f1c1573f17f4ed47af17

We'll investigate upgrading our assimp version for 2021.12.

**Comment by tobias-ourmachinery** [comment]
Fixed in 2021.11
