### ISSUE TITLE
Import FXB: Buffer size should be known after load

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#745]
![image](https://user-images.githubusercontent.com/70658708/130786106-eb53db7b-797c-4fc5-9176-b6c065ecc430.png)

https://www.kenney.nl/assets/retro-urban-kit

`balcony_typeA.fbx`

GLB Import;
![image](https://user-images.githubusercontent.com/70658708/130786251-c310ac25-738f-47f5-86c1-5a8188d4379e.png)
FBX:
![image](https://user-images.githubusercontent.com/70658708/130786288-172f47b4-4df8-45e8-b4a9-a7ff5d649ccb.png)

**Comment by simon-ourmachinery** [comment]
Side note: When then dragging it into the scene and undo this you get a NULL lookup from the Truth

**Comment by frank-ourmachinery** [comment]
I've tried testing with a few different importers and none can properly import the FBX version.

**Comment by simon-ourmachinery** [comment]
so you are saying the model is bad?

**Comment by frank-ourmachinery** [comment]
I don't think Assimp can load this FBX model, perhaps the official SDK can.

**Comment by tobias-ourmachinery** [comment]
Did a pass over this. The `aiMaterial` property `$tex.file` points to an empty string. This is a bug in assimp. Might be worth investigating if it has been fixed in a later release of assimp but will close it for now.
