### ISSUE TITLE
Change Size: If bigger set bigger then your resolution/ screen size you have no way to reset

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#754]
Solution:
- Do not allow bigger than native resolution

**Comment by leonardo-ourmachinery** [comment]
We're now covered against this as the engine will detect windows with rect bigger than the screen and maximize them instead. 
(It will also assign a "reasonable" position and size so that when you de-maximize the window it will be completely visible).
