### ISSUE TITLE
Label changes are not always reflected when drawing node

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#76]
Sometimes when I change the `Label` of a node, the graph doesn't update. It seems pretty easy to reproduce if you just change the label a couple of times. Reloading the graph seems to fix the issue, so it's probably a cache problem.

![image](https://user-images.githubusercontent.com/26548514/72832658-2da85e00-3c3a-11ea-8147-a63de47f30d2.png)

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/fb45ca4476b65817108e8ce9e643f4acb36de451
