### ISSUE TITLE
Not successful in hosting server for collaboration 

### ISSUE THREAD

**Issue by Selmar** [OurMachinery/themachinery-public#767]
Hi,

I tried to use the collaboration feature with a friend, but we had a few issues:
- He could not connect if I hosted a regular server, despite setting up port forwarding (though it is possible I did something wrong).
- We tried hosting via discord, and I could invite him (and we could both join Simon's collab session), but he would not be able to join. I was not able to join his session either. Simon was not able to join our sessions either.
- For discord, the port is hardcoded to something around 20000, but the router my ISP provides does not allow me to forward ports below 50k (don't ask me why).

**Comment by karl-zylinski-ourmachinery** [comment]
Hi, thanks for the report. We will attempt an overhaul of how we setup connections for 2021.9 or 2021.10.

**Comment by karl-zylinski-ourmachinery** [comment]
For release 2022.1 we have changed Discord collaboration to our new NAT traversal / punchthrough code. Discord collaboration mode uses this and there is an explicit NAT connection mode which will try to do this. This should work more reliably and not require any port forwards.
