### ISSUE TITLE
When copy/pasting a node, the error state is not shown correctly

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#77]
Before copy paste:

![image](https://user-images.githubusercontent.com/26548514/72834412-a230cc00-3c3d-11ea-8ca7-70c8e726acc7.png)

After copy pasting the top node:

![image](https://user-images.githubusercontent.com/26548514/72834439-b4ab0580-3c3d-11ea-999f-3f39c86ca9a0.png)

The newly connected node doesn't have the error status set... but note that the two nodes on the bottom also loose their error flag.

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/d74cde4d8647650766ce2cdc4fade0d446f38591
