### ISSUE TITLE
Closing last Workspace with unsaved changes and clicking "Cancel" results in weirdness

### ISSUE THREAD

**Issue by kraybit** [OurMachinery/themachinery-public#772]
Reproduce
- Open TM 2021.8
- Have one workspace
- Move the World-entity in the scene (Make a change)
- Go to Menu -> Window -> Close Workspace
- Select Cancel

What happens
- All panels are closed
- Entity Tree is **_nuked_** (Observed when opening a new Workspace with Default Layout)

What should happen
- Probably nothing

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.8.a. I removed the option of closing the last workspace.
