### ISSUE TITLE
Right clicking a prototype instance should give option to open said prototype

### ISSUE THREAD

**Issue by RiederAlex** [OurMachinery/themachinery-public#773]
Currently I'm finding it cumbersome to get towards the prototype from the instances.

For first level prototype instances, I have to click it and then inside Properties -> Open Prototype.
For nested prototypes inside the first level, there is currently no option at all to (in)directly open the prototype.

I would suggest adding an entry to directly open the prototype to the context menu for both cases.

![image](https://user-images.githubusercontent.com/14026803/131177461-ab709e81-15ef-4d05-a628-ec40a9aae04e.png)

![image](https://user-images.githubusercontent.com/14026803/131177067-908f3d81-9eff-460a-8bd8-964505917e24.png)

**Comment by leonardo-ourmachinery** [comment]
I think this has been fixed here:
https://github.com/OurMachinery/themachinery-public/issues/967

-the "open prototype" menu entry is at the 0th level of the context menu
-it's possible to open chldren of instanced prototype prototypes
