### ISSUE TITLE
Entity Tree shortcuts like Space / Shift+Space stop working if the mouse is used to make a second selection.

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#774]
If you select a different tab, then go back to the Entity Tree or use the keyboard to change selections the shortcuts still work.

https://user-images.githubusercontent.com/27040/131202448-d3a15923-3180-46cf-afcf-6de3186b8240.mp4

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.8.a
