### ISSUE TITLE
Website: There's no link in the menu to the Books

### ISSUE THREAD

**Issue by kraybit** [OurMachinery/themachinery-public#775]
The machinery website (https://ourmachinery.com/) has no link in the menu to the books (https://ourmachinery.github.io/themachinery-books).

Comment
I stumbled on the Books by accident in Discord.

**Comment by niklas-ourmachinery** [comment]
The books are still in "preview mode" which is why we haven't officially added them to the web site yet. But I agree, we should do that since they're still helpful.

**Comment by niklas-ourmachinery** [comment]
Fixed.
