### ISSUE TITLE
Deleting nodes will sometimes delete the wrong connections from the graph

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#78]
Repro case:

1. Open `animation` sample project version https://github.com/OurMachinery/sample-projects/commit/1e7af783ecc6501f25b7d9e7cb1122c59e5cffb3.
2. Open `test-scene`
3. Open Graph component in root.

You should see this:

![image](https://user-images.githubusercontent.com/26548514/72836396-6566d400-3c41-11ea-9f20-5b7cbc6d091f.png)

4. Select the top nodes and delete them:

![image](https://user-images.githubusercontent.com/26548514/72836370-4cf6b980-3c41-11ea-88a0-677fd012a36b.png)

**Comment by karl-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/f896e6f254c2dbb52300f84d84b58fa4f00b4c9a
