### ISSUE TITLE
Animation state machine triggers upgrade

### ISSUE THREAD

**Issue by ProtonGustave** [OurMachinery/themachinery-public#781]
I basically have a problem with crossfading. When user finish attack i crossfade it into movement state(idle/run). I need to know when attack is finished so i set a trigger at the end but it doesn't get triggered because of crossfade  and current triggers implementation
Your comments from ASM source:
![image](https://user-images.githubusercontent.com/35541456/131361528-73a2a696-59a7-47b4-b64a-ebd5f0fb1552.png)

**Comment by niklas-ourmachinery** [comment]
I fixed this for 2021.11 so that blending out animations also have their triggers triggered. I also refactored the code a bit so that it will become easier to add more options for this in the future.
