### ISSUE TITLE
Cannot change mip level or Slice of an image in preview tab

### ISSUE THREAD

**Issue by raphael-ourmachinery** [OurMachinery/themachinery-public#782]
Trying to change image mip level or slice doesn't work, text box loses the focus immediately and workspace bar gains focus, it's like it was clicked instead of textbox control. Repro steps:
- Create a new creation graph;
- Add a `Create GPU Image` and modify `Layers` to 10;
- Add a `Filter Image` node;
- Add a `Image Output` node;
- Try to change mip level or slice in preview tab.
![Screenshot from 2021-09-01 17-21-26](https://user-images.githubusercontent.com/75702792/131739473-b828799d-8696-4516-ad54-e0b543943165.png)

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed for 2021.8a and in master.
