### ISSUE TITLE
Shader system resource mapping <-> HLSL syntax is not documented completely

### ISSUE THREAD

**Issue by Selmar** [OurMachinery/themachinery-public#786]
In the shader system reference (which is really great, by the way), some things are only implied. For example:
- it does not mention that a writable texture should be `RWTexture2D` and not `Texture2D` (though kind of obvious)
- it does not speak about some types, like `RWStructuredBuffer` (does it work? and what about the other types that aren't in the doc?)
- it does not mention that the `uav` flag means the buffer is writable and should be defined as `RW[Object]` instead of just `[Object]`

There's likely a line to draw somewhere, for what is part of your documentation and what is HLSL documentation.

It would also be interesting to know how shader system resources map to the vulkan backend (that's more a personal interest, but can be useful to know for performance reasons)

For `uav`, maybe, from an API point of view, it could make more sense to name it `writable`, but I don't know the nuances of `uav` (and in some sense it makes sense to stay close to the HLSL definitions).

**Comment by frank-ourmachinery** [comment]
I've added a section to the shader system reference for the resource mapping in both HLSL and SPIR-V. It should become available on the website with the next release.

The term UAV implies something more than just that the resource is writable. It also specifies that these writes can be temporally unordered. The term is also commonly used in the HLSL environment which is currently the only supported shader language.

**Comment by Selmar** [comment]
Thanks!

> The term UAV implies something more than just that the resource is writable. It also specifies that these writes can be temporally unordered. The term is also commonly used in the HLSL environment which is currently the only supported shader language.

Right. This is always implied when a regularly bound resource is writable, isn't it?
