### ISSUE TITLE
Crash with Procedural Forest Sample

### ISSUE THREAD

**Issue by julhe** [OurMachinery/themachinery-public#787]
To reproduce:

1. Load the Project ([https://ourmachinery.com/files/procedural-forest-09-02.7z]())
2. Open `world.entity`
3. 💥 

Dump: [the_machinery_exe 2021-09-05 12.39.39.zip](https://github.com/OurMachinery/themachinery-public/files/7111422/the_machinery_exe.2021-09-05.12.39.39.zip)

System:

- Radeon 6800 XT
- Ryzen 3900x
- Windows 10 64-Bit
- Machinery 2021.8a (Release build from website)

**Comment by frank-ourmachinery** [comment]
Could you supply us with the log file as well? It should be in `Appdata\Local\TheMachinery\Logs`.

**Comment by julhe** [comment]
[2021-09-05 12.39.27.log](https://github.com/OurMachinery/themachinery-public/files/7115989/2021-09-05.12.39.27.log)

**Comment by tobias-ourmachinery** [comment]
We're waiting to receive a RDNA2 card from AMD for testing, as soon as it arrives we'll see if we can repro this. 

If you want to investigate this further on your own I suggest you install the Vulkan SDK and start the machinery with `--vulkan-validation` and see if that catches anything in the log before the crash.

**Comment by tobias-ourmachinery** [comment]
We finally got our hands on a Radeon 6900XT card now and fixed a bunch of validation errors and other AMD related issues. 

I can now open the procedural forest sample without any issues. All fixes will be rolled out in the 2021.11 release in about a week or so. Will close this for now, please reopen it if the issue still persist when testing in 2021.11.
