### ISSUE TITLE
Application of a published Project receives mouse input if window is not focused

### ISSUE THREAD

**Issue by DMI-1407** [OurMachinery/themachinery-public#790]
I dunno if its an issue of the project or the engine.

If i publish a project the exe _(the application of the published project)_ does receive mouse input even if the windows is not in focus.
_(i personally dont think that receiving any kind of input while not in focus is a wanted behavior..., at least it shouldnt be the default)_

Steps to reproduce:
1. open a project _(e.g. procedural-forest and delete the sequences)_ that has a "normal" camera _(so you can fly around)_.
2. publish the project.
3. start the exe of the published project.
4. start another application _(e.g. browser)_
5. scroll with the mouse wheel.

Result:
The application is not in focus. _(because you started a browser after starting the published project)_
The camera in the application of tm is zooming in or out.

Assumption:
The application is not in focus. _(because you started a browser after starting the published project)_
The application of tm does ignore user-input that is used for controlling.
_(exotic stuff like voice input by side.... i mean mouse-, keyboard-, gamepad/joystick-input)_

**Comment by leonardo-ourmachinery** [comment]
Thank you for reporting this.
You are definitively correct, the camera shouldn't update if the game window is not in focus. We'll make sure to fix this for the next release.
