### ISSUE TITLE
Cannot launch downloaded update because of space in path

### ISSUE THREAD

**Issue by ThatGuyMike7** [OurMachinery/themachinery-public#792]
![image](https://user-images.githubusercontent.com/13405250/132881423-26a4c9f9-57fc-48c5-8c88-fede49c3eb51.png)

This error box opened every time I clicked on the "Launch" button there. Right after "E:\Dieser", there is a space in the actual path to the The Machinery zip file that was downloaded. Path was truncated right before the space.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.9.

@raphael-ourmachinery Can you check if this fix works on Linux?

**Comment by raphael-ourmachinery** [comment]
It's working on Linux.
