### ISSUE TITLE
Sky atmosphere component sun light bug

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#793]
The sky atmosphere component has a bug where if you override the component in the scene and restart the editor, it loses the sun-light reference making it so the sun does not follow the rotation of the sky.

**Comment by raphael-ourmachinery** [comment]
Probably is related to https://github.com/OurMachinery/themachinery-public/issues/666.

**Comment by raphael-ourmachinery** [comment]
I couldn't reproduce it anymore, @DaveTheGameDev Does this still happens on your side?

**Comment by DaveTheGameDev** [comment]
I haven't had it for a while now. @raphael-ourmachinery

**Comment by raphael-ourmachinery** [comment]
Thanks, I'll close this issue, but feel free to reopen it if you see this bug again.
