### ISSUE TITLE
Unreadable syntax highlighting on blog post

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#799]
There seems to be syntax highlighting issue in https://ourmachinery.com/post/the-machinery-shader-system-part-2/ ( windows, chrome and edge ).

![unknown](https://user-images.githubusercontent.com/1103761/133909104-56ab3ad6-330c-40b1-a50c-377d61b7fee4.png)

**Comment by niklas-ourmachinery** [comment]
Fixed.

The issue was that the code was marked as JSON and wasn't actually JSON (it's our own extension of JSON) -- and in addition, the error highlighting of the monokai style was weird.
