### ISSUE TITLE
Importing external assets in hot reload mode causes infinite error loop

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#80]
While importing an external asset (e.g. mesh, image) from disk in `--hot-reload` mode, it appears that `the_machinery_dll` fails to load and subsequently cause an infinite `Bad Image` alert loop.

**Comment by niklas-ourmachinery** [comment]
Hmm... that seems weird... it shouldn't really try to hot-reload `the_machinery_dll` at that point, since it hasn't been change. Can you post the log that you get here?

**Comment by cyberfrank** [comment]
I also noticed that a `the_machinery.dll` file is created **at the location of the project** prior to the crash occuring. This behavior appears to only be true in `--hot-reload` mode. Note that the `TM_PRE_ALPHA_DIR` is not in the same directory, I just happen to have the project file on the desktop.

![Capture](https://user-images.githubusercontent.com/3429723/73161754-92f1c880-40ec-11ea-80ad-f7d5990bc42b.PNG)

Get the log file here: [2020-01-27 10.02.08.log](https://github.com/OurMachinery/themachinery-public/files/4116266/2020-01-27.10.02.08.log)
