### ISSUE TITLE
Support media key events on Windows

### ISSUE THREAD

**Issue by karll-ourmachinery** [OurMachinery/themachinery-public#801]
Currently, media keys (_Volume Up_, _Volume Down_...) aren't supported nor handled. 
See `VK_VOLUME_DOWN` in https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes.

At the very least we should handle them, otherwise the editor prints the following error whenever the keys are pressed:
```
❌ C:\ourmachinery\themachinery\plugins\os_window\os_window.win32.c(1416): error: GetKeyNameText() failed for 1000000
```

----

This issue may also be relevant for Linux and MacOS.

**Comment by niklas-ourmachinery** [comment]
Okay... so I did a dig into this... the wonderful quirkiness of Microsoft APIs.

* For `RAWKEYBOARD` events that have one of the extended flags set `e->flags & RI_KEY_E0` or `e->flags & RI_KEY_E1`, `e->MakeCode` won't actually be set to the scan code of the key. In this case, we have to call `MapVirtualKey()` to get the scan code of the key.

* `GetKeyNameText()` is also behaving erratically -- when passed `2E` with the extended bit set, which is what my keyboard sends for "volume down", it will actually return "C" (which is what `2E` without the extended bit should convert to, see http://www.quadibloc.com/comp/scan.htm). However, for some extended keys it *does* return the right value. I.e. for `1C` it returns `Enter` without the extended key and `Num Enter` with the extended key.

I think we're actually better off not relying on these functions at all, but instead just using the hard-coded names from `tm_input_api->keyboard_item_names()`. Will push a fix with that.
