### ISSUE TITLE
light theme - dock target icon

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#802]
the dock target icon in the light theme seems to be from the dark theme

![image](https://user-images.githubusercontent.com/1103761/134120111-4c8e8442-c623-4c08-b94d-df0bbaaa19cf.png)

**Comment by karll-ourmachinery** [comment]
Oops! We weren't setting a background color at all for the drop zones, thanks!

**Comment by eigenbom** [comment]
Much nicer, thx!

![image](https://user-images.githubusercontent.com/1103761/134605986-c22b4c68-c66a-4cd0-8ccb-29d8cc9acf64.png)
