### ISSUE TITLE
Light theme - default parameters in input fields make input field look disabled/inactive

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#805]
The colour of text in input fields make them look disabled. Users may think they cannot interact with these fields.

![image](https://user-images.githubusercontent.com/1103761/134125613-9bd58007-5715-4124-93fa-6a8d3e85da97.png)

**Comment by karll-ourmachinery** [comment]
The reason why these input fields are inherited from a prototype, at least for now they need a different color to make this information available to the user. The faded input matches well with the "inherited value" concept,  but it does look ambiguous if there are no overridden or disabled input fields to contrast..

I have added a little bit more color to the "faded" input to differentiate it from disabled inputs.
Do any of these seem more readable to you? 
![image](https://user-images.githubusercontent.com/82545839/134503329-55be14af-4bcf-4621-99c9-d21b7751a68f.png)
![image](https://user-images.githubusercontent.com/82545839/134502939-3528235f-73d3-466d-bd98-9bd50d789aa2.png)

**Comment by karll-ourmachinery** [comment]
I should do a proper pass over the light theme soon, we have done quite some ui changes without giving much attention to the light theme.

**Comment by eigenbom** [comment]
I think that's better for sure 👍
