### ISSUE TITLE
Sorting in asset browser tree view is reversed from icon view

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#807]
![image](https://user-images.githubusercontent.com/57644882/134502818-1a678f66-ab5c-4464-b289-d83110a8e9d9.png)

See that the order of items in the tree view is reversed from the icon view

**Comment by karll-ourmachinery** [comment]
Fixed!
1. Tree cache didn't sort it's directories according to the selected sort function.
2. Tree cache wasn't refreshed when changing sort modes. Ended up adding a `is_sort_dirty` flag for this, as sort modes don't change the asset's version, and computing a hash over the directory list sounds overkill.
