### ISSUE TITLE
Subgraph node behaves weird when there is no property tab

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#812]
If you open a graph in its own workspace and create a subgraph node, it doesn't show the input and output connectors and you can't open it.

If you create a Properties tab and select the subgraph node, the connectors will appear and the subgraph can now be opened.

![subgraph](https://user-images.githubusercontent.com/26548514/134703086-ff7c0266-0945-4b5c-b049-fd1be143b087.gif)

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/ee12bd7764df9101c0e9ddacff53091eace2c510
