### ISSUE TITLE
new version pop-up downloads the windows build on linux

### ISSUE THREAD

**Issue by minirop** [OurMachinery/themachinery-public#818]
When I clicked the "download' button on the pop-up saying the 2021.9 was there, it made me download the windows build.
When clicking on "get" in the "downloads" tab, I get the (correct) linux build.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.9.a.

@raphael-ourmachinery Can you check that the fix works?

**Comment by raphael-ourmachinery** [comment]
It's working.
