### ISSUE TITLE
Missing node types in animation sample

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#82]
In the animation sample, there are nodes that have their node type missing.

Repro: Open animation sample, open the graph of the xbox, get this in the console:
![error in log](https://user-images.githubusercontent.com/57644882/73166128-858d0c00-40f5-11ea-939c-57a15e3d4c5c.png)

**Comment by niklas-ourmachinery** [comment]
Fixed.
