### ISSUE TITLE
Tab focus event is called twice when clicking on an entity in `Entity Tree`

### ISSUE THREAD

**Issue by karll-ourmachinery** [OurMachinery/themachinery-public#822]
It seems the event is called once when the mouse button goes down (`press`) and again when it goes up (`release`).
Probably we want it to happen only on `release` as the user may not want to change focus when dragging entities to reorder them.

**Comment by leonardo-ourmachinery** [comment]
Fixed for 2022.2.
Now The Entity Tree only sends the tab focus event when necessary: simply clicking on an entity will only send the event on the mouse pressed.
