### ISSUE TITLE
Simulation entry not loading when opening a sample project.

### ISSUE THREAD

**Issue by minirop** [OurMachinery/themachinery-public#824]
When I open one of the sample project using a `Simulation Entry`, the field of the component is `** Missing or Unknown **`.
Openings that fail:
* "open" on the "download" tab
* "file > open project"
* "file > open recent > ..."

But if I open the project, then close TM and reopening it again (so the project load on boot), I have the popup asking me if I allow execution of the code. If I click yes, everything works as expected. (if I check "memorize that setting for that project" then it works all the time in all situation)

ps: I'm on Linux Manjaro

**Comment by minirop** [comment]
I didn't have any. So I removed the `"always_allow_dll_project_paths"` to check again:
1/ open "gameplay first person" from the DL tab, got the popup
2/ open "gameplay interaction" from the DL tab, got the popup too but crashed when clicked "allow"
3/ restart TM
4/ open "gameplay first person" didn't got the popup, and never got it again whatever I did.

So it seems there are moments when I do have the popup but most of the time, I don't. I'll investigate on my side (also if I manage to get the crash again).

**Comment by minirop** [comment]
For whatever reason, even on the 2021.9 I have the popup each time now.
But I noticed that if TM crashes, then the popup stops appearing unless you restart (i.e. TM closes gracefully)
So maybe, I always had a `crash-recovery-file.data` file so it would never show the popup.

**Comment by niklas-ourmachinery** [comment]
I've implemented these two suggestions for 2021.11.
