### ISSUE TITLE
Input connector of subgraph doesn't get "filled" when entering a value

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#833]
Reproduction case:

* Create a subgraph with two inputs (Event + Float).
* On the subgraph node, enter a value in the Float field.
* Note that the connector doesn't become "filled".
* Expected behavior: The connector should become "filled" to indicate that a value has been supplied.

![subgraph-property-edit](https://user-images.githubusercontent.com/26548514/136833159-41a5421d-968e-4273-8113-8120b678ccaa.gif)

**Comment by niklas-ourmachinery** [comment]
Maybe the connector for subgraph input should always be filled then, since it always has a value?

For other nodes, a filled connector means "has a value" not "value is changed from default" -- i.e. it is possible to have a value that is the default value. I think we should follow the same semantics for the subgraph nodes.

**Comment by karl-zylinski-ourmachinery** [comment]
I don't think that's correct. See the picture below. Here the node is in a valid state, the defaults visible on the the connectors will be used, so the connector has, as far as the user is concerned, a value. There's no data present on those connectors in the graph, but that is of little concern to the user. For users I think 'filled' means "value is changed from default".

![bild](https://user-images.githubusercontent.com/57644882/138091566-4c05bca3-dfc5-4b53-b7c8-064d724fd05b.png)

I could make the connectors always filled, but it would feel inconsistent with how other nodes work.

**Comment by niklas-ourmachinery** [comment]
The node is in a valid state in this case because the parameters are optional, so they do not need to have a value. In this case they don't have a value.

There are situations where this distinction makes a difference. For example look at this Vec3:

![image](https://user-images.githubusercontent.com/26548514/138353439-52898cd3-dbaa-412b-9e5f-c94e6304bd4c.png)

This is an invalid state, because one of the required connectors (A) doesn't have any data. If I press return in one of its fields I will supply the data:

![image](https://user-images.githubusercontent.com/26548514/138353540-d700dad2-1e8f-4c23-939a-dd871340ef3b.png)

Now the connector is filled because it has data (the data happens to be the same as the default value) and the node is valid. I can remove the data by right-clicking and selecting Delete Data:

![image](https://user-images.githubusercontent.com/26548514/138353786-afbee8c5-35cf-468b-ae4e-f6cdd27d788d.png)

And that then brings me back to the state with no data:

![image](https://user-images.githubusercontent.com/26548514/138353832-08188a2d-57bc-491a-8dc1-b991a6bead27.png)

Maybe we need to improve this UI in general. I see several issues:

* There is no way of telling in the UI whether a connector is optional or not, so you kind of just having to keep supplying values until it "works".
* The "I have no value" state is pretty subtle and hard to distinguish from "I have a value that is the default value" case.
* The "error bar" is kind of subtle too.

@karll-ourmachinery Do you have any ideas?

**Comment by niklas-ourmachinery** [comment]
Maybe the error should show up around the connector that is lacking a value... to make it clearer where the error is coming from.

**Comment by karl-zylinski-ourmachinery** [comment]
I have done these changes in master:
- Missing connection errors are shown next to the connector name.
- Many nodes now have optional connectors, such as all vecN add nodes etc.
- The hint that the node is instantiated is now a triangle in the upper right corner.
- The connector rectangle is only filled if the connector has a connection, but not for when it has data with no connection.

![image](https://user-images.githubusercontent.com/57644882/152382777-59b503b0-e072-4703-ae62-d41ce83228d5.png)

Closing this now.
