### ISSUE TITLE
Progress API & task manager needs overhaul

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#856]
When publishing a project the Progress bar in the status bar / task manager is not correctly updated. When using breakpoints the correct fraction is set but it seems to be that the `status` call only returns `0` for the fractions.
![image](https://user-images.githubusercontent.com/70658708/138916150-dc5d7d02-198d-41e1-b1f4-6554dfa486fc.png)

> As you can see it's very broken in many ways, lots of unnamed tasks etc. Maybe I'll spend tmrw trying to fix this up a bit. (@karl-zylinski-ourmachinery )

**Comment by karl-zylinski-ourmachinery** [comment]
We now have a concept of ownership of tasks. Tasks can be owned by a non-task (for example associated with a The Truth pointer) or have another task as owner. The task manager can display cancelled tasks. The task manager colors done and cancelled tasks in a nice way now.
