### ISSUE TITLE
It's possible to accidentally click on a check box using the entity picker,

### ISSUE THREAD

**Issue by raphael-ourmachinery** [OurMachinery/themachinery-public#860]
When choosing the sun entity on the atmospheric component, it is easy to uncheck `Offset to Ground` .
![Screenshot from 2021-10-27 11-31-20](https://user-images.githubusercontent.com/75702792/139087242-25f1dc5a-e5f1-4ef1-980e-d268ed6fb245.png)

**Comment by niklas-ourmachinery** [comment]
The problem was that clicks on the "sun-light" went "through" the entity picker right and selected/deselected the checkbox under it. I cannot reproduce this anymore so I think it has been fixed.
