### ISSUE TITLE
collaboration does not handle big projects properly

### ISSUE THREAD

**Issue by simon-ourmachinery** [OurMachinery/themachinery-public#863]
When trying collab with procedural forest version 09-02 the moment I connected to @frank-ourmachinery's session his PC used all the RAM and kicked me out of the session. The scene/project stayed.

The logs are as follows:

```txt
[DEV] host_recv_request_buffers: 705 buffers
[DEV] host sending buffers: 2.6 GB -> 20 B
```

[2021-10-28 11.40.47.log](https://github.com/OurMachinery/themachinery-public/files/7433073/2021-10-28.11.40.47.log)

**Comment by raphael-ourmachinery** [comment]
@simon-ourmachinery can you check if this still occurs?

**Comment by niklas-ourmachinery** [comment]
This should be fixed now... I've successfully collaborated on the procedural forest project.

The Vulkan Mem thing is probably a separate issue, but the bug with collaboration not handling big projects have been fixed.
