### ISSUE TITLE
Crash when hovering over animation item in Tab dropdown

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#866]
The editor freezes and crashes when hovering over the "Animation" item. This item happens to be the first item in the Tab dropdown, so it appears that just hovering over any item causes the crash. I am however able to "go around" to start browsing the dropdown from the bottom to confirm that the crash indeed only happens when hovering "Animation". 
The item does not highlight nor unfold to the right prior to the crash. 

Occurs only on **The Machinery 2021.10**. 100% reproduction on my desktop Windows 10 and laptop Windows 11 machine. 

![image](https://user-images.githubusercontent.com/3429723/139528216-2468f169-e4ca-4185-aea5-07b3b3aca40d.png)

**Comment by niklas-ourmachinery** [comment]
Reproduced -- will push a fix as soon as possible.

**Comment by niklas-ourmachinery** [comment]
As a workaround, if you enable "Tools > Feature Flags > Animation Curves" the crash will disappear.

**Comment by niklas-ourmachinery** [comment]
Fixed for 2021.10.a.
