### ISSUE TITLE
Double-clicking in entity tree behaves differently for entities and components

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#867]
Double clicking a component:

* Instantiate (if not instantiated)
* Otherwise -- open in editor

Double clicking an entity:

* Unlock (if not selected)
* Frame (if selected)

This inconsistency is a bit confusing... I think the Component behavior makes more sense, and maybe we should have that behavior for entities too. (Unless double-clicking to frame is something users are used to from other programs...)

**Comment by karl-zylinski-ourmachinery** [comment]
I did these changes
CTRL + double click overrides
SHIFT + CTRL + double click removes override

These modifiers are hinted by the context menu accelerator.

This follows how the properties panel and graph does it. Then for entities, double click can still focus etc. Does this resolve this or does the entity behavior still seem off?

**Comment by niklas-ourmachinery** [comment]
I think this works, closing for now.
