### ISSUE TITLE
Visual Studio 2022 hot reload support?

### ISSUE THREAD

**Issue by geekrelief** [OurMachinery/themachinery-public#872]
2022 was just released with support for hot reload for C++ https://www.youtube.com/watch?v=x_gr6DNrJuM  I tried testing out hot reloading with a simple change to the editor.  I got an error saying the Debug Information has to be set to the `/ZI`  flag for `Edit and Continue`, https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-170 but I got this error: ```Edit and Continue could not create a safe command line to compile changes. Please ensure that the same version of the compiler used to compile the code originally is installed with the current Visual Studio installation. More information may be available in the Debug pane of the Output window (Debug > Windows > Output).```

It'd be nice to support this if possible. If not maybe these are the guys to talk to:
https://devblogs.microsoft.com/visualstudio/author/dmitrylyalin/
https://devblogs.microsoft.com/cppblog/author/davidli1microsoft-com/

For reference:
https://devblogs.microsoft.com/cppblog/edit-your-c-code-while-debugging-with-hot-reload-in-visual-studio-2022/
https://devblogs.microsoft.com/visualstudio/speed-up-your-dotnet-and-cplusplus-development-with-hot-reload-in-visual-studio-2022/

**Comment by geekrelief** [comment]
Looks like premake recently added support for 2022 too. https://github.com/premake/premake-core/commit/12bc2ea3486e20478002086f7810dcfc1ddff027

**Comment by leonardo-ourmachinery** [comment]
Pushed to master.

**Comment by leonardo-ourmachinery** [comment]
@geekrelief FYI, we decided to disable edit and continue support by default as we're taking a ~20% performance hit when enabling it.

But you should be able to just set `editandcontinue` to true in the premake and you'll be good to go.
