### ISSUE TITLE
Crash when deleting a dcc_asset via asset browser

### ISSUE THREAD

**Issue by lachsinc** [OurMachinery/themachinery-public#873]
Perhaps related to #742, apologies if this should be part of that issue. 
Unlike #742 it also occurs prior to deletion of the entity.
Occurs reliably for me on release-2021.10.a (and on git master at time of writing).

Repro:
1. New project
2. Import file (.gltf in my case, but happens with .fbx too)
3. 'Extract assets' on new .dcc_asset
4. ~~Drag the new .entity into world~~ Nevermind, this isn't necessary, perhaps because entity/asset is open in 'Preview' tab?
5. Delete the .dcc_asset

Read access violation @ vulkan_render_backend.c:6466
`VkBuffer ibuf = rm->buffers[buffer_index].buffer;`

![repro-delete-dcc](https://user-images.githubusercontent.com/1400236/141480923-395059c7-4163-48b2-9b02-8578f26ba153.gif)

**Comment by lachsinc** [comment]
Debugged this further, that buffer_index during crash often contains the value 'DESTROYED_RESOURCE' - though protecting against that still eventually results in a crash with a bad buffer index being used.

Root cause may be runtime_unload() inside dcc_asset_creation_graph.c releasing render resources without discretion (reference_count is never checked prior to releasing the mesh's buffers?). Not certain though, I only poked through quickly.

**Comment by tobias-ourmachinery** [comment]
Fixed in 2021.11
