### ISSUE TITLE
Wrong lighting at specific angle/position in animation sample

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#878]
https://user-images.githubusercontent.com/70660839/142424904-73ccc773-9fb2-42b9-bc8d-4fb9a49f1a8f.mp4

In all the occurrences I was able to make it "go away" by just changing the viewing angle, like in the video.
It seems to be happening when "playing around" with the roof reflection.

**Comment by tobias-ourmachinery** [comment]
Colors used in the Animation Sample was a bit all over the place.. I've done a pass making sure the materials are better confugired and tweaked sun shadows / exposure values a bit. Things are more well behaving now.
