### ISSUE TITLE
Crash when selecting multiple entities and meshes

### ISSUE THREAD

**Issue by LoffanElemental** [OurMachinery/themachinery-public#885]
When shift selecting multiple objects like entities and meshes in the asset browser or the entity tree view Machinery crashes. Also if I drag select in the scene view the editor chrashes. In the scene view it is 100% crash rate in the entity and asset browser view it is around 50-60%

 Ver: The Machinery 2021.11-dev

**Comment by niklas-ourmachinery** [comment]
I'm not able to reproduce this... it might have been a temporary issue. Can you try again with latest and see if you still get it?

**Comment by Tisten** [comment]
Latest code solves it, thanks
