### ISSUE TITLE
Node has unknown type: `tm_geometry_triangle`

### ISSUE THREAD

**Issue by hsjunnesson** [OurMachinery/themachinery-public#888]
Having copied the code snippet from the tutorial book on how to create a GPU geometry node I get the following error after loading a creation graph that uses the new geometry node. This is using themachinery built from current master.
In order for the geometry to show up, I need to click the "Triangle" node again, which reruns `triangle_node__compile` and then it works.

```
❌ C:\Users\Hans\Documents\GitHub\thrust-machinery\themachinery\plugins\graph_importer\graph_importer.c(167): error: Node has unknown type: `tm_geometry_triangle`
```

**Comment by niklas-ourmachinery** [comment]
@karl-zylinski-ourmachinery This is your tutorial, right? Can you check the steps?

**Comment by frank-ourmachinery** [comment]
There are some small compile errors in the final code snippet that I will fix, but I cannot get the runtime error that you are getting. The error that you're getting seems to indicate that the `tm_geometry_triangle` node wasn't registered as a node. Perhaps the plugin didn't load?

**Comment by hsjunnesson** [comment]
> The error that you're getting seems to indicate that the tm_geometry_triangle node wasn't registered as a node. Perhaps the plugin didn't load?

The way this plugin is setup is that it's not a "general" plugin. I drag the dll into the editor and check "Import when changed". 
tm_level is the plugin that does setups the triangle node:

```
tm_add_or_remove_implementation(reg, load, tm_creation_graph_node_type_i, &triangle_node);
```

This is the log:

```
Loading project DLL tm_level-c0adcb8749ccfd4.dll.
❌ C:\Users\Hans\Documents\GitHub\thrust-machinery\themachinery\plugins\graph_importer\graph_importer.c(167): error: Node has unknown type: `tm_geometry_triangle`
```

**Comment by frank-ourmachinery** [comment]
The error seems to be harmless but annoying. The creation graph node is only loaded when the plugin is loaded, which in turn is loaded after the first round of initialization. So any saved creation graph with the triangle node in it (that was loaded as an asset plugin) will complain in the first frame before the asset plugins are loaded. 

A possible fix for this would be to order the asset loading and force asset plugins to be loaded first. Which would make sense to me.

**Comment by hsjunnesson** [comment]
Feel free to close this issue if it's a minor issue.

**Comment by simon-ourmachinery** [comment]
maybe related #892

**Comment by niklas-ourmachinery** [comment]
Yes, I think #892 is the right way to fix this.
