### ISSUE TITLE
Feature request - tags filtering in the Entity Tree Tab

### ISSUE THREAD

**Issue by hsjunnesson** [OurMachinery/themachinery-public#890]
I think the Tags Component is great, I use it for a lot of organizing of my entities in my scenes, in my runtime code. But I'd like to be able to find or filter entities in the editor as well.

It would be useful for me to be able to quickly find entities matching a tag, which would expand all nested entities. And also to filter, to show only entities that have a selected tag.

**Comment by hsjunnesson** [comment]
Leo also added, in a discord conversation, that it would be useful to be able to query entities with specific tags in the Simulation State Tab as well.

https://discord.com/channels/690290013585408136/691973666140848148/914984049850875975

**Comment by leonardo-ourmachinery** [comment]
Implemented in master, for both the Entity Tree and the Simulation State Tab.
