### ISSUE TITLE
Component or Properties Overrideable by Default

### ISSUE THREAD

**Issue by JonLangfordUK** [OurMachinery/themachinery-public#895]
It would be great if you could mark a component and/or a property to always be overrideable in instances of a prototype.

For example, a user could have made a prototype for a light fixture (combined light and mesh), but for each instance of that prototype, we want to allow the user to override the mesh. It would be great if we could mark the render component, or its properties to always allow overrides on instances, rather than having to right-click and override on each every time.

The number of tools I've made in the past on previous game projects that required artists or designers to override properties each time is substantial. I know that there would be pushback from our team if they had to mark a property as overrideable each time.

**Comment by leonardo-ourmachinery** [comment]
I think that once we have #1020 up and running this won't be an issue anymore since you will be able to just inspect the properties of the unoverridden components and edit them seamlessly, with the edited properties being automatically overridden.

Closing this for now.
