### ISSUE TITLE
Networking no longer works on > 2021.11

### ISSUE THREAD

**Issue by RiederAlex** [OurMachinery/themachinery-public#899]
I wanted to give the networking a try, but it no longer works out of the box with versions > 2021.11, whereas the exact same setup works in 2021.10a. I've tested it on Windows.

The root cause of this is that the server is unable to send responses to the client, which was broken by commit 37817f95ab50c9b754a470fb5efb41bcfcc584ac, changing "private__create_socket", which now binds to 0.0.0.0 instead of the localhost. The returned handle from this function is stored and at a later point re-used to fill the "delayed_packet_t->address" (via a 'socket_getsockname') - so the receiver tries to send the response to "0.0.0.0:<port>", which fails silently.

Locally I've fixed it by binding again to 'TM_SOCKET_IP_LOCALHOST', but I guess this is only a temporary solution.

**Comment by leonardo-ourmachinery** [comment]
Thank you for reporting and for spending your time identifying what the issue actually was.
I've pushed a fix here: https://github.com/OurMachinery/themachinery/commit/e8a36ada7cd3527e57329b53c89a14fc68b79342

Basically we should consider "127.0.0.1" as the IP of local nodes, even if they were binded with "0" (We have to do that if we want it to work across the real network) and "getsockname" returns "0".

Thanks again.
