### ISSUE TITLE
Rename items in Asset Browser (and other places) on click and hover

### ISSUE THREAD

**Issue by nekitu** [OurMachinery/themachinery-public#9]

**Comment by niklas-ourmachinery** [comment]
I know this is how it works in the Windows explorer, but I don't know if I'm a great fan of this, it's kind of annoying to have these things that are triggered by a time delay.

**Comment by nekitu** [comment]
Ok, at least F2 key when item is selected and focused, would be fast

**Comment by niklas-ourmachinery** [comment]
I added a separate issue for that: #29.

**Comment by karl-zylinski-ourmachinery** [comment]
I'm not a fan of click-wait either. Closing until someone requests that specifically. I was thinking if there are some accessibility reasons for supporting this, but I don't think so either.
