### ISSUE TITLE
Cannot import new assets if there is an error

### ISSUE THREAD

**Issue by xenobrain** [OurMachinery/themachinery-public#900]
To reproduce:
1) Drag one of the attached FBX into the asset browser.  The following error will appear in the console 
> '❌ ../../../plugins/assimp/assimp.c:608:0: error: Could not find image file `/home/xenobrain/Downloads/POLYGON_ScifiSpace_SourceFiles/StaticMeshes/PolygonSciFiSpace_Texture_03_A.png` -- reference to texture removed from material.

2) Drag the other FBX into the asset browser.  Another instance of the previous asset will appear instead.

3) To resolve, delete `.the_machinery` folder and reopen the project

System is Arch Linux.  Build of The Machinery is git master as of this report.

[assets.tar.gz](https://github.com/OurMachinery/themachinery-public/files/7697671/assets.tar.gz)

**Comment by Unesty** [comment]
I on Arch Linux have the same issue.

**Comment by raphael-ourmachinery** [comment]
I couldn't reproduce it on last master.

**Comment by xenobrain** [comment]
Video: https://drive.google.com/file/d/1m6hDFoK5GHmBFH3WWf6yuAioOmA61Qd0/view?usp=sharing
Build: master/81d4b8a42bf0323ca94294d0b49019bd653b75cb

.the_machinery directory was removed prior

**Comment by simon-ourmachinery** [comment]
Can you check the .the_machinery folder if the import folder is cleared after the import.

**Comment by simon-ourmachinery** [comment]
my last comment is invalid since no zip or folder is involved. the actual error message can be ignored the problem is that it imports the same thing 2 times or more.

**Comment by simon-ourmachinery** [comment]
@xenobrain  can you go to `plugins\asset_importer\asset_importer.c` and add in `import_multiple_task` a log for the path and maybe set a breakpoint to see whats going on? The asset importer API maybe the problem.

**Comment by simon-ourmachinery** [comment]
@raphael-ourmachinery I did a lil bit of a live debugging with @xenobrain and we found out that it has something todo with `os_windows_linux.c` and `XCB_SELECTION_NOTIFY` `window->dropped_files` . They are oddly not correct... 

Every time its the same file ...

**Comment by xenobrain** [comment]
in os_window_linux.c:693 
`if (xcb_icccm_get_text_property_reply(window->connection, prop_cookie, &reply, NULL)) {`
the contents of `reply.name` are not updated correctly the second time an asset is dragged into the window

This may be a KDE/KWin specific issue as it did not occur under an LXQt/OpenBox environment on the same machine

**Comment by raphael-ourmachinery** [comment]
I was able to reproduce it using Dolphin file manager only, although, closing and reopening it solve the issue for me, I'm investigating the reason.

**Comment by raphael-ourmachinery** [comment]
Hopefully is fixed on master now, probably the issue because I incorrectly interpreted XDND protocol, not sure why the issue happened only with dolphin/kde. @xenobrain @Unesty could you confirm if it's working now?

**Comment by xenobrain** [comment]
I can confirm the fix
