### ISSUE TITLE
crash when destroying entity with simulation entry

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#905]
repro:
1. create a simulation entry plugin (e.g., using the default template)
2. create a proto entity containing the simulation entry
3. create a graph that spawns and then destroys the entity on init
4. crash occurs in simulation_entry_system__shutdown

this is the simplest case to repro the crash, but i've seen this occur more generally when destroying entities that have simulation entries

![image](https://user-images.githubusercontent.com/1103761/146098959-e7c99244-da1b-4427-b0c2-7ce2e0308883.png)

![image](https://user-images.githubusercontent.com/1103761/146098146-647a4393-bd25-4d44-b859-72b8e686f948.png)

**Comment by simon-ourmachinery** [comment]
I can reproduce it to 100% my assumption is that since we queue removed systems that this breaks some pointers since they might be deleted before the removal. Ill see what I can do.

**Comment by eigenbom** [comment]
note i can also repro this without an explicit destroy just by pressing the restart simulation button

**Comment by simon-ourmachinery** [comment]
_Note_:
Maybe related to https://github.com/OurMachinery/themachinery/issues/841
