### ISSUE TITLE
Old graphs with dangling connectors does not work.

### ISSUE THREAD

**Issue by tobias-ourmachinery** [OurMachinery/themachinery-public#91]
When loading old graphs that have dangling connectors in its data model (due to the old graph editor code being broken when dealing with prototype graphs) the graph interpreter fails to resolve that correctly resulting in incorrect evaluation of the graph. 

This is likely a regression since the implementation of the `tm_graph_importer_api` helper API. We either need to make the importer API aware of this or migrate the data to get rid of the connections.

**Comment by karl-ourmachinery** [comment]
Partially fixed, the migration to alleviate this is in now. But the shader compilation bug is still there.

**Comment by tobias-ourmachinery** [comment]
Fixed.
