### ISSUE TITLE
Editor crashes when opening "Modified Assets" in a sample project

### ISSUE THREAD

**Issue by eliaspekkala** [OurMachinery/themachinery-public#92]
Steps:

1. Start: the-machinery.exe
2. Press: File -> Open Project...
3. Select: default-content.the_machinery (or any other sample project)
4. Press: View -> Modified Assets
5. The Machinery freezes (Not Responding)
6. The Machinery crashes

Info:

- OS: Windows 10 Pro (1909)
- CARD: NVIDIA GeForce GTX 980 Ti
- DRIVER: NVIDIA Graphics Driver 441.87
- MACHINERY: pre-alpha-200122-1536
- SAMPLES: pre-alpha-data-191213

**Comment by niklas-ourmachinery** [comment]
Fixed.
