### ISSUE TITLE
graph add node - fuzzier search

### ISSUE THREAD

**Issue by eigenbom** [OurMachinery/themachinery-public#922]
searching e.g., "constant float" reveals no nodes, but would be nice for the search to get fuzzier at that point and return "float constant"
![image](https://user-images.githubusercontent.com/1103761/146626224-f971d7af-6c7c-4f69-948f-dde7a1e631a9.png)

**Comment by frank-ourmachinery** [comment]
I've spent some time making the search feature fuzzier. The scoring will probably get more tweaking over time as we find more test cases to unit test against, but for now, it seems to have improved quite a bit over the old one.

![image](https://user-images.githubusercontent.com/70658773/179932943-8eaa7d1f-1ca6-417a-a3dd-2f82c392766b.png)
![image](https://user-images.githubusercontent.com/70658773/179933002-4f8bbd2a-98b7-4b89-a9fd-df96ce82e259.png)
