### ISSUE TITLE
Visual indication for distinct graphs

### ISSUE THREAD

**Issue by RiederAlex** [OurMachinery/themachinery-public#924]
I sometimes work on 2 graphs at the same time and switch around between them quite a lot, but there is no visual distinction which graph is which, which confuses me often.

Possible solution would either be to extend the breadcrumb system, which is used by subgraphs, 
or change the name from "Graph: Graph Component" to something like "Graph: Player" or "Graph: Player/Collision", as long as its not a graph asset. 

![image](https://user-images.githubusercontent.com/14026803/146642454-60b02c3f-a464-4714-99a1-27a9070b87b4.png)

**Comment by simon-ourmachinery** [comment]
The issue is that graphs have no name unless explicitly set. Maybe we can make it that they have the name of the entity. Or the asset if a graph asset.

**Comment by niklas-ourmachinery** [comment]
Yes, I think in this case, we should maybe show the name of the closest parent that has a "name" field.

**Comment by TobiasElemental** [comment]
I find this an important improvement as well as I often have 4-5 graphs open at the same time.

**Comment by simon-ourmachinery** [comment]
@TobiasElemental I just moved it up my prio

**Comment by simon-ourmachinery** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/70658708/154503845-6cc36893-d268-4ea1-92fa-297fc63adae9.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/70658708/154503890-3cc2c295-6e1f-4c81-825e-03433f1d76ac.png">

@TobiasElemental @RiederAlex I have adjusted the name display of the Graph Tab. It will always show you the name of the entity, asset or if its subgraph of the subgraph. If its a Asset/Entity it will show such in braces. I am not sure if that's needed so your feedback is welcome.
