### ISSUE TITLE
noises.tmsl uses common names for defines

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#934]
`noises.tmsl` contains, for example, `#define K 0.142857142857`. This makes it impossible to use `K` as a name when you include this file. So if you include both `noises.tmsl` and `color_spaces.tmsl` (in this order), you'll get an error, because the latter has `const float4 K = ...`.

**Comment by simon-ourmachinery** [comment]
@endragor could you provide a pr?

**Comment by tobias-ourmachinery** [comment]
@raphael-ourmachinery Can you make sure the problematic defines are undefined after their uses in that file, thanks!

**Comment by raphael-ourmachinery** [comment]
It's fixed on master now.
