### ISSUE TITLE
Cannot control format of an imported image

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#937]
When importing an image, it seems you have no choice but to use `R8G8B8A8` format, which is a huge waste of space if the image contains just one channel.
It also makes it not possible to use RGBE images (typically used for environment maps).

**Comment by frank-ourmachinery** [comment]
The default image loader (used for `.jpg`, `.jpeg`, `.png`, `.gif`, `.bmp`, `.psd`, `.pic`, `.hdr`, and `.tga`) now supports loading images with one or two channels as `R8_UNORM` and `R8G8_UNORM` respectively. To add support for exponent compression formats we would have to add a specific compression to the buffer format API (likely called E5).
