### ISSUE TITLE
Allow to avoid duplicating assets

### ISSUE THREAD

**Issue by endragor** [OurMachinery/themachinery-public#940]
Currently, you have to commit the binary blobs (.tm_buffers) into the repository, even if they could be reimported from the original assets. It would be nice to be able to store such assets in a separate folder (or mark them some other way that can be easily added to `.gitignore`) and have the editor reimport them if they are missing.

**Comment by niklas-ourmachinery** [comment]
I don't think we will add anything like this to The Machinery. It seems a bit complicated and has multiple possible failure points -- like what if the original file isn't there any more, preventing us from reimporting. We prefer for projects to be self-contained.
