### ISSUE TITLE
tm_graph_cached_node_result buffers can contain uninitialized memory

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#943]
I'm having a project which becomes flaged as "dirty" immediately when opened. When comparing the data of the assets (creation graphs) which are flagged as changed, I see differences in the tm_graph_cached_node_result buffer files which indicates that they contain uninitialized stack memory. (0xcccccccc values)

This is possibly because of how the graphs are created, so to make it easier to fix this exact issue I guess I need to create a small project with such an asset.

Another related note on the topic: When playing around with the graphs I've had hard crashes in the-machinery when combining certain nodes (I don't remember which ones, so I can't create a specific issue about this). It would be quite easy to write a script using fuzzy logic which automatically creates graphs using the nodes supported by the editor. This way you can easily find crashes, and cases where uninitialized memory are used without having repro cases of issues where this has been experienced.

**Comment by Tisten** [comment]
The repro is compressed with 7z (3MB), not zip (it became 25MB)
[Repro.7z.zip](https://github.com/OurMachinery/themachinery-public/files/7838807/Repro.7z.zip)

This project should show as "dirty" every time you open it, no matter if you have just saved it before closing it.

The 0xcccccccc values are written if the editor is compiled in debug, in release it will likely be whatever random was at that memory when saving.

Compare assets\Backpack.tm_buffers\219045414302cd4c and assets\Backpack.tm_buffers\45da0bf6d6f3d95b, the first differing bytes are 0xcccccccc at 15980 bytes into the file.

This problem will waste quite a lot of memory on disk since it writes new files for ever creation graph in a project every time you save. It also feels like the "cached graph results" are accumulating forever, i.e. leaking memory and not wiping cached garbage.

**Comment by Tisten** [comment]
I guess my bug is a duplicate of the last comment of https://github.com/OurMachinery/themachinery-public/issues/278 where @selmar has reported that .creation asset changed every time he opened the view.

**Comment by tobias-ourmachinery** [comment]
Fixed, see discussion in #980

**Comment by Tisten** [comment]
I have one more question about this issue before I leave it:

In the Backpack.tm_creation of the repro there are 196 "tm_shader_system_compiled_result" entries, of which there are 41 unique buffers consuming 77MB, but there is only one graph. Is there a good purpose of keeping all those historic entries forever?

**Comment by tobias-ourmachinery** [comment]
Hmm.. Looking at the project now and I'm too confused. 

@karl-zylinski-ourmachinery any idea why we keep on appending new `tm_graph_cached_node_result` to the node `3ff522a3-d00c-870b-a320-70ee5a8676ee` ?

Something must be leaking those entries right? We should just have the latest `tm_graph_cached_node_result` stored.

**Comment by karl-zylinski-ourmachinery** [comment]
Fixed in https://github.com/OurMachinery/themachinery/commit/d723f8f496e3d9f6022d53d62613a09b5bc61e00

We now deinstantiate invalid Cached Node Results properly. The big list of duplicates are removed using a migration.
