### ISSUE TITLE
tmbuild fails when Visual Studio 2022 is installed, ignoring --build-tool

### ISSUE THREAD

**Issue by redoak** [OurMachinery/themachinery-public#947]
With VS2022 17.0.4 and VS2019 16.11.8 installed (both with MSVC v142) building the minimal plugin fails with:

```
<MYDIR>\plugins\minimal>%TM_SDK_DIR%\bin\tmbuild.exe --build-tool vs2019
Error: no such action 'vs2022'
tmbuild: could not run `"<MYDIR>\lib\premake-5.0.0-alpha14-windows\premake5" --file=premake5.lua "vs2022" ""`


*** BUILD FAILED ***
```

There's no difference between running `tmbuild.exe` and `tmbuild.exe --build-tool vs2019`.

Setting `TM_VS2019_DIR` resolves the issue and the build succeeds.

For context, I set `TM_SDK_DIR` and `TM_LIB_DIR` with a bat file before calling tmbuild. From a quick search I see that premake-5.0.0-alpha14 does not have the vs2022 exporter—it was added in premake-5.0.0-beta1.

**Comment by simon-ourmachinery** [comment]
@frank-ourmachinery maybe this is introduced by you?

**Comment by simon-ourmachinery** [comment]
With what build are you working?@redoak source build or binary build?

**Comment by redoak** [comment]
@simon-ourmachinery Binary, the-machinery-2021.11.a-windows.

I tested it with a fresh install. Opened TM, created a new project, generated a minimal plugin, opened command prompt and set TM_SDK_DIR, and finally ran `tmbuild.exe --build-tool vs2019` in the minimal directory.

**Comment by simon-ourmachinery** [comment]
Thanks! I think I know the issue let me investigate I'll come back to you

**Comment by simon-ourmachinery** [comment]
@redoak  in your `libs.json` file you need to adjust the premake binding:
```json
{
    "premake-win": {
        "build-platforms": [
            "windows"
        ],
        "lib": "premake-5.0.0-beta1-windows",
        "role": "premake5"
    },
    "premake-linux": {
        "build-platforms": [
            "linux"
        ],
        "lib": "premake-5.0.0-alpha15-linux",
        "role": "premake5"
    }
}
```

**Comment by simon-ourmachinery** [comment]
It is fixed on master and therefore on the next release!
