### ISSUE TITLE
"Non-destructive" Set prototype command

### ISSUE THREAD

**Issue by leonardo-ourmachinery** [OurMachinery/themachinery-public#953]
When I change the prototype of an entity, all of its components are _always_ deleted, even if the new prototype doesn't have them.

In this situation, for example:
<img width="1438" alt="Screenshot 2022-01-05 090601" src="https://user-images.githubusercontent.com/70660839/148211839-d00fc003-4a7a-4a15-a1e2-a867b0af5903.png">

I decided that my bow should be a "base_object" instead of a "base_static", and so I changed the prototype via the properties view, but in this specific use case I think there should be  way for me to "merge" the two prototypes, as otherwise I will loose the Render component as the new prototype doesn't have it.
<img width="1442" alt="Screenshot 2022-01-05 090631" src="https://user-images.githubusercontent.com/70660839/148212106-8f336ceb-fab6-43c4-9e47-f2c416a6119e.png">

Not saying this should be the default, but I think it's a common enough use case that we should at least offer a smarter option.

**Comment by niklas-ourmachinery** [comment]
It should probably keep all locally added or modified stuff (or at least have an option for that) -- unless it conflicts with the prototype (i.e. unless the new prototype already has a Render component).

**Comment by leonardo-ourmachinery** [comment]
Fixed in master via https://github.com/OurMachinery/themachinery/commit/19ef8f3f1bc77d3c4089e08971c1fe44cab853ce
I didn't find a good place for giving the user a "choice"... so I made it always behave this way for now.
