### ISSUE TITLE
Graph: InitEvent does not have correct transform yet

### ISSUE THREAD

**Issue by RiederAlex** [OurMachinery/themachinery-public#960]
When spawning entities via graphs, e.g.
![image](https://user-images.githubusercontent.com/14026803/148651191-4b466e08-cc9c-4aa0-b4bf-7153518b2289.png)

The initial transform of the entity at the time of "InitEvent" of the spawned entity will always be (0,0,0).
So this (graph from the spawned entity) will always print 0,0,0.
![image](https://user-images.githubusercontent.com/14026803/148651225-664f4014-48c2-4c09-bc9b-70aae895394f.png)
In the first call of "TickEvent" the transform will be correctly set.

This behavior is quite counter intuitive, as I would like to use the "InitEvent" to perform the setup of the entity, like creating tweens, which requires the transform.

**Comment by simon-ourmachinery** [comment]
potentially fixed after some verficiation. @RiederAlex  do you still have the issue with the latest of the master, in case you have SC access?
