### ISSUE TITLE
Closing TheMachinery while minimized breaks next startup on windows

### ISSUE THREAD

**Issue by RiederAlex** [OurMachinery/themachinery-public#962]
Reproduce:
Open themachinery.exe & close it, the application settings inside AppData\Local\The Machinery\Project Settings\<...>.json will read something like
```
...
"window_width": 1920,
"window_height": 1040,
"maximized": true,
...
```

Open up themachinery.exe, minimize it, and then close it via the taskbar.
The project settings file will now read:
```
"window_x": -32000,
"window_y": -32000,
"window_width": 160,
"window_height": 28,
```

Opening up themachinery.exe again will hide the window somewhere offscreen, with no easy way to recover it.
I tested it on Win10 and a single 1920x1080 monitor.

**Comment by leonardo-ourmachinery** [comment]
Fixed for 2022.1 (Windows) with https://github.com/OurMachinery/themachinery/commit/4e775e2f402e3719a70b9f9039d1b3a3c30e521f

@raphael-ourmachinery  can you verify what happens on Linux? On Windows there's a function called `GetWindowPlacement` that returns exactly what we want, but I don't know if there's something similar on Linux.
