### ISSUE TITLE
Support opening child prototypes in new workspace

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#967]
It's currently only possible to use the "open prototype in new workspace" -action for children to the currently opened entity. As a user I would like to be able to directly use this action for grand children as well i.e. directly open prototypes that are children to other prototypes.

**Comment by simon-ourmachinery** [comment]
@ElementalAndy which version of the engine? The binary or the master version?

**Comment by niklas-ourmachinery** [comment]
@simon-ourmachinery This happens in any version.

It's the following scenario:

* You have an instance of a prototype entity in the scene.
* That prototype has an instance of another prototype in it.
* In the scene, if you expand it and right-click the child prototype, the "Open Prototype in New Workspace" option is not there.

This should be a pretty easy fix.

**Comment by simon-ourmachinery** [comment]
Oh ok I miss understood.

**Comment by niklas-ourmachinery** [comment]
Fixed in master for 2022.1.
