### ISSUE TITLE
Capsule physics shape is spawned lying down

### ISSUE THREAD

**Issue by karl-ourmachinery** [OurMachinery/themachinery-public#97]
Might just be what I'm used to, but the capsule physics shape is "lying down" instead of standing when you add it to an entity. It can be fixed with a rotated sub-entity, but I think that the most common use-case for capsules are characters, for which this is inconvenient.

**Comment by karl-ourmachinery** [comment]
I noticed now that the Physics Mover capsule is "standing", which I guess may be used more often for characters. Still, a bit inconsistent.

**Comment by niklas-ourmachinery** [comment]
We follow the PhysX convention here. This is pretty much an arbitrary choice and I don't think there's a compelling enough reason to change it.
