### ISSUE TITLE
Copy and paste, undo, then paste

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#973]
- Git master
- Linux 

 If I copy + paste an entity, then copy and paste the pasted entity, then Ctrl+Z a few times, (removes the entity) and then paste again. I get an empty "Entity deadbeef" where deadbeef is a random hex value

**Comment by leonardo-ourmachinery** [comment]
I wasn't able to exactly repro it the way you described it, but I was getting other errors. The entity tree tab wasn't correctly handling copying/pasting "dead" objects. 

It's fixed in master and for 2022.1
