### ISSUE TITLE
Default copy paste behaviour

### ISSUE THREAD

**Issue by jamesmintram** [OurMachinery/themachinery-public#975]
Selecting an entity in the scene, and using Ctrl+C then Ctrl+v will paste the new entity as a child of the entity you have just copied.

I would expect it to paste the new entity as a sibling of the entity I just copied.

**Comment by leonardo-ourmachinery** [comment]
I'm trying to repro the issue but I'm not able to.
In the video, when I copy and paste box/sphere in the scene they get actually created as "clones" of themselves, which is what you were expecting.

Maybe the issue has been fixed on master? Or do you meant something different?

https://user-images.githubusercontent.com/70660839/150780677-742aa525-4a78-4647-905f-431dd12aa20d.mp4

**Comment by jamesmintram** [comment]
Hmm. Can't repro it now. I'll re-open if I can find a way to repro.
