### ISSUE TITLE
Physx mover not created until second frame

### ISSUE THREAD

**Issue by karl-zylinski-ourmachinery** [OurMachinery/themachinery-public#98]
I use the physx mover to set velocities of my character. I ran into this:

- Put a physics mover component on some object
- Try to get the _physx_ mover component (which seems to be created from the physics mover) during the first frame
- You get null, it doesn't seem to have been mirrored yet
- During the second frame you can fetch the physx mover like you wanted

**Comment by niklas-ourmachinery** [comment]
Yes, this is how it works now. The mirrored PhysX components are created on the first PhysX update. I could probably add a function for direct access of the mover before that though.

**Comment by karl-zylinski-ourmachinery** [comment]
I think this issue is bigger than it may seem. Anyone who tries to use a mover from code will get strange, inexplicable errors on their first frame and if they try to do setup stuff on their mover the first frame / during some init phase then that won't work.

**Comment by leonardo-ourmachinery** [comment]
I agree with Karl. I encountered the problem when I was setting the parent of the transform component of an entity at creation time, and then of course the transform parent got overridden when the mover was created.

this is enough to trigger the bug, assuming the entity has a body component:
(pseudo code)
`tm_entity_t e = tm_entity_api->create_entity();
tm_physx_scene_api->set_kinematic(e, true);
tm_transform_component_api->set_parent(e, parent);
`

But I think that the only 100% correct solution is that Physx should be notified of the creation of specific components and react to that immediately (creating its own components, potentially not properly initializing them, but at least creating them) and that seems tricky and costly.

**Comment by leonardo-ourmachinery** [comment]
@karl-zylinski-ourmachinery what do you think of https://github.com/OurMachinery/themachinery/pull/879? (I could only ask for one reviewer)

**Comment by leonardo-ourmachinery** [comment]
Fixed in master.
