### ISSUE TITLE
Machinery's save data is not deterministic

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#980]
- **Version:** Git Master Branch
- **OS:** Windows

After opening a project which is a few weeks old, and clicking through all folders in the asset tab, a lot of the assets were marked dirty. I saved these changes as a new project, then opened the old project, clicked through the asset folders again and saved as yet another project. Then I diffed the two projects and there were a lot of files which were different. The differences were mostly in 'tm_shader_system_compiled_result' entries and UUIDs of thumbnails.

Note that all this happened without actually changing any of the assets, I just expanded the folders and clicked on each of the folders.

**Comment by Tisten** [comment]
When saving in Release, this issue is also guilty for causing non-deteministict results:
https://github.com/OurMachinery/themachinery-public/issues/943

**Comment by karl-zylinski-ourmachinery** [comment]
Some work has been done to address this:
- Thumbnails are only set on assets that are already dirty
- For non-dirty assets, updated thumbnails are stored in a runtime Thumbnail Repository that is independent of The Truth.
- Thumbnails never change UUID

We still need to look at the tm_shader_system_compiled_result issues.

**Comment by karl-zylinski-ourmachinery** [comment]
I have now made the UUIDs of the cache objects stay the same. Tobias Persson is investigating the non deterministic buffer output.

**Comment by tobias-ourmachinery** [comment]
Unfortunately it appears to be the regions containing the SPIRV output from the DXCompiler that are non-deterministic. Will do some more tests and then try to find out if this is a known issue or not. Maybe we are doing something wrong in how we setup the compiler.. Hmm..

@Tisten

**Comment by tobias-ourmachinery** [comment]
Upgrading the DXC compiler might solve this. There was a fix related to SPIRV output determinism as late as Dec 6 2021: https://github.com/microsoft/DirectXShaderCompiler/pull/4129

**Comment by tobias-ourmachinery** [comment]
Quick update on this, @frank-ourmachinery is working on updating DXC to the latest stable version (2021-12-08) and from my tests the SPIRV output from DXC is now deterministic. 

As soon as we can pull the switch and roll out the new version we'll ping this issue.

FYI @Tisten

**Comment by Tisten** [comment]
Thank you, great progress

**Comment by tobias-ourmachinery** [comment]
DXC has now been updated and save data should now be deterministic. 

Closing this issue for now.
