### ISSUE TITLE
Editing the active camera entity while in active simulation crashes TM

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#982]
- **Version:** Git Master Branch
- **OS:** Windows

Editing the active camera entity while in active simulation crashes TM. 
The simulation camera's transform component becomes null in simulation.c tick(..)
![image](https://user-images.githubusercontent.com/91697782/151528826-11b2d1c3-f411-4acd-8292-c0cc46858faa.png)

**Comment by leonardo-ourmachinery** [comment]
Fixed in master with https://github.com/OurMachinery/themachinery/commit/ad6704439efc05cd6de328eddcc895572aea3c77
