### ISSUE TITLE
Importing dcc assets not possible when connected to collaboration server

### ISSUE THREAD

**Issue by Tisten** [OurMachinery/themachinery-public#983]
- **Version:** Git Master Branch
- **OS:** Windows

When working as a collaborator client, dragging a dcc_asset into the Asset browser doesn't make it visible in the Preview tab as it otherwise does, and the "Extract Assets" button in the Properties tab is greyed out.

Connected as a client
![image](https://user-images.githubusercontent.com/6726075/151543611-384c36f3-92ec-4242-b0c4-3c4160a6f995.png)

Not connected as a client
![image](https://user-images.githubusercontent.com/6726075/151543628-5ede391d-996a-4707-95b1-e096b2d998eb.png)

**Comment by niklas-ourmachinery** [comment]
Fixed for 2022.1.a.
