### ISSUE TITLE
Crash: Renaming variable to an empty string in creation graph

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#988]
- **Version:** Git Master Branch
- **OS:** Windows

Changing the name field here, saving setting it back to an empty string and saving, will cause a crash when you close the graphs tab (sometimes just on the save itself)

Tested it with the geometry creation graph in the core folder.
![image](https://user-images.githubusercontent.com/21057342/151887742-61e04a37-ee2c-4145-ae83-bb02fe24fd6a.png)
![image](https://user-images.githubusercontent.com/21057342/151887757-9f084382-996c-4907-a986-bb7eb8d03f34.png)

**Comment by niklas-ourmachinery** [comment]
`io_read_resource_slot()` gets called with a corrupt value for `io` (not NULL, but not pointing to valid memory). `inst->shader` looks bad too:

![image](https://user-images.githubusercontent.com/26548514/152027787-3125921b-f852-4555-992c-cb08d9186c1f.png)

@tobias-ourmachinery or @karl-zylinski-ourmachinery, can you take a look?

**Comment by tobias-ourmachinery** [comment]
Fixed in 2022.1.a
