### ISSUE TITLE
Vulkan crash when reloading shaders while an entity is selected in scene view

### ISSUE THREAD

**Issue by cyberfrank** [OurMachinery/themachinery-public#99]
As long as no entity is selected (i.e highlighted in the scene view), the shader reload works fine. However, if the selection highlight and gizmos are visible in any case (so far), a shader reload causes a crash.  This issue have repeatedly occured while working on another shader that is also used in the same scene. The error given: **C:\repos\themachinery\plugins\vulkan_render_backend\vulkan_render_backend.c(3648): error: res == VK_SUCCESS**

**Comment by tobias-ourmachinery** [comment]
Fixed.
