### ISSUE TITLE
Support for keyboard shortcuts in the ASM Tree View

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#990]
As a user I expect standard keyboard shortcuts to work in the Animation State Machine Tree View. I would like to be able to e.g. copy and paste with "CTRL+ C" and "CTRL+ V", delete with "DEL" and rename with "F2". Preferably this should work for all nodes in the tree view e.g. states, transitions, events, variables and layers.

**Comment by niklas-ourmachinery** [comment]
* [ ] Copy/Paste with Ctrl+C, Ctrl+V
* [ ] Delete with DEL
* [ ] Rename with F2

**Comment by niklas-ourmachinery** [comment]
Fixed in master
