### ISSUE TITLE
Support "rename" in the the State Graphs context menu

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#992]
Would be nice to be able to rename states from the State Graph without having to go to the Tree View.

**Comment by niklas-ourmachinery** [comment]
You don't have to go to the Tree View, you can just select the state in the State Graph and then you can give it a new name in the Properties.

Does this work, or would you like to be able to do it in the graph itself? That's a little bit more involved, since currently we don't have any rename workflow in the graphs.

**Comment by ElementalAndy** [comment]
It would be great if it could be done in the graph itself but it's definitely on the "nice to have" side.

**Comment by ElementalAndy** [comment]
On that note. Adding a way for issue authors to add a severity/priority would be good.

**Comment by WorryBird** [comment]
I totally agree. IMO it's useful to be able to flag something as critical or as a blocker though. But, yes that too can become worthless if issue authors misuse it.

**Comment by ElementalAndy** [comment]
_When it comes to "nice-to-have"/"low priority" features I think the best approach is to close them as "won't fix" after a while._

I totally agree and if you are able to continue to be this active in communication around issues it's maybe not needed. Authors can always write in the issue description if it's a critical issue or blocker.

**Comment by niklas-ourmachinery** [comment]
Agreed... and also, if you have a critical issue that is not getting fixed, just keep bugging us... 😄 -- either here, in the Discord channel, etc. We're always juggling a lot of issues so things can get forgotten.

**Comment by niklas-ourmachinery** [comment]
On that note, I'll close this issue for now... we'll see if we'll address it in the future.
