### ISSUE TITLE
Preview tab's timeline breaks when the tab is "too" wide 

### ISSUE THREAD

**Issue by ElementalAndy** [OurMachinery/themachinery-public#993]
- **Version:** Git Master Branch
- **OS:** Windows

The rendering of the Preview tab's timeline breaks when the width of the tab is too large.
Below is the expected timeline rendering:
![image](https://user-images.githubusercontent.com/91697782/151953754-40d5b097-aa8c-4e64-91e1-1ae10f366cbb.png)
Below is the resized tab with e.g. missing timeline cursor:
![image](https://user-images.githubusercontent.com/91697782/151953924-50d2af80-714a-4fde-93bf-ba6fc435f670.png)

**Comment by niklas-ourmachinery** [comment]
I can't reproduce this behavior... I've made the tab as wide as my 4K screen and it still draws correctly, with the cursor.

Could you maybe send me a small project file where you get this behavior?

**Comment by ElementalAndy** [comment]
Added a small project here. I can reproduce the issue by just resizing the preview tab when the animation clip is selected in the asset browser.
[issue993.zip](https://github.com/OurMachinery/themachinery-public/files/7984927/issue993.zip)

**Comment by niklas-ourmachinery** [comment]
Reproduced with your project. Investigating...

**Comment by niklas-ourmachinery** [comment]
Fixed in master
