### ISSUE TITLE
Trying to issue a draw call without having a render pass bound

### ISSUE THREAD

**Issue by niklas-ourmachinery** [OurMachinery/themachinery-public#995]
- **Version:** Git Master Branch
- **OS:** Windows

Repro case:

* Open the project from #993.
* Switch between selecting `Running Jump` and `world` in the entity browser.
* Whenever `world` is selected, the following error message will be printed:

~~~
❌ c:\work\themachinery\plugins\vulkan_render_backend\vulkan_render_backend.c(6437): error: Trying to issue a draw call without having a render pass bound! Skipping! (45)
~~~

**Comment by tobias-ourmachinery** [comment]
Fixed in master.
