### ISSUE TITLE
Hot reload stops working if engine is launched via a bat script

### ISSUE THREAD

**Issue by DaveTheGameDev** [OurMachinery/themachinery-public#999]
- **Version:** Git Master Branch
- **OS:** Windows 

Hot reload stops working if engine is launched via a bat script

script used
```bat
@echo off

if exist "engine\\bin\\Debug\\the-machinery.exe" (
    start "" "engine\\bin\\Debug\\the-machinery.exe" --load-project ".\project_one\project.the_machinery_dir"
) else (
    if exist "engine\\bin\\Release\\the-machinery.exe" (
        start "" "engine\\bin\\Release\\the-machinery.exe" --load-project ".\project_one\project.the_machinery_dir"
    )
)
```
Screenshot of the folder structure I have going
![image](https://user-images.githubusercontent.com/21057342/152497482-19bd0454-c13d-4a86-bcb6-487aec8ef826.png)

**Comment by DaveTheGameDev** [comment]
Note can confirm the dll was copied. Also tested with a manual copy paste.

**Comment by DaveTheGameDev** [comment]
I seem to have figured out the issue sorry mostly , looks like I was thinking clean dlls would hotreload (same code)
Leads me to a new question, if i add a new dll entirely to the plugin folder, should that get loaded?

**Comment by simon-ourmachinery** [comment]
@DaveTheGameDev So the actual issue/question: What happens when we have 2 DLL's: One of the projects one of the global plugin dll folder which one gets loaded?

Example:
- tm_mygameplay.dll--> part of the project
- tm_mygameplay.dll--> part of the `/plugins` folder

**Comment by niklas-ourmachinery** [comment]
@DaveTheGameDev I'll close this issue since you say you've figured it out. If there is a still an issue, please let us know. I'm a bit unsure what you mean by "thinking clean dlls would hotreload".

If you add a new DLL to the plugin folder while the engine is running it does not get loaded, hot reload only reloads already existing DLLs.

**Comment by DaveTheGameDev** [comment]
@niklas-ourmachinery  All good. When I said clean dll I meant a rebuilt dll of the exact same code using the clean argument in TMBuild.

**Comment by niklas-ourmachinery** [comment]
It checks the modified date of the file, so a clean rebuild should trigger a reload.

**Comment by DaveTheGameDev** [comment]
Interesting I will double check for a repro because it was not working that way for me at all.
